# pyright: reportPrivateUsage = none

import jep

class HttpsServer[**Ts](jep._PyJObject): ...

class Headers[**Ts](jep._PyJObject): ...

class HttpContext[**Ts](jep._PyJObject): ...

class BasicAuthenticator[**Ts](jep._PyJObject): ...

class Filter[**Ts](jep._PyJObject): ...

class Authenticator[**Ts](jep._PyJObject): ...

class HttpsConfigurator[**Ts](jep._PyJObject): ...

class HttpsExchange[**Ts](jep._PyJObject): ...

class HttpsParameters[**Ts](jep._PyJObject): ...

class HttpExchange[**Ts](jep._PyJObject): ...

class HttpServer[**Ts](jep._PyJObject): ...

class HttpHandler[**Ts](jep._PyJObject): ...

class HttpPrincipal[**Ts](jep._PyJObject): ...

