import jep

class HttpServer(jep._PyJObject): ...

class Headers(jep._PyJObject): ...

class BasicAuthenticator(jep._PyJObject): ...

class HttpHandler(jep._PyJObject): ...

class HttpsExchange(jep._PyJObject): ...

class Filter(jep._PyJObject): ...

class HttpsParameters(jep._PyJObject): ...

class HttpExchange(jep._PyJObject): ...

class HttpPrincipal(jep._PyJObject): ...

class HttpContext(jep._PyJObject): ...

class HttpsServer(jep._PyJObject): ...

class HttpsConfigurator(jep._PyJObject): ...

class Authenticator(jep._PyJObject): ...

