import jep

class HttpServer(jep.PyJObject): ...

class Headers(jep.PyJObject): ...

class BasicAuthenticator(jep.PyJObject): ...

class HttpHandler(jep.PyJObject): ...

class HttpsExchange(jep.PyJObject): ...

class Filter(jep.PyJObject): ...

class HttpsParameters(jep.PyJObject): ...

class HttpExchange(jep.PyJObject): ...

class HttpPrincipal(jep.PyJObject): ...

class HttpContext(jep.PyJObject): ...

class HttpsServer(jep.PyJObject): ...

class HttpsConfigurator(jep.PyJObject): ...

class Authenticator(jep.PyJObject): ...

