# pyright: reportPrivateUsage = none

import jep

class DynUnionHelper[**Ts](jep._PyJObject): ...

class DynValueCommonOperations[**Ts](jep._PyJObject): ...

class DynFixed[**Ts](jep._PyJObject): ...

class _DynEnumStub[**Ts](jep._PyJObject): ...

class DynEnumHelper[**Ts](jep._PyJObject): ...

class DynAnyOperations[**Ts](jep._PyJObject): ...

class NameValuePair[**Ts](jep._PyJObject): ...

class DynStructOperations[**Ts](jep._PyJObject): ...

class DynValue[**Ts](jep._PyJObject): ...

class DynValueBox[**Ts](jep._PyJObject): ...

class _DynSequenceStub[**Ts](jep._PyJObject): ...

class DynSequence[**Ts](jep._PyJObject): ...

class DynValueHelper[**Ts](jep._PyJObject): ...

class DynValueBoxOperations[**Ts](jep._PyJObject): ...

class FieldNameHelper[**Ts](jep._PyJObject): ...

class DynSequenceHelper[**Ts](jep._PyJObject): ...

class _DynValueStub[**Ts](jep._PyJObject): ...

class DynSequenceOperations[**Ts](jep._PyJObject): ...

class DynAnyFactoryOperations[**Ts](jep._PyJObject): ...

class AnySeqHelper[**Ts](jep._PyJObject): ...

class _DynFixedStub[**Ts](jep._PyJObject): ...

class NameDynAnyPairHelper[**Ts](jep._PyJObject): ...

class DynArrayOperations[**Ts](jep._PyJObject): ...

class DynFixedHelper[**Ts](jep._PyJObject): ...

class _DynArrayStub[**Ts](jep._PyJObject): ...

class DynValueCommon[**Ts](jep._PyJObject): ...

class DynAnyFactoryHelper[**Ts](jep._PyJObject): ...

class DynValueOperations[**Ts](jep._PyJObject): ...

class DynAnyHelper[**Ts](jep._PyJObject): ...

class DynUnion[**Ts](jep._PyJObject): ...

class NameDynAnyPairSeqHelper[**Ts](jep._PyJObject): ...

class NameValuePairHelper[**Ts](jep._PyJObject): ...

class _DynStructStub[**Ts](jep._PyJObject): ...

class DynFixedOperations[**Ts](jep._PyJObject): ...

class DynArray[**Ts](jep._PyJObject): ...

class NameDynAnyPair[**Ts](jep._PyJObject): ...

class DynUnionOperations[**Ts](jep._PyJObject): ...

class DynArrayHelper[**Ts](jep._PyJObject): ...

class _DynAnyFactoryStub[**Ts](jep._PyJObject): ...

class NameValuePairSeqHelper[**Ts](jep._PyJObject): ...

class DynEnum[**Ts](jep._PyJObject): ...

class DynAnyFactory[**Ts](jep._PyJObject): ...

class DynStructHelper[**Ts](jep._PyJObject): ...

class _DynUnionStub[**Ts](jep._PyJObject): ...

class DynStruct[**Ts](jep._PyJObject): ...

class DynAnySeqHelper[**Ts](jep._PyJObject): ...

class DynAny[**Ts](jep._PyJObject): ...

class _DynAnyStub[**Ts](jep._PyJObject): ...

class DynEnumOperations[**Ts](jep._PyJObject): ...

