# pyright: reportPrivateUsage = none

import jep

class ExtendedSocketOptions[**Ts](jep._PyJObject): ...

class SocketFlow[**Ts](jep._PyJObject): ...

class Sockets[**Ts](jep._PyJObject): ...

class NetworkPermission[**Ts](jep._PyJObject): ...

