# pyright: reportPrivateUsage = none

import jep

class JPEGHuffmanTable[**Ts](jep._PyJObject): ...

class JPEGImageWriteParam[**Ts](jep._PyJObject): ...

class JPEGQTable[**Ts](jep._PyJObject): ...

class JPEGImageReadParam[**Ts](jep._PyJObject): ...

