import jep

class TIFFTag(jep._PyJObject): ...

class TIFFDirectory(jep._PyJObject): ...

class ExifGPSTagSet(jep._PyJObject): ...

class TIFFImageReadParam(jep._PyJObject): ...

class ExifParentTIFFTagSet(jep._PyJObject): ...

class ExifTIFFTagSet(jep._PyJObject): ...

class TIFFField(jep._PyJObject): ...

class BaselineTIFFTagSet(jep._PyJObject): ...

class TIFFTagSet(jep._PyJObject): ...

class GeoTIFFTagSet(jep._PyJObject): ...

class ExifInteroperabilityTagSet(jep._PyJObject): ...

class FaxTIFFTagSet(jep._PyJObject): ...

