# pyright: reportPrivateUsage = none

import jep

class GeoTIFFTagSet[**Ts](jep._PyJObject): ...

class ExifParentTIFFTagSet[**Ts](jep._PyJObject): ...

class BaselineTIFFTagSet[**Ts](jep._PyJObject): ...

class ExifGPSTagSet[**Ts](jep._PyJObject): ...

class TIFFImageReadParam[**Ts](jep._PyJObject): ...

class ExifInteroperabilityTagSet[**Ts](jep._PyJObject): ...

class TIFFTag[**Ts](jep._PyJObject): ...

class TIFFDirectory[**Ts](jep._PyJObject): ...

class FaxTIFFTagSet[**Ts](jep._PyJObject): ...

class TIFFField[**Ts](jep._PyJObject): ...

class ExifTIFFTagSet[**Ts](jep._PyJObject): ...

class TIFFTagSet[**Ts](jep._PyJObject): ...

