import jep

class TIFFTag(jep.PyJObject): ...

class TIFFDirectory(jep.PyJObject): ...

class ExifGPSTagSet(jep.PyJObject): ...

class TIFFImageReadParam(jep.PyJObject): ...

class ExifParentTIFFTagSet(jep.PyJObject): ...

class ExifTIFFTagSet(jep.PyJObject): ...

class TIFFField(jep.PyJObject): ...

class BaselineTIFFTagSet(jep.PyJObject): ...

class TIFFTagSet(jep.PyJObject): ...

class GeoTIFFTagSet(jep.PyJObject): ...

class ExifInteroperabilityTagSet(jep.PyJObject): ...

class FaxTIFFTagSet(jep.PyJObject): ...

