# pyright: reportPrivateUsage = none

import jep

class Style[**Ts](jep._PyJObject): ...

class StyleableIntegerProperty[**Ts](jep._PyJObject): ...

class SimpleStyleableObjectProperty[**Ts](jep._PyJObject): ...

class Match[**Ts](jep._PyJObject): ...

class Stylesheet[**Ts](jep._PyJObject): ...

class SimpleStyleableLongProperty[**Ts](jep._PyJObject): ...

class ParsedValue[**Ts](jep._PyJObject): ...

class SimpleStyleableStringProperty[**Ts](jep._PyJObject): ...

class StyleableDoubleProperty[**Ts](jep._PyJObject): ...

class CssParser[**Ts](jep._PyJObject): ...

class SimpleStyleableIntegerProperty[**Ts](jep._PyJObject): ...

class Size[**Ts](jep._PyJObject): ...

class SizeUnits[**Ts](jep._PyJObject): ...

class Rule[**Ts](jep._PyJObject): ...

class StyleableObjectProperty[**Ts](jep._PyJObject): ...

class SimpleStyleableFloatProperty[**Ts](jep._PyJObject): ...

class CompoundSelector[**Ts](jep._PyJObject): ...

class StyleableFloatProperty[**Ts](jep._PyJObject): ...

class StyleOrigin[**Ts](jep._PyJObject): ...

class SimpleStyleableBooleanProperty[**Ts](jep._PyJObject): ...

class SimpleStyleableDoubleProperty[**Ts](jep._PyJObject): ...

class CssMetaData[**Ts](jep._PyJObject): ...

class FontFace[**Ts](jep._PyJObject): ...

class Selector[**Ts](jep._PyJObject): ...

class StyleableBooleanProperty[**Ts](jep._PyJObject): ...

class SimpleSelector[**Ts](jep._PyJObject): ...

class StyleableLongProperty[**Ts](jep._PyJObject): ...

class StyleablePropertyFactory[**Ts](jep._PyJObject): ...

class StyleableStringProperty[**Ts](jep._PyJObject): ...

class StyleableProperty[**Ts](jep._PyJObject): ...

class StyleClass[**Ts](jep._PyJObject): ...

class FontCssMetaData[**Ts](jep._PyJObject): ...

class StyleConverter[**Ts](jep._PyJObject): ...

class PseudoClass[**Ts](jep._PyJObject): ...

class Declaration[**Ts](jep._PyJObject): ...

class Styleable[**Ts](jep._PyJObject): ...

