import jep

class Styleable(jep._PyJObject): ...

class SimpleStyleableBooleanProperty(jep._PyJObject): ...

class Selector(jep._PyJObject): ...

class SizeUnits(jep._PyJObject): ...

class Match(jep._PyJObject): ...

class Declaration(jep._PyJObject): ...

class CompoundSelector(jep._PyJObject): ...

class Size(jep._PyJObject): ...

class StyleableIntegerProperty(jep._PyJObject): ...

class StyleablePropertyFactory(jep._PyJObject): ...

class StyleableBooleanProperty(jep._PyJObject): ...

class Style(jep._PyJObject): ...

class SimpleStyleableObjectProperty(jep._PyJObject): ...

class ParsedValue(jep._PyJObject): ...

class StyleClass(jep._PyJObject): ...

class Stylesheet(jep._PyJObject): ...

class CssMetaData(jep._PyJObject): ...

class SimpleStyleableLongProperty(jep._PyJObject): ...

class StyleOrigin(jep._PyJObject): ...

class StyleableProperty(jep._PyJObject): ...

class PseudoClass(jep._PyJObject): ...

class SimpleStyleableFloatProperty(jep._PyJObject): ...

class StyleableLongProperty(jep._PyJObject): ...

class StyleableObjectProperty(jep._PyJObject): ...

class StyleableFloatProperty(jep._PyJObject): ...

class CssParser(jep._PyJObject): ...

class StyleableDoubleProperty(jep._PyJObject): ...

class StyleConverter(jep._PyJObject): ...

class StyleableStringProperty(jep._PyJObject): ...

class SimpleStyleableDoubleProperty(jep._PyJObject): ...

class FontFace(jep._PyJObject): ...

class SimpleStyleableIntegerProperty(jep._PyJObject): ...

class Rule(jep._PyJObject): ...

class SimpleSelector(jep._PyJObject): ...

class FontCssMetaData(jep._PyJObject): ...

class SimpleStyleableStringProperty(jep._PyJObject): ...

