import jep

class Styleable(jep.PyJObject): ...

class SimpleStyleableBooleanProperty(jep.PyJObject): ...

class Selector(jep.PyJObject): ...

class SizeUnits(jep.PyJObject): ...

class Match(jep.PyJObject): ...

class Declaration(jep.PyJObject): ...

class CompoundSelector(jep.PyJObject): ...

class Size(jep.PyJObject): ...

class StyleableIntegerProperty(jep.PyJObject): ...

class StyleablePropertyFactory(jep.PyJObject): ...

class StyleableBooleanProperty(jep.PyJObject): ...

class Style(jep.PyJObject): ...

class SimpleStyleableObjectProperty(jep.PyJObject): ...

class ParsedValue(jep.PyJObject): ...

class StyleClass(jep.PyJObject): ...

class Stylesheet(jep.PyJObject): ...

class CssMetaData(jep.PyJObject): ...

class SimpleStyleableLongProperty(jep.PyJObject): ...

class StyleOrigin(jep.PyJObject): ...

class StyleableProperty(jep.PyJObject): ...

class PseudoClass(jep.PyJObject): ...

class SimpleStyleableFloatProperty(jep.PyJObject): ...

class StyleableLongProperty(jep.PyJObject): ...

class StyleableObjectProperty(jep.PyJObject): ...

class StyleableFloatProperty(jep.PyJObject): ...

class CssParser(jep.PyJObject): ...

class StyleableDoubleProperty(jep.PyJObject): ...

class StyleConverter(jep.PyJObject): ...

class StyleableStringProperty(jep.PyJObject): ...

class SimpleStyleableDoubleProperty(jep.PyJObject): ...

class FontFace(jep.PyJObject): ...

class SimpleStyleableIntegerProperty(jep.PyJObject): ...

class Rule(jep.PyJObject): ...

class SimpleSelector(jep.PyJObject): ...

class FontCssMetaData(jep.PyJObject): ...

class SimpleStyleableStringProperty(jep.PyJObject): ...

