import jep

class CursorConverter(jep._PyJObject): ...

class StopConverter(jep._PyJObject): ...

class InsetsConverter(jep._PyJObject): ...

class FontConverter(jep._PyJObject): ...

class SizeConverter(jep._PyJObject): ...

class DurationConverter(jep._PyJObject): ...

class ShapeConverter(jep._PyJObject): ...

class LadderConverter(jep._PyJObject): ...

class URLConverter(jep._PyJObject): ...

class DeriveColorConverter(jep._PyJObject): ...

class EffectConverter(jep._PyJObject): ...

class ColorConverter(jep._PyJObject): ...

class BooleanConverter(jep._PyJObject): ...

class PaintConverter(jep._PyJObject): ...

class DeriveSizeConverter(jep._PyJObject): ...

class EnumConverter(jep._PyJObject): ...

