# pyright: reportPrivateUsage = none

import jep

class DeriveColorConverter[**Ts](jep._PyJObject): ...

class SizeConverter[**Ts](jep._PyJObject): ...

class ColorConverter[**Ts](jep._PyJObject): ...

class InsetsConverter[**Ts](jep._PyJObject): ...

class PaintConverter[**Ts](jep._PyJObject): ...

class StringConverter[**Ts](jep._PyJObject): ...

class CursorConverter[**Ts](jep._PyJObject): ...

class StopConverter[**Ts](jep._PyJObject): ...

class ShapeConverter[**Ts](jep._PyJObject): ...

class URLConverter[**Ts](jep._PyJObject): ...

class DeriveSizeConverter[**Ts](jep._PyJObject): ...

class DurationConverter[**Ts](jep._PyJObject): ...

class FontConverter[**Ts](jep._PyJObject): ...

class BooleanConverter[**Ts](jep._PyJObject): ...

class EffectConverter[**Ts](jep._PyJObject): ...

class LadderConverter[**Ts](jep._PyJObject): ...

