import jep

class CursorConverter(jep.PyJObject): ...

class StopConverter(jep.PyJObject): ...

class InsetsConverter(jep.PyJObject): ...

class FontConverter(jep.PyJObject): ...

class SizeConverter(jep.PyJObject): ...

class DurationConverter(jep.PyJObject): ...

class ShapeConverter(jep.PyJObject): ...

class LadderConverter(jep.PyJObject): ...

class URLConverter(jep.PyJObject): ...

class DeriveColorConverter(jep.PyJObject): ...

class EffectConverter(jep.PyJObject): ...

class ColorConverter(jep.PyJObject): ...

class BooleanConverter(jep.PyJObject): ...

class PaintConverter(jep.PyJObject): ...

class DeriveSizeConverter(jep.PyJObject): ...

class EnumConverter(jep.PyJObject): ...

