import jep

class PrincipalComparator(jep._PyJObject): ...

class SolarisPrincipal(jep._PyJObject): ...

class NTSidPrimaryGroupPrincipal(jep._PyJObject): ...

class SolarisNumericGroupPrincipal(jep._PyJObject): ...

class NTUserPrincipal(jep._PyJObject): ...

class LdapPrincipal(jep._PyJObject): ...

class UnixNumericGroupPrincipal(jep._PyJObject): ...

class NTSidDomainPrincipal(jep._PyJObject): ...

class NTNumericCredential(jep._PyJObject): ...

class NTDomainPrincipal(jep._PyJObject): ...

class SolarisNumericUserPrincipal(jep._PyJObject): ...

class NTSid(jep._PyJObject): ...

class NTSidGroupPrincipal(jep._PyJObject): ...

class PolicyFile(jep._PyJObject): ...

class UserPrincipal(jep._PyJObject): ...

class X500Principal(jep._PyJObject): ...

class NTSidUserPrincipal(jep._PyJObject): ...

class UnixNumericUserPrincipal(jep._PyJObject): ...

class UnixPrincipal(jep._PyJObject): ...

