# pyright: reportPrivateUsage = none

import jep

class UnixNumericGroupPrincipal[**Ts](jep._PyJObject): ...

class NTSidDomainPrincipal[**Ts](jep._PyJObject): ...

class NTSidUserPrincipal[**Ts](jep._PyJObject): ...

class X500Principal[**Ts](jep._PyJObject): ...

class PolicyFile[**Ts](jep._PyJObject): ...

class NTNumericCredential[**Ts](jep._PyJObject): ...

class SolarisNumericGroupPrincipal[**Ts](jep._PyJObject): ...

class NTSidPrimaryGroupPrincipal[**Ts](jep._PyJObject): ...

class SolarisPrincipal[**Ts](jep._PyJObject): ...

class UnixPrincipal[**Ts](jep._PyJObject): ...

class LdapPrincipal[**Ts](jep._PyJObject): ...

class UnixNumericUserPrincipal[**Ts](jep._PyJObject): ...

class NTUserPrincipal[**Ts](jep._PyJObject): ...

class NTSid[**Ts](jep._PyJObject): ...

class UserPrincipal[**Ts](jep._PyJObject): ...

class NTSidGroupPrincipal[**Ts](jep._PyJObject): ...

class SolarisNumericUserPrincipal[**Ts](jep._PyJObject): ...

class PrincipalComparator[**Ts](jep._PyJObject): ...

class NTDomainPrincipal[**Ts](jep._PyJObject): ...

