import jep

class PrincipalComparator(jep.PyJObject): ...

class SolarisPrincipal(jep.PyJObject): ...

class NTSidPrimaryGroupPrincipal(jep.PyJObject): ...

class SolarisNumericGroupPrincipal(jep.PyJObject): ...

class NTUserPrincipal(jep.PyJObject): ...

class LdapPrincipal(jep.PyJObject): ...

class UnixNumericGroupPrincipal(jep.PyJObject): ...

class NTSidDomainPrincipal(jep.PyJObject): ...

class NTNumericCredential(jep.PyJObject): ...

class NTDomainPrincipal(jep.PyJObject): ...

class SolarisNumericUserPrincipal(jep.PyJObject): ...

class NTSid(jep.PyJObject): ...

class NTSidGroupPrincipal(jep.PyJObject): ...

class PolicyFile(jep.PyJObject): ...

class UserPrincipal(jep.PyJObject): ...

class X500Principal(jep.PyJObject): ...

class NTSidUserPrincipal(jep.PyJObject): ...

class UnixNumericUserPrincipal(jep.PyJObject): ...

class UnixPrincipal(jep.PyJObject): ...

