# pyright: reportPrivateUsage = none

import jep

class SolarisLoginModule[**Ts](jep._PyJObject): ...

class UnixLoginModule[**Ts](jep._PyJObject): ...

class NTSystem[**Ts](jep._PyJObject): ...

class NTLoginModule[**Ts](jep._PyJObject): ...

class JndiLoginModule[**Ts](jep._PyJObject): ...

class Krb5LoginModule[**Ts](jep._PyJObject): ...

class LdapLoginModule[**Ts](jep._PyJObject): ...

class KeyStoreLoginModule[**Ts](jep._PyJObject): ...

class SolarisSystem[**Ts](jep._PyJObject): ...

