import jep

class SolarisSystem(jep._PyJObject): ...

class KeyStoreLoginModule(jep._PyJObject): ...

class LdapLoginModule(jep._PyJObject): ...

class NTLoginModule(jep._PyJObject): ...

class NTSystem(jep._PyJObject): ...

class JndiLoginModule(jep._PyJObject): ...

class UnixSystem(jep._PyJObject): ...

class Krb5LoginModule(jep._PyJObject): ...

class UnixLoginModule(jep._PyJObject): ...

