import jep

class SolarisSystem(jep.PyJObject): ...

class KeyStoreLoginModule(jep.PyJObject): ...

class LdapLoginModule(jep.PyJObject): ...

class NTLoginModule(jep.PyJObject): ...

class NTSystem(jep.PyJObject): ...

class JndiLoginModule(jep.PyJObject): ...

class UnixSystem(jep.PyJObject): ...

class Krb5LoginModule(jep.PyJObject): ...

class UnixLoginModule(jep.PyJObject): ...

