import jep

class ValueTree(jep._PyJObject): ...

class EntityTree(jep._PyJObject): ...

class EndElementTree(jep._PyJObject): ...

class DocTreeVisitor(jep._PyJObject): ...

class DeprecatedTree(jep._PyJObject): ...

class DocRootTree(jep._PyJObject): ...

class BlockTagTree(jep._PyJObject): ...

class ProvidesTree(jep._PyJObject): ...

class UsesTree(jep._PyJObject): ...

class ErroneousTree(jep._PyJObject): ...

class SerialTree(jep._PyJObject): ...

class UnknownBlockTagTree(jep._PyJObject): ...

class LinkTree(jep._PyJObject): ...

class AttributeTree(jep._PyJObject): ...

class ReturnTree(jep._PyJObject): ...

class LiteralTree(jep._PyJObject): ...

class CommentTree(jep._PyJObject): ...

class SerialFieldTree(jep._PyJObject): ...

class UnknownInlineTagTree(jep._PyJObject): ...

class SinceTree(jep._PyJObject): ...

class DocTree(jep._PyJObject): ...

class HiddenTree(jep._PyJObject): ...

class IndexTree(jep._PyJObject): ...

class ThrowsTree(jep._PyJObject): ...

class StartElementTree(jep._PyJObject): ...

class SummaryTree(jep._PyJObject): ...

class SerialDataTree(jep._PyJObject): ...

class DocCommentTree(jep._PyJObject): ...

class AuthorTree(jep._PyJObject): ...

class TextTree(jep._PyJObject): ...

class ReferenceTree(jep._PyJObject): ...

class DocTypeTree(jep._PyJObject): ...

class VersionTree(jep._PyJObject): ...

class ParamTree(jep._PyJObject): ...

class InlineTagTree(jep._PyJObject): ...

class SeeTree(jep._PyJObject): ...

class IdentifierTree(jep._PyJObject): ...

class InheritDocTree(jep._PyJObject): ...

