import jep

class ValueTree(jep.PyJObject): ...

class EntityTree(jep.PyJObject): ...

class EndElementTree(jep.PyJObject): ...

class DocTreeVisitor(jep.PyJObject): ...

class DeprecatedTree(jep.PyJObject): ...

class DocRootTree(jep.PyJObject): ...

class BlockTagTree(jep.PyJObject): ...

class ProvidesTree(jep.PyJObject): ...

class UsesTree(jep.PyJObject): ...

class ErroneousTree(jep.PyJObject): ...

class SerialTree(jep.PyJObject): ...

class UnknownBlockTagTree(jep.PyJObject): ...

class LinkTree(jep.PyJObject): ...

class AttributeTree(jep.PyJObject): ...

class ReturnTree(jep.PyJObject): ...

class LiteralTree(jep.PyJObject): ...

class CommentTree(jep.PyJObject): ...

class SerialFieldTree(jep.PyJObject): ...

class UnknownInlineTagTree(jep.PyJObject): ...

class SinceTree(jep.PyJObject): ...

class DocTree(jep.PyJObject): ...

class HiddenTree(jep.PyJObject): ...

class IndexTree(jep.PyJObject): ...

class ThrowsTree(jep.PyJObject): ...

class StartElementTree(jep.PyJObject): ...

class SummaryTree(jep.PyJObject): ...

class SerialDataTree(jep.PyJObject): ...

class DocCommentTree(jep.PyJObject): ...

class AuthorTree(jep.PyJObject): ...

class TextTree(jep.PyJObject): ...

class ReferenceTree(jep.PyJObject): ...

class DocTypeTree(jep.PyJObject): ...

class VersionTree(jep.PyJObject): ...

class ParamTree(jep.PyJObject): ...

class InlineTagTree(jep.PyJObject): ...

class SeeTree(jep.PyJObject): ...

class IdentifierTree(jep.PyJObject): ...

class InheritDocTree(jep.PyJObject): ...

