# pyright: reportPrivateUsage = none

import jep

class SerialTree[**Ts](jep._PyJObject): ...

class SinceTree[**Ts](jep._PyJObject): ...

class UnknownInlineTagTree[**Ts](jep._PyJObject): ...

class VersionTree[**Ts](jep._PyJObject): ...

class StartElementTree[**Ts](jep._PyJObject): ...

class EntityTree[**Ts](jep._PyJObject): ...

class DocRootTree[**Ts](jep._PyJObject): ...

class ParamTree[**Ts](jep._PyJObject): ...

class ThrowsTree[**Ts](jep._PyJObject): ...

class CommentTree[**Ts](jep._PyJObject): ...

class IndexTree[**Ts](jep._PyJObject): ...

class DocCommentTree[**Ts](jep._PyJObject): ...

class DocTreeVisitor[**Ts](jep._PyJObject): ...

class LiteralTree[**Ts](jep._PyJObject): ...

class SeeTree[**Ts](jep._PyJObject): ...

class InlineTagTree[**Ts](jep._PyJObject): ...

class SummaryTree[**Ts](jep._PyJObject): ...

class LinkTree[**Ts](jep._PyJObject): ...

class BlockTagTree[**Ts](jep._PyJObject): ...

class AttributeTree[**Ts](jep._PyJObject): ...

class DocTree[**Ts](jep._PyJObject): ...

class TextTree[**Ts](jep._PyJObject): ...

class SerialDataTree[**Ts](jep._PyJObject): ...

class DeprecatedTree[**Ts](jep._PyJObject): ...

class AuthorTree[**Ts](jep._PyJObject): ...

class UsesTree[**Ts](jep._PyJObject): ...

class ErroneousTree[**Ts](jep._PyJObject): ...

class ReferenceTree[**Ts](jep._PyJObject): ...

class UnknownBlockTagTree[**Ts](jep._PyJObject): ...

class SerialFieldTree[**Ts](jep._PyJObject): ...

class ReturnTree[**Ts](jep._PyJObject): ...

class HiddenTree[**Ts](jep._PyJObject): ...

class ProvidesTree[**Ts](jep._PyJObject): ...

class EndElementTree[**Ts](jep._PyJObject): ...

class ValueTree[**Ts](jep._PyJObject): ...

class DocTypeTree[**Ts](jep._PyJObject): ...

class InheritDocTree[**Ts](jep._PyJObject): ...

class IdentifierTree[**Ts](jep._PyJObject): ...

