import jep

class Tree(jep._PyJObject): ...

class WildcardTree(jep._PyJObject): ...

class BreakTree(jep._PyJObject): ...

class RequiresTree(jep._PyJObject): ...

class CaseTree(jep._PyJObject): ...

class IntersectionTypeTree(jep._PyJObject): ...

class CompoundAssignmentTree(jep._PyJObject): ...

class InstanceOfTree(jep._PyJObject): ...

class WhileLoopTree(jep._PyJObject): ...

class Scope(jep._PyJObject): ...

class PackageTree(jep._PyJObject): ...

class NewClassTree(jep._PyJObject): ...

class MethodTree(jep._PyJObject): ...

class UnaryTree(jep._PyJObject): ...

class AssertTree(jep._PyJObject): ...

class AssignmentTree(jep._PyJObject): ...

class ClassTree(jep._PyJObject): ...

class UsesTree(jep._PyJObject): ...

class LambdaExpressionTree(jep._PyJObject): ...

class LiteralTree(jep._PyJObject): ...

class AnnotationTree(jep._PyJObject): ...

class ModuleTree(jep._PyJObject): ...

class IdentifierTree(jep._PyJObject): ...

class ContinueTree(jep._PyJObject): ...

class BinaryTree(jep._PyJObject): ...

class TypeCastTree(jep._PyJObject): ...

class ArrayTypeTree(jep._PyJObject): ...

class CatchTree(jep._PyJObject): ...

class ParenthesizedTree(jep._PyJObject): ...

class ExpressionTree(jep._PyJObject): ...

class BlockTree(jep._PyJObject): ...

class MethodInvocationTree(jep._PyJObject): ...

class EnhancedForLoopTree(jep._PyJObject): ...

class MemberSelectTree(jep._PyJObject): ...

class MemberReferenceTree(jep._PyJObject): ...

class OpensTree(jep._PyJObject): ...

class SynchronizedTree(jep._PyJObject): ...

class ModifiersTree(jep._PyJObject): ...

class ConditionalExpressionTree(jep._PyJObject): ...

class SwitchTree(jep._PyJObject): ...

class NewArrayTree(jep._PyJObject): ...

class ExpressionStatementTree(jep._PyJObject): ...

class LineMap(jep._PyJObject): ...

class DirectiveTree(jep._PyJObject): ...

class ImportTree(jep._PyJObject): ...

class ThrowTree(jep._PyJObject): ...

class ProvidesTree(jep._PyJObject): ...

class TreeVisitor(jep._PyJObject): ...

class TryTree(jep._PyJObject): ...

class ArrayAccessTree(jep._PyJObject): ...

class ParameterizedTypeTree(jep._PyJObject): ...

class CompilationUnitTree(jep._PyJObject): ...

class DoWhileLoopTree(jep._PyJObject): ...

class UnionTypeTree(jep._PyJObject): ...

class TypeParameterTree(jep._PyJObject): ...

class VariableTree(jep._PyJObject): ...

class IfTree(jep._PyJObject): ...

class ErroneousTree(jep._PyJObject): ...

class ExportsTree(jep._PyJObject): ...

class ForLoopTree(jep._PyJObject): ...

class LabeledStatementTree(jep._PyJObject): ...

class StatementTree(jep._PyJObject): ...

class AnnotatedTypeTree(jep._PyJObject): ...

class ReturnTree(jep._PyJObject): ...

class PrimitiveTypeTree(jep._PyJObject): ...

class EmptyStatementTree(jep._PyJObject): ...

