# pyright: reportPrivateUsage = none

import jep

class ReturnTree[**Ts](jep._PyJObject): ...

class BreakTree[**Ts](jep._PyJObject): ...

class CaseTree[**Ts](jep._PyJObject): ...

class AssertTree[**Ts](jep._PyJObject): ...

class ForLoopTree[**Ts](jep._PyJObject): ...

class IdentifierTree[**Ts](jep._PyJObject): ...

class ModifiersTree[**Ts](jep._PyJObject): ...

class ErroneousTree[**Ts](jep._PyJObject): ...

class CatchTree[**Ts](jep._PyJObject): ...

class ThrowTree[**Ts](jep._PyJObject): ...

class ExpressionStatementTree[**Ts](jep._PyJObject): ...

class WildcardTree[**Ts](jep._PyJObject): ...

class VariableTree[**Ts](jep._PyJObject): ...

class ParameterizedTypeTree[**Ts](jep._PyJObject): ...

class StatementTree[**Ts](jep._PyJObject): ...

class MemberReferenceTree[**Ts](jep._PyJObject): ...

class InstanceOfTree[**Ts](jep._PyJObject): ...

class ParenthesizedTree[**Ts](jep._PyJObject): ...

class IntersectionTypeTree[**Ts](jep._PyJObject): ...

class ImportTree[**Ts](jep._PyJObject): ...

class NewClassTree[**Ts](jep._PyJObject): ...

class AnnotatedTypeTree[**Ts](jep._PyJObject): ...

class RequiresTree[**Ts](jep._PyJObject): ...

class BinaryTree[**Ts](jep._PyJObject): ...

class AnnotationTree[**Ts](jep._PyJObject): ...

class DirectiveTree[**Ts](jep._PyJObject): ...

class LambdaExpressionTree[**Ts](jep._PyJObject): ...

class Tree[**Ts](jep._PyJObject): ...

class EmptyStatementTree[**Ts](jep._PyJObject): ...

class ExportsTree[**Ts](jep._PyJObject): ...

class ArrayAccessTree[**Ts](jep._PyJObject): ...

class MethodInvocationTree[**Ts](jep._PyJObject): ...

class ProvidesTree[**Ts](jep._PyJObject): ...

class DoWhileLoopTree[**Ts](jep._PyJObject): ...

class BlockTree[**Ts](jep._PyJObject): ...

class MemberSelectTree[**Ts](jep._PyJObject): ...

class TypeParameterTree[**Ts](jep._PyJObject): ...

class PackageTree[**Ts](jep._PyJObject): ...

class AssignmentTree[**Ts](jep._PyJObject): ...

class TypeCastTree[**Ts](jep._PyJObject): ...

class UnaryTree[**Ts](jep._PyJObject): ...

class SwitchTree[**Ts](jep._PyJObject): ...

class ExpressionTree[**Ts](jep._PyJObject): ...

class PrimitiveTypeTree[**Ts](jep._PyJObject): ...

class LiteralTree[**Ts](jep._PyJObject): ...

class SynchronizedTree[**Ts](jep._PyJObject): ...

class Scope[**Ts](jep._PyJObject): ...

class OpensTree[**Ts](jep._PyJObject): ...

class ArrayTypeTree[**Ts](jep._PyJObject): ...

class CompilationUnitTree[**Ts](jep._PyJObject): ...

class IfTree[**Ts](jep._PyJObject): ...

class MethodTree[**Ts](jep._PyJObject): ...

class ModuleTree[**Ts](jep._PyJObject): ...

class WhileLoopTree[**Ts](jep._PyJObject): ...

class TreeVisitor[**Ts](jep._PyJObject): ...

class ClassTree[**Ts](jep._PyJObject): ...

class NewArrayTree[**Ts](jep._PyJObject): ...

class LineMap[**Ts](jep._PyJObject): ...

class UnionTypeTree[**Ts](jep._PyJObject): ...

class EnhancedForLoopTree[**Ts](jep._PyJObject): ...

class UsesTree[**Ts](jep._PyJObject): ...

class ConditionalExpressionTree[**Ts](jep._PyJObject): ...

class ContinueTree[**Ts](jep._PyJObject): ...

class TryTree[**Ts](jep._PyJObject): ...

class LabeledStatementTree[**Ts](jep._PyJObject): ...

class CompoundAssignmentTree[**Ts](jep._PyJObject): ...

