import jep

class Tree(jep.PyJObject): ...

class WildcardTree(jep.PyJObject): ...

class BreakTree(jep.PyJObject): ...

class RequiresTree(jep.PyJObject): ...

class CaseTree(jep.PyJObject): ...

class IntersectionTypeTree(jep.PyJObject): ...

class CompoundAssignmentTree(jep.PyJObject): ...

class InstanceOfTree(jep.PyJObject): ...

class WhileLoopTree(jep.PyJObject): ...

class Scope(jep.PyJObject): ...

class PackageTree(jep.PyJObject): ...

class NewClassTree(jep.PyJObject): ...

class MethodTree(jep.PyJObject): ...

class UnaryTree(jep.PyJObject): ...

class AssertTree(jep.PyJObject): ...

class AssignmentTree(jep.PyJObject): ...

class ClassTree(jep.PyJObject): ...

class UsesTree(jep.PyJObject): ...

class LambdaExpressionTree(jep.PyJObject): ...

class LiteralTree(jep.PyJObject): ...

class AnnotationTree(jep.PyJObject): ...

class ModuleTree(jep.PyJObject): ...

class IdentifierTree(jep.PyJObject): ...

class ContinueTree(jep.PyJObject): ...

class BinaryTree(jep.PyJObject): ...

class TypeCastTree(jep.PyJObject): ...

class ArrayTypeTree(jep.PyJObject): ...

class CatchTree(jep.PyJObject): ...

class ParenthesizedTree(jep.PyJObject): ...

class ExpressionTree(jep.PyJObject): ...

class BlockTree(jep.PyJObject): ...

class MethodInvocationTree(jep.PyJObject): ...

class EnhancedForLoopTree(jep.PyJObject): ...

class MemberSelectTree(jep.PyJObject): ...

class MemberReferenceTree(jep.PyJObject): ...

class OpensTree(jep.PyJObject): ...

class SynchronizedTree(jep.PyJObject): ...

class ModifiersTree(jep.PyJObject): ...

class ConditionalExpressionTree(jep.PyJObject): ...

class SwitchTree(jep.PyJObject): ...

class NewArrayTree(jep.PyJObject): ...

class ExpressionStatementTree(jep.PyJObject): ...

class LineMap(jep.PyJObject): ...

class DirectiveTree(jep.PyJObject): ...

class ImportTree(jep.PyJObject): ...

class ThrowTree(jep.PyJObject): ...

class ProvidesTree(jep.PyJObject): ...

class TreeVisitor(jep.PyJObject): ...

class TryTree(jep.PyJObject): ...

class ArrayAccessTree(jep.PyJObject): ...

class ParameterizedTypeTree(jep.PyJObject): ...

class CompilationUnitTree(jep.PyJObject): ...

class DoWhileLoopTree(jep.PyJObject): ...

class UnionTypeTree(jep.PyJObject): ...

class TypeParameterTree(jep.PyJObject): ...

class VariableTree(jep.PyJObject): ...

class IfTree(jep.PyJObject): ...

class ErroneousTree(jep.PyJObject): ...

class ExportsTree(jep.PyJObject): ...

class ForLoopTree(jep.PyJObject): ...

class LabeledStatementTree(jep.PyJObject): ...

class StatementTree(jep.PyJObject): ...

class AnnotatedTypeTree(jep.PyJObject): ...

class ReturnTree(jep.PyJObject): ...

class PrimitiveTypeTree(jep.PyJObject): ...

class EmptyStatementTree(jep.PyJObject): ...

