import jep

class DocTreeScanner(jep._PyJObject): ...

class TreePath(jep._PyJObject): ...

class DocTreeFactory(jep._PyJObject): ...

class TreeScanner(jep._PyJObject): ...

class SimpleDocTreeVisitor(jep._PyJObject): ...

class SimpleTreeVisitor(jep._PyJObject): ...

class JavacTask(jep._PyJObject): ...

class DocTreePath(jep._PyJObject): ...

class TreePathScanner(jep._PyJObject): ...

class Trees(jep._PyJObject): ...

class Plugin(jep._PyJObject): ...

class DocSourcePositions(jep._PyJObject): ...

class DocTrees(jep._PyJObject): ...

class TaskEvent(jep._PyJObject): ...

class DocTreePathScanner(jep._PyJObject): ...

class TaskListener(jep._PyJObject): ...

class SourcePositions(jep._PyJObject): ...

