# pyright: reportPrivateUsage = none

import jep

class DocTrees[**Ts](jep._PyJObject): ...

class TreeScanner[**Ts](jep._PyJObject): ...

class TaskListener[**Ts](jep._PyJObject): ...

class DocTreeScanner[**Ts](jep._PyJObject): ...

class JavacTask[**Ts](jep._PyJObject): ...

class TreePathScanner[**Ts](jep._PyJObject): ...

class SourcePositions[**Ts](jep._PyJObject): ...

class TreePath[**Ts](jep._PyJObject): ...

class DocTreeFactory[**Ts](jep._PyJObject): ...

class SimpleTreeVisitor[**Ts](jep._PyJObject): ...

class Trees[**Ts](jep._PyJObject): ...

class TaskEvent[**Ts](jep._PyJObject): ...

class Plugin[**Ts](jep._PyJObject): ...

class SimpleDocTreeVisitor[**Ts](jep._PyJObject): ...

class DocTreePath[**Ts](jep._PyJObject): ...

class DocTreePathScanner[**Ts](jep._PyJObject): ...

class DocSourcePositions[**Ts](jep._PyJObject): ...

