import jep

class DocTreeScanner(jep.PyJObject): ...

class TreePath(jep.PyJObject): ...

class DocTreeFactory(jep.PyJObject): ...

class TreeScanner(jep.PyJObject): ...

class SimpleDocTreeVisitor(jep.PyJObject): ...

class SimpleTreeVisitor(jep.PyJObject): ...

class JavacTask(jep.PyJObject): ...

class DocTreePath(jep.PyJObject): ...

class TreePathScanner(jep.PyJObject): ...

class Trees(jep.PyJObject): ...

class Plugin(jep.PyJObject): ...

class DocSourcePositions(jep.PyJObject): ...

class DocTrees(jep.PyJObject): ...

class TaskEvent(jep.PyJObject): ...

class DocTreePathScanner(jep.PyJObject): ...

class TaskListener(jep.PyJObject): ...

class SourcePositions(jep.PyJObject): ...

