import jep

class InvalidationListener(jep._PyJObject): ...

class WeakListener(jep._PyJObject): ...

class DefaultProperty(jep._PyJObject): ...

class NamedArg(jep._PyJObject): ...

class WeakInvalidationListener(jep._PyJObject): ...

class Observable(jep._PyJObject): ...

