import jep

class InvalidationListener(jep.PyJObject): ...

class WeakListener(jep.PyJObject): ...

class DefaultProperty(jep.PyJObject): ...

class NamedArg(jep.PyJObject): ...

class WeakInvalidationListener(jep.PyJObject): ...

class Observable(jep.PyJObject): ...

