# pyright: reportPrivateUsage = none

import jep

class WeakInvalidationListener[**Ts](jep._PyJObject): ...

class WeakListener[**Ts](jep._PyJObject): ...

class Observable[**Ts](jep._PyJObject): ...

class InvalidationListener[**Ts](jep._PyJObject): ...

class NamedArg[**Ts](jep._PyJObject): ...

class DefaultProperty[**Ts](jep._PyJObject): ...

