import jep

class NumberBinding(jep.PyJObject): ...

class LongBinding(jep.PyJObject): ...

class BooleanExpression(jep.PyJObject): ...

class IntegerExpression(jep.PyJObject): ...

class FloatExpression(jep.PyJObject): ...

class NumberExpressionBase(jep.PyJObject): ...

class ObjectExpression(jep.PyJObject): ...

class ListBinding(jep.PyJObject): ...

class Binding(jep.PyJObject): ...

class LongExpression(jep.PyJObject): ...

class When(jep.PyJObject): ...

class ObjectBinding(jep.PyJObject): ...

class DoubleBinding(jep.PyJObject): ...

class SetBinding(jep.PyJObject): ...

class IntegerBinding(jep.PyJObject): ...

class ListExpression(jep.PyJObject): ...

class DoubleExpression(jep.PyJObject): ...

class StringBinding(jep.PyJObject): ...

class MapExpression(jep.PyJObject): ...

class SetExpression(jep.PyJObject): ...

class Bindings(jep.PyJObject): ...

class MapBinding(jep.PyJObject): ...

class NumberExpression(jep.PyJObject): ...

class BooleanBinding(jep.PyJObject): ...

class FloatBinding(jep.PyJObject): ...

class StringExpression(jep.PyJObject): ...

