import jep

class NumberBinding(jep._PyJObject): ...

class LongBinding(jep._PyJObject): ...

class BooleanExpression(jep._PyJObject): ...

class IntegerExpression(jep._PyJObject): ...

class FloatExpression(jep._PyJObject): ...

class NumberExpressionBase(jep._PyJObject): ...

class ObjectExpression(jep._PyJObject): ...

class ListBinding(jep._PyJObject): ...

class Binding(jep._PyJObject): ...

class LongExpression(jep._PyJObject): ...

class When(jep._PyJObject): ...

class ObjectBinding(jep._PyJObject): ...

class DoubleBinding(jep._PyJObject): ...

class SetBinding(jep._PyJObject): ...

class IntegerBinding(jep._PyJObject): ...

class ListExpression(jep._PyJObject): ...

class DoubleExpression(jep._PyJObject): ...

class StringBinding(jep._PyJObject): ...

class MapExpression(jep._PyJObject): ...

class SetExpression(jep._PyJObject): ...

class Bindings(jep._PyJObject): ...

class MapBinding(jep._PyJObject): ...

class NumberExpression(jep._PyJObject): ...

class BooleanBinding(jep._PyJObject): ...

class FloatBinding(jep._PyJObject): ...

class StringExpression(jep._PyJObject): ...

