# pyright: reportPrivateUsage = none

import jep

class IntegerBinding[**Ts](jep._PyJObject): ...

class ObjectExpression[**Ts](jep._PyJObject): ...

class When[**Ts](jep._PyJObject): ...

class FloatExpression[**Ts](jep._PyJObject): ...

class MapExpression[**Ts](jep._PyJObject): ...

class SetExpression[**Ts](jep._PyJObject): ...

class DoubleBinding[**Ts](jep._PyJObject): ...

class ListBinding[**Ts](jep._PyJObject): ...

class IntegerExpression[**Ts](jep._PyJObject): ...

class ListExpression[**Ts](jep._PyJObject): ...

class SetBinding[**Ts](jep._PyJObject): ...

class LongBinding[**Ts](jep._PyJObject): ...

class StringBinding[**Ts](jep._PyJObject): ...

class NumberExpression[**Ts](jep._PyJObject): ...

class Binding[**Ts](jep._PyJObject): ...

class NumberBinding[**Ts](jep._PyJObject): ...

class ObjectBinding[**Ts](jep._PyJObject): ...

class NumberExpressionBase[**Ts](jep._PyJObject): ...

class Bindings[**Ts](jep._PyJObject): ...

class FloatBinding[**Ts](jep._PyJObject): ...

class BooleanBinding[**Ts](jep._PyJObject): ...

class LongExpression[**Ts](jep._PyJObject): ...

class MapBinding[**Ts](jep._PyJObject): ...

class DoubleExpression[**Ts](jep._PyJObject): ...

class BooleanExpression[**Ts](jep._PyJObject): ...

class StringExpression[**Ts](jep._PyJObject): ...

