import jep

class WritableBooleanValue(jep.PyJObject): ...

class ObservableStringValue(jep.PyJObject): ...

class ObservableDoubleValue(jep.PyJObject): ...

class WritableMapValue(jep.PyJObject): ...

class WritableDoubleValue(jep.PyJObject): ...

class WritableIntegerValue(jep.PyJObject): ...

class ObservableLongValue(jep.PyJObject): ...

class ObservableBooleanValue(jep.PyJObject): ...

class WritableValue(jep.PyJObject): ...

class ObservableValueBase(jep.PyJObject): ...

class WritableFloatValue(jep.PyJObject): ...

class WeakChangeListener(jep.PyJObject): ...

class ObservableNumberValue(jep.PyJObject): ...

class ObservableListValue(jep.PyJObject): ...

class WritableListValue(jep.PyJObject): ...

class WritableSetValue(jep.PyJObject): ...

class ObservableMapValue(jep.PyJObject): ...

class ChangeListener(jep.PyJObject): ...

class ObservableFloatValue(jep.PyJObject): ...

class ObservableObjectValue(jep.PyJObject): ...

class WritableObjectValue(jep.PyJObject): ...

class ObservableIntegerValue(jep.PyJObject): ...

class WritableNumberValue(jep.PyJObject): ...

class ObservableValue(jep.PyJObject): ...

class WritableStringValue(jep.PyJObject): ...

class WritableLongValue(jep.PyJObject): ...

