import jep

class WritableBooleanValue(jep._PyJObject): ...

class ObservableStringValue(jep._PyJObject): ...

class ObservableDoubleValue(jep._PyJObject): ...

class WritableMapValue(jep._PyJObject): ...

class WritableDoubleValue(jep._PyJObject): ...

class WritableIntegerValue(jep._PyJObject): ...

class ObservableLongValue(jep._PyJObject): ...

class ObservableBooleanValue(jep._PyJObject): ...

class WritableValue(jep._PyJObject): ...

class ObservableValueBase(jep._PyJObject): ...

class WritableFloatValue(jep._PyJObject): ...

class WeakChangeListener(jep._PyJObject): ...

class ObservableNumberValue(jep._PyJObject): ...

class ObservableListValue(jep._PyJObject): ...

class WritableListValue(jep._PyJObject): ...

class WritableSetValue(jep._PyJObject): ...

class ObservableMapValue(jep._PyJObject): ...

class ChangeListener(jep._PyJObject): ...

class ObservableFloatValue(jep._PyJObject): ...

class ObservableObjectValue(jep._PyJObject): ...

class WritableObjectValue(jep._PyJObject): ...

class ObservableIntegerValue(jep._PyJObject): ...

class WritableNumberValue(jep._PyJObject): ...

class ObservableValue(jep._PyJObject): ...

class WritableStringValue(jep._PyJObject): ...

class WritableLongValue(jep._PyJObject): ...

