# pyright: reportPrivateUsage = none

import jep

class ObservableNumberValue[**Ts](jep._PyJObject): ...

class WritableIntegerValue[**Ts](jep._PyJObject): ...

class WritableDoubleValue[**Ts](jep._PyJObject): ...

class WritableListValue[**Ts](jep._PyJObject): ...

class ObservableStringValue[**Ts](jep._PyJObject): ...

class ObservableBooleanValue[**Ts](jep._PyJObject): ...

class WritableMapValue[**Ts](jep._PyJObject): ...

class WritableLongValue[**Ts](jep._PyJObject): ...

class ChangeListener[**Ts](jep._PyJObject): ...

class WritableValue[**Ts](jep._PyJObject): ...

class ObservableValue[**Ts](jep._PyJObject): ...

class ObservableMapValue[**Ts](jep._PyJObject): ...

class WritableBooleanValue[**Ts](jep._PyJObject): ...

class WritableFloatValue[**Ts](jep._PyJObject): ...

class ObservableIntegerValue[**Ts](jep._PyJObject): ...

class WritableObjectValue[**Ts](jep._PyJObject): ...

class WeakChangeListener[**Ts](jep._PyJObject): ...

class ObservableObjectValue[**Ts](jep._PyJObject): ...

class WritableNumberValue[**Ts](jep._PyJObject): ...

class ObservableListValue[**Ts](jep._PyJObject): ...

class ObservableFloatValue[**Ts](jep._PyJObject): ...

class ObservableDoubleValue[**Ts](jep._PyJObject): ...

class ObservableLongValue[**Ts](jep._PyJObject): ...

class WritableStringValue[**Ts](jep._PyJObject): ...

class ObservableSetValue[**Ts](jep._PyJObject): ...

class ObservableValueBase[**Ts](jep._PyJObject): ...

