import jep

class Clip(jep.PyJObject): ...

class AudioSystem(jep.PyJObject): ...

class DataLine(jep.PyJObject): ...

class UnsupportedAudioFileException(jep.PyJObject): ...

class CompoundControl(jep.PyJObject): ...

class AudioInputStream(jep.PyJObject): ...

class BooleanControl(jep.PyJObject): ...

class FloatControl(jep.PyJObject): ...

class EnumControl(jep.PyJObject): ...

class Port(jep.PyJObject): ...

class Control(jep.PyJObject): ...

class ReverbType(jep.PyJObject): ...

class AudioPermission(jep.PyJObject): ...

class Mixer(jep.PyJObject): ...

class AudioFormat(jep.PyJObject): ...

class LineUnavailableException(jep.PyJObject): ...

class LineEvent(jep.PyJObject): ...

class TargetDataLine(jep.PyJObject): ...

class Line(jep.PyJObject): ...

class SourceDataLine(jep.PyJObject): ...

class LineListener(jep.PyJObject): ...

class AudioFileFormat(jep.PyJObject): ...

