# pyright: reportPrivateUsage = none

import jep

class AudioSystem[**Ts](jep._PyJObject): ...

class LineListener[**Ts](jep._PyJObject): ...

class ReverbType[**Ts](jep._PyJObject): ...

class AudioFileFormat[**Ts](jep._PyJObject): ...

class EnumControl[**Ts](jep._PyJObject): ...

class SourceDataLine[**Ts](jep._PyJObject): ...

class AudioInputStream[**Ts](jep._PyJObject): ...

class TargetDataLine[**Ts](jep._PyJObject): ...

class Mixer[**Ts](jep._PyJObject): ...

class Line[**Ts](jep._PyJObject): ...

class BooleanControl[**Ts](jep._PyJObject): ...

class LineEvent[**Ts](jep._PyJObject): ...

class DataLine[**Ts](jep._PyJObject): ...

class AudioPermission[**Ts](jep._PyJObject): ...

class UnsupportedAudioFileException[**Ts](jep._PyJObject): ...

class AudioFormat[**Ts](jep._PyJObject): ...

class LineUnavailableException[**Ts](jep._PyJObject): ...

class Port[**Ts](jep._PyJObject): ...

class CompoundControl[**Ts](jep._PyJObject): ...

class Clip[**Ts](jep._PyJObject): ...

class Control[**Ts](jep._PyJObject): ...

class FloatControl[**Ts](jep._PyJObject): ...

