import jep

class Clip(jep._PyJObject): ...

class AudioSystem(jep._PyJObject): ...

class DataLine(jep._PyJObject): ...

class UnsupportedAudioFileException(jep._PyJObject): ...

class CompoundControl(jep._PyJObject): ...

class AudioInputStream(jep._PyJObject): ...

class BooleanControl(jep._PyJObject): ...

class FloatControl(jep._PyJObject): ...

class EnumControl(jep._PyJObject): ...

class Port(jep._PyJObject): ...

class Control(jep._PyJObject): ...

class ReverbType(jep._PyJObject): ...

class AudioPermission(jep._PyJObject): ...

class Mixer(jep._PyJObject): ...

class AudioFormat(jep._PyJObject): ...

class LineUnavailableException(jep._PyJObject): ...

class LineEvent(jep._PyJObject): ...

class TargetDataLine(jep._PyJObject): ...

class Line(jep._PyJObject): ...

class SourceDataLine(jep._PyJObject): ...

class LineListener(jep._PyJObject): ...

class AudioFileFormat(jep._PyJObject): ...

