import jep

class Pair(jep._PyJObject): ...

class Duration(jep._PyJObject): ...

class Builder(jep._PyJObject): ...

class StringConverter(jep._PyJObject): ...

class FXPermission(jep._PyJObject): ...

class Callback(jep._PyJObject): ...

class BuilderFactory(jep._PyJObject): ...

