import jep

class Pair(jep.PyJObject): ...

class Duration(jep.PyJObject): ...

class Builder(jep.PyJObject): ...

class StringConverter(jep.PyJObject): ...

class FXPermission(jep.PyJObject): ...

class Callback(jep.PyJObject): ...

class BuilderFactory(jep.PyJObject): ...

