# pyright: reportPrivateUsage = none

import jep

class Duration[**Ts](jep._PyJObject): ...

class FXPermission[**Ts](jep._PyJObject): ...

class StringConverter[**Ts](jep._PyJObject): ...

class Pair[**Ts](jep._PyJObject): ...

class Callback[**Ts](jep._PyJObject): ...

class Builder[**Ts](jep._PyJObject): ...

class BuilderFactory[**Ts](jep._PyJObject): ...

