import jep

class BooleanStringConverter(jep.PyJObject): ...

class ByteStringConverter(jep.PyJObject): ...

class NumberStringConverter(jep.PyJObject): ...

class BigIntegerStringConverter(jep.PyJObject): ...

class DoubleStringConverter(jep.PyJObject): ...

class CurrencyStringConverter(jep.PyJObject): ...

class ShortStringConverter(jep.PyJObject): ...

class FormatStringConverter(jep.PyJObject): ...

class IntegerStringConverter(jep.PyJObject): ...

class PercentageStringConverter(jep.PyJObject): ...

class LocalDateTimeStringConverter(jep.PyJObject): ...

class DefaultStringConverter(jep.PyJObject): ...

class FloatStringConverter(jep.PyJObject): ...

class LocalTimeStringConverter(jep.PyJObject): ...

class TimeStringConverter(jep.PyJObject): ...

class DateTimeStringConverter(jep.PyJObject): ...

class CharacterStringConverter(jep.PyJObject): ...

class LocalDateStringConverter(jep.PyJObject): ...

class LongStringConverter(jep.PyJObject): ...

class BigDecimalStringConverter(jep.PyJObject): ...

