import jep

class BooleanStringConverter(jep._PyJObject): ...

class ByteStringConverter(jep._PyJObject): ...

class NumberStringConverter(jep._PyJObject): ...

class BigIntegerStringConverter(jep._PyJObject): ...

class DoubleStringConverter(jep._PyJObject): ...

class CurrencyStringConverter(jep._PyJObject): ...

class ShortStringConverter(jep._PyJObject): ...

class FormatStringConverter(jep._PyJObject): ...

class IntegerStringConverter(jep._PyJObject): ...

class PercentageStringConverter(jep._PyJObject): ...

class LocalDateTimeStringConverter(jep._PyJObject): ...

class DefaultStringConverter(jep._PyJObject): ...

class FloatStringConverter(jep._PyJObject): ...

class LocalTimeStringConverter(jep._PyJObject): ...

class TimeStringConverter(jep._PyJObject): ...

class DateTimeStringConverter(jep._PyJObject): ...

class CharacterStringConverter(jep._PyJObject): ...

class LocalDateStringConverter(jep._PyJObject): ...

class LongStringConverter(jep._PyJObject): ...

class BigDecimalStringConverter(jep._PyJObject): ...

