# pyright: reportPrivateUsage = none

import jep

class BigDecimalStringConverter[**Ts](jep._PyJObject): ...

class FormatStringConverter[**Ts](jep._PyJObject): ...

class PercentageStringConverter[**Ts](jep._PyJObject): ...

class CharacterStringConverter[**Ts](jep._PyJObject): ...

class LongStringConverter[**Ts](jep._PyJObject): ...

class LocalDateTimeStringConverter[**Ts](jep._PyJObject): ...

class FloatStringConverter[**Ts](jep._PyJObject): ...

class CurrencyStringConverter[**Ts](jep._PyJObject): ...

class ShortStringConverter[**Ts](jep._PyJObject): ...

class DateStringConverter[**Ts](jep._PyJObject): ...

class IntegerStringConverter[**Ts](jep._PyJObject): ...

class ByteStringConverter[**Ts](jep._PyJObject): ...

class DefaultStringConverter[**Ts](jep._PyJObject): ...

class DateTimeStringConverter[**Ts](jep._PyJObject): ...

class NumberStringConverter[**Ts](jep._PyJObject): ...

class LocalTimeStringConverter[**Ts](jep._PyJObject): ...

class BigIntegerStringConverter[**Ts](jep._PyJObject): ...

class BooleanStringConverter[**Ts](jep._PyJObject): ...

class DoubleStringConverter[**Ts](jep._PyJObject): ...

class LocalDateStringConverter[**Ts](jep._PyJObject): ...

