# pyright: reportPrivateUsage = none

import jep

class PropertyChangeEvent[**Ts](jep._PyJObject): ...

class VetoableChangeListenerProxy[**Ts](jep._PyJObject): ...

class PropertyEditorSupport[**Ts](jep._PyJObject): ...

class IndexedPropertyChangeEvent[**Ts](jep._PyJObject): ...

class DefaultPersistenceDelegate[**Ts](jep._PyJObject): ...

class Encoder[**Ts](jep._PyJObject): ...

class Customizer[**Ts](jep._PyJObject): ...

class PropertyEditorManager[**Ts](jep._PyJObject): ...

class PropertyEditor[**Ts](jep._PyJObject): ...

class Visibility[**Ts](jep._PyJObject): ...

class BeanInfo[**Ts](jep._PyJObject): ...

class Transient[**Ts](jep._PyJObject): ...

class PropertyChangeListenerProxy[**Ts](jep._PyJObject): ...

class EventSetDescriptor[**Ts](jep._PyJObject): ...

class VetoableChangeSupport[**Ts](jep._PyJObject): ...

class PersistenceDelegate[**Ts](jep._PyJObject): ...

class ParameterDescriptor[**Ts](jep._PyJObject): ...

class XMLDecoder[**Ts](jep._PyJObject): ...

class DesignMode[**Ts](jep._PyJObject): ...

class PropertyChangeSupport[**Ts](jep._PyJObject): ...

class PropertyChangeListener[**Ts](jep._PyJObject): ...

class PropertyDescriptor[**Ts](jep._PyJObject): ...

class VetoableChangeListener[**Ts](jep._PyJObject): ...

class BeanDescriptor[**Ts](jep._PyJObject): ...

class XMLEncoder[**Ts](jep._PyJObject): ...

class BeanProperty[**Ts](jep._PyJObject): ...

class FeatureDescriptor[**Ts](jep._PyJObject): ...

class EventHandler[**Ts](jep._PyJObject): ...

class JavaBean[**Ts](jep._PyJObject): ...

class ExceptionListener[**Ts](jep._PyJObject): ...

class SimpleBeanInfo[**Ts](jep._PyJObject): ...

class AppletInitializer[**Ts](jep._PyJObject): ...

class Expression[**Ts](jep._PyJObject): ...

class Beans[**Ts](jep._PyJObject): ...

class IndexedPropertyDescriptor[**Ts](jep._PyJObject): ...

class MethodDescriptor[**Ts](jep._PyJObject): ...

class Introspector[**Ts](jep._PyJObject): ...

class ConstructorProperties[**Ts](jep._PyJObject): ...

class Statement[**Ts](jep._PyJObject): ...

class IntrospectionException[**Ts](jep._PyJObject): ...

class PropertyVetoException[**Ts](jep._PyJObject): ...

