import jep

class Encoder(jep.PyJObject): ...

class PropertyChangeListener(jep.PyJObject): ...

class Beans(jep.PyJObject): ...

class IndexedPropertyChangeEvent(jep.PyJObject): ...

class BeanProperty(jep.PyJObject): ...

class PropertyChangeEvent(jep.PyJObject): ...

class ParameterDescriptor(jep.PyJObject): ...

class Introspector(jep.PyJObject): ...

class VetoableChangeSupport(jep.PyJObject): ...

class PropertyDescriptor(jep.PyJObject): ...

class IntrospectionException(jep.PyJObject): ...

class XMLDecoder(jep.PyJObject): ...

class ExceptionListener(jep.PyJObject): ...

class MethodDescriptor(jep.PyJObject): ...

class ConstructorProperties(jep.PyJObject): ...

class IndexedPropertyDescriptor(jep.PyJObject): ...

class PropertyChangeListenerProxy(jep.PyJObject): ...

class Expression(jep.PyJObject): ...

class VetoableChangeListenerProxy(jep.PyJObject): ...

class Visibility(jep.PyJObject): ...

class EventSetDescriptor(jep.PyJObject): ...

class Statement(jep.PyJObject): ...

class JavaBean(jep.PyJObject): ...

class PropertyChangeSupport(jep.PyJObject): ...

class FeatureDescriptor(jep.PyJObject): ...

class XMLEncoder(jep.PyJObject): ...

class PropertyEditorSupport(jep.PyJObject): ...

class PropertyEditor(jep.PyJObject): ...

class AppletInitializer(jep.PyJObject): ...

class VetoableChangeListener(jep.PyJObject): ...

class BeanDescriptor(jep.PyJObject): ...

class BeanInfo(jep.PyJObject): ...

class PropertyVetoException(jep.PyJObject): ...

class DefaultPersistenceDelegate(jep.PyJObject): ...

class Transient(jep.PyJObject): ...

class PropertyEditorManager(jep.PyJObject): ...

class SimpleBeanInfo(jep.PyJObject): ...

class Customizer(jep.PyJObject): ...

class PersistenceDelegate(jep.PyJObject): ...

class DesignMode(jep.PyJObject): ...

class EventHandler(jep.PyJObject): ...

