import jep

class Encoder(jep._PyJObject): ...

class PropertyChangeListener(jep._PyJObject): ...

class Beans(jep._PyJObject): ...

class IndexedPropertyChangeEvent(jep._PyJObject): ...

class BeanProperty(jep._PyJObject): ...

class PropertyChangeEvent(jep._PyJObject): ...

class ParameterDescriptor(jep._PyJObject): ...

class Introspector(jep._PyJObject): ...

class VetoableChangeSupport(jep._PyJObject): ...

class PropertyDescriptor(jep._PyJObject): ...

class IntrospectionException(jep._PyJObject): ...

class XMLDecoder(jep._PyJObject): ...

class ExceptionListener(jep._PyJObject): ...

class MethodDescriptor(jep._PyJObject): ...

class ConstructorProperties(jep._PyJObject): ...

class IndexedPropertyDescriptor(jep._PyJObject): ...

class PropertyChangeListenerProxy(jep._PyJObject): ...

class Expression(jep._PyJObject): ...

class VetoableChangeListenerProxy(jep._PyJObject): ...

class Visibility(jep._PyJObject): ...

class EventSetDescriptor(jep._PyJObject): ...

class Statement(jep._PyJObject): ...

class JavaBean(jep._PyJObject): ...

class PropertyChangeSupport(jep._PyJObject): ...

class FeatureDescriptor(jep._PyJObject): ...

class XMLEncoder(jep._PyJObject): ...

class PropertyEditorSupport(jep._PyJObject): ...

class PropertyEditor(jep._PyJObject): ...

class AppletInitializer(jep._PyJObject): ...

class VetoableChangeListener(jep._PyJObject): ...

class BeanDescriptor(jep._PyJObject): ...

class BeanInfo(jep._PyJObject): ...

class PropertyVetoException(jep._PyJObject): ...

class DefaultPersistenceDelegate(jep._PyJObject): ...

class Transient(jep._PyJObject): ...

class PropertyEditorManager(jep._PyJObject): ...

class SimpleBeanInfo(jep._PyJObject): ...

class Customizer(jep._PyJObject): ...

class PersistenceDelegate(jep._PyJObject): ...

class DesignMode(jep._PyJObject): ...

class EventHandler(jep._PyJObject): ...

