import jep

class BeanContextChild(jep.PyJObject): ...

class BeanContextServiceRevokedListener(jep.PyJObject): ...

class BeanContextServiceProvider(jep.PyJObject): ...

class BeanContextChildComponentProxy(jep.PyJObject): ...

class BeanContextProxy(jep.PyJObject): ...

class BeanContextServices(jep.PyJObject): ...

class BeanContextServicesSupport(jep.PyJObject): ...

class BeanContextChildSupport(jep.PyJObject): ...

class BeanContextContainerProxy(jep.PyJObject): ...

class BeanContext(jep.PyJObject): ...

class BeanContextMembershipListener(jep.PyJObject): ...

class BeanContextSupport(jep.PyJObject): ...

class BeanContextServiceProviderBeanInfo(jep.PyJObject): ...

class BeanContextEvent(jep.PyJObject): ...

class BeanContextServicesListener(jep.PyJObject): ...

class BeanContextServiceAvailableEvent(jep.PyJObject): ...

class BeanContextServiceRevokedEvent(jep.PyJObject): ...

