# pyright: reportPrivateUsage = none

import jep

class BeanContextContainerProxy[**Ts](jep._PyJObject): ...

class BeanContextChildSupport[**Ts](jep._PyJObject): ...

class BeanContextChild[**Ts](jep._PyJObject): ...

class BeanContextServices[**Ts](jep._PyJObject): ...

class BeanContextServiceProvider[**Ts](jep._PyJObject): ...

class BeanContextServicesListener[**Ts](jep._PyJObject): ...

class BeanContextServiceProviderBeanInfo[**Ts](jep._PyJObject): ...

class BeanContextMembershipListener[**Ts](jep._PyJObject): ...

class BeanContextServiceAvailableEvent[**Ts](jep._PyJObject): ...

class BeanContextServiceRevokedEvent[**Ts](jep._PyJObject): ...

class BeanContextEvent[**Ts](jep._PyJObject): ...

class BeanContextServicesSupport[**Ts](jep._PyJObject): ...

class BeanContextProxy[**Ts](jep._PyJObject): ...

class BeanContext[**Ts](jep._PyJObject): ...

class BeanContextServiceRevokedListener[**Ts](jep._PyJObject): ...

class BeanContextChildComponentProxy[**Ts](jep._PyJObject): ...

class BeanContextMembershipEvent[**Ts](jep._PyJObject): ...

