import jep

class BeanContextChild(jep._PyJObject): ...

class BeanContextServiceRevokedListener(jep._PyJObject): ...

class BeanContextServiceProvider(jep._PyJObject): ...

class BeanContextChildComponentProxy(jep._PyJObject): ...

class BeanContextProxy(jep._PyJObject): ...

class BeanContextServices(jep._PyJObject): ...

class BeanContextServicesSupport(jep._PyJObject): ...

class BeanContextChildSupport(jep._PyJObject): ...

class BeanContextContainerProxy(jep._PyJObject): ...

class BeanContext(jep._PyJObject): ...

class BeanContextMembershipListener(jep._PyJObject): ...

class BeanContextSupport(jep._PyJObject): ...

class BeanContextServiceProviderBeanInfo(jep._PyJObject): ...

class BeanContextEvent(jep._PyJObject): ...

class BeanContextServicesListener(jep._PyJObject): ...

class BeanContextServiceAvailableEvent(jep._PyJObject): ...

class BeanContextServiceRevokedEvent(jep._PyJObject): ...

