import jep

class Animation(jep.PyJObject): ...

class PauseTransition(jep.PyJObject): ...

class FadeTransition(jep.PyJObject): ...

class Interpolator(jep.PyJObject): ...

class KeyValue(jep.PyJObject): ...

class PathTransition(jep.PyJObject): ...

class ScaleTransition(jep.PyJObject): ...

class AnimationTimer(jep.PyJObject): ...

class ParallelTransition(jep.PyJObject): ...

class Transition(jep.PyJObject): ...

class StrokeTransition(jep.PyJObject): ...

class RotateTransition(jep.PyJObject): ...

class Timeline(jep.PyJObject): ...

class FillTransition(jep.PyJObject): ...

class SequentialTransition(jep.PyJObject): ...

class KeyFrame(jep.PyJObject): ...

class Interpolatable(jep.PyJObject): ...

class TranslateTransition(jep.PyJObject): ...

