# pyright: reportPrivateUsage = none

import jep

class Interpolatable[**Ts](jep._PyJObject): ...

class TranslateTransition[**Ts](jep._PyJObject): ...

class FadeTransition[**Ts](jep._PyJObject): ...

class Transition[**Ts](jep._PyJObject): ...

class PathTransition[**Ts](jep._PyJObject): ...

class StrokeTransition[**Ts](jep._PyJObject): ...

class SequentialTransition[**Ts](jep._PyJObject): ...

class KeyFrame[**Ts](jep._PyJObject): ...

class RotateTransition[**Ts](jep._PyJObject): ...

class Timeline[**Ts](jep._PyJObject): ...

class Interpolator[**Ts](jep._PyJObject): ...

class AnimationTimer[**Ts](jep._PyJObject): ...

class KeyValue[**Ts](jep._PyJObject): ...

class ParallelTransition[**Ts](jep._PyJObject): ...

class FillTransition[**Ts](jep._PyJObject): ...

class PauseTransition[**Ts](jep._PyJObject): ...

class Animation[**Ts](jep._PyJObject): ...

class ScaleTransition[**Ts](jep._PyJObject): ...

