import jep

class Animation(jep._PyJObject): ...

class PauseTransition(jep._PyJObject): ...

class FadeTransition(jep._PyJObject): ...

class Interpolator(jep._PyJObject): ...

class KeyValue(jep._PyJObject): ...

class PathTransition(jep._PyJObject): ...

class ScaleTransition(jep._PyJObject): ...

class AnimationTimer(jep._PyJObject): ...

class ParallelTransition(jep._PyJObject): ...

class Transition(jep._PyJObject): ...

class StrokeTransition(jep._PyJObject): ...

class RotateTransition(jep._PyJObject): ...

class Timeline(jep._PyJObject): ...

class FillTransition(jep._PyJObject): ...

class SequentialTransition(jep._PyJObject): ...

class KeyFrame(jep._PyJObject): ...

class Interpolatable(jep._PyJObject): ...

class TranslateTransition(jep._PyJObject): ...

