# pyright: reportPrivateUsage = none

import jep

class ConditionalFeature[**Ts](jep._PyJObject): ...

class Application[**Ts](jep._PyJObject): ...

class HostServices[**Ts](jep._PyJObject): ...

class Platform[**Ts](jep._PyJObject): ...

class Preloader[**Ts](jep._PyJObject): ...

