import jep

class Application(jep._PyJObject): ...

class ConditionalFeature(jep._PyJObject): ...

class Preloader(jep._PyJObject): ...

class Platform(jep._PyJObject): ...

class HostServices(jep._PyJObject): ...

