import jep

class Application(jep.PyJObject): ...

class ConditionalFeature(jep.PyJObject): ...

class Preloader(jep.PyJObject): ...

class Platform(jep.PyJObject): ...

class HostServices(jep.PyJObject): ...

