# pyright: reportPrivateUsage = none

import jep

class WorkerStateEvent[**Ts](jep._PyJObject): ...

class Task[**Ts](jep._PyJObject): ...

class Service[**Ts](jep._PyJObject): ...

class Worker[**Ts](jep._PyJObject): ...

class ScheduledService[**Ts](jep._PyJObject): ...

