import jep

class ScheduledService(jep._PyJObject): ...

class Service(jep._PyJObject): ...

class WorkerStateEvent(jep._PyJObject): ...

class Worker(jep._PyJObject): ...

class Task(jep._PyJObject): ...

