import jep

class ScheduledService(jep.PyJObject): ...

class Service(jep.PyJObject): ...

class WorkerStateEvent(jep.PyJObject): ...

class Worker(jep.PyJObject): ...

class Task(jep.PyJObject): ...

