import jep

class EventDispatcher(jep.PyJObject): ...

class WeakEventHandler(jep.PyJObject): ...

class EventType(jep.PyJObject): ...

class ActionEvent(jep.PyJObject): ...

class EventDispatchChain(jep.PyJObject): ...

class EventTarget(jep.PyJObject): ...

class Event(jep.PyJObject): ...

class EventHandler(jep.PyJObject): ...

