import jep

class EventDispatcher(jep._PyJObject): ...

class WeakEventHandler(jep._PyJObject): ...

class EventType(jep._PyJObject): ...

class ActionEvent(jep._PyJObject): ...

class EventDispatchChain(jep._PyJObject): ...

class EventTarget(jep._PyJObject): ...

class Event(jep._PyJObject): ...

class EventHandler(jep._PyJObject): ...

