# pyright: reportPrivateUsage = none

import jep

class EventHandler[**Ts](jep._PyJObject): ...

class ActionEvent[**Ts](jep._PyJObject): ...

class EventTarget[**Ts](jep._PyJObject): ...

class Event[**Ts](jep._PyJObject): ...

class EventType[**Ts](jep._PyJObject): ...

class EventDispatcher[**Ts](jep._PyJObject): ...

class WeakEventHandler[**Ts](jep._PyJObject): ...

class EventDispatchChain[**Ts](jep._PyJObject): ...

