# pyright: reportPrivateUsage = none

import jep

class FXML[**Ts](jep._PyJObject): ...

class Initializable[**Ts](jep._PyJObject): ...

class LoadListener[**Ts](jep._PyJObject): ...

class LoadException[**Ts](jep._PyJObject): ...

class FXMLLoader[**Ts](jep._PyJObject): ...

class JavaFXBuilderFactory[**Ts](jep._PyJObject): ...

