import jep

class FXMLLoader(jep._PyJObject): ...

class JavaFXBuilderFactory(jep._PyJObject): ...

class LoadListener(jep._PyJObject): ...

class FXML(jep._PyJObject): ...

class LoadException(jep._PyJObject): ...

class Initializable(jep._PyJObject): ...

