import jep

class FXMLLoader(jep.PyJObject): ...

class JavaFXBuilderFactory(jep.PyJObject): ...

class LoadListener(jep.PyJObject): ...

class FXML(jep.PyJObject): ...

class LoadException(jep.PyJObject): ...

class Initializable(jep.PyJObject): ...

