# pyright: reportPrivateUsage = none

import jep

class Rectangle2D[**Ts](jep._PyJObject): ...

class Point3D[**Ts](jep._PyJObject): ...

class Bounds[**Ts](jep._PyJObject): ...

class Pos[**Ts](jep._PyJObject): ...

class Dimension2D[**Ts](jep._PyJObject): ...

class Insets[**Ts](jep._PyJObject): ...

class NodeOrientation[**Ts](jep._PyJObject): ...

class Orientation[**Ts](jep._PyJObject): ...

class VerticalDirection[**Ts](jep._PyJObject): ...

class VPos[**Ts](jep._PyJObject): ...

class Point2D[**Ts](jep._PyJObject): ...

class HorizontalDirection[**Ts](jep._PyJObject): ...

class HPos[**Ts](jep._PyJObject): ...

class Side[**Ts](jep._PyJObject): ...

class BoundingBox[**Ts](jep._PyJObject): ...

