import jep

class HorizontalDirection(jep._PyJObject): ...

class NodeOrientation(jep._PyJObject): ...

class Rectangle2D(jep._PyJObject): ...

class Dimension2D(jep._PyJObject): ...

class Point2D(jep._PyJObject): ...

class Bounds(jep._PyJObject): ...

class Side(jep._PyJObject): ...

class Orientation(jep._PyJObject): ...

class BoundingBox(jep._PyJObject): ...

class Pos(jep._PyJObject): ...

class Point3D(jep._PyJObject): ...

class Insets(jep._PyJObject): ...

class VPos(jep._PyJObject): ...

class HPos(jep._PyJObject): ...

class VerticalDirection(jep._PyJObject): ...

