import jep

class HorizontalDirection(jep.PyJObject): ...

class NodeOrientation(jep.PyJObject): ...

class Rectangle2D(jep.PyJObject): ...

class Dimension2D(jep.PyJObject): ...

class Point2D(jep.PyJObject): ...

class Bounds(jep.PyJObject): ...

class Side(jep.PyJObject): ...

class Orientation(jep.PyJObject): ...

class BoundingBox(jep.PyJObject): ...

class Pos(jep.PyJObject): ...

class Point3D(jep.PyJObject): ...

class Insets(jep.PyJObject): ...

class VPos(jep.PyJObject): ...

class HPos(jep.PyJObject): ...

class VerticalDirection(jep.PyJObject): ...

