import jep

class PageLayout(jep._PyJObject): ...

class PrinterAttributes(jep._PyJObject): ...

class PrintColor(jep._PyJObject): ...

class PrinterJob(jep._PyJObject): ...

class Collation(jep._PyJObject): ...

class PaperSource(jep._PyJObject): ...

class Printer(jep._PyJObject): ...

class PrintQuality(jep._PyJObject): ...

class PrintResolution(jep._PyJObject): ...

class JobSettings(jep._PyJObject): ...

class PrintSides(jep._PyJObject): ...

class PageRange(jep._PyJObject): ...

class Paper(jep._PyJObject): ...

class PageOrientation(jep._PyJObject): ...

