import jep

class PageLayout(jep.PyJObject): ...

class PrinterAttributes(jep.PyJObject): ...

class PrintColor(jep.PyJObject): ...

class PrinterJob(jep.PyJObject): ...

class Collation(jep.PyJObject): ...

class PaperSource(jep.PyJObject): ...

class Printer(jep.PyJObject): ...

class PrintQuality(jep.PyJObject): ...

class PrintResolution(jep.PyJObject): ...

class JobSettings(jep.PyJObject): ...

class PrintSides(jep.PyJObject): ...

class PageRange(jep.PyJObject): ...

class Paper(jep.PyJObject): ...

class PageOrientation(jep.PyJObject): ...

