# pyright: reportPrivateUsage = none

import jep

class PrintResolution[**Ts](jep._PyJObject): ...

class PageRange[**Ts](jep._PyJObject): ...

class PrintQuality[**Ts](jep._PyJObject): ...

class PrinterAttributes[**Ts](jep._PyJObject): ...

class Printer[**Ts](jep._PyJObject): ...

class JobSettings[**Ts](jep._PyJObject): ...

class Collation[**Ts](jep._PyJObject): ...

class PrintSides[**Ts](jep._PyJObject): ...

class PrinterJob[**Ts](jep._PyJObject): ...

class PrintColor[**Ts](jep._PyJObject): ...

class PageLayout[**Ts](jep._PyJObject): ...

class PageOrientation[**Ts](jep._PyJObject): ...

class Paper[**Ts](jep._PyJObject): ...

class PaperSource[**Ts](jep._PyJObject): ...

