import jep

class Stage(jep._PyJObject): ...

class FileChooser(jep._PyJObject): ...

class Screen(jep._PyJObject): ...

class WindowEvent(jep._PyJObject): ...

class Popup(jep._PyJObject): ...

class Window(jep._PyJObject): ...

class PopupWindow(jep._PyJObject): ...

class Modality(jep._PyJObject): ...

class StageStyle(jep._PyJObject): ...

class DirectoryChooser(jep._PyJObject): ...

