import jep

class Stage(jep.PyJObject): ...

class FileChooser(jep.PyJObject): ...

class Screen(jep.PyJObject): ...

class WindowEvent(jep.PyJObject): ...

class Popup(jep.PyJObject): ...

class Window(jep.PyJObject): ...

class PopupWindow(jep.PyJObject): ...

class Modality(jep.PyJObject): ...

class StageStyle(jep.PyJObject): ...

class DirectoryChooser(jep.PyJObject): ...

