# pyright: reportPrivateUsage = none

import jep

class WindowEvent[**Ts](jep._PyJObject): ...

class Window[**Ts](jep._PyJObject): ...

class Screen[**Ts](jep._PyJObject): ...

class DirectoryChooser[**Ts](jep._PyJObject): ...

class Popup[**Ts](jep._PyJObject): ...

class Stage[**Ts](jep._PyJObject): ...

class Modality[**Ts](jep._PyJObject): ...

class FileChooser[**Ts](jep._PyJObject): ...

class StageStyle[**Ts](jep._PyJObject): ...

class PopupWindow[**Ts](jep._PyJObject): ...

