# pyright: reportPrivateUsage = none

import jep

class SimpleFloatProperty[**Ts](jep._PyJObject): ...

class StringProperty[**Ts](jep._PyJObject): ...

class ReadOnlyDoubleProperty[**Ts](jep._PyJObject): ...

class BooleanPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyFloatProperty[**Ts](jep._PyJObject): ...

class IntegerPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyFloatWrapper[**Ts](jep._PyJObject): ...

class FloatProperty[**Ts](jep._PyJObject): ...

class LongProperty[**Ts](jep._PyJObject): ...

class MapProperty[**Ts](jep._PyJObject): ...

class ReadOnlyLongPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyLongProperty[**Ts](jep._PyJObject): ...

class ReadOnlyDoubleWrapper[**Ts](jep._PyJObject): ...

class ReadOnlyLongWrapper[**Ts](jep._PyJObject): ...

class SimpleObjectProperty[**Ts](jep._PyJObject): ...

class ReadOnlyStringProperty[**Ts](jep._PyJObject): ...

class MapPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyIntegerWrapper[**Ts](jep._PyJObject): ...

class DoubleProperty[**Ts](jep._PyJObject): ...

class ReadOnlyIntegerProperty[**Ts](jep._PyJObject): ...

class ReadOnlyListProperty[**Ts](jep._PyJObject): ...

class ReadOnlyBooleanPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyBooleanProperty[**Ts](jep._PyJObject): ...

class SimpleBooleanProperty[**Ts](jep._PyJObject): ...

class ReadOnlyListWrapper[**Ts](jep._PyJObject): ...

class LongPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyStringPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyFloatPropertyBase[**Ts](jep._PyJObject): ...

class SimpleMapProperty[**Ts](jep._PyJObject): ...

class SimpleIntegerProperty[**Ts](jep._PyJObject): ...

class ReadOnlyMapWrapper[**Ts](jep._PyJObject): ...

class BooleanProperty[**Ts](jep._PyJObject): ...

class FloatPropertyBase[**Ts](jep._PyJObject): ...

class SimpleLongProperty[**Ts](jep._PyJObject): ...

class ListPropertyBase[**Ts](jep._PyJObject): ...

class SimpleDoubleProperty[**Ts](jep._PyJObject): ...

class SimpleStringProperty[**Ts](jep._PyJObject): ...

class ReadOnlySetProperty[**Ts](jep._PyJObject): ...

class SetProperty[**Ts](jep._PyJObject): ...

class ReadOnlySetPropertyBase[**Ts](jep._PyJObject): ...

class SetPropertyBase[**Ts](jep._PyJObject): ...

class Property[**Ts](jep._PyJObject): ...

class SimpleListProperty[**Ts](jep._PyJObject): ...

class ReadOnlyMapPropertyBase[**Ts](jep._PyJObject): ...

class SimpleSetProperty[**Ts](jep._PyJObject): ...

class ReadOnlyMapProperty[**Ts](jep._PyJObject): ...

class ReadOnlyObjectPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyBooleanWrapper[**Ts](jep._PyJObject): ...

class ReadOnlyObjectProperty[**Ts](jep._PyJObject): ...

class IntegerProperty[**Ts](jep._PyJObject): ...

class ReadOnlySetWrapper[**Ts](jep._PyJObject): ...

class StringPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyStringWrapper[**Ts](jep._PyJObject): ...

class ReadOnlyProperty[**Ts](jep._PyJObject): ...

class ReadOnlyIntegerPropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyDoublePropertyBase[**Ts](jep._PyJObject): ...

class DoublePropertyBase[**Ts](jep._PyJObject): ...

class ReadOnlyListPropertyBase[**Ts](jep._PyJObject): ...

class ObjectPropertyBase[**Ts](jep._PyJObject): ...

class ObjectProperty[**Ts](jep._PyJObject): ...

class ReadOnlyObjectWrapper[**Ts](jep._PyJObject): ...

class ListProperty[**Ts](jep._PyJObject): ...

