import jep

class ReadOnlyIntegerPropertyBase(jep._PyJObject): ...

class ReadOnlyIntegerWrapper(jep._PyJObject): ...

class SimpleMapProperty(jep._PyJObject): ...

class SimpleBooleanProperty(jep._PyJObject): ...

class SimpleFloatProperty(jep._PyJObject): ...

class BooleanProperty(jep._PyJObject): ...

class ReadOnlyDoubleProperty(jep._PyJObject): ...

class ReadOnlyDoublePropertyBase(jep._PyJObject): ...

class ReadOnlyObjectPropertyBase(jep._PyJObject): ...

class BooleanPropertyBase(jep._PyJObject): ...

class ReadOnlySetWrapper(jep._PyJObject): ...

class ListPropertyBase(jep._PyJObject): ...

class ObjectProperty(jep._PyJObject): ...

class Property(jep._PyJObject): ...

class MapProperty(jep._PyJObject): ...

class MapPropertyBase(jep._PyJObject): ...

class ReadOnlyMapWrapper(jep._PyJObject): ...

class ReadOnlyBooleanPropertyBase(jep._PyJObject): ...

class IntegerProperty(jep._PyJObject): ...

class ReadOnlyFloatWrapper(jep._PyJObject): ...

class ObjectPropertyBase(jep._PyJObject): ...

class ReadOnlyFloatPropertyBase(jep._PyJObject): ...

class SetPropertyBase(jep._PyJObject): ...

class ReadOnlyLongProperty(jep._PyJObject): ...

class FloatProperty(jep._PyJObject): ...

class ReadOnlySetProperty(jep._PyJObject): ...

class SimpleIntegerProperty(jep._PyJObject): ...

class DoublePropertyBase(jep._PyJObject): ...

class SimpleListProperty(jep._PyJObject): ...

class ReadOnlyIntegerProperty(jep._PyJObject): ...

class ReadOnlyListPropertyBase(jep._PyJObject): ...

class ReadOnlyMapPropertyBase(jep._PyJObject): ...

class FloatPropertyBase(jep._PyJObject): ...

class ReadOnlyBooleanProperty(jep._PyJObject): ...

class ReadOnlySetPropertyBase(jep._PyJObject): ...

class ReadOnlyLongPropertyBase(jep._PyJObject): ...

class ReadOnlyLongWrapper(jep._PyJObject): ...

class ReadOnlyMapProperty(jep._PyJObject): ...

class ReadOnlyDoubleWrapper(jep._PyJObject): ...

class SimpleSetProperty(jep._PyJObject): ...

class ReadOnlyBooleanWrapper(jep._PyJObject): ...

class StringProperty(jep._PyJObject): ...

class ReadOnlyListWrapper(jep._PyJObject): ...

class SimpleStringProperty(jep._PyJObject): ...

class SimpleObjectProperty(jep._PyJObject): ...

class ReadOnlyStringProperty(jep._PyJObject): ...

class StringPropertyBase(jep._PyJObject): ...

class ReadOnlyObjectWrapper(jep._PyJObject): ...

class IntegerPropertyBase(jep._PyJObject): ...

class ReadOnlyProperty(jep._PyJObject): ...

class SimpleLongProperty(jep._PyJObject): ...

class ReadOnlyFloatProperty(jep._PyJObject): ...

class ReadOnlyListProperty(jep._PyJObject): ...

class ReadOnlyStringWrapper(jep._PyJObject): ...

class DoubleProperty(jep._PyJObject): ...

class ReadOnlyObjectProperty(jep._PyJObject): ...

class ReadOnlyStringPropertyBase(jep._PyJObject): ...

class SimpleDoubleProperty(jep._PyJObject): ...

class LongProperty(jep._PyJObject): ...

class SetProperty(jep._PyJObject): ...

class LongPropertyBase(jep._PyJObject): ...

class ListProperty(jep._PyJObject): ...

