import jep

class ReadOnlyIntegerPropertyBase(jep.PyJObject): ...

class ReadOnlyIntegerWrapper(jep.PyJObject): ...

class SimpleMapProperty(jep.PyJObject): ...

class SimpleBooleanProperty(jep.PyJObject): ...

class SimpleFloatProperty(jep.PyJObject): ...

class BooleanProperty(jep.PyJObject): ...

class ReadOnlyDoubleProperty(jep.PyJObject): ...

class ReadOnlyDoublePropertyBase(jep.PyJObject): ...

class ReadOnlyObjectPropertyBase(jep.PyJObject): ...

class BooleanPropertyBase(jep.PyJObject): ...

class ReadOnlySetWrapper(jep.PyJObject): ...

class ListPropertyBase(jep.PyJObject): ...

class ObjectProperty(jep.PyJObject): ...

class Property(jep.PyJObject): ...

class MapProperty(jep.PyJObject): ...

class MapPropertyBase(jep.PyJObject): ...

class ReadOnlyMapWrapper(jep.PyJObject): ...

class ReadOnlyBooleanPropertyBase(jep.PyJObject): ...

class IntegerProperty(jep.PyJObject): ...

class ReadOnlyFloatWrapper(jep.PyJObject): ...

class ObjectPropertyBase(jep.PyJObject): ...

class ReadOnlyFloatPropertyBase(jep.PyJObject): ...

class SetPropertyBase(jep.PyJObject): ...

class ReadOnlyLongProperty(jep.PyJObject): ...

class FloatProperty(jep.PyJObject): ...

class ReadOnlySetProperty(jep.PyJObject): ...

class SimpleIntegerProperty(jep.PyJObject): ...

class DoublePropertyBase(jep.PyJObject): ...

class SimpleListProperty(jep.PyJObject): ...

class ReadOnlyIntegerProperty(jep.PyJObject): ...

class ReadOnlyListPropertyBase(jep.PyJObject): ...

class ReadOnlyMapPropertyBase(jep.PyJObject): ...

class FloatPropertyBase(jep.PyJObject): ...

class ReadOnlyBooleanProperty(jep.PyJObject): ...

class ReadOnlySetPropertyBase(jep.PyJObject): ...

class ReadOnlyLongPropertyBase(jep.PyJObject): ...

class ReadOnlyLongWrapper(jep.PyJObject): ...

class ReadOnlyMapProperty(jep.PyJObject): ...

class ReadOnlyDoubleWrapper(jep.PyJObject): ...

class SimpleSetProperty(jep.PyJObject): ...

class ReadOnlyBooleanWrapper(jep.PyJObject): ...

class StringProperty(jep.PyJObject): ...

class ReadOnlyListWrapper(jep.PyJObject): ...

class SimpleStringProperty(jep.PyJObject): ...

class SimpleObjectProperty(jep.PyJObject): ...

class ReadOnlyStringProperty(jep.PyJObject): ...

class StringPropertyBase(jep.PyJObject): ...

class ReadOnlyObjectWrapper(jep.PyJObject): ...

class IntegerPropertyBase(jep.PyJObject): ...

class ReadOnlyProperty(jep.PyJObject): ...

class SimpleLongProperty(jep.PyJObject): ...

class ReadOnlyFloatProperty(jep.PyJObject): ...

class ReadOnlyListProperty(jep.PyJObject): ...

class ReadOnlyStringWrapper(jep.PyJObject): ...

class DoubleProperty(jep.PyJObject): ...

class ReadOnlyObjectProperty(jep.PyJObject): ...

class ReadOnlyStringPropertyBase(jep.PyJObject): ...

class SimpleDoubleProperty(jep.PyJObject): ...

class LongProperty(jep.PyJObject): ...

class SetProperty(jep.PyJObject): ...

class LongPropertyBase(jep.PyJObject): ...

class ListProperty(jep.PyJObject): ...

