# pyright: reportPrivateUsage = none

import jep

class ReadOnlyJavaBeanProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanLongProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanIntegerPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanStringPropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanFloatPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanObjectProperty[**Ts](jep._PyJObject): ...

class JavaBeanFloatPropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanStringPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanIntegerProperty[**Ts](jep._PyJObject): ...

class JavaBeanIntegerProperty[**Ts](jep._PyJObject): ...

class JavaBeanLongProperty[**Ts](jep._PyJObject): ...

class JavaBeanIntegerPropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanDoubleProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanDoublePropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanDoublePropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanBooleanPropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanFloatProperty[**Ts](jep._PyJObject): ...

class JavaBeanBooleanProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanDoubleProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanBooleanPropertyBuilder[**Ts](jep._PyJObject): ...

class JavaBeanStringProperty[**Ts](jep._PyJObject): ...

class JavaBeanObjectProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanBooleanProperty[**Ts](jep._PyJObject): ...

class JavaBeanObjectPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanObjectPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanStringProperty[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanLongPropertyBuilder[**Ts](jep._PyJObject): ...

class ReadOnlyJavaBeanFloatProperty[**Ts](jep._PyJObject): ...

