import jep

class ReadOnlyJavaBeanIntegerProperty(jep.PyJObject): ...

class JavaBeanBooleanProperty(jep.PyJObject): ...

class JavaBeanLongProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanStringPropertyBuilder(jep.PyJObject): ...

class JavaBeanIntegerPropertyBuilder(jep.PyJObject): ...

class JavaBeanDoublePropertyBuilder(jep.PyJObject): ...

class ReadOnlyJavaBeanProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanFloatProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanLongPropertyBuilder(jep.PyJObject): ...

class JavaBeanStringPropertyBuilder(jep.PyJObject): ...

class ReadOnlyJavaBeanLongProperty(jep.PyJObject): ...

class JavaBeanStringProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanDoubleProperty(jep.PyJObject): ...

class JavaBeanDoubleProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanIntegerPropertyBuilder(jep.PyJObject): ...

class ReadOnlyJavaBeanBooleanPropertyBuilder(jep.PyJObject): ...

class JavaBeanObjectProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanBooleanProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanStringProperty(jep.PyJObject): ...

class ReadOnlyJavaBeanObjectProperty(jep.PyJObject): ...

class JavaBeanIntegerProperty(jep.PyJObject): ...

class JavaBeanFloatProperty(jep.PyJObject): ...

class JavaBeanObjectPropertyBuilder(jep.PyJObject): ...

class ReadOnlyJavaBeanFloatPropertyBuilder(jep.PyJObject): ...

class JavaBeanProperty(jep.PyJObject): ...

class JavaBeanBooleanPropertyBuilder(jep.PyJObject): ...

class JavaBeanLongPropertyBuilder(jep.PyJObject): ...

class JavaBeanFloatPropertyBuilder(jep.PyJObject): ...

class ReadOnlyJavaBeanObjectPropertyBuilder(jep.PyJObject): ...

