import jep

class ReadOnlyJavaBeanIntegerProperty(jep._PyJObject): ...

class JavaBeanBooleanProperty(jep._PyJObject): ...

class JavaBeanLongProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanStringPropertyBuilder(jep._PyJObject): ...

class JavaBeanIntegerPropertyBuilder(jep._PyJObject): ...

class JavaBeanDoublePropertyBuilder(jep._PyJObject): ...

class ReadOnlyJavaBeanProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanFloatProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanLongPropertyBuilder(jep._PyJObject): ...

class JavaBeanStringPropertyBuilder(jep._PyJObject): ...

class ReadOnlyJavaBeanLongProperty(jep._PyJObject): ...

class JavaBeanStringProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanDoubleProperty(jep._PyJObject): ...

class JavaBeanDoubleProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanIntegerPropertyBuilder(jep._PyJObject): ...

class ReadOnlyJavaBeanBooleanPropertyBuilder(jep._PyJObject): ...

class JavaBeanObjectProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanBooleanProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanStringProperty(jep._PyJObject): ...

class ReadOnlyJavaBeanObjectProperty(jep._PyJObject): ...

class JavaBeanIntegerProperty(jep._PyJObject): ...

class JavaBeanFloatProperty(jep._PyJObject): ...

class JavaBeanObjectPropertyBuilder(jep._PyJObject): ...

class ReadOnlyJavaBeanFloatPropertyBuilder(jep._PyJObject): ...

class JavaBeanProperty(jep._PyJObject): ...

class JavaBeanBooleanPropertyBuilder(jep._PyJObject): ...

class JavaBeanLongPropertyBuilder(jep._PyJObject): ...

class JavaBeanFloatPropertyBuilder(jep._PyJObject): ...

class ReadOnlyJavaBeanObjectPropertyBuilder(jep._PyJObject): ...

