import jep

class ArrayBlockingQueue(jep._PyJObject): ...

class TimeoutException(jep._PyJObject): ...

class CopyOnWriteArrayList(jep._PyJObject): ...

class Future(jep._PyJObject): ...

class ConcurrentNavigableMap(jep._PyJObject): ...

class RecursiveAction(jep._PyJObject): ...

class PriorityBlockingQueue(jep._PyJObject): ...

class LinkedTransferQueue(jep._PyJObject): ...

class ExecutorService(jep._PyJObject): ...

class CopyOnWriteArraySet(jep._PyJObject): ...

class TimeUnit(jep._PyJObject): ...

class ForkJoinPool(jep._PyJObject): ...

class LinkedBlockingDeque(jep._PyJObject): ...

class RecursiveTask(jep._PyJObject): ...

class Flow(jep._PyJObject): ...

class CompletionException(jep._PyJObject): ...

class ExecutionException(jep._PyJObject): ...

class RejectedExecutionException(jep._PyJObject): ...

class Phaser(jep._PyJObject): ...

class AbstractExecutorService(jep._PyJObject): ...

class ForkJoinTask(jep._PyJObject): ...

class Callable(jep._PyJObject): ...

class BlockingDeque(jep._PyJObject): ...

class Exchanger(jep._PyJObject): ...

class ExecutorCompletionService(jep._PyJObject): ...

class Delayed(jep._PyJObject): ...

class ConcurrentHashMap(jep._PyJObject): ...

class SubmissionPublisher(jep._PyJObject): ...

class CompletionService(jep._PyJObject): ...

class ConcurrentLinkedDeque(jep._PyJObject): ...

class ScheduledFuture(jep._PyJObject): ...

class Semaphore(jep._PyJObject): ...

class CountDownLatch(jep._PyJObject): ...

class CancellationException(jep._PyJObject): ...

class ThreadFactory(jep._PyJObject): ...

class DelayQueue(jep._PyJObject): ...

class ConcurrentMap(jep._PyJObject): ...

class TransferQueue(jep._PyJObject): ...

class ConcurrentSkipListMap(jep._PyJObject): ...

class CompletableFuture(jep._PyJObject): ...

class RunnableFuture(jep._PyJObject): ...

class ThreadLocalRandom(jep._PyJObject): ...

class RunnableScheduledFuture(jep._PyJObject): ...

class LinkedBlockingQueue(jep._PyJObject): ...

class SynchronousQueue(jep._PyJObject): ...

class ThreadPoolExecutor(jep._PyJObject): ...

class BrokenBarrierException(jep._PyJObject): ...

class BlockingQueue(jep._PyJObject): ...

class RejectedExecutionHandler(jep._PyJObject): ...

class ConcurrentLinkedQueue(jep._PyJObject): ...

class CyclicBarrier(jep._PyJObject): ...

class Executor(jep._PyJObject): ...

class ScheduledThreadPoolExecutor(jep._PyJObject): ...

class CompletionStage(jep._PyJObject): ...

class ScheduledExecutorService(jep._PyJObject): ...

class Executors(jep._PyJObject): ...

class FutureTask(jep._PyJObject): ...

class CountedCompleter(jep._PyJObject): ...

class ConcurrentSkipListSet(jep._PyJObject): ...

class ForkJoinWorkerThread(jep._PyJObject): ...

