import jep

class ArrayBlockingQueue(jep.PyJObject): ...

class TimeoutException(jep.PyJObject): ...

class CopyOnWriteArrayList(jep.PyJObject): ...

class Future(jep.PyJObject): ...

class ConcurrentNavigableMap(jep.PyJObject): ...

class RecursiveAction(jep.PyJObject): ...

class PriorityBlockingQueue(jep.PyJObject): ...

class LinkedTransferQueue(jep.PyJObject): ...

class ExecutorService(jep.PyJObject): ...

class CopyOnWriteArraySet(jep.PyJObject): ...

class TimeUnit(jep.PyJObject): ...

class ForkJoinPool(jep.PyJObject): ...

class LinkedBlockingDeque(jep.PyJObject): ...

class RecursiveTask(jep.PyJObject): ...

class Flow(jep.PyJObject): ...

class CompletionException(jep.PyJObject): ...

class ExecutionException(jep.PyJObject): ...

class RejectedExecutionException(jep.PyJObject): ...

class Phaser(jep.PyJObject): ...

class AbstractExecutorService(jep.PyJObject): ...

class ForkJoinTask(jep.PyJObject): ...

class Callable(jep.PyJObject): ...

class BlockingDeque(jep.PyJObject): ...

class Exchanger(jep.PyJObject): ...

class ExecutorCompletionService(jep.PyJObject): ...

class Delayed(jep.PyJObject): ...

class ConcurrentHashMap(jep.PyJObject): ...

class SubmissionPublisher(jep.PyJObject): ...

class CompletionService(jep.PyJObject): ...

class ConcurrentLinkedDeque(jep.PyJObject): ...

class ScheduledFuture(jep.PyJObject): ...

class Semaphore(jep.PyJObject): ...

class CountDownLatch(jep.PyJObject): ...

class CancellationException(jep.PyJObject): ...

class ThreadFactory(jep.PyJObject): ...

class DelayQueue(jep.PyJObject): ...

class ConcurrentMap(jep.PyJObject): ...

class TransferQueue(jep.PyJObject): ...

class ConcurrentSkipListMap(jep.PyJObject): ...

class CompletableFuture(jep.PyJObject): ...

class RunnableFuture(jep.PyJObject): ...

class ThreadLocalRandom(jep.PyJObject): ...

class RunnableScheduledFuture(jep.PyJObject): ...

class LinkedBlockingQueue(jep.PyJObject): ...

class SynchronousQueue(jep.PyJObject): ...

class ThreadPoolExecutor(jep.PyJObject): ...

class BrokenBarrierException(jep.PyJObject): ...

class BlockingQueue(jep.PyJObject): ...

class RejectedExecutionHandler(jep.PyJObject): ...

class ConcurrentLinkedQueue(jep.PyJObject): ...

class CyclicBarrier(jep.PyJObject): ...

class Executor(jep.PyJObject): ...

class ScheduledThreadPoolExecutor(jep.PyJObject): ...

class CompletionStage(jep.PyJObject): ...

class ScheduledExecutorService(jep.PyJObject): ...

class Executors(jep.PyJObject): ...

class FutureTask(jep.PyJObject): ...

class CountedCompleter(jep.PyJObject): ...

class ConcurrentSkipListSet(jep.PyJObject): ...

class ForkJoinWorkerThread(jep.PyJObject): ...

