# pyright: reportPrivateUsage = none

import jep

class CyclicBarrier[**Ts](jep._PyJObject): ...

class CountedCompleter[**Ts](jep._PyJObject): ...

class ScheduledThreadPoolExecutor[**Ts](jep._PyJObject): ...

class RunnableFuture[**Ts](jep._PyJObject): ...

class ConcurrentLinkedQueue[**Ts](jep._PyJObject): ...

class PriorityBlockingQueue[**Ts](jep._PyJObject): ...

class TransferQueue[**Ts](jep._PyJObject): ...

class BrokenBarrierException[**Ts](jep._PyJObject): ...

class AbstractExecutorService[**Ts](jep._PyJObject): ...

class ThreadPoolExecutor[**Ts](jep._PyJObject): ...

class ThreadLocalRandom[**Ts](jep._PyJObject): ...

class DelayQueue[**Ts](jep._PyJObject): ...

class ArrayBlockingQueue[**Ts](jep._PyJObject): ...

class ConcurrentSkipListSet[**Ts](jep._PyJObject): ...

class CompletionService[**Ts](jep._PyJObject): ...

class BlockingQueue[**Ts](jep._PyJObject): ...

class TimeoutException[**Ts](jep._PyJObject): ...

class ExecutorCompletionService[**Ts](jep._PyJObject): ...

class Callable[**Ts](jep._PyJObject): ...

class CompletableFuture[**Ts](jep._PyJObject): ...

class LinkedBlockingQueue[**Ts](jep._PyJObject): ...

class BlockingDeque[**Ts](jep._PyJObject): ...

class RejectedExecutionException[**Ts](jep._PyJObject): ...

class ExecutionException[**Ts](jep._PyJObject): ...

class Semaphore[**Ts](jep._PyJObject): ...

class TimeUnit[**Ts](jep._PyJObject): ...

class Delayed[**Ts](jep._PyJObject): ...

class Future[**Ts](jep._PyJObject): ...

class LinkedTransferQueue[**Ts](jep._PyJObject): ...

class ForkJoinTask[**Ts](jep._PyJObject): ...

class Executors[**Ts](jep._PyJObject): ...

class Phaser[**Ts](jep._PyJObject): ...

class LinkedBlockingDeque[**Ts](jep._PyJObject): ...

class SubmissionPublisher[**Ts](jep._PyJObject): ...

class Executor[**Ts](jep._PyJObject): ...

class CountDownLatch[**Ts](jep._PyJObject): ...

class CompletionException[**Ts](jep._PyJObject): ...

class ForkJoinWorkerThread[**Ts](jep._PyJObject): ...

class FutureTask[**Ts](jep._PyJObject): ...

class ScheduledFuture[**Ts](jep._PyJObject): ...

class CancellationException[**Ts](jep._PyJObject): ...

class ConcurrentSkipListMap[**Ts](jep._PyJObject): ...

class RunnableScheduledFuture[**Ts](jep._PyJObject): ...

class RecursiveAction[**Ts](jep._PyJObject): ...

class Flow[**Ts](jep._PyJObject): ...

class SynchronousQueue[**Ts](jep._PyJObject): ...

class CompletionStage[**Ts](jep._PyJObject): ...

class CopyOnWriteArrayList[**Ts](jep._PyJObject): ...

class ForkJoinPool[**Ts](jep._PyJObject): ...

class Exchanger[**Ts](jep._PyJObject): ...

class ThreadFactory[**Ts](jep._PyJObject): ...

class ConcurrentLinkedDeque[**Ts](jep._PyJObject): ...

class ScheduledExecutorService[**Ts](jep._PyJObject): ...

class RecursiveTask[**Ts](jep._PyJObject): ...

class ConcurrentHashMap[**Ts](jep._PyJObject): ...

class ConcurrentNavigableMap[**Ts](jep._PyJObject): ...

class ExecutorService[**Ts](jep._PyJObject): ...

class ConcurrentMap[**Ts](jep._PyJObject): ...

class CopyOnWriteArraySet[**Ts](jep._PyJObject): ...

class RejectedExecutionHandler[**Ts](jep._PyJObject): ...

