import jep

class AtomicStampedReference(jep._PyJObject): ...

class AtomicIntegerFieldUpdater(jep._PyJObject): ...

class AtomicReference(jep._PyJObject): ...

class AtomicLongFieldUpdater(jep._PyJObject): ...

class AtomicBoolean(jep._PyJObject): ...

class AtomicLong(jep._PyJObject): ...

class AtomicReferenceArray(jep._PyJObject): ...

class LongAccumulator(jep._PyJObject): ...

class DoubleAdder(jep._PyJObject): ...

class AtomicLongArray(jep._PyJObject): ...

class AtomicMarkableReference(jep._PyJObject): ...

class AtomicIntegerArray(jep._PyJObject): ...

class AtomicReferenceFieldUpdater(jep._PyJObject): ...

class LongAdder(jep._PyJObject): ...

class DoubleAccumulator(jep._PyJObject): ...

class AtomicInteger(jep._PyJObject): ...

