import jep

class AtomicStampedReference(jep.PyJObject): ...

class AtomicIntegerFieldUpdater(jep.PyJObject): ...

class AtomicReference(jep.PyJObject): ...

class AtomicLongFieldUpdater(jep.PyJObject): ...

class AtomicBoolean(jep.PyJObject): ...

class AtomicLong(jep.PyJObject): ...

class AtomicReferenceArray(jep.PyJObject): ...

class LongAccumulator(jep.PyJObject): ...

class DoubleAdder(jep.PyJObject): ...

class AtomicLongArray(jep.PyJObject): ...

class AtomicMarkableReference(jep.PyJObject): ...

class AtomicIntegerArray(jep.PyJObject): ...

class AtomicReferenceFieldUpdater(jep.PyJObject): ...

class LongAdder(jep.PyJObject): ...

class DoubleAccumulator(jep.PyJObject): ...

class AtomicInteger(jep.PyJObject): ...

