# pyright: reportPrivateUsage = none

import jep

class LongAccumulator[**Ts](jep._PyJObject): ...

class AtomicLongArray[**Ts](jep._PyJObject): ...

class DoubleAccumulator[**Ts](jep._PyJObject): ...

class LongAdder[**Ts](jep._PyJObject): ...

class AtomicIntegerArray[**Ts](jep._PyJObject): ...

class AtomicInteger[**Ts](jep._PyJObject): ...

class AtomicLongFieldUpdater[**Ts](jep._PyJObject): ...

class AtomicIntegerFieldUpdater[**Ts](jep._PyJObject): ...

class AtomicStampedReference[**Ts](jep._PyJObject): ...

class AtomicBoolean[**Ts](jep._PyJObject): ...

class AtomicMarkableReference[**Ts](jep._PyJObject): ...

class AtomicLong[**Ts](jep._PyJObject): ...

class DoubleAdder[**Ts](jep._PyJObject): ...

class AtomicReference[**Ts](jep._PyJObject): ...

class AtomicReferenceArray[**Ts](jep._PyJObject): ...

class AtomicReferenceFieldUpdater[**Ts](jep._PyJObject): ...

