import jep

class Condition(jep._PyJObject): ...

class AbstractQueuedLongSynchronizer(jep._PyJObject): ...

class ReadWriteLock(jep._PyJObject): ...

class AbstractOwnableSynchronizer(jep._PyJObject): ...

class ReentrantLock(jep._PyJObject): ...

class AbstractQueuedSynchronizer(jep._PyJObject): ...

class Lock(jep._PyJObject): ...

class LockSupport(jep._PyJObject): ...

class ReentrantReadWriteLock(jep._PyJObject): ...

