import jep

class Condition(jep.PyJObject): ...

class AbstractQueuedLongSynchronizer(jep.PyJObject): ...

class ReadWriteLock(jep.PyJObject): ...

class AbstractOwnableSynchronizer(jep.PyJObject): ...

class ReentrantLock(jep.PyJObject): ...

class AbstractQueuedSynchronizer(jep.PyJObject): ...

class Lock(jep.PyJObject): ...

class LockSupport(jep.PyJObject): ...

class ReentrantReadWriteLock(jep.PyJObject): ...

