# pyright: reportPrivateUsage = none

import jep

class ReentrantLock[**Ts](jep._PyJObject): ...

class Condition[**Ts](jep._PyJObject): ...

class Lock[**Ts](jep._PyJObject): ...

class LockSupport[**Ts](jep._PyJObject): ...

class AbstractOwnableSynchronizer[**Ts](jep._PyJObject): ...

class AbstractQueuedSynchronizer[**Ts](jep._PyJObject): ...

class ReentrantReadWriteLock[**Ts](jep._PyJObject): ...

class StampedLock[**Ts](jep._PyJObject): ...

class ReadWriteLock[**Ts](jep._PyJObject): ...

