import jep

class AgentInitializationException(jep.PyJObject): ...

class AgentLoadException(jep.PyJObject): ...

class VirtualMachine(jep.PyJObject): ...

class AttachNotSupportedException(jep.PyJObject): ...

class AttachOperationFailedException(jep.PyJObject): ...

class AttachPermission(jep.PyJObject): ...

class VirtualMachineDescriptor(jep.PyJObject): ...

