import jep

class AgentInitializationException(jep._PyJObject): ...

class AgentLoadException(jep._PyJObject): ...

class VirtualMachine(jep._PyJObject): ...

class AttachNotSupportedException(jep._PyJObject): ...

class AttachOperationFailedException(jep._PyJObject): ...

class AttachPermission(jep._PyJObject): ...

class VirtualMachineDescriptor(jep._PyJObject): ...

