# pyright: reportPrivateUsage = none

import jep

class VirtualMachine[**Ts](jep._PyJObject): ...

class AttachNotSupportedException[**Ts](jep._PyJObject): ...

class AgentLoadException[**Ts](jep._PyJObject): ...

class AgentInitializationException[**Ts](jep._PyJObject): ...

class AttachPermission[**Ts](jep._PyJObject): ...

class VirtualMachineDescriptor[**Ts](jep._PyJObject): ...

class AttachOperationFailedException[**Ts](jep._PyJObject): ...

