import jep

class MessageContext(jep._PyJObject): ...

class LogicalMessageContext(jep._PyJObject): ...

class Handler(jep._PyJObject): ...

class HandlerResolver(jep._PyJObject): ...

class LogicalHandler(jep._PyJObject): ...

class PortInfo(jep._PyJObject): ...

