# pyright: reportPrivateUsage = none

import jep

class LogicalMessageContext[**Ts](jep._PyJObject): ...

class LogicalHandler[**Ts](jep._PyJObject): ...

class Handler[**Ts](jep._PyJObject): ...

class HandlerResolver[**Ts](jep._PyJObject): ...

class PortInfo[**Ts](jep._PyJObject): ...

class MessageContext[**Ts](jep._PyJObject): ...

