import jep

class MessageContext(jep.PyJObject): ...

class LogicalMessageContext(jep.PyJObject): ...

class Handler(jep.PyJObject): ...

class HandlerResolver(jep.PyJObject): ...

class LogicalHandler(jep.PyJObject): ...

class PortInfo(jep.PyJObject): ...

