import jep

class ServantLocatorPOA(jep._PyJObject): ...

class ServantRetentionPolicyValue(jep._PyJObject): ...

class ForwardRequestHelper(jep._PyJObject): ...

class ThreadPolicy(jep._PyJObject): ...

class ServantLocatorHelper(jep._PyJObject): ...

class ForwardRequest(jep._PyJObject): ...

class AdapterActivatorOperations(jep._PyJObject): ...

class ID_UNIQUENESS_POLICY_ID(jep._PyJObject): ...

class LifespanPolicyOperations(jep._PyJObject): ...

class IdUniquenessPolicy(jep._PyJObject): ...

class IdUniquenessPolicyOperations(jep._PyJObject): ...

class REQUEST_PROCESSING_POLICY_ID(jep._PyJObject): ...

class ID_ASSIGNMENT_POLICY_ID(jep._PyJObject): ...

class IdAssignmentPolicyValue(jep._PyJObject): ...

class ServantRetentionPolicyOperations(jep._PyJObject): ...

class IMPLICIT_ACTIVATION_POLICY_ID(jep._PyJObject): ...

class THREAD_POLICY_ID(jep._PyJObject): ...

class ServantManagerOperations(jep._PyJObject): ...

class IdUniquenessPolicyValue(jep._PyJObject): ...

class SERVANT_RETENTION_POLICY_ID(jep._PyJObject): ...

class ServantActivatorOperations(jep._PyJObject): ...

class RequestProcessingPolicyOperations(jep._PyJObject): ...

class ServantRetentionPolicy(jep._PyJObject): ...

class ImplicitActivationPolicyOperations(jep._PyJObject): ...

class IdAssignmentPolicy(jep._PyJObject): ...

class ServantActivator(jep._PyJObject): ...

class POAManagerOperations(jep._PyJObject): ...

class ImplicitActivationPolicyValue(jep._PyJObject): ...

class POA(jep._PyJObject): ...

class RequestProcessingPolicyValue(jep._PyJObject): ...

class IdAssignmentPolicyOperations(jep._PyJObject): ...

class DynamicImplementation(jep._PyJObject): ...

class LIFESPAN_POLICY_ID(jep._PyJObject): ...

class AdapterActivator(jep._PyJObject): ...

class ServantLocator(jep._PyJObject): ...

class RequestProcessingPolicy(jep._PyJObject): ...

class Servant(jep._PyJObject): ...

class _ServantLocatorStub(jep._PyJObject): ...

class POAHelper(jep._PyJObject): ...

class CurrentHelper(jep._PyJObject): ...

class ServantLocatorOperations(jep._PyJObject): ...

class ServantActivatorPOA(jep._PyJObject): ...

class ServantManager(jep._PyJObject): ...

class LifespanPolicy(jep._PyJObject): ...

class POAOperations(jep._PyJObject): ...

class _ServantActivatorStub(jep._PyJObject): ...

class CurrentOperations(jep._PyJObject): ...

class ThreadPolicyOperations(jep._PyJObject): ...

class ImplicitActivationPolicy(jep._PyJObject): ...

class ServantActivatorHelper(jep._PyJObject): ...

class POAManager(jep._PyJObject): ...

class ThreadPolicyValue(jep._PyJObject): ...

class LifespanPolicyValue(jep._PyJObject): ...

class Current(jep._PyJObject): ...

