import jep

class ServantLocatorPOA(jep.PyJObject): ...

class ServantRetentionPolicyValue(jep.PyJObject): ...

class ForwardRequestHelper(jep.PyJObject): ...

class ThreadPolicy(jep.PyJObject): ...

class ServantLocatorHelper(jep.PyJObject): ...

class ForwardRequest(jep.PyJObject): ...

class AdapterActivatorOperations(jep.PyJObject): ...

class ID_UNIQUENESS_POLICY_ID(jep.PyJObject): ...

class LifespanPolicyOperations(jep.PyJObject): ...

class IdUniquenessPolicy(jep.PyJObject): ...

class IdUniquenessPolicyOperations(jep.PyJObject): ...

class REQUEST_PROCESSING_POLICY_ID(jep.PyJObject): ...

class ID_ASSIGNMENT_POLICY_ID(jep.PyJObject): ...

class IdAssignmentPolicyValue(jep.PyJObject): ...

class ServantRetentionPolicyOperations(jep.PyJObject): ...

class IMPLICIT_ACTIVATION_POLICY_ID(jep.PyJObject): ...

class THREAD_POLICY_ID(jep.PyJObject): ...

class ServantManagerOperations(jep.PyJObject): ...

class IdUniquenessPolicyValue(jep.PyJObject): ...

class SERVANT_RETENTION_POLICY_ID(jep.PyJObject): ...

class ServantActivatorOperations(jep.PyJObject): ...

class RequestProcessingPolicyOperations(jep.PyJObject): ...

class ServantRetentionPolicy(jep.PyJObject): ...

class ImplicitActivationPolicyOperations(jep.PyJObject): ...

class IdAssignmentPolicy(jep.PyJObject): ...

class ServantActivator(jep.PyJObject): ...

class POAManagerOperations(jep.PyJObject): ...

class ImplicitActivationPolicyValue(jep.PyJObject): ...

class POA(jep.PyJObject): ...

class RequestProcessingPolicyValue(jep.PyJObject): ...

class IdAssignmentPolicyOperations(jep.PyJObject): ...

class DynamicImplementation(jep.PyJObject): ...

class LIFESPAN_POLICY_ID(jep.PyJObject): ...

class AdapterActivator(jep.PyJObject): ...

class ServantLocator(jep.PyJObject): ...

class RequestProcessingPolicy(jep.PyJObject): ...

class Servant(jep.PyJObject): ...

class _ServantLocatorStub(jep.PyJObject): ...

class POAHelper(jep.PyJObject): ...

class CurrentHelper(jep.PyJObject): ...

class ServantLocatorOperations(jep.PyJObject): ...

class ServantActivatorPOA(jep.PyJObject): ...

class ServantManager(jep.PyJObject): ...

class LifespanPolicy(jep.PyJObject): ...

class POAOperations(jep.PyJObject): ...

class _ServantActivatorStub(jep.PyJObject): ...

class CurrentOperations(jep.PyJObject): ...

class ThreadPolicyOperations(jep.PyJObject): ...

class ImplicitActivationPolicy(jep.PyJObject): ...

class ServantActivatorHelper(jep.PyJObject): ...

class POAManager(jep.PyJObject): ...

class ThreadPolicyValue(jep.PyJObject): ...

class LifespanPolicyValue(jep.PyJObject): ...

class Current(jep.PyJObject): ...

