# pyright: reportPrivateUsage = none

import jep

class POA[**Ts](jep._PyJObject): ...

class RequestProcessingPolicy[**Ts](jep._PyJObject): ...

class ImplicitActivationPolicy[**Ts](jep._PyJObject): ...

class ServantManager[**Ts](jep._PyJObject): ...

class CurrentOperations[**Ts](jep._PyJObject): ...

class IdUniquenessPolicyValue[**Ts](jep._PyJObject): ...

class RequestProcessingPolicyOperations[**Ts](jep._PyJObject): ...

class _ServantActivatorStub[**Ts](jep._PyJObject): ...

class Servant[**Ts](jep._PyJObject): ...

class SERVANT_RETENTION_POLICY_ID[**Ts](jep._PyJObject): ...

class ServantActivatorHelper[**Ts](jep._PyJObject): ...

class ThreadPolicyOperations[**Ts](jep._PyJObject): ...

class IdUniquenessPolicy[**Ts](jep._PyJObject): ...

class LIFESPAN_POLICY_ID[**Ts](jep._PyJObject): ...

class IdAssignmentPolicy[**Ts](jep._PyJObject): ...

class POAManagerOperations[**Ts](jep._PyJObject): ...

class DynamicImplementation[**Ts](jep._PyJObject): ...

class Current[**Ts](jep._PyJObject): ...

class AdapterActivator[**Ts](jep._PyJObject): ...

class ThreadPolicy[**Ts](jep._PyJObject): ...

class ImplicitActivationPolicyOperations[**Ts](jep._PyJObject): ...

class ServantRetentionPolicyOperations[**Ts](jep._PyJObject): ...

class POAHelper[**Ts](jep._PyJObject): ...

class ServantActivator[**Ts](jep._PyJObject): ...

class _ServantLocatorStub[**Ts](jep._PyJObject): ...

class POAOperations[**Ts](jep._PyJObject): ...

class ForwardRequest[**Ts](jep._PyJObject): ...

class LifespanPolicyValue[**Ts](jep._PyJObject): ...

class ServantManagerOperations[**Ts](jep._PyJObject): ...

class ServantLocatorHelper[**Ts](jep._PyJObject): ...

class ServantLocatorOperations[**Ts](jep._PyJObject): ...

class IMPLICIT_ACTIVATION_POLICY_ID[**Ts](jep._PyJObject): ...

class ID_ASSIGNMENT_POLICY_ID[**Ts](jep._PyJObject): ...

class ServantRetentionPolicy[**Ts](jep._PyJObject): ...

class ImplicitActivationPolicyValue[**Ts](jep._PyJObject): ...

class IdUniquenessPolicyOperations[**Ts](jep._PyJObject): ...

class ServantRetentionPolicyValue[**Ts](jep._PyJObject): ...

class ForwardRequestHelper[**Ts](jep._PyJObject): ...

class CurrentHelper[**Ts](jep._PyJObject): ...

class ServantLocator[**Ts](jep._PyJObject): ...

class REQUEST_PROCESSING_POLICY_ID[**Ts](jep._PyJObject): ...

class ID_UNIQUENESS_POLICY_ID[**Ts](jep._PyJObject): ...

class THREAD_POLICY_ID[**Ts](jep._PyJObject): ...

class ServantActivatorOperations[**Ts](jep._PyJObject): ...

class LifespanPolicy[**Ts](jep._PyJObject): ...

class IdAssignmentPolicyOperations[**Ts](jep._PyJObject): ...

class RequestProcessingPolicyValue[**Ts](jep._PyJObject): ...

class IdAssignmentPolicyValue[**Ts](jep._PyJObject): ...

class ThreadPolicyValue[**Ts](jep._PyJObject): ...

class AdapterActivatorOperations[**Ts](jep._PyJObject): ...

class ServantActivatorPOA[**Ts](jep._PyJObject): ...

class LifespanPolicyOperations[**Ts](jep._PyJObject): ...

class POAManager[**Ts](jep._PyJObject): ...

class ServantLocatorPOA[**Ts](jep._PyJObject): ...

