import jep

class ServantAlreadyActiveHelper(jep._PyJObject): ...

class ServantAlreadyActive(jep._PyJObject): ...

class ServantNotActive(jep._PyJObject): ...

class AdapterAlreadyExistsHelper(jep._PyJObject): ...

class AdapterNonExistent(jep._PyJObject): ...

class ObjectNotActiveHelper(jep._PyJObject): ...

class WrongPolicyHelper(jep._PyJObject): ...

class AdapterAlreadyExists(jep._PyJObject): ...

class InvalidPolicyHelper(jep._PyJObject): ...

class ObjectNotActive(jep._PyJObject): ...

class ObjectAlreadyActiveHelper(jep._PyJObject): ...

class WrongAdapter(jep._PyJObject): ...

class WrongAdapterHelper(jep._PyJObject): ...

class ServantNotActiveHelper(jep._PyJObject): ...

class WrongPolicy(jep._PyJObject): ...

class InvalidPolicy(jep._PyJObject): ...

class AdapterNonExistentHelper(jep._PyJObject): ...

class NoServant(jep._PyJObject): ...

class ObjectAlreadyActive(jep._PyJObject): ...

