# pyright: reportPrivateUsage = none

import jep

class ObjectAlreadyActive[**Ts](jep._PyJObject): ...

class ObjectAlreadyActiveHelper[**Ts](jep._PyJObject): ...

class AdapterNonExistentHelper[**Ts](jep._PyJObject): ...

class ServantAlreadyActiveHelper[**Ts](jep._PyJObject): ...

class ServantAlreadyActive[**Ts](jep._PyJObject): ...

class NoServant[**Ts](jep._PyJObject): ...

class NoServantHelper[**Ts](jep._PyJObject): ...

class ServantNotActive[**Ts](jep._PyJObject): ...

class WrongPolicyHelper[**Ts](jep._PyJObject): ...

class WrongPolicy[**Ts](jep._PyJObject): ...

class ServantNotActiveHelper[**Ts](jep._PyJObject): ...

class AdapterAlreadyExists[**Ts](jep._PyJObject): ...

class WrongAdapter[**Ts](jep._PyJObject): ...

class WrongAdapterHelper[**Ts](jep._PyJObject): ...

class InvalidPolicy[**Ts](jep._PyJObject): ...

class AdapterNonExistent[**Ts](jep._PyJObject): ...

class ObjectNotActive[**Ts](jep._PyJObject): ...

class AdapterAlreadyExistsHelper[**Ts](jep._PyJObject): ...

class ObjectNotActiveHelper[**Ts](jep._PyJObject): ...

