import jep

class ServantAlreadyActiveHelper(jep.PyJObject): ...

class ServantAlreadyActive(jep.PyJObject): ...

class ServantNotActive(jep.PyJObject): ...

class AdapterAlreadyExistsHelper(jep.PyJObject): ...

class AdapterNonExistent(jep.PyJObject): ...

class ObjectNotActiveHelper(jep.PyJObject): ...

class WrongPolicyHelper(jep.PyJObject): ...

class AdapterAlreadyExists(jep.PyJObject): ...

class InvalidPolicyHelper(jep.PyJObject): ...

class ObjectNotActive(jep.PyJObject): ...

class ObjectAlreadyActiveHelper(jep.PyJObject): ...

class WrongAdapter(jep.PyJObject): ...

class WrongAdapterHelper(jep.PyJObject): ...

class ServantNotActiveHelper(jep.PyJObject): ...

class WrongPolicy(jep.PyJObject): ...

class InvalidPolicy(jep.PyJObject): ...

class AdapterNonExistentHelper(jep.PyJObject): ...

class NoServant(jep.PyJObject): ...

class ObjectAlreadyActive(jep.PyJObject): ...

