# pyright: reportPrivateUsage = none

import jep

class ArrayReference[**Ts](jep._PyJObject): ...

class ThreadReference[**Ts](jep._PyJObject): ...

class ByteValue[**Ts](jep._PyJObject): ...

class Field[**Ts](jep._PyJObject): ...

class ReferenceType[**Ts](jep._PyJObject): ...

class TypeComponent[**Ts](jep._PyJObject): ...

class InvalidTypeException[**Ts](jep._PyJObject): ...

class ClassLoaderReference[**Ts](jep._PyJObject): ...

class InvalidLineNumberException[**Ts](jep._PyJObject): ...

class LocalVariable[**Ts](jep._PyJObject): ...

class InvocationException[**Ts](jep._PyJObject): ...

class ObjectCollectedException[**Ts](jep._PyJObject): ...

class Value[**Ts](jep._PyJObject): ...

class ClassObjectReference[**Ts](jep._PyJObject): ...

class Type[**Ts](jep._PyJObject): ...

class VoidType[**Ts](jep._PyJObject): ...

class Accessible[**Ts](jep._PyJObject): ...

class PrimitiveValue[**Ts](jep._PyJObject): ...

class Bootstrap[**Ts](jep._PyJObject): ...

class DoubleType[**Ts](jep._PyJObject): ...

class BooleanType[**Ts](jep._PyJObject): ...

class VMCannotBeModifiedException[**Ts](jep._PyJObject): ...

class Method[**Ts](jep._PyJObject): ...

class Mirror[**Ts](jep._PyJObject): ...

class VMDisconnectedException[**Ts](jep._PyJObject): ...

class ShortType[**Ts](jep._PyJObject): ...

class StackFrame[**Ts](jep._PyJObject): ...

class MonitorInfo[**Ts](jep._PyJObject): ...

class InterfaceType[**Ts](jep._PyJObject): ...

class DoubleValue[**Ts](jep._PyJObject): ...

class LongType[**Ts](jep._PyJObject): ...

class Location[**Ts](jep._PyJObject): ...

class InvalidCodeIndexException[**Ts](jep._PyJObject): ...

class ModuleReference[**Ts](jep._PyJObject): ...

class InternalException[**Ts](jep._PyJObject): ...

class VirtualMachine[**Ts](jep._PyJObject): ...

class IncompatibleThreadStateException[**Ts](jep._PyJObject): ...

class ArrayType[**Ts](jep._PyJObject): ...

class ClassNotPreparedException[**Ts](jep._PyJObject): ...

class StringReference[**Ts](jep._PyJObject): ...

class ShortValue[**Ts](jep._PyJObject): ...

class IntegerType[**Ts](jep._PyJObject): ...

class Locatable[**Ts](jep._PyJObject): ...

class VirtualMachineManager[**Ts](jep._PyJObject): ...

class CharValue[**Ts](jep._PyJObject): ...

class ByteType[**Ts](jep._PyJObject): ...

class BooleanValue[**Ts](jep._PyJObject): ...

class VoidValue[**Ts](jep._PyJObject): ...

class InvalidStackFrameException[**Ts](jep._PyJObject): ...

class LongValue[**Ts](jep._PyJObject): ...

class ClassType[**Ts](jep._PyJObject): ...

class InconsistentDebugInfoException[**Ts](jep._PyJObject): ...

class VMMismatchException[**Ts](jep._PyJObject): ...

class PathSearchingVirtualMachine[**Ts](jep._PyJObject): ...

class ObjectReference[**Ts](jep._PyJObject): ...

class ClassNotLoadedException[**Ts](jep._PyJObject): ...

class PrimitiveType[**Ts](jep._PyJObject): ...

class FloatType[**Ts](jep._PyJObject): ...

class IntegerValue[**Ts](jep._PyJObject): ...

class InvalidModuleException[**Ts](jep._PyJObject): ...

class FloatValue[**Ts](jep._PyJObject): ...

class AbsentInformationException[**Ts](jep._PyJObject): ...

class JDIPermission[**Ts](jep._PyJObject): ...

class ThreadGroupReference[**Ts](jep._PyJObject): ...

class CharType[**Ts](jep._PyJObject): ...

class NativeMethodException[**Ts](jep._PyJObject): ...

class VMOutOfMemoryException[**Ts](jep._PyJObject): ...

