import jep

class StackFrame(jep.PyJObject): ...

class FloatValue(jep.PyJObject): ...

class BooleanValue(jep.PyJObject): ...

class Accessible(jep.PyJObject): ...

class ObjectReference(jep.PyJObject): ...

class InvocationException(jep.PyJObject): ...

class LongValue(jep.PyJObject): ...

class LocalVariable(jep.PyJObject): ...

class IncompatibleThreadStateException(jep.PyJObject): ...

class Method(jep.PyJObject): ...

class ClassType(jep.PyJObject): ...

class NativeMethodException(jep.PyJObject): ...

class Locatable(jep.PyJObject): ...

class IntegerValue(jep.PyJObject): ...

class ClassLoaderReference(jep.PyJObject): ...

class ModuleReference(jep.PyJObject): ...

class CharType(jep.PyJObject): ...

class ShortValue(jep.PyJObject): ...

class InvalidTypeException(jep.PyJObject): ...

class PrimitiveValue(jep.PyJObject): ...

class FloatType(jep.PyJObject): ...

class Type(jep.PyJObject): ...

class Value(jep.PyJObject): ...

class Bootstrap(jep.PyJObject): ...

class InvalidLineNumberException(jep.PyJObject): ...

class VMOutOfMemoryException(jep.PyJObject): ...

class ReferenceType(jep.PyJObject): ...

class InvalidModuleException(jep.PyJObject): ...

class StringReference(jep.PyJObject): ...

class ArrayReference(jep.PyJObject): ...

class BooleanType(jep.PyJObject): ...

class InterfaceType(jep.PyJObject): ...

class ClassNotLoadedException(jep.PyJObject): ...

class VMMismatchException(jep.PyJObject): ...

class VoidValue(jep.PyJObject): ...

class PathSearchingVirtualMachine(jep.PyJObject): ...

class VoidType(jep.PyJObject): ...

class VirtualMachine(jep.PyJObject): ...

class InternalException(jep.PyJObject): ...

class PrimitiveType(jep.PyJObject): ...

class VMCannotBeModifiedException(jep.PyJObject): ...

class InconsistentDebugInfoException(jep.PyJObject): ...

class InvalidCodeIndexException(jep.PyJObject): ...

class AbsentInformationException(jep.PyJObject): ...

class IntegerType(jep.PyJObject): ...

class VirtualMachineManager(jep.PyJObject): ...

class ArrayType(jep.PyJObject): ...

class Field(jep.PyJObject): ...

class DoubleType(jep.PyJObject): ...

class VMDisconnectedException(jep.PyJObject): ...

class ThreadReference(jep.PyJObject): ...

class ByteValue(jep.PyJObject): ...

class Mirror(jep.PyJObject): ...

class ShortType(jep.PyJObject): ...

class InvalidStackFrameException(jep.PyJObject): ...

class ThreadGroupReference(jep.PyJObject): ...

class ClassObjectReference(jep.PyJObject): ...

class CharValue(jep.PyJObject): ...

class TypeComponent(jep.PyJObject): ...

class LongType(jep.PyJObject): ...

class ClassNotPreparedException(jep.PyJObject): ...

class Location(jep.PyJObject): ...

class ByteType(jep.PyJObject): ...

class ObjectCollectedException(jep.PyJObject): ...

class MonitorInfo(jep.PyJObject): ...

class DoubleValue(jep.PyJObject): ...

class JDIPermission(jep.PyJObject): ...

