import jep

class StackFrame(jep._PyJObject): ...

class FloatValue(jep._PyJObject): ...

class BooleanValue(jep._PyJObject): ...

class Accessible(jep._PyJObject): ...

class ObjectReference(jep._PyJObject): ...

class InvocationException(jep._PyJObject): ...

class LongValue(jep._PyJObject): ...

class LocalVariable(jep._PyJObject): ...

class IncompatibleThreadStateException(jep._PyJObject): ...

class Method(jep._PyJObject): ...

class ClassType(jep._PyJObject): ...

class NativeMethodException(jep._PyJObject): ...

class Locatable(jep._PyJObject): ...

class IntegerValue(jep._PyJObject): ...

class ClassLoaderReference(jep._PyJObject): ...

class ModuleReference(jep._PyJObject): ...

class CharType(jep._PyJObject): ...

class ShortValue(jep._PyJObject): ...

class InvalidTypeException(jep._PyJObject): ...

class PrimitiveValue(jep._PyJObject): ...

class FloatType(jep._PyJObject): ...

class Type(jep._PyJObject): ...

class Value(jep._PyJObject): ...

class Bootstrap(jep._PyJObject): ...

class InvalidLineNumberException(jep._PyJObject): ...

class VMOutOfMemoryException(jep._PyJObject): ...

class ReferenceType(jep._PyJObject): ...

class InvalidModuleException(jep._PyJObject): ...

class StringReference(jep._PyJObject): ...

class ArrayReference(jep._PyJObject): ...

class BooleanType(jep._PyJObject): ...

class InterfaceType(jep._PyJObject): ...

class ClassNotLoadedException(jep._PyJObject): ...

class VMMismatchException(jep._PyJObject): ...

class VoidValue(jep._PyJObject): ...

class PathSearchingVirtualMachine(jep._PyJObject): ...

class VoidType(jep._PyJObject): ...

class VirtualMachine(jep._PyJObject): ...

class InternalException(jep._PyJObject): ...

class PrimitiveType(jep._PyJObject): ...

class VMCannotBeModifiedException(jep._PyJObject): ...

class InconsistentDebugInfoException(jep._PyJObject): ...

class InvalidCodeIndexException(jep._PyJObject): ...

class AbsentInformationException(jep._PyJObject): ...

class IntegerType(jep._PyJObject): ...

class VirtualMachineManager(jep._PyJObject): ...

class ArrayType(jep._PyJObject): ...

class Field(jep._PyJObject): ...

class DoubleType(jep._PyJObject): ...

class VMDisconnectedException(jep._PyJObject): ...

class ThreadReference(jep._PyJObject): ...

class ByteValue(jep._PyJObject): ...

class Mirror(jep._PyJObject): ...

class ShortType(jep._PyJObject): ...

class InvalidStackFrameException(jep._PyJObject): ...

class ThreadGroupReference(jep._PyJObject): ...

class ClassObjectReference(jep._PyJObject): ...

class CharValue(jep._PyJObject): ...

class TypeComponent(jep._PyJObject): ...

class LongType(jep._PyJObject): ...

class ClassNotPreparedException(jep._PyJObject): ...

class Location(jep._PyJObject): ...

class ByteType(jep._PyJObject): ...

class ObjectCollectedException(jep._PyJObject): ...

class MonitorInfo(jep._PyJObject): ...

class DoubleValue(jep._PyJObject): ...

class JDIPermission(jep._PyJObject): ...

