# pyright: reportPrivateUsage = none

import jep

class MonitorContendedEnterEvent[**Ts](jep._PyJObject): ...

class WatchpointEvent[**Ts](jep._PyJObject): ...

class ClassUnloadEvent[**Ts](jep._PyJObject): ...

class ModificationWatchpointEvent[**Ts](jep._PyJObject): ...

class StepEvent[**Ts](jep._PyJObject): ...

class ThreadDeathEvent[**Ts](jep._PyJObject): ...

class MethodEntryEvent[**Ts](jep._PyJObject): ...

class LocatableEvent[**Ts](jep._PyJObject): ...

class EventIterator[**Ts](jep._PyJObject): ...

class VMStartEvent[**Ts](jep._PyJObject): ...

class ExceptionEvent[**Ts](jep._PyJObject): ...

class Event[**Ts](jep._PyJObject): ...

class ThreadStartEvent[**Ts](jep._PyJObject): ...

class VMDeathEvent[**Ts](jep._PyJObject): ...

class BreakpointEvent[**Ts](jep._PyJObject): ...

class MonitorWaitedEvent[**Ts](jep._PyJObject): ...

class EventSet[**Ts](jep._PyJObject): ...

class EventQueue[**Ts](jep._PyJObject): ...

class MonitorWaitEvent[**Ts](jep._PyJObject): ...

class AccessWatchpointEvent[**Ts](jep._PyJObject): ...

class MethodExitEvent[**Ts](jep._PyJObject): ...

class ClassPrepareEvent[**Ts](jep._PyJObject): ...

class VMDisconnectEvent[**Ts](jep._PyJObject): ...

