import jep

class MonitorWaitEvent(jep._PyJObject): ...

class ClassUnloadEvent(jep._PyJObject): ...

class MethodExitEvent(jep._PyJObject): ...

class EventIterator(jep._PyJObject): ...

class EventSet(jep._PyJObject): ...

class VMDeathEvent(jep._PyJObject): ...

class Event(jep._PyJObject): ...

class MonitorWaitedEvent(jep._PyJObject): ...

class ThreadStartEvent(jep._PyJObject): ...

class MonitorContendedEnterEvent(jep._PyJObject): ...

class MethodEntryEvent(jep._PyJObject): ...

class LocatableEvent(jep._PyJObject): ...

class MonitorContendedEnteredEvent(jep._PyJObject): ...

class StepEvent(jep._PyJObject): ...

class EventQueue(jep._PyJObject): ...

class ModificationWatchpointEvent(jep._PyJObject): ...

class VMDisconnectEvent(jep._PyJObject): ...

class ExceptionEvent(jep._PyJObject): ...

class BreakpointEvent(jep._PyJObject): ...

class AccessWatchpointEvent(jep._PyJObject): ...

class VMStartEvent(jep._PyJObject): ...

class ThreadDeathEvent(jep._PyJObject): ...

class ClassPrepareEvent(jep._PyJObject): ...

class WatchpointEvent(jep._PyJObject): ...

