import jep

class MonitorWaitEvent(jep.PyJObject): ...

class ClassUnloadEvent(jep.PyJObject): ...

class MethodExitEvent(jep.PyJObject): ...

class EventIterator(jep.PyJObject): ...

class EventSet(jep.PyJObject): ...

class VMDeathEvent(jep.PyJObject): ...

class Event(jep.PyJObject): ...

class MonitorWaitedEvent(jep.PyJObject): ...

class ThreadStartEvent(jep.PyJObject): ...

class MonitorContendedEnterEvent(jep.PyJObject): ...

class MethodEntryEvent(jep.PyJObject): ...

class LocatableEvent(jep.PyJObject): ...

class MonitorContendedEnteredEvent(jep.PyJObject): ...

class StepEvent(jep.PyJObject): ...

class EventQueue(jep.PyJObject): ...

class ModificationWatchpointEvent(jep.PyJObject): ...

class VMDisconnectEvent(jep.PyJObject): ...

class ExceptionEvent(jep.PyJObject): ...

class BreakpointEvent(jep.PyJObject): ...

class AccessWatchpointEvent(jep.PyJObject): ...

class VMStartEvent(jep.PyJObject): ...

class ThreadDeathEvent(jep.PyJObject): ...

class ClassPrepareEvent(jep.PyJObject): ...

class WatchpointEvent(jep.PyJObject): ...

