import jep

class MethodEntryRequest(jep.PyJObject): ...

class ModificationWatchpointRequest(jep.PyJObject): ...

class MonitorWaitRequest(jep.PyJObject): ...

class ClassPrepareRequest(jep.PyJObject): ...

class EventRequest(jep.PyJObject): ...

class EventRequestManager(jep.PyJObject): ...

class VMDeathRequest(jep.PyJObject): ...

class StepRequest(jep.PyJObject): ...

class DuplicateRequestException(jep.PyJObject): ...

class WatchpointRequest(jep.PyJObject): ...

class ThreadStartRequest(jep.PyJObject): ...

class ClassUnloadRequest(jep.PyJObject): ...

class BreakpointRequest(jep.PyJObject): ...

class MethodExitRequest(jep.PyJObject): ...

class MonitorContendedEnterRequest(jep.PyJObject): ...

class InvalidRequestStateException(jep.PyJObject): ...

class ThreadDeathRequest(jep.PyJObject): ...

class AccessWatchpointRequest(jep.PyJObject): ...

class ExceptionRequest(jep.PyJObject): ...

class MonitorContendedEnteredRequest(jep.PyJObject): ...

