# pyright: reportPrivateUsage = none

import jep

class MethodEntryRequest[**Ts](jep._PyJObject): ...

class ClassPrepareRequest[**Ts](jep._PyJObject): ...

class StepRequest[**Ts](jep._PyJObject): ...

class EventRequest[**Ts](jep._PyJObject): ...

class MonitorContendedEnteredRequest[**Ts](jep._PyJObject): ...

class ThreadStartRequest[**Ts](jep._PyJObject): ...

class EventRequestManager[**Ts](jep._PyJObject): ...

class InvalidRequestStateException[**Ts](jep._PyJObject): ...

class BreakpointRequest[**Ts](jep._PyJObject): ...

class ThreadDeathRequest[**Ts](jep._PyJObject): ...

class MonitorContendedEnterRequest[**Ts](jep._PyJObject): ...

class ExceptionRequest[**Ts](jep._PyJObject): ...

class MonitorWaitRequest[**Ts](jep._PyJObject): ...

class MonitorWaitedRequest[**Ts](jep._PyJObject): ...

class ClassUnloadRequest[**Ts](jep._PyJObject): ...

class AccessWatchpointRequest[**Ts](jep._PyJObject): ...

class ModificationWatchpointRequest[**Ts](jep._PyJObject): ...

class MethodExitRequest[**Ts](jep._PyJObject): ...

class WatchpointRequest[**Ts](jep._PyJObject): ...

class VMDeathRequest[**Ts](jep._PyJObject): ...

class DuplicateRequestException[**Ts](jep._PyJObject): ...

