import jep

class MethodEntryRequest(jep._PyJObject): ...

class ModificationWatchpointRequest(jep._PyJObject): ...

class MonitorWaitRequest(jep._PyJObject): ...

class ClassPrepareRequest(jep._PyJObject): ...

class EventRequest(jep._PyJObject): ...

class EventRequestManager(jep._PyJObject): ...

class VMDeathRequest(jep._PyJObject): ...

class StepRequest(jep._PyJObject): ...

class DuplicateRequestException(jep._PyJObject): ...

class WatchpointRequest(jep._PyJObject): ...

class ThreadStartRequest(jep._PyJObject): ...

class ClassUnloadRequest(jep._PyJObject): ...

class BreakpointRequest(jep._PyJObject): ...

class MethodExitRequest(jep._PyJObject): ...

class MonitorContendedEnterRequest(jep._PyJObject): ...

class InvalidRequestStateException(jep._PyJObject): ...

class ThreadDeathRequest(jep._PyJObject): ...

class AccessWatchpointRequest(jep._PyJObject): ...

class ExceptionRequest(jep._PyJObject): ...

class MonitorContendedEnteredRequest(jep._PyJObject): ...

