# pyright: reportPrivateUsage = none

import jep

class VarSnippet[**Ts](jep._PyJObject): ...

class MethodSnippet[**Ts](jep._PyJObject): ...

class JShellException[**Ts](jep._PyJObject): ...

class Snippet[**Ts](jep._PyJObject): ...

class ImportSnippet[**Ts](jep._PyJObject): ...

class Diag[**Ts](jep._PyJObject): ...

class ExpressionSnippet[**Ts](jep._PyJObject): ...

class SnippetEvent[**Ts](jep._PyJObject): ...

class UnresolvedReferenceException[**Ts](jep._PyJObject): ...

class ErroneousSnippet[**Ts](jep._PyJObject): ...

class JShell[**Ts](jep._PyJObject): ...

class TypeDeclSnippet[**Ts](jep._PyJObject): ...

class DeclarationSnippet[**Ts](jep._PyJObject): ...

class SourceCodeAnalysis[**Ts](jep._PyJObject): ...

class PersistentSnippet[**Ts](jep._PyJObject): ...

class EvalException[**Ts](jep._PyJObject): ...

class StatementSnippet[**Ts](jep._PyJObject): ...

