import jep

class DeclarationSnippet(jep.PyJObject): ...

class UnresolvedReferenceException(jep.PyJObject): ...

class PersistentSnippet(jep.PyJObject): ...

class VarSnippet(jep.PyJObject): ...

class Snippet(jep.PyJObject): ...

class Diag(jep.PyJObject): ...

class ErroneousSnippet(jep.PyJObject): ...

class SnippetEvent(jep.PyJObject): ...

class ImportSnippet(jep.PyJObject): ...

class StatementSnippet(jep.PyJObject): ...

class EvalException(jep.PyJObject): ...

class TypeDeclSnippet(jep.PyJObject): ...

class JShell(jep.PyJObject): ...

class MethodSnippet(jep.PyJObject): ...

class JShellException(jep.PyJObject): ...

class ExpressionSnippet(jep.PyJObject): ...

class SourceCodeAnalysis(jep.PyJObject): ...

