import jep

class DeclarationSnippet(jep._PyJObject): ...

class UnresolvedReferenceException(jep._PyJObject): ...

class PersistentSnippet(jep._PyJObject): ...

class VarSnippet(jep._PyJObject): ...

class Snippet(jep._PyJObject): ...

class Diag(jep._PyJObject): ...

class ErroneousSnippet(jep._PyJObject): ...

class SnippetEvent(jep._PyJObject): ...

class ImportSnippet(jep._PyJObject): ...

class StatementSnippet(jep._PyJObject): ...

class EvalException(jep._PyJObject): ...

class TypeDeclSnippet(jep._PyJObject): ...

class JShell(jep._PyJObject): ...

class MethodSnippet(jep._PyJObject): ...

class JShellException(jep._PyJObject): ...

class ExpressionSnippet(jep._PyJObject): ...

class SourceCodeAnalysis(jep._PyJObject): ...

