import jep

class Util(jep._PyJObject): ...

class LocalExecutionControl(jep._PyJObject): ...

class JdiInitiator(jep._PyJObject): ...

class LocalExecutionControlProvider(jep._PyJObject): ...

class JdiExecutionControlProvider(jep._PyJObject): ...

class LoaderDelegate(jep._PyJObject): ...

class JdiExecutionControl(jep._PyJObject): ...

class StreamingExecutionControl(jep._PyJObject): ...

class DirectExecutionControl(jep._PyJObject): ...

class JdiDefaultExecutionControl(jep._PyJObject): ...

class RemoteExecutionControl(jep._PyJObject): ...

