# pyright: reportPrivateUsage = none

import jep

class Util[**Ts](jep._PyJObject): ...

class JdiInitiator[**Ts](jep._PyJObject): ...

class LocalExecutionControl[**Ts](jep._PyJObject): ...

class StreamingExecutionControl[**Ts](jep._PyJObject): ...

class FailOverExecutionControlProvider[**Ts](jep._PyJObject): ...

class JdiExecutionControl[**Ts](jep._PyJObject): ...

class RemoteExecutionControl[**Ts](jep._PyJObject): ...

class DirectExecutionControl[**Ts](jep._PyJObject): ...

class JdiExecutionControlProvider[**Ts](jep._PyJObject): ...

class LocalExecutionControlProvider[**Ts](jep._PyJObject): ...

class LoaderDelegate[**Ts](jep._PyJObject): ...

class JdiDefaultExecutionControl[**Ts](jep._PyJObject): ...

