import jep

class Util(jep.PyJObject): ...

class LocalExecutionControl(jep.PyJObject): ...

class JdiInitiator(jep.PyJObject): ...

class LocalExecutionControlProvider(jep.PyJObject): ...

class JdiExecutionControlProvider(jep.PyJObject): ...

class LoaderDelegate(jep.PyJObject): ...

class JdiExecutionControl(jep.PyJObject): ...

class StreamingExecutionControl(jep.PyJObject): ...

class DirectExecutionControl(jep.PyJObject): ...

class JdiDefaultExecutionControl(jep.PyJObject): ...

class RemoteExecutionControl(jep.PyJObject): ...

