import jep

class ExecutionEnv(jep._PyJObject): ...

class SPIResolutionException(jep._PyJObject): ...

class ExecutionControlProvider(jep._PyJObject): ...

class ExecutionControl(jep._PyJObject): ...

