# pyright: reportPrivateUsage = none

import jep

class OverrunStyle[**Ts](jep._PyJObject): ...

class TreeView[**Ts](jep._PyJObject): ...

class MenuButton[**Ts](jep._PyJObject): ...

class ListCell[**Ts](jep._PyJObject): ...

class TableCell[**Ts](jep._PyJObject): ...

class TablePositionBase[**Ts](jep._PyJObject): ...

class TreeTableColumn[**Ts](jep._PyJObject): ...

class CustomMenuItem[**Ts](jep._PyJObject): ...

class TreeTableRow[**Ts](jep._PyJObject): ...

class DialogEvent[**Ts](jep._PyJObject): ...

class IndexedCell[**Ts](jep._PyJObject): ...

class SkinBase[**Ts](jep._PyJObject): ...

class TreeTableView[**Ts](jep._PyJObject): ...

class ColorPicker[**Ts](jep._PyJObject): ...

class Skin[**Ts](jep._PyJObject): ...

class TextInputControl[**Ts](jep._PyJObject): ...

class ToggleGroup[**Ts](jep._PyJObject): ...

class ContentDisplay[**Ts](jep._PyJObject): ...

class SortEvent[**Ts](jep._PyJObject): ...

class RadioMenuItem[**Ts](jep._PyJObject): ...

class ProgressIndicator[**Ts](jep._PyJObject): ...

class TitledPane[**Ts](jep._PyJObject): ...

class MenuItem[**Ts](jep._PyJObject): ...

class ListView[**Ts](jep._PyJObject): ...

class Button[**Ts](jep._PyJObject): ...

class TabPane[**Ts](jep._PyJObject): ...

class Cell[**Ts](jep._PyJObject): ...

class TreeTablePosition[**Ts](jep._PyJObject): ...

class DateCell[**Ts](jep._PyJObject): ...

class CheckBoxTreeItem[**Ts](jep._PyJObject): ...

class TextInputDialog[**Ts](jep._PyJObject): ...

class FocusModel[**Ts](jep._PyJObject): ...

class TableFocusModel[**Ts](jep._PyJObject): ...

class Skinnable[**Ts](jep._PyJObject): ...

class ContextMenu[**Ts](jep._PyJObject): ...

class Pagination[**Ts](jep._PyJObject): ...

class Label[**Ts](jep._PyJObject): ...

class ButtonType[**Ts](jep._PyJObject): ...

class TablePosition[**Ts](jep._PyJObject): ...

class SelectionModel[**Ts](jep._PyJObject): ...

class IndexRange[**Ts](jep._PyJObject): ...

class Accordion[**Ts](jep._PyJObject): ...

class SpinnerValueFactory[**Ts](jep._PyJObject): ...

class Tab[**Ts](jep._PyJObject): ...

class TableSelectionModel[**Ts](jep._PyJObject): ...

class TextArea[**Ts](jep._PyJObject): ...

class ComboBox[**Ts](jep._PyJObject): ...

class TreeItem[**Ts](jep._PyJObject): ...

class ChoiceDialog[**Ts](jep._PyJObject): ...

class Alert[**Ts](jep._PyJObject): ...

class ToggleButton[**Ts](jep._PyJObject): ...

class CheckMenuItem[**Ts](jep._PyJObject): ...

class ProgressBar[**Ts](jep._PyJObject): ...

class SplitPane[**Ts](jep._PyJObject): ...

class DatePicker[**Ts](jep._PyJObject): ...

class TreeCell[**Ts](jep._PyJObject): ...

class TreeTableCell[**Ts](jep._PyJObject): ...

class ButtonBase[**Ts](jep._PyJObject): ...

class DialogPane[**Ts](jep._PyJObject): ...

class ToolBar[**Ts](jep._PyJObject): ...

class Tooltip[**Ts](jep._PyJObject): ...

class TreeSortMode[**Ts](jep._PyJObject): ...

class SelectionMode[**Ts](jep._PyJObject): ...

class Toggle[**Ts](jep._PyJObject): ...

class Dialog[**Ts](jep._PyJObject): ...

class CheckBox[**Ts](jep._PyJObject): ...

class Menu[**Ts](jep._PyJObject): ...

class SplitMenuButton[**Ts](jep._PyJObject): ...

class RadioButton[**Ts](jep._PyJObject): ...

class ButtonBar[**Ts](jep._PyJObject): ...

class TableRow[**Ts](jep._PyJObject): ...

class Hyperlink[**Ts](jep._PyJObject): ...

class PasswordField[**Ts](jep._PyJObject): ...

class TableColumn[**Ts](jep._PyJObject): ...

class TextFormatter[**Ts](jep._PyJObject): ...

class ScrollBar[**Ts](jep._PyJObject): ...

class ResizeFeaturesBase[**Ts](jep._PyJObject): ...

class TableColumnBase[**Ts](jep._PyJObject): ...

class Separator[**Ts](jep._PyJObject): ...

class ScrollToEvent[**Ts](jep._PyJObject): ...

class MultipleSelectionModel[**Ts](jep._PyJObject): ...

class Control[**Ts](jep._PyJObject): ...

class TableView[**Ts](jep._PyJObject): ...

class ComboBoxBase[**Ts](jep._PyJObject): ...

class Labeled[**Ts](jep._PyJObject): ...

class ScrollPane[**Ts](jep._PyJObject): ...

class ChoiceBox[**Ts](jep._PyJObject): ...

class Spinner[**Ts](jep._PyJObject): ...

class SeparatorMenuItem[**Ts](jep._PyJObject): ...

class TextField[**Ts](jep._PyJObject): ...

class Slider[**Ts](jep._PyJObject): ...

class SingleSelectionModel[**Ts](jep._PyJObject): ...

class MenuBar[**Ts](jep._PyJObject): ...

class PopupControl[**Ts](jep._PyJObject): ...

