# pyright: reportPrivateUsage = none

import jep

class PropertyValueFactory[**Ts](jep._PyJObject): ...

class ProgressBarTreeTableCell[**Ts](jep._PyJObject): ...

class TextFieldTableCell[**Ts](jep._PyJObject): ...

class TextFieldTreeTableCell[**Ts](jep._PyJObject): ...

class ChoiceBoxListCell[**Ts](jep._PyJObject): ...

class ComboBoxTreeTableCell[**Ts](jep._PyJObject): ...

class ChoiceBoxTableCell[**Ts](jep._PyJObject): ...

class MapValueFactory[**Ts](jep._PyJObject): ...

class ChoiceBoxTreeCell[**Ts](jep._PyJObject): ...

class TextFieldTreeCell[**Ts](jep._PyJObject): ...

class CheckBoxListCell[**Ts](jep._PyJObject): ...

class ComboBoxTableCell[**Ts](jep._PyJObject): ...

class TextFieldListCell[**Ts](jep._PyJObject): ...

class TreeItemPropertyValueFactory[**Ts](jep._PyJObject): ...

class CheckBoxTreeTableCell[**Ts](jep._PyJObject): ...

class ComboBoxTreeCell[**Ts](jep._PyJObject): ...

class ProgressBarTableCell[**Ts](jep._PyJObject): ...

class CheckBoxTreeCell[**Ts](jep._PyJObject): ...

class ComboBoxListCell[**Ts](jep._PyJObject): ...

class ChoiceBoxTreeTableCell[**Ts](jep._PyJObject): ...

