# pyright: reportPrivateUsage = none

import jep

class TreeViewSkin[**Ts](jep._PyJObject): ...

class PaginationSkin[**Ts](jep._PyJObject): ...

class TableRowSkin[**Ts](jep._PyJObject): ...

class ProgressIndicatorSkin[**Ts](jep._PyJObject): ...

class LabelSkin[**Ts](jep._PyJObject): ...

class RadioButtonSkin[**Ts](jep._PyJObject): ...

class ScrollPaneSkin[**Ts](jep._PyJObject): ...

class ListViewSkin[**Ts](jep._PyJObject): ...

class ContextMenuSkin[**Ts](jep._PyJObject): ...

class ComboBoxListViewSkin[**Ts](jep._PyJObject): ...

class SeparatorSkin[**Ts](jep._PyJObject): ...

class TableColumnHeader[**Ts](jep._PyJObject): ...

class LabeledSkinBase[**Ts](jep._PyJObject): ...

class CheckBoxSkin[**Ts](jep._PyJObject): ...

class ListCellSkin[**Ts](jep._PyJObject): ...

class TableCellSkin[**Ts](jep._PyJObject): ...

class TableViewSkinBase[**Ts](jep._PyJObject): ...

class TooltipSkin[**Ts](jep._PyJObject): ...

class MenuBarSkin[**Ts](jep._PyJObject): ...

class TreeCellSkin[**Ts](jep._PyJObject): ...

class SpinnerSkin[**Ts](jep._PyJObject): ...

class ButtonSkin[**Ts](jep._PyJObject): ...

class ToggleButtonSkin[**Ts](jep._PyJObject): ...

class TabPaneSkin[**Ts](jep._PyJObject): ...

class ScrollBarSkin[**Ts](jep._PyJObject): ...

class TextAreaSkin[**Ts](jep._PyJObject): ...

class TableHeaderRow[**Ts](jep._PyJObject): ...

class ChoiceBoxSkin[**Ts](jep._PyJObject): ...

class SplitMenuButtonSkin[**Ts](jep._PyJObject): ...

class MenuButtonSkin[**Ts](jep._PyJObject): ...

class TableViewSkin[**Ts](jep._PyJObject): ...

class ButtonBarSkin[**Ts](jep._PyJObject): ...

class ColorPickerSkin[**Ts](jep._PyJObject): ...

class DatePickerSkin[**Ts](jep._PyJObject): ...

class AccordionSkin[**Ts](jep._PyJObject): ...

class TreeTableViewSkin[**Ts](jep._PyJObject): ...

class TreeTableCellSkin[**Ts](jep._PyJObject): ...

class NestedTableColumnHeader[**Ts](jep._PyJObject): ...

class VirtualContainerBase[**Ts](jep._PyJObject): ...

class ComboBoxPopupControl[**Ts](jep._PyJObject): ...

class ToolBarSkin[**Ts](jep._PyJObject): ...

class TextInputControlSkin[**Ts](jep._PyJObject): ...

class TableCellSkinBase[**Ts](jep._PyJObject): ...

class SliderSkin[**Ts](jep._PyJObject): ...

class TableRowSkinBase[**Ts](jep._PyJObject): ...

class DateCellSkin[**Ts](jep._PyJObject): ...

class HyperlinkSkin[**Ts](jep._PyJObject): ...

class CellSkinBase[**Ts](jep._PyJObject): ...

class SplitPaneSkin[**Ts](jep._PyJObject): ...

class VirtualFlow[**Ts](jep._PyJObject): ...

class ProgressBarSkin[**Ts](jep._PyJObject): ...

class TextFieldSkin[**Ts](jep._PyJObject): ...

class MenuButtonSkinBase[**Ts](jep._PyJObject): ...

class TitledPaneSkin[**Ts](jep._PyJObject): ...

class ComboBoxBaseSkin[**Ts](jep._PyJObject): ...

class TreeTableRowSkin[**Ts](jep._PyJObject): ...

