import jep

class RMISecurityManager(jep.PyJObject): ...

class StubNotFoundException(jep.PyJObject): ...

class MarshalledObject(jep.PyJObject): ...

class NotBoundException(jep.PyJObject): ...

class UnknownHostException(jep.PyJObject): ...

class UnexpectedException(jep.PyJObject): ...

class ConnectException(jep.PyJObject): ...

class AlreadyBoundException(jep.PyJObject): ...

class AccessException(jep.PyJObject): ...

class ServerException(jep.PyJObject): ...

class ServerRuntimeException(jep.PyJObject): ...

class UnmarshalException(jep.PyJObject): ...

class Remote(jep.PyJObject): ...

class ConnectIOException(jep.PyJObject): ...

class RemoteException(jep.PyJObject): ...

class RMISecurityException(jep.PyJObject): ...

class NoSuchObjectException(jep.PyJObject): ...

class Naming(jep.PyJObject): ...

class MarshalException(jep.PyJObject): ...

class ServerError(jep.PyJObject): ...

