# pyright: reportPrivateUsage = none

import jep

class NotBoundException[**Ts](jep._PyJObject): ...

class AlreadyBoundException[**Ts](jep._PyJObject): ...

class NoSuchObjectException[**Ts](jep._PyJObject): ...

class ServerException[**Ts](jep._PyJObject): ...

class ConnectIOException[**Ts](jep._PyJObject): ...

class MarshalledObject[**Ts](jep._PyJObject): ...

class UnexpectedException[**Ts](jep._PyJObject): ...

class ServerRuntimeException[**Ts](jep._PyJObject): ...

class UnknownHostException[**Ts](jep._PyJObject): ...

class RMISecurityManager[**Ts](jep._PyJObject): ...

class RMISecurityException[**Ts](jep._PyJObject): ...

class ConnectException[**Ts](jep._PyJObject): ...

class StubNotFoundException[**Ts](jep._PyJObject): ...

class MarshalException[**Ts](jep._PyJObject): ...

class RemoteException[**Ts](jep._PyJObject): ...

class Remote[**Ts](jep._PyJObject): ...

class AccessException[**Ts](jep._PyJObject): ...

class Naming[**Ts](jep._PyJObject): ...

class UnmarshalException[**Ts](jep._PyJObject): ...

class ServerError[**Ts](jep._PyJObject): ...

