import jep

class RMISecurityManager(jep._PyJObject): ...

class StubNotFoundException(jep._PyJObject): ...

class MarshalledObject(jep._PyJObject): ...

class NotBoundException(jep._PyJObject): ...

class UnknownHostException(jep._PyJObject): ...

class UnexpectedException(jep._PyJObject): ...

class ConnectException(jep._PyJObject): ...

class AlreadyBoundException(jep._PyJObject): ...

class AccessException(jep._PyJObject): ...

class ServerException(jep._PyJObject): ...

class ServerRuntimeException(jep._PyJObject): ...

class UnmarshalException(jep._PyJObject): ...

class Remote(jep._PyJObject): ...

class ConnectIOException(jep._PyJObject): ...

class RemoteException(jep._PyJObject): ...

class RMISecurityException(jep._PyJObject): ...

class NoSuchObjectException(jep._PyJObject): ...

class Naming(jep._PyJObject): ...

class MarshalException(jep._PyJObject): ...

class ServerError(jep._PyJObject): ...

