import jep

class Activatable(jep._PyJObject): ...

class ActivationInstantiator(jep._PyJObject): ...

class ActivateFailedException(jep._PyJObject): ...

class ActivationGroupID(jep._PyJObject): ...

class ActivationDesc(jep._PyJObject): ...

class ActivationMonitor(jep._PyJObject): ...

class ActivationGroup_Stub(jep._PyJObject): ...

class UnknownGroupException(jep._PyJObject): ...

class ActivationGroup(jep._PyJObject): ...

class ActivationException(jep._PyJObject): ...

class ActivationGroupDesc(jep._PyJObject): ...

class Activator(jep._PyJObject): ...

class UnknownObjectException(jep._PyJObject): ...

class ActivationSystem(jep._PyJObject): ...

class ActivationID(jep._PyJObject): ...

