# pyright: reportPrivateUsage = none

import jep

class ActivationGroup[**Ts](jep._PyJObject): ...

class UnknownGroupException[**Ts](jep._PyJObject): ...

class ActivationException[**Ts](jep._PyJObject): ...

class ActivationDesc[**Ts](jep._PyJObject): ...

class UnknownObjectException[**Ts](jep._PyJObject): ...

class ActivationMonitor[**Ts](jep._PyJObject): ...

class ActivationSystem[**Ts](jep._PyJObject): ...

class ActivationInstantiator[**Ts](jep._PyJObject): ...

class ActivateFailedException[**Ts](jep._PyJObject): ...

class Activatable[**Ts](jep._PyJObject): ...

class ActivationGroupID[**Ts](jep._PyJObject): ...

class ActivationGroup_Stub[**Ts](jep._PyJObject): ...

class ActivationGroupDesc[**Ts](jep._PyJObject): ...

class Activator[**Ts](jep._PyJObject): ...

class ActivationID[**Ts](jep._PyJObject): ...

