import jep

class Activatable(jep.PyJObject): ...

class ActivationInstantiator(jep.PyJObject): ...

class ActivateFailedException(jep.PyJObject): ...

class ActivationGroupID(jep.PyJObject): ...

class ActivationDesc(jep.PyJObject): ...

class ActivationMonitor(jep.PyJObject): ...

class ActivationGroup_Stub(jep.PyJObject): ...

class UnknownGroupException(jep.PyJObject): ...

class ActivationGroup(jep.PyJObject): ...

class ActivationException(jep.PyJObject): ...

class ActivationGroupDesc(jep.PyJObject): ...

class Activator(jep.PyJObject): ...

class UnknownObjectException(jep.PyJObject): ...

class ActivationSystem(jep.PyJObject): ...

class ActivationID(jep.PyJObject): ...

