import jep

class UID(jep.PyJObject): ...

class ServerCloneException(jep.PyJObject): ...

class RemoteStub(jep.PyJObject): ...

class Skeleton(jep.PyJObject): ...

class RMIClassLoaderSpi(jep.PyJObject): ...

class SkeletonMismatchException(jep.PyJObject): ...

class RemoteObjectInvocationHandler(jep.PyJObject): ...

class SkeletonNotFoundException(jep.PyJObject): ...

class RemoteServer(jep.PyJObject): ...

class SocketSecurityException(jep.PyJObject): ...

class Unreferenced(jep.PyJObject): ...

class LoaderHandler(jep.PyJObject): ...

class RemoteCall(jep.PyJObject): ...

class RMIClientSocketFactory(jep.PyJObject): ...

class ExportException(jep.PyJObject): ...

class UnicastRemoteObject(jep.PyJObject): ...

class ServerNotActiveException(jep.PyJObject): ...

class RMIClassLoader(jep.PyJObject): ...

class Operation(jep.PyJObject): ...

class LogStream(jep.PyJObject): ...

class RemoteRef(jep.PyJObject): ...

class RMIFailureHandler(jep.PyJObject): ...

class RMIServerSocketFactory(jep.PyJObject): ...

class ObjID(jep.PyJObject): ...

class RemoteObject(jep.PyJObject): ...

class ServerRef(jep.PyJObject): ...

