# pyright: reportPrivateUsage = none

import jep

class ObjID[**Ts](jep._PyJObject): ...

class RMIClassLoaderSpi[**Ts](jep._PyJObject): ...

class Unreferenced[**Ts](jep._PyJObject): ...

class RMIClientSocketFactory[**Ts](jep._PyJObject): ...

class RemoteCall[**Ts](jep._PyJObject): ...

class SocketSecurityException[**Ts](jep._PyJObject): ...

class ServerCloneException[**Ts](jep._PyJObject): ...

class RMIFailureHandler[**Ts](jep._PyJObject): ...

class ServerNotActiveException[**Ts](jep._PyJObject): ...

class RemoteRef[**Ts](jep._PyJObject): ...

class RMIServerSocketFactory[**Ts](jep._PyJObject): ...

class UnicastRemoteObject[**Ts](jep._PyJObject): ...

class SkeletonMismatchException[**Ts](jep._PyJObject): ...

class SkeletonNotFoundException[**Ts](jep._PyJObject): ...

class Operation[**Ts](jep._PyJObject): ...

class RemoteObject[**Ts](jep._PyJObject): ...

class LogStream[**Ts](jep._PyJObject): ...

class Skeleton[**Ts](jep._PyJObject): ...

class RMISocketFactory[**Ts](jep._PyJObject): ...

class ServerRef[**Ts](jep._PyJObject): ...

class RemoteObjectInvocationHandler[**Ts](jep._PyJObject): ...

class LoaderHandler[**Ts](jep._PyJObject): ...

class UID[**Ts](jep._PyJObject): ...

class ExportException[**Ts](jep._PyJObject): ...

class RMIClassLoader[**Ts](jep._PyJObject): ...

class RemoteServer[**Ts](jep._PyJObject): ...

