import jep

class UID(jep._PyJObject): ...

class ServerCloneException(jep._PyJObject): ...

class RemoteStub(jep._PyJObject): ...

class Skeleton(jep._PyJObject): ...

class RMIClassLoaderSpi(jep._PyJObject): ...

class SkeletonMismatchException(jep._PyJObject): ...

class RemoteObjectInvocationHandler(jep._PyJObject): ...

class SkeletonNotFoundException(jep._PyJObject): ...

class RemoteServer(jep._PyJObject): ...

class SocketSecurityException(jep._PyJObject): ...

class Unreferenced(jep._PyJObject): ...

class LoaderHandler(jep._PyJObject): ...

class RemoteCall(jep._PyJObject): ...

class RMIClientSocketFactory(jep._PyJObject): ...

class ExportException(jep._PyJObject): ...

class UnicastRemoteObject(jep._PyJObject): ...

class ServerNotActiveException(jep._PyJObject): ...

class RMIClassLoader(jep._PyJObject): ...

class Operation(jep._PyJObject): ...

class LogStream(jep._PyJObject): ...

class RemoteRef(jep._PyJObject): ...

class RMIFailureHandler(jep._PyJObject): ...

class RMIServerSocketFactory(jep._PyJObject): ...

class ObjID(jep._PyJObject): ...

class RemoteObject(jep._PyJObject): ...

class ServerRef(jep._PyJObject): ...

