# pyright: reportPrivateUsage = none

import jep

class Category[**Ts](jep._PyJObject): ...

class MetadataDefinition[**Ts](jep._PyJObject): ...

class BooleanFlag[**Ts](jep._PyJObject): ...

class MemoryAddress[**Ts](jep._PyJObject): ...

class Configuration[**Ts](jep._PyJObject): ...

class SettingControl[**Ts](jep._PyJObject): ...

class Unsigned[**Ts](jep._PyJObject): ...

class TransitionTo[**Ts](jep._PyJObject): ...

class Name[**Ts](jep._PyJObject): ...

class FlightRecorderPermission[**Ts](jep._PyJObject): ...

class Timestamp[**Ts](jep._PyJObject): ...

class Threshold[**Ts](jep._PyJObject): ...

class Enabled[**Ts](jep._PyJObject): ...

class AnnotationElement[**Ts](jep._PyJObject): ...

class Event[**Ts](jep._PyJObject): ...

class TransitionFrom[**Ts](jep._PyJObject): ...

class StackTrace[**Ts](jep._PyJObject): ...

class Frequency[**Ts](jep._PyJObject): ...

class Timespan[**Ts](jep._PyJObject): ...

class FlightRecorder[**Ts](jep._PyJObject): ...

class EventSettings[**Ts](jep._PyJObject): ...

class Label[**Ts](jep._PyJObject): ...

class SettingDescriptor[**Ts](jep._PyJObject): ...

class Experimental[**Ts](jep._PyJObject): ...

class Percentage[**Ts](jep._PyJObject): ...

class EventType[**Ts](jep._PyJObject): ...

class Description[**Ts](jep._PyJObject): ...

class SettingDefinition[**Ts](jep._PyJObject): ...

class RecordingState[**Ts](jep._PyJObject): ...

class Recording[**Ts](jep._PyJObject): ...

class Period[**Ts](jep._PyJObject): ...

class ContentType[**Ts](jep._PyJObject): ...

class DataAmount[**Ts](jep._PyJObject): ...

class EventFactory[**Ts](jep._PyJObject): ...

class Relational[**Ts](jep._PyJObject): ...

class ValueDescriptor[**Ts](jep._PyJObject): ...

class Registered[**Ts](jep._PyJObject): ...

class FlightRecorderListener[**Ts](jep._PyJObject): ...

