import jep

class Threshold(jep.PyJObject): ...

class Recording(jep.PyJObject): ...

class Unsigned(jep.PyJObject): ...

class MetadataDefinition(jep.PyJObject): ...

class Description(jep.PyJObject): ...

class EventFactory(jep.PyJObject): ...

class Event(jep.PyJObject): ...

class ValueDescriptor(jep.PyJObject): ...

class BooleanFlag(jep.PyJObject): ...

class RecordingState(jep.PyJObject): ...

class ContentType(jep.PyJObject): ...

class FlightRecorder(jep.PyJObject): ...

class SettingControl(jep.PyJObject): ...

class SettingDescriptor(jep.PyJObject): ...

class Registered(jep.PyJObject): ...

class Period(jep.PyJObject): ...

class MemoryAddress(jep.PyJObject): ...

class TransitionFrom(jep.PyJObject): ...

class Percentage(jep.PyJObject): ...

class EventType(jep.PyJObject): ...

class SettingDefinition(jep.PyJObject): ...

class StackTrace(jep.PyJObject): ...

class EventSettings(jep.PyJObject): ...

class Relational(jep.PyJObject): ...

class FlightRecorderPermission(jep.PyJObject): ...

class Configuration(jep.PyJObject): ...

class Enabled(jep.PyJObject): ...

class Experimental(jep.PyJObject): ...

class FlightRecorderListener(jep.PyJObject): ...

class Label(jep.PyJObject): ...

class Category(jep.PyJObject): ...

class TransitionTo(jep.PyJObject): ...

class Name(jep.PyJObject): ...

class AnnotationElement(jep.PyJObject): ...

class Timespan(jep.PyJObject): ...

class Timestamp(jep.PyJObject): ...

class Frequency(jep.PyJObject): ...

class DataAmount(jep.PyJObject): ...

