import jep

class Threshold(jep._PyJObject): ...

class Recording(jep._PyJObject): ...

class Unsigned(jep._PyJObject): ...

class MetadataDefinition(jep._PyJObject): ...

class Description(jep._PyJObject): ...

class EventFactory(jep._PyJObject): ...

class Event(jep._PyJObject): ...

class ValueDescriptor(jep._PyJObject): ...

class BooleanFlag(jep._PyJObject): ...

class RecordingState(jep._PyJObject): ...

class ContentType(jep._PyJObject): ...

class FlightRecorder(jep._PyJObject): ...

class SettingControl(jep._PyJObject): ...

class SettingDescriptor(jep._PyJObject): ...

class Registered(jep._PyJObject): ...

class Period(jep._PyJObject): ...

class MemoryAddress(jep._PyJObject): ...

class TransitionFrom(jep._PyJObject): ...

class Percentage(jep._PyJObject): ...

class EventType(jep._PyJObject): ...

class SettingDefinition(jep._PyJObject): ...

class StackTrace(jep._PyJObject): ...

class EventSettings(jep._PyJObject): ...

class Relational(jep._PyJObject): ...

class FlightRecorderPermission(jep._PyJObject): ...

class Configuration(jep._PyJObject): ...

class Enabled(jep._PyJObject): ...

class Experimental(jep._PyJObject): ...

class FlightRecorderListener(jep._PyJObject): ...

class Label(jep._PyJObject): ...

class Category(jep._PyJObject): ...

class TransitionTo(jep._PyJObject): ...

class Name(jep._PyJObject): ...

class AnnotationElement(jep._PyJObject): ...

class Timespan(jep._PyJObject): ...

class Timestamp(jep._PyJObject): ...

class Frequency(jep._PyJObject): ...

class DataAmount(jep._PyJObject): ...

