# pyright: reportPrivateUsage = none

import jep

class RecordingFile[**Ts](jep._PyJObject): ...

class RecordedThreadGroup[**Ts](jep._PyJObject): ...

class RecordedClass[**Ts](jep._PyJObject): ...

class RecordedThread[**Ts](jep._PyJObject): ...

class RecordedMethod[**Ts](jep._PyJObject): ...

class RecordedClassLoader[**Ts](jep._PyJObject): ...

class RecordedObject[**Ts](jep._PyJObject): ...

class RecordedFrame[**Ts](jep._PyJObject): ...

class RecordedEvent[**Ts](jep._PyJObject): ...

