import jep

class RecordedClassLoader(jep.PyJObject): ...

class RecordedThreadGroup(jep.PyJObject): ...

class RecordedObject(jep.PyJObject): ...

class RecordedFrame(jep.PyJObject): ...

class RecordedThread(jep.PyJObject): ...

class RecordedClass(jep.PyJObject): ...

class RecordedStackTrace(jep.PyJObject): ...

class RecordedMethod(jep.PyJObject): ...

class RecordingFile(jep.PyJObject): ...

