import jep

class RecordedClassLoader(jep._PyJObject): ...

class RecordedThreadGroup(jep._PyJObject): ...

class RecordedObject(jep._PyJObject): ...

class RecordedFrame(jep._PyJObject): ...

class RecordedThread(jep._PyJObject): ...

class RecordedClass(jep._PyJObject): ...

class RecordedStackTrace(jep._PyJObject): ...

class RecordedMethod(jep._PyJObject): ...

class RecordingFile(jep._PyJObject): ...

