# pyright: reportPrivateUsage = none

import jep

class AbstractNotificationHandler[**Ts](jep._PyJObject): ...

class SctpStandardSocketOptions[**Ts](jep._PyJObject): ...

class PeerAddressChangeNotification[**Ts](jep._PyJObject): ...

class SctpMultiChannel[**Ts](jep._PyJObject): ...

class IllegalUnbindException[**Ts](jep._PyJObject): ...

class SctpServerChannel[**Ts](jep._PyJObject): ...

class IllegalReceiveException[**Ts](jep._PyJObject): ...

class AssociationChangeNotification[**Ts](jep._PyJObject): ...

class SendFailedNotification[**Ts](jep._PyJObject): ...

class Association[**Ts](jep._PyJObject): ...

class InvalidStreamException[**Ts](jep._PyJObject): ...

class ShutdownNotification[**Ts](jep._PyJObject): ...

class SctpSocketOption[**Ts](jep._PyJObject): ...

class SctpChannel[**Ts](jep._PyJObject): ...

class MessageInfo[**Ts](jep._PyJObject): ...

class HandlerResult[**Ts](jep._PyJObject): ...

class NotificationHandler[**Ts](jep._PyJObject): ...

class Notification[**Ts](jep._PyJObject): ...

