import jep

class SctpSocketOption(jep.PyJObject): ...

class Association(jep.PyJObject): ...

class MessageInfo(jep.PyJObject): ...

class PeerAddressChangeNotification(jep.PyJObject): ...

class Notification(jep.PyJObject): ...

class AbstractNotificationHandler(jep.PyJObject): ...

class NotificationHandler(jep.PyJObject): ...

class SctpStandardSocketOptions(jep.PyJObject): ...

class IllegalUnbindException(jep.PyJObject): ...

class SctpServerChannel(jep.PyJObject): ...

class IllegalReceiveException(jep.PyJObject): ...

class SendFailedNotification(jep.PyJObject): ...

class SctpMultiChannel(jep.PyJObject): ...

class HandlerResult(jep.PyJObject): ...

class AssociationChangeNotification(jep.PyJObject): ...

class SctpChannel(jep.PyJObject): ...

class ShutdownNotification(jep.PyJObject): ...

class InvalidStreamException(jep.PyJObject): ...

