import jep

class SctpSocketOption(jep._PyJObject): ...

class Association(jep._PyJObject): ...

class MessageInfo(jep._PyJObject): ...

class PeerAddressChangeNotification(jep._PyJObject): ...

class Notification(jep._PyJObject): ...

class AbstractNotificationHandler(jep._PyJObject): ...

class NotificationHandler(jep._PyJObject): ...

class SctpStandardSocketOptions(jep._PyJObject): ...

class IllegalUnbindException(jep._PyJObject): ...

class SctpServerChannel(jep._PyJObject): ...

class IllegalReceiveException(jep._PyJObject): ...

class SendFailedNotification(jep._PyJObject): ...

class SctpMultiChannel(jep._PyJObject): ...

class HandlerResult(jep._PyJObject): ...

class AssociationChangeNotification(jep._PyJObject): ...

class SctpChannel(jep._PyJObject): ...

class ShutdownNotification(jep._PyJObject): ...

class InvalidStreamException(jep._PyJObject): ...

