# pyright: reportPrivateUsage = none

import jep

class HttpHeaders[**Ts](jep._PyJObject): ...

class HttpClient[**Ts](jep._PyJObject): ...

class WebSocket[**Ts](jep._PyJObject): ...

class WebSocketHandshakeException[**Ts](jep._PyJObject): ...

class HttpTimeoutException[**Ts](jep._PyJObject): ...

class HttpRequest[**Ts](jep._PyJObject): ...

class MultiMapResult[**Ts](jep._PyJObject): ...

class HttpResponse[**Ts](jep._PyJObject): ...

