import jep

class HttpRequest(jep.PyJObject): ...

class MultiMapResult(jep.PyJObject): ...

class WebSocket(jep.PyJObject): ...

class HttpResponse(jep.PyJObject): ...

class WebSocketHandshakeException(jep.PyJObject): ...

class HttpClient(jep.PyJObject): ...

class HttpHeaders(jep.PyJObject): ...

class HttpTimeoutException(jep.PyJObject): ...

