import jep

class HttpRequest(jep._PyJObject): ...

class MultiMapResult(jep._PyJObject): ...

class WebSocket(jep._PyJObject): ...

class HttpResponse(jep._PyJObject): ...

class WebSocketHandshakeException(jep._PyJObject): ...

class HttpClient(jep._PyJObject): ...

class HttpHeaders(jep._PyJObject): ...

class HttpTimeoutException(jep._PyJObject): ...

