import jep

class DOMImplementationSource(jep.PyJObject): ...

class Text(jep.PyJObject): ...

class TypeInfo(jep.PyJObject): ...

class DOMException(jep.PyJObject): ...

class ProcessingInstruction(jep.PyJObject): ...

class DOMLocator(jep.PyJObject): ...

class DOMErrorHandler(jep.PyJObject): ...

class DOMImplementation(jep.PyJObject): ...

class DOMError(jep.PyJObject): ...

class Entity(jep.PyJObject): ...

class NodeList(jep.PyJObject): ...

class Node(jep.PyJObject): ...

class NameList(jep.PyJObject): ...

class DOMImplementationList(jep.PyJObject): ...

class DOMConfiguration(jep.PyJObject): ...

class CDATASection(jep.PyJObject): ...

class DocumentType(jep.PyJObject): ...

class Comment(jep.PyJObject): ...

class Attr(jep.PyJObject): ...

class CharacterData(jep.PyJObject): ...

class ElementTraversal(jep.PyJObject): ...

class Element(jep.PyJObject): ...

class DocumentFragment(jep.PyJObject): ...

class NamedNodeMap(jep.PyJObject): ...

class Notation(jep.PyJObject): ...

class Document(jep.PyJObject): ...

class UserDataHandler(jep.PyJObject): ...

class DOMStringList(jep.PyJObject): ...

class EntityReference(jep.PyJObject): ...

