# pyright: reportPrivateUsage = none

import jep

class TypeInfo[**Ts](jep._PyJObject): ...

class NameList[**Ts](jep._PyJObject): ...

class EntityReference[**Ts](jep._PyJObject): ...

class CharacterData[**Ts](jep._PyJObject): ...

class ProcessingInstruction[**Ts](jep._PyJObject): ...

class Element[**Ts](jep._PyJObject): ...

class Document[**Ts](jep._PyJObject): ...

class DOMException[**Ts](jep._PyJObject): ...

class Node[**Ts](jep._PyJObject): ...

class Notation[**Ts](jep._PyJObject): ...

class DOMStringList[**Ts](jep._PyJObject): ...

class DocumentType[**Ts](jep._PyJObject): ...

class DOMImplementationSource[**Ts](jep._PyJObject): ...

class DOMLocator[**Ts](jep._PyJObject): ...

class Text[**Ts](jep._PyJObject): ...

class Entity[**Ts](jep._PyJObject): ...

class CDATASection[**Ts](jep._PyJObject): ...

class Attr[**Ts](jep._PyJObject): ...

class DOMError[**Ts](jep._PyJObject): ...

class ElementTraversal[**Ts](jep._PyJObject): ...

class DOMConfiguration[**Ts](jep._PyJObject): ...

class DOMImplementation[**Ts](jep._PyJObject): ...

class Comment[**Ts](jep._PyJObject): ...

class NodeList[**Ts](jep._PyJObject): ...

class DOMErrorHandler[**Ts](jep._PyJObject): ...

class DOMImplementationList[**Ts](jep._PyJObject): ...

class UserDataHandler[**Ts](jep._PyJObject): ...

class DocumentFragment[**Ts](jep._PyJObject): ...

class NamedNodeMap[**Ts](jep._PyJObject): ...

