import jep

class DOMImplementationSource(jep._PyJObject): ...

class Text(jep._PyJObject): ...

class TypeInfo(jep._PyJObject): ...

class DOMException(jep._PyJObject): ...

class ProcessingInstruction(jep._PyJObject): ...

class DOMLocator(jep._PyJObject): ...

class DOMErrorHandler(jep._PyJObject): ...

class DOMImplementation(jep._PyJObject): ...

class DOMError(jep._PyJObject): ...

class Entity(jep._PyJObject): ...

class NodeList(jep._PyJObject): ...

class Node(jep._PyJObject): ...

class NameList(jep._PyJObject): ...

class DOMImplementationList(jep._PyJObject): ...

class DOMConfiguration(jep._PyJObject): ...

class CDATASection(jep._PyJObject): ...

class DocumentType(jep._PyJObject): ...

class Comment(jep._PyJObject): ...

class Attr(jep._PyJObject): ...

class CharacterData(jep._PyJObject): ...

class ElementTraversal(jep._PyJObject): ...

class Element(jep._PyJObject): ...

class DocumentFragment(jep._PyJObject): ...

class NamedNodeMap(jep._PyJObject): ...

class Notation(jep._PyJObject): ...

class Document(jep._PyJObject): ...

class UserDataHandler(jep._PyJObject): ...

class DOMStringList(jep._PyJObject): ...

class EntityReference(jep._PyJObject): ...

