import jep

class DOMImplementationCSS(jep.PyJObject): ...

class CSSFontFaceRule(jep.PyJObject): ...

class RGBColor(jep.PyJObject): ...

class CSS2Properties(jep.PyJObject): ...

class CSSPageRule(jep.PyJObject): ...

class CSSStyleSheet(jep.PyJObject): ...

class CSSStyleRule(jep.PyJObject): ...

class Counter(jep.PyJObject): ...

class CSSPrimitiveValue(jep.PyJObject): ...

class CSSRuleList(jep.PyJObject): ...

class CSSUnknownRule(jep.PyJObject): ...

class CSSStyleDeclaration(jep.PyJObject): ...

class ViewCSS(jep.PyJObject): ...

class DocumentCSS(jep.PyJObject): ...

class CSSValueList(jep.PyJObject): ...

class ElementCSSInlineStyle(jep.PyJObject): ...

class CSSValue(jep.PyJObject): ...

class Rect(jep.PyJObject): ...

class CSSCharsetRule(jep.PyJObject): ...

class CSSRule(jep.PyJObject): ...

class CSSImportRule(jep.PyJObject): ...

class CSSMediaRule(jep.PyJObject): ...

