import jep

class DOMImplementationCSS(jep._PyJObject): ...

class CSSFontFaceRule(jep._PyJObject): ...

class RGBColor(jep._PyJObject): ...

class CSS2Properties(jep._PyJObject): ...

class CSSPageRule(jep._PyJObject): ...

class CSSStyleSheet(jep._PyJObject): ...

class CSSStyleRule(jep._PyJObject): ...

class Counter(jep._PyJObject): ...

class CSSPrimitiveValue(jep._PyJObject): ...

class CSSRuleList(jep._PyJObject): ...

class CSSUnknownRule(jep._PyJObject): ...

class CSSStyleDeclaration(jep._PyJObject): ...

class ViewCSS(jep._PyJObject): ...

class DocumentCSS(jep._PyJObject): ...

class CSSValueList(jep._PyJObject): ...

class ElementCSSInlineStyle(jep._PyJObject): ...

class CSSValue(jep._PyJObject): ...

class Rect(jep._PyJObject): ...

class CSSCharsetRule(jep._PyJObject): ...

class CSSRule(jep._PyJObject): ...

class CSSImportRule(jep._PyJObject): ...

class CSSMediaRule(jep._PyJObject): ...

