# pyright: reportPrivateUsage = none

import jep

class DocumentCSS[**Ts](jep._PyJObject): ...

class CSSRule[**Ts](jep._PyJObject): ...

class CSSMediaRule[**Ts](jep._PyJObject): ...

class ElementCSSInlineStyle[**Ts](jep._PyJObject): ...

class CSSStyleSheet[**Ts](jep._PyJObject): ...

class CSSPrimitiveValue[**Ts](jep._PyJObject): ...

class DOMImplementationCSS[**Ts](jep._PyJObject): ...

class CSSValueList[**Ts](jep._PyJObject): ...

class CSSStyleRule[**Ts](jep._PyJObject): ...

class RGBColor[**Ts](jep._PyJObject): ...

class CSSFontFaceRule[**Ts](jep._PyJObject): ...

class ViewCSS[**Ts](jep._PyJObject): ...

class CSSValue[**Ts](jep._PyJObject): ...

class CSSCharsetRule[**Ts](jep._PyJObject): ...

class CSSStyleDeclaration[**Ts](jep._PyJObject): ...

class CSSImportRule[**Ts](jep._PyJObject): ...

class CSSUnknownRule[**Ts](jep._PyJObject): ...

class CSSPageRule[**Ts](jep._PyJObject): ...

class CSS2Properties[**Ts](jep._PyJObject): ...

class CSSRuleList[**Ts](jep._PyJObject): ...

class Rect[**Ts](jep._PyJObject): ...

class Counter[**Ts](jep._PyJObject): ...

