import jep

class Event(jep.PyJObject): ...

class DocumentEvent(jep.PyJObject): ...

class MouseEvent(jep.PyJObject): ...

class EventException(jep.PyJObject): ...

class EventTarget(jep.PyJObject): ...

class EventListener(jep.PyJObject): ...

class MutationEvent(jep.PyJObject): ...

class UIEvent(jep.PyJObject): ...

