import jep

class Event(jep._PyJObject): ...

class DocumentEvent(jep._PyJObject): ...

class MouseEvent(jep._PyJObject): ...

class EventException(jep._PyJObject): ...

class EventTarget(jep._PyJObject): ...

class EventListener(jep._PyJObject): ...

class MutationEvent(jep._PyJObject): ...

class UIEvent(jep._PyJObject): ...

