# pyright: reportPrivateUsage = none

import jep

class DocumentEvent[**Ts](jep._PyJObject): ...

class EventException[**Ts](jep._PyJObject): ...

class EventListener[**Ts](jep._PyJObject): ...

class Event[**Ts](jep._PyJObject): ...

class MouseEvent[**Ts](jep._PyJObject): ...

class UIEvent[**Ts](jep._PyJObject): ...

class MutationEvent[**Ts](jep._PyJObject): ...

class EventTarget[**Ts](jep._PyJObject): ...

