import jep

class HTMLDOMImplementation(jep.PyJObject): ...

class HTMLIFrameElement(jep.PyJObject): ...

class HTMLHRElement(jep.PyJObject): ...

class HTMLMetaElement(jep.PyJObject): ...

class HTMLLabelElement(jep.PyJObject): ...

class HTMLHeadElement(jep.PyJObject): ...

class HTMLMenuElement(jep.PyJObject): ...

class HTMLDivElement(jep.PyJObject): ...

class HTMLPreElement(jep.PyJObject): ...

class HTMLParamElement(jep.PyJObject): ...

class HTMLInputElement(jep.PyJObject): ...

class HTMLHtmlElement(jep.PyJObject): ...

class HTMLImageElement(jep.PyJObject): ...

class HTMLAreaElement(jep.PyJObject): ...

class HTMLModElement(jep.PyJObject): ...

class HTMLBRElement(jep.PyJObject): ...

class HTMLTableCellElement(jep.PyJObject): ...

class HTMLOptionElement(jep.PyJObject): ...

class HTMLLegendElement(jep.PyJObject): ...

class HTMLTextAreaElement(jep.PyJObject): ...

class HTMLTableCaptionElement(jep.PyJObject): ...

class HTMLTitleElement(jep.PyJObject): ...

class HTMLUListElement(jep.PyJObject): ...

class HTMLLIElement(jep.PyJObject): ...

class HTMLQuoteElement(jep.PyJObject): ...

class HTMLHeadingElement(jep.PyJObject): ...

class HTMLIsIndexElement(jep.PyJObject): ...

class HTMLAppletElement(jep.PyJObject): ...

class HTMLTableRowElement(jep.PyJObject): ...

class HTMLDocument(jep.PyJObject): ...

class HTMLOListElement(jep.PyJObject): ...

class HTMLFrameSetElement(jep.PyJObject): ...

class HTMLOptGroupElement(jep.PyJObject): ...

class HTMLButtonElement(jep.PyJObject): ...

class HTMLFontElement(jep.PyJObject): ...

class HTMLTableElement(jep.PyJObject): ...

class HTMLFieldSetElement(jep.PyJObject): ...

class HTMLDListElement(jep.PyJObject): ...

class HTMLLinkElement(jep.PyJObject): ...

class HTMLTableColElement(jep.PyJObject): ...

class HTMLParagraphElement(jep.PyJObject): ...

class HTMLBaseElement(jep.PyJObject): ...

class HTMLSelectElement(jep.PyJObject): ...

class HTMLBaseFontElement(jep.PyJObject): ...

class HTMLDirectoryElement(jep.PyJObject): ...

class HTMLScriptElement(jep.PyJObject): ...

class HTMLElement(jep.PyJObject): ...

class HTMLStyleElement(jep.PyJObject): ...

class HTMLCollection(jep.PyJObject): ...

class HTMLObjectElement(jep.PyJObject): ...

class HTMLFormElement(jep.PyJObject): ...

class HTMLBodyElement(jep.PyJObject): ...

class HTMLMapElement(jep.PyJObject): ...

class HTMLAnchorElement(jep.PyJObject): ...

class HTMLTableSectionElement(jep.PyJObject): ...

