# pyright: reportPrivateUsage = none

import jep

class HTMLLIElement[**Ts](jep._PyJObject): ...

class HTMLElement[**Ts](jep._PyJObject): ...

class HTMLHeadingElement[**Ts](jep._PyJObject): ...

class HTMLPreElement[**Ts](jep._PyJObject): ...

class HTMLFrameElement[**Ts](jep._PyJObject): ...

class HTMLSelectElement[**Ts](jep._PyJObject): ...

class HTMLTableColElement[**Ts](jep._PyJObject): ...

class HTMLUListElement[**Ts](jep._PyJObject): ...

class HTMLBRElement[**Ts](jep._PyJObject): ...

class HTMLOptionElement[**Ts](jep._PyJObject): ...

class HTMLMenuElement[**Ts](jep._PyJObject): ...

class HTMLAppletElement[**Ts](jep._PyJObject): ...

class HTMLObjectElement[**Ts](jep._PyJObject): ...

class HTMLQuoteElement[**Ts](jep._PyJObject): ...

class HTMLMetaElement[**Ts](jep._PyJObject): ...

class HTMLAreaElement[**Ts](jep._PyJObject): ...

class HTMLDListElement[**Ts](jep._PyJObject): ...

class HTMLIsIndexElement[**Ts](jep._PyJObject): ...

class HTMLOptGroupElement[**Ts](jep._PyJObject): ...

class HTMLFormElement[**Ts](jep._PyJObject): ...

class HTMLBaseFontElement[**Ts](jep._PyJObject): ...

class HTMLTableCaptionElement[**Ts](jep._PyJObject): ...

class HTMLDocument[**Ts](jep._PyJObject): ...

class HTMLLinkElement[**Ts](jep._PyJObject): ...

class HTMLOListElement[**Ts](jep._PyJObject): ...

class HTMLHRElement[**Ts](jep._PyJObject): ...

class HTMLTableElement[**Ts](jep._PyJObject): ...

class HTMLImageElement[**Ts](jep._PyJObject): ...

class HTMLInputElement[**Ts](jep._PyJObject): ...

class HTMLParagraphElement[**Ts](jep._PyJObject): ...

class HTMLHtmlElement[**Ts](jep._PyJObject): ...

class HTMLDivElement[**Ts](jep._PyJObject): ...

class HTMLParamElement[**Ts](jep._PyJObject): ...

class HTMLScriptElement[**Ts](jep._PyJObject): ...

class HTMLAnchorElement[**Ts](jep._PyJObject): ...

class HTMLTextAreaElement[**Ts](jep._PyJObject): ...

class HTMLTitleElement[**Ts](jep._PyJObject): ...

class HTMLStyleElement[**Ts](jep._PyJObject): ...

class HTMLButtonElement[**Ts](jep._PyJObject): ...

class HTMLBaseElement[**Ts](jep._PyJObject): ...

class HTMLFieldSetElement[**Ts](jep._PyJObject): ...

class HTMLMapElement[**Ts](jep._PyJObject): ...

class HTMLTableRowElement[**Ts](jep._PyJObject): ...

class HTMLLegendElement[**Ts](jep._PyJObject): ...

class HTMLTableCellElement[**Ts](jep._PyJObject): ...

class HTMLFrameSetElement[**Ts](jep._PyJObject): ...

class HTMLCollection[**Ts](jep._PyJObject): ...

class HTMLIFrameElement[**Ts](jep._PyJObject): ...

class HTMLDirectoryElement[**Ts](jep._PyJObject): ...

class HTMLModElement[**Ts](jep._PyJObject): ...

class HTMLFontElement[**Ts](jep._PyJObject): ...

class HTMLBodyElement[**Ts](jep._PyJObject): ...

class HTMLTableSectionElement[**Ts](jep._PyJObject): ...

class HTMLDOMImplementation[**Ts](jep._PyJObject): ...

class HTMLLabelElement[**Ts](jep._PyJObject): ...

