import jep

class HTMLDOMImplementation(jep._PyJObject): ...

class HTMLIFrameElement(jep._PyJObject): ...

class HTMLHRElement(jep._PyJObject): ...

class HTMLMetaElement(jep._PyJObject): ...

class HTMLLabelElement(jep._PyJObject): ...

class HTMLHeadElement(jep._PyJObject): ...

class HTMLMenuElement(jep._PyJObject): ...

class HTMLDivElement(jep._PyJObject): ...

class HTMLPreElement(jep._PyJObject): ...

class HTMLParamElement(jep._PyJObject): ...

class HTMLInputElement(jep._PyJObject): ...

class HTMLHtmlElement(jep._PyJObject): ...

class HTMLImageElement(jep._PyJObject): ...

class HTMLAreaElement(jep._PyJObject): ...

class HTMLModElement(jep._PyJObject): ...

class HTMLBRElement(jep._PyJObject): ...

class HTMLTableCellElement(jep._PyJObject): ...

class HTMLOptionElement(jep._PyJObject): ...

class HTMLLegendElement(jep._PyJObject): ...

class HTMLTextAreaElement(jep._PyJObject): ...

class HTMLTableCaptionElement(jep._PyJObject): ...

class HTMLTitleElement(jep._PyJObject): ...

class HTMLUListElement(jep._PyJObject): ...

class HTMLLIElement(jep._PyJObject): ...

class HTMLQuoteElement(jep._PyJObject): ...

class HTMLHeadingElement(jep._PyJObject): ...

class HTMLIsIndexElement(jep._PyJObject): ...

class HTMLAppletElement(jep._PyJObject): ...

class HTMLTableRowElement(jep._PyJObject): ...

class HTMLDocument(jep._PyJObject): ...

class HTMLOListElement(jep._PyJObject): ...

class HTMLFrameSetElement(jep._PyJObject): ...

class HTMLOptGroupElement(jep._PyJObject): ...

class HTMLButtonElement(jep._PyJObject): ...

class HTMLFontElement(jep._PyJObject): ...

class HTMLTableElement(jep._PyJObject): ...

class HTMLFieldSetElement(jep._PyJObject): ...

class HTMLDListElement(jep._PyJObject): ...

class HTMLLinkElement(jep._PyJObject): ...

class HTMLTableColElement(jep._PyJObject): ...

class HTMLParagraphElement(jep._PyJObject): ...

class HTMLBaseElement(jep._PyJObject): ...

class HTMLSelectElement(jep._PyJObject): ...

class HTMLBaseFontElement(jep._PyJObject): ...

class HTMLDirectoryElement(jep._PyJObject): ...

class HTMLScriptElement(jep._PyJObject): ...

class HTMLElement(jep._PyJObject): ...

class HTMLStyleElement(jep._PyJObject): ...

class HTMLCollection(jep._PyJObject): ...

class HTMLObjectElement(jep._PyJObject): ...

class HTMLFormElement(jep._PyJObject): ...

class HTMLBodyElement(jep._PyJObject): ...

class HTMLMapElement(jep._PyJObject): ...

class HTMLAnchorElement(jep._PyJObject): ...

class HTMLTableSectionElement(jep._PyJObject): ...

