import jep

class LSResourceResolver(jep._PyJObject): ...

class LSInput(jep._PyJObject): ...

class LSParser(jep._PyJObject): ...

class LSOutput(jep._PyJObject): ...

class LSException(jep._PyJObject): ...

class LSLoadEvent(jep._PyJObject): ...

class LSSerializer(jep._PyJObject): ...

class DOMImplementationLS(jep._PyJObject): ...

class LSProgressEvent(jep._PyJObject): ...

class LSSerializerFilter(jep._PyJObject): ...

class LSParserFilter(jep._PyJObject): ...

