# pyright: reportPrivateUsage = none

import jep

class LSSerializerFilter[**Ts](jep._PyJObject): ...

class LSResourceResolver[**Ts](jep._PyJObject): ...

class LSException[**Ts](jep._PyJObject): ...

class LSParserFilter[**Ts](jep._PyJObject): ...

class LSOutput[**Ts](jep._PyJObject): ...

class DOMImplementationLS[**Ts](jep._PyJObject): ...

class LSInput[**Ts](jep._PyJObject): ...

class LSLoadEvent[**Ts](jep._PyJObject): ...

class LSParser[**Ts](jep._PyJObject): ...

class LSSerializer[**Ts](jep._PyJObject): ...

class LSProgressEvent[**Ts](jep._PyJObject): ...

