import jep

class LSResourceResolver(jep.PyJObject): ...

class LSInput(jep.PyJObject): ...

class LSParser(jep.PyJObject): ...

class LSOutput(jep.PyJObject): ...

class LSException(jep.PyJObject): ...

class LSLoadEvent(jep.PyJObject): ...

class LSSerializer(jep.PyJObject): ...

class DOMImplementationLS(jep.PyJObject): ...

class LSProgressEvent(jep.PyJObject): ...

class LSSerializerFilter(jep.PyJObject): ...

class LSParserFilter(jep.PyJObject): ...

