import jep

class StyleSheetList(jep.PyJObject): ...

class DocumentStyle(jep.PyJObject): ...

class StyleSheet(jep.PyJObject): ...

class MediaList(jep.PyJObject): ...

class LinkStyle(jep.PyJObject): ...

