import jep

class StyleSheetList(jep._PyJObject): ...

class DocumentStyle(jep._PyJObject): ...

class StyleSheet(jep._PyJObject): ...

class MediaList(jep._PyJObject): ...

class LinkStyle(jep._PyJObject): ...

