# pyright: reportPrivateUsage = none

import jep

class LinkStyle[**Ts](jep._PyJObject): ...

class DocumentStyle[**Ts](jep._PyJObject): ...

class StyleSheet[**Ts](jep._PyJObject): ...

class StyleSheetList[**Ts](jep._PyJObject): ...

class MediaList[**Ts](jep._PyJObject): ...

