# pyright: reportPrivateUsage = none

import jep

class NodeIterator[**Ts](jep._PyJObject): ...

class NodeFilter[**Ts](jep._PyJObject): ...

class TreeWalker[**Ts](jep._PyJObject): ...

class DocumentTraversal[**Ts](jep._PyJObject): ...

