import jep

class XPathExpression(jep._PyJObject): ...

class XPathNSResolver(jep._PyJObject): ...

class XPathException(jep._PyJObject): ...

class XPathNamespace(jep._PyJObject): ...

class XPathEvaluator(jep._PyJObject): ...

class XPathResult(jep._PyJObject): ...

