# pyright: reportPrivateUsage = none

import jep

class XPathException[**Ts](jep._PyJObject): ...

class XPathNSResolver[**Ts](jep._PyJObject): ...

class XPathResult[**Ts](jep._PyJObject): ...

class XPathEvaluator[**Ts](jep._PyJObject): ...

class XPathNamespace[**Ts](jep._PyJObject): ...

class XPathExpression[**Ts](jep._PyJObject): ...

