import jep

class XPathExpression(jep.PyJObject): ...

class XPathNSResolver(jep.PyJObject): ...

class XPathException(jep.PyJObject): ...

class XPathNamespace(jep.PyJObject): ...

class XPathEvaluator(jep.PyJObject): ...

class XPathResult(jep.PyJObject): ...

