# pyright: reportPrivateUsage = none

import jep

class MidiFileFormat[**Ts](jep._PyJObject): ...

class SoundbankResource[**Ts](jep._PyJObject): ...

class InvalidMidiDataException[**Ts](jep._PyJObject): ...

class MidiUnavailableException[**Ts](jep._PyJObject): ...

class MidiEvent[**Ts](jep._PyJObject): ...

class MidiSystem[**Ts](jep._PyJObject): ...

class Transmitter[**Ts](jep._PyJObject): ...

class SysexMessage[**Ts](jep._PyJObject): ...

class Sequence[**Ts](jep._PyJObject): ...

class MetaEventListener[**Ts](jep._PyJObject): ...

class VoiceStatus[**Ts](jep._PyJObject): ...

class Soundbank[**Ts](jep._PyJObject): ...

class MidiChannel[**Ts](jep._PyJObject): ...

class MidiDeviceReceiver[**Ts](jep._PyJObject): ...

class Patch[**Ts](jep._PyJObject): ...

class MidiDeviceTransmitter[**Ts](jep._PyJObject): ...

class Sequencer[**Ts](jep._PyJObject): ...

class ControllerEventListener[**Ts](jep._PyJObject): ...

class Instrument[**Ts](jep._PyJObject): ...

class Synthesizer[**Ts](jep._PyJObject): ...

class MidiMessage[**Ts](jep._PyJObject): ...

class ShortMessage[**Ts](jep._PyJObject): ...

class Receiver[**Ts](jep._PyJObject): ...

class MidiDevice[**Ts](jep._PyJObject): ...

class MetaMessage[**Ts](jep._PyJObject): ...

class Track[**Ts](jep._PyJObject): ...

