import jep

class Synthesizer(jep._PyJObject): ...

class Track(jep._PyJObject): ...

class Instrument(jep._PyJObject): ...

class Receiver(jep._PyJObject): ...

class Sequence(jep._PyJObject): ...

class MidiUnavailableException(jep._PyJObject): ...

class MidiDeviceTransmitter(jep._PyJObject): ...

class Soundbank(jep._PyJObject): ...

class MidiDevice(jep._PyJObject): ...

class Transmitter(jep._PyJObject): ...

class Sequencer(jep._PyJObject): ...

class SysexMessage(jep._PyJObject): ...

class MidiDeviceReceiver(jep._PyJObject): ...

class SoundbankResource(jep._PyJObject): ...

class ShortMessage(jep._PyJObject): ...

class MetaMessage(jep._PyJObject): ...

class MidiMessage(jep._PyJObject): ...

class InvalidMidiDataException(jep._PyJObject): ...

class MidiEvent(jep._PyJObject): ...

class ControllerEventListener(jep._PyJObject): ...

class Patch(jep._PyJObject): ...

class VoiceStatus(jep._PyJObject): ...

class MidiSystem(jep._PyJObject): ...

class MetaEventListener(jep._PyJObject): ...

class MidiChannel(jep._PyJObject): ...

class MidiFileFormat(jep._PyJObject): ...

