import jep

class Synthesizer(jep.PyJObject): ...

class Track(jep.PyJObject): ...

class Instrument(jep.PyJObject): ...

class Receiver(jep.PyJObject): ...

class Sequence(jep.PyJObject): ...

class MidiUnavailableException(jep.PyJObject): ...

class MidiDeviceTransmitter(jep.PyJObject): ...

class Soundbank(jep.PyJObject): ...

class MidiDevice(jep.PyJObject): ...

class Transmitter(jep.PyJObject): ...

class Sequencer(jep.PyJObject): ...

class SysexMessage(jep.PyJObject): ...

class MidiDeviceReceiver(jep.PyJObject): ...

class SoundbankResource(jep.PyJObject): ...

class ShortMessage(jep.PyJObject): ...

class MetaMessage(jep.PyJObject): ...

class MidiMessage(jep.PyJObject): ...

class InvalidMidiDataException(jep.PyJObject): ...

class MidiEvent(jep.PyJObject): ...

class ControllerEventListener(jep.PyJObject): ...

class Patch(jep.PyJObject): ...

class VoiceStatus(jep.PyJObject): ...

class MidiSystem(jep.PyJObject): ...

class MetaEventListener(jep.PyJObject): ...

class MidiChannel(jep.PyJObject): ...

class MidiFileFormat(jep.PyJObject): ...

