import jep

class TargetedNotification(jep._PyJObject): ...

class JMXConnectorServerFactory(jep._PyJObject): ...

class JMXAddressable(jep._PyJObject): ...

class JMXProviderException(jep._PyJObject): ...

class MBeanServerForwarder(jep._PyJObject): ...

class JMXConnectorServerProvider(jep._PyJObject): ...

class JMXConnectorServer(jep._PyJObject): ...

class NotificationResult(jep._PyJObject): ...

class JMXAuthenticator(jep._PyJObject): ...

class JMXConnector(jep._PyJObject): ...

class JMXServerErrorException(jep._PyJObject): ...

class JMXServiceURL(jep._PyJObject): ...

class JMXConnectorFactory(jep._PyJObject): ...

class JMXConnectorProvider(jep._PyJObject): ...

class JMXPrincipal(jep._PyJObject): ...

class JMXConnectionNotification(jep._PyJObject): ...

class SubjectDelegationPermission(jep._PyJObject): ...

class JMXConnectorServerMBean(jep._PyJObject): ...

