import jep

class TargetedNotification(jep.PyJObject): ...

class JMXConnectorServerFactory(jep.PyJObject): ...

class JMXAddressable(jep.PyJObject): ...

class JMXProviderException(jep.PyJObject): ...

class MBeanServerForwarder(jep.PyJObject): ...

class JMXConnectorServerProvider(jep.PyJObject): ...

class JMXConnectorServer(jep.PyJObject): ...

class NotificationResult(jep.PyJObject): ...

class JMXAuthenticator(jep.PyJObject): ...

class JMXConnector(jep.PyJObject): ...

class JMXServerErrorException(jep.PyJObject): ...

class JMXServiceURL(jep.PyJObject): ...

class JMXConnectorFactory(jep.PyJObject): ...

class JMXConnectorProvider(jep.PyJObject): ...

class JMXPrincipal(jep.PyJObject): ...

class JMXConnectionNotification(jep.PyJObject): ...

class SubjectDelegationPermission(jep.PyJObject): ...

class JMXConnectorServerMBean(jep.PyJObject): ...

