# pyright: reportPrivateUsage = none

import jep

class JMXConnectorFactory[**Ts](jep._PyJObject): ...

class JMXConnectorServerFactory[**Ts](jep._PyJObject): ...

class JMXConnectorServerProvider[**Ts](jep._PyJObject): ...

class JMXAddressable[**Ts](jep._PyJObject): ...

class JMXConnectorServer[**Ts](jep._PyJObject): ...

class JMXConnectionNotification[**Ts](jep._PyJObject): ...

class TargetedNotification[**Ts](jep._PyJObject): ...

class JMXConnectorServerMBean[**Ts](jep._PyJObject): ...

class JMXAuthenticator[**Ts](jep._PyJObject): ...

class SubjectDelegationPermission[**Ts](jep._PyJObject): ...

class MBeanServerForwarder[**Ts](jep._PyJObject): ...

class JMXServiceURL[**Ts](jep._PyJObject): ...

class JMXProviderException[**Ts](jep._PyJObject): ...

class JMXServerErrorException[**Ts](jep._PyJObject): ...

class JMXConnector[**Ts](jep._PyJObject): ...

class NotificationResult[**Ts](jep._PyJObject): ...

class JMXConnectorProvider[**Ts](jep._PyJObject): ...

class JMXPrincipal[**Ts](jep._PyJObject): ...

