# pyright: reportPrivateUsage = none

import jep

class RMIServerImpl_Stub[**Ts](jep._PyJObject): ...

class RMIServer[**Ts](jep._PyJObject): ...

class RMIConnector[**Ts](jep._PyJObject): ...

class RMIConnection[**Ts](jep._PyJObject): ...

class RMIConnectorServer[**Ts](jep._PyJObject): ...

class RMIJRMPServerImpl[**Ts](jep._PyJObject): ...

class RMIConnectionImpl_Stub[**Ts](jep._PyJObject): ...

class RMIConnectionImpl[**Ts](jep._PyJObject): ...

class RMIServerImpl[**Ts](jep._PyJObject): ...

