import jep

class OutputKeys(jep._PyJObject): ...

class Templates(jep._PyJObject): ...

class Source(jep._PyJObject): ...

class TransformerFactoryConfigurationError(jep._PyJObject): ...

class TransformerConfigurationException(jep._PyJObject): ...

class URIResolver(jep._PyJObject): ...

class TransformerFactory(jep._PyJObject): ...

class SourceLocator(jep._PyJObject): ...

class TransformerException(jep._PyJObject): ...

class ErrorListener(jep._PyJObject): ...

class Result(jep._PyJObject): ...

class Transformer(jep._PyJObject): ...

