import jep

class OutputKeys(jep.PyJObject): ...

class Templates(jep.PyJObject): ...

class Source(jep.PyJObject): ...

class TransformerFactoryConfigurationError(jep.PyJObject): ...

class TransformerConfigurationException(jep.PyJObject): ...

class URIResolver(jep.PyJObject): ...

class TransformerFactory(jep.PyJObject): ...

class SourceLocator(jep.PyJObject): ...

class TransformerException(jep.PyJObject): ...

class ErrorListener(jep.PyJObject): ...

class Result(jep.PyJObject): ...

class Transformer(jep.PyJObject): ...

