# pyright: reportPrivateUsage = none

import jep

class TransformerException[**Ts](jep._PyJObject): ...

class TransformerFactoryConfigurationError[**Ts](jep._PyJObject): ...

class Source[**Ts](jep._PyJObject): ...

class Result[**Ts](jep._PyJObject): ...

class OutputKeys[**Ts](jep._PyJObject): ...

class ErrorListener[**Ts](jep._PyJObject): ...

class URIResolver[**Ts](jep._PyJObject): ...

class TransformerConfigurationException[**Ts](jep._PyJObject): ...

class Transformer[**Ts](jep._PyJObject): ...

class TransformerFactory[**Ts](jep._PyJObject): ...

class SourceLocator[**Ts](jep._PyJObject): ...

class Templates[**Ts](jep._PyJObject): ...

