import jep

class TransformerHandler(jep._PyJObject): ...

class SAXResult(jep._PyJObject): ...

class TemplatesHandler(jep._PyJObject): ...

class SAXSource(jep._PyJObject): ...

class SAXTransformerFactory(jep._PyJObject): ...

