import jep

class TransformerHandler(jep.PyJObject): ...

class SAXResult(jep.PyJObject): ...

class TemplatesHandler(jep.PyJObject): ...

class SAXSource(jep.PyJObject): ...

class SAXTransformerFactory(jep.PyJObject): ...

