# pyright: reportPrivateUsage = none

import jep

class SAXSource[**Ts](jep._PyJObject): ...

class SAXResult[**Ts](jep._PyJObject): ...

class SAXTransformerFactory[**Ts](jep._PyJObject): ...

class TemplatesHandler[**Ts](jep._PyJObject): ...

