# pyright: reportPrivateUsage = none

import jep

class MappedByteBuffer[**Ts](jep._PyJObject): ...

class DoubleBuffer[**Ts](jep._PyJObject): ...

class InvalidMarkException[**Ts](jep._PyJObject): ...

class BufferOverflowException[**Ts](jep._PyJObject): ...

class ByteOrder[**Ts](jep._PyJObject): ...

class ReadOnlyBufferException[**Ts](jep._PyJObject): ...

class Buffer[**Ts](jep._PyJObject): ...

class LongBuffer[**Ts](jep._PyJObject): ...

class BufferUnderflowException[**Ts](jep._PyJObject): ...

class ByteBuffer[**Ts](jep._PyJObject): ...

class IntBuffer[**Ts](jep._PyJObject): ...

class CharBuffer[**Ts](jep._PyJObject): ...

class ShortBuffer[**Ts](jep._PyJObject): ...

class FloatBuffer[**Ts](jep._PyJObject): ...

