import jep

class ReadOnlyBufferException(jep._PyJObject): ...

class DoubleBuffer(jep._PyJObject): ...

class ByteBuffer(jep._PyJObject): ...

class ByteOrder(jep._PyJObject): ...

class CharBuffer(jep._PyJObject): ...

class InvalidMarkException(jep._PyJObject): ...

class Buffer(jep._PyJObject): ...

class LongBuffer(jep._PyJObject): ...

class ShortBuffer(jep._PyJObject): ...

class MappedByteBuffer(jep._PyJObject): ...

class BufferOverflowException(jep._PyJObject): ...

class IntBuffer(jep._PyJObject): ...

class FloatBuffer(jep._PyJObject): ...

class BufferUnderflowException(jep._PyJObject): ...

