import jep

class ReadOnlyBufferException(jep.PyJObject): ...

class DoubleBuffer(jep.PyJObject): ...

class ByteBuffer(jep.PyJObject): ...

class ByteOrder(jep.PyJObject): ...

class CharBuffer(jep.PyJObject): ...

class InvalidMarkException(jep.PyJObject): ...

class Buffer(jep.PyJObject): ...

class LongBuffer(jep.PyJObject): ...

class ShortBuffer(jep.PyJObject): ...

class MappedByteBuffer(jep.PyJObject): ...

class BufferOverflowException(jep.PyJObject): ...

class IntBuffer(jep.PyJObject): ...

class FloatBuffer(jep.PyJObject): ...

class BufferUnderflowException(jep.PyJObject): ...

