# pyright: reportPrivateUsage = none

import jep

class CSS[**Ts](jep._PyJObject): ...

class HTMLDocument[**Ts](jep._PyJObject): ...

class HTML[**Ts](jep._PyJObject): ...

class ParagraphView[**Ts](jep._PyJObject): ...

class HTMLWriter[**Ts](jep._PyJObject): ...

class HTMLFrameHyperlinkEvent[**Ts](jep._PyJObject): ...

class HTMLEditorKit[**Ts](jep._PyJObject): ...

class FormView[**Ts](jep._PyJObject): ...

class MinimalHTMLWriter[**Ts](jep._PyJObject): ...

class ListView[**Ts](jep._PyJObject): ...

class InlineView[**Ts](jep._PyJObject): ...

class ObjectView[**Ts](jep._PyJObject): ...

class StyleSheet[**Ts](jep._PyJObject): ...

class ImageView[**Ts](jep._PyJObject): ...

class Option[**Ts](jep._PyJObject): ...

class FormSubmitEvent[**Ts](jep._PyJObject): ...

