import jep

class HTMLFrameHyperlinkEvent(jep._PyJObject): ...

class InlineView(jep._PyJObject): ...

class CSS(jep._PyJObject): ...

class ParagraphView(jep._PyJObject): ...

class ImageView(jep._PyJObject): ...

class HTMLWriter(jep._PyJObject): ...

class ObjectView(jep._PyJObject): ...

class BlockView(jep._PyJObject): ...

class HTML(jep._PyJObject): ...

class FormSubmitEvent(jep._PyJObject): ...

class Option(jep._PyJObject): ...

class StyleSheet(jep._PyJObject): ...

class HTMLEditorKit(jep._PyJObject): ...

class MinimalHTMLWriter(jep._PyJObject): ...

class HTMLDocument(jep._PyJObject): ...

class FormView(jep._PyJObject): ...

