import jep

class HTMLFrameHyperlinkEvent(jep.PyJObject): ...

class InlineView(jep.PyJObject): ...

class CSS(jep.PyJObject): ...

class ParagraphView(jep.PyJObject): ...

class ImageView(jep.PyJObject): ...

class HTMLWriter(jep.PyJObject): ...

class ObjectView(jep.PyJObject): ...

class BlockView(jep.PyJObject): ...

class HTML(jep.PyJObject): ...

class FormSubmitEvent(jep.PyJObject): ...

class Option(jep.PyJObject): ...

class StyleSheet(jep.PyJObject): ...

class HTMLEditorKit(jep.PyJObject): ...

class MinimalHTMLWriter(jep.PyJObject): ...

class HTMLDocument(jep.PyJObject): ...

class FormView(jep.PyJObject): ...

