import jep

class DocumentParser(jep._PyJObject): ...

class DTD(jep._PyJObject): ...

class DTDConstants(jep._PyJObject): ...

class Parser(jep._PyJObject): ...

class AttributeList(jep._PyJObject): ...

class Element(jep._PyJObject): ...

class ContentModel(jep._PyJObject): ...

class TagElement(jep._PyJObject): ...

class Entity(jep._PyJObject): ...

