# pyright: reportPrivateUsage = none

import jep

class ParserDelegator[**Ts](jep._PyJObject): ...

class TagElement[**Ts](jep._PyJObject): ...

class DTD[**Ts](jep._PyJObject): ...

class Element[**Ts](jep._PyJObject): ...

class DocumentParser[**Ts](jep._PyJObject): ...

class ContentModel[**Ts](jep._PyJObject): ...

class Entity[**Ts](jep._PyJObject): ...

class AttributeList[**Ts](jep._PyJObject): ...

class Parser[**Ts](jep._PyJObject): ...

