import jep

class DocumentParser(jep.PyJObject): ...

class DTD(jep.PyJObject): ...

class DTDConstants(jep.PyJObject): ...

class Parser(jep.PyJObject): ...

class AttributeList(jep.PyJObject): ...

class Element(jep.PyJObject): ...

class ContentModel(jep.PyJObject): ...

class TagElement(jep.PyJObject): ...

class Entity(jep.PyJObject): ...

