# pyright: reportPrivateUsage = none

import jep

class ReferralException[**Ts](jep._PyJObject): ...

class NameClassPair[**Ts](jep._PyJObject): ...

class InsufficientResourcesException[**Ts](jep._PyJObject): ...

class TimeLimitExceededException[**Ts](jep._PyJObject): ...

class Referenceable[**Ts](jep._PyJObject): ...

class ServiceUnavailableException[**Ts](jep._PyJObject): ...

class LinkLoopException[**Ts](jep._PyJObject): ...

class AuthenticationNotSupportedException[**Ts](jep._PyJObject): ...

class BinaryRefAddr[**Ts](jep._PyJObject): ...

class LimitExceededException[**Ts](jep._PyJObject): ...

class NameAlreadyBoundException[**Ts](jep._PyJObject): ...

class StringRefAddr[**Ts](jep._PyJObject): ...

class NamingException[**Ts](jep._PyJObject): ...

class InvalidNameException[**Ts](jep._PyJObject): ...

class LinkException[**Ts](jep._PyJObject): ...

class ConfigurationException[**Ts](jep._PyJObject): ...

class ContextNotEmptyException[**Ts](jep._PyJObject): ...

class Binding[**Ts](jep._PyJObject): ...

class SizeLimitExceededException[**Ts](jep._PyJObject): ...

class CannotProceedException[**Ts](jep._PyJObject): ...

class MalformedLinkException[**Ts](jep._PyJObject): ...

class Context[**Ts](jep._PyJObject): ...

class Reference[**Ts](jep._PyJObject): ...

class NameNotFoundException[**Ts](jep._PyJObject): ...

class Name[**Ts](jep._PyJObject): ...

class OperationNotSupportedException[**Ts](jep._PyJObject): ...

class AuthenticationException[**Ts](jep._PyJObject): ...

class NamingSecurityException[**Ts](jep._PyJObject): ...

class RefAddr[**Ts](jep._PyJObject): ...

class InitialContext[**Ts](jep._PyJObject): ...

class LinkRef[**Ts](jep._PyJObject): ...

class NoInitialContextException[**Ts](jep._PyJObject): ...

class NoPermissionException[**Ts](jep._PyJObject): ...

class PartialResultException[**Ts](jep._PyJObject): ...

class CompoundName[**Ts](jep._PyJObject): ...

class NotContextException[**Ts](jep._PyJObject): ...

class NamingEnumeration[**Ts](jep._PyJObject): ...

class CommunicationException[**Ts](jep._PyJObject): ...

class CompositeName[**Ts](jep._PyJObject): ...

class InterruptedNamingException[**Ts](jep._PyJObject): ...

class NameParser[**Ts](jep._PyJObject): ...

