import jep

class CannotProceedException(jep.PyJObject): ...

class ReferralException(jep.PyJObject): ...

class NamingEnumeration(jep.PyJObject): ...

class InterruptedNamingException(jep.PyJObject): ...

class CompositeName(jep.PyJObject): ...

class TimeLimitExceededException(jep.PyJObject): ...

class Binding(jep.PyJObject): ...

class NamingException(jep.PyJObject): ...

class BinaryRefAddr(jep.PyJObject): ...

class ContextNotEmptyException(jep.PyJObject): ...

class PartialResultException(jep.PyJObject): ...

class NotContextException(jep.PyJObject): ...

class InsufficientResourcesException(jep.PyJObject): ...

class SizeLimitExceededException(jep.PyJObject): ...

class AuthenticationException(jep.PyJObject): ...

class NameParser(jep.PyJObject): ...

class NameNotFoundException(jep.PyJObject): ...

class Name(jep.PyJObject): ...

class NamingSecurityException(jep.PyJObject): ...

class OperationNotSupportedException(jep.PyJObject): ...

class CommunicationException(jep.PyJObject): ...

class Context(jep.PyJObject): ...

class LinkException(jep.PyJObject): ...

class LimitExceededException(jep.PyJObject): ...

class ConfigurationException(jep.PyJObject): ...

class NameAlreadyBoundException(jep.PyJObject): ...

class LinkLoopException(jep.PyJObject): ...

class StringRefAddr(jep.PyJObject): ...

class LinkRef(jep.PyJObject): ...

class MalformedLinkException(jep.PyJObject): ...

class NameClassPair(jep.PyJObject): ...

class NoPermissionException(jep.PyJObject): ...

class NoInitialContextException(jep.PyJObject): ...

class ServiceUnavailableException(jep.PyJObject): ...

class Reference(jep.PyJObject): ...

class CompoundName(jep.PyJObject): ...

class RefAddr(jep.PyJObject): ...

class InvalidNameException(jep.PyJObject): ...

class AuthenticationNotSupportedException(jep.PyJObject): ...

class Referenceable(jep.PyJObject): ...

class InitialContext(jep.PyJObject): ...

