import jep

class CannotProceedException(jep._PyJObject): ...

class ReferralException(jep._PyJObject): ...

class NamingEnumeration(jep._PyJObject): ...

class InterruptedNamingException(jep._PyJObject): ...

class CompositeName(jep._PyJObject): ...

class TimeLimitExceededException(jep._PyJObject): ...

class Binding(jep._PyJObject): ...

class NamingException(jep._PyJObject): ...

class BinaryRefAddr(jep._PyJObject): ...

class ContextNotEmptyException(jep._PyJObject): ...

class PartialResultException(jep._PyJObject): ...

class NotContextException(jep._PyJObject): ...

class InsufficientResourcesException(jep._PyJObject): ...

class SizeLimitExceededException(jep._PyJObject): ...

class AuthenticationException(jep._PyJObject): ...

class NameParser(jep._PyJObject): ...

class NameNotFoundException(jep._PyJObject): ...

class Name(jep._PyJObject): ...

class NamingSecurityException(jep._PyJObject): ...

class OperationNotSupportedException(jep._PyJObject): ...

class CommunicationException(jep._PyJObject): ...

class Context(jep._PyJObject): ...

class LinkException(jep._PyJObject): ...

class LimitExceededException(jep._PyJObject): ...

class ConfigurationException(jep._PyJObject): ...

class NameAlreadyBoundException(jep._PyJObject): ...

class LinkLoopException(jep._PyJObject): ...

class StringRefAddr(jep._PyJObject): ...

class LinkRef(jep._PyJObject): ...

class MalformedLinkException(jep._PyJObject): ...

class NameClassPair(jep._PyJObject): ...

class NoPermissionException(jep._PyJObject): ...

class NoInitialContextException(jep._PyJObject): ...

class ServiceUnavailableException(jep._PyJObject): ...

class Reference(jep._PyJObject): ...

class CompoundName(jep._PyJObject): ...

class RefAddr(jep._PyJObject): ...

class InvalidNameException(jep._PyJObject): ...

class AuthenticationNotSupportedException(jep._PyJObject): ...

class Referenceable(jep._PyJObject): ...

class InitialContext(jep._PyJObject): ...

