import jep

class BasicAttributes(jep.PyJObject): ...

class SearchControls(jep.PyJObject): ...

class AttributeInUseException(jep.PyJObject): ...

class Attribute(jep.PyJObject): ...

class InvalidSearchFilterException(jep.PyJObject): ...

class DirContext(jep.PyJObject): ...

class InvalidAttributesException(jep.PyJObject): ...

class BasicAttribute(jep.PyJObject): ...

class AttributeModificationException(jep.PyJObject): ...

class InvalidAttributeValueException(jep.PyJObject): ...

class ModificationItem(jep.PyJObject): ...

class SchemaViolationException(jep.PyJObject): ...

class SearchResult(jep.PyJObject): ...

class Attributes(jep.PyJObject): ...

class NoSuchAttributeException(jep.PyJObject): ...

class InitialDirContext(jep.PyJObject): ...

class InvalidAttributeIdentifierException(jep.PyJObject): ...

class InvalidSearchControlsException(jep.PyJObject): ...

