import jep

class BasicAttributes(jep._PyJObject): ...

class SearchControls(jep._PyJObject): ...

class AttributeInUseException(jep._PyJObject): ...

class Attribute(jep._PyJObject): ...

class InvalidSearchFilterException(jep._PyJObject): ...

class DirContext(jep._PyJObject): ...

class InvalidAttributesException(jep._PyJObject): ...

class BasicAttribute(jep._PyJObject): ...

class AttributeModificationException(jep._PyJObject): ...

class InvalidAttributeValueException(jep._PyJObject): ...

class ModificationItem(jep._PyJObject): ...

class SchemaViolationException(jep._PyJObject): ...

class SearchResult(jep._PyJObject): ...

class Attributes(jep._PyJObject): ...

class NoSuchAttributeException(jep._PyJObject): ...

class InitialDirContext(jep._PyJObject): ...

class InvalidAttributeIdentifierException(jep._PyJObject): ...

class InvalidSearchControlsException(jep._PyJObject): ...

