# pyright: reportPrivateUsage = none

import jep

class Attribute[**Ts](jep._PyJObject): ...

class InitialDirContext[**Ts](jep._PyJObject): ...

class NoSuchAttributeException[**Ts](jep._PyJObject): ...

class BasicAttribute[**Ts](jep._PyJObject): ...

class SearchResult[**Ts](jep._PyJObject): ...

class InvalidAttributeIdentifierException[**Ts](jep._PyJObject): ...

class AttributeModificationException[**Ts](jep._PyJObject): ...

class SchemaViolationException[**Ts](jep._PyJObject): ...

class AttributeInUseException[**Ts](jep._PyJObject): ...

class ModificationItem[**Ts](jep._PyJObject): ...

class BasicAttributes[**Ts](jep._PyJObject): ...

class SearchControls[**Ts](jep._PyJObject): ...

class DirContext[**Ts](jep._PyJObject): ...

class InvalidSearchFilterException[**Ts](jep._PyJObject): ...

class InvalidAttributeValueException[**Ts](jep._PyJObject): ...

class Attributes[**Ts](jep._PyJObject): ...

class InvalidAttributesException[**Ts](jep._PyJObject): ...

class InvalidSearchControlsException[**Ts](jep._PyJObject): ...

