import jep

class NamespaceChangeListener(jep._PyJObject): ...

class NamingEvent(jep._PyJObject): ...

class NamingListener(jep._PyJObject): ...

class NamingExceptionEvent(jep._PyJObject): ...

class EventDirContext(jep._PyJObject): ...

class ObjectChangeListener(jep._PyJObject): ...

class EventContext(jep._PyJObject): ...

