import jep

class NamespaceChangeListener(jep.PyJObject): ...

class NamingEvent(jep.PyJObject): ...

class NamingListener(jep.PyJObject): ...

class NamingExceptionEvent(jep.PyJObject): ...

class EventDirContext(jep.PyJObject): ...

class ObjectChangeListener(jep.PyJObject): ...

class EventContext(jep.PyJObject): ...

