# pyright: reportPrivateUsage = none

import jep

class NamingListener[**Ts](jep._PyJObject): ...

class EventDirContext[**Ts](jep._PyJObject): ...

class EventContext[**Ts](jep._PyJObject): ...

class NamingEvent[**Ts](jep._PyJObject): ...

class NamespaceChangeListener[**Ts](jep._PyJObject): ...

class ObjectChangeListener[**Ts](jep._PyJObject): ...

class NamingExceptionEvent[**Ts](jep._PyJObject): ...

