# pyright: reportPrivateUsage = none

import jep

class LdapReferralException[**Ts](jep._PyJObject): ...

class ExtendedResponse[**Ts](jep._PyJObject): ...

class StartTlsResponse[**Ts](jep._PyJObject): ...

class PagedResultsResponseControl[**Ts](jep._PyJObject): ...

class UnsolicitedNotificationEvent[**Ts](jep._PyJObject): ...

class SortKey[**Ts](jep._PyJObject): ...

class ControlFactory[**Ts](jep._PyJObject): ...

class HasControls[**Ts](jep._PyJObject): ...

class StartTlsRequest[**Ts](jep._PyJObject): ...

class Rdn[**Ts](jep._PyJObject): ...

class InitialLdapContext[**Ts](jep._PyJObject): ...

class SortResponseControl[**Ts](jep._PyJObject): ...

class BasicControl[**Ts](jep._PyJObject): ...

class LdapContext[**Ts](jep._PyJObject): ...

class LdapName[**Ts](jep._PyJObject): ...

class UnsolicitedNotificationListener[**Ts](jep._PyJObject): ...

class Control[**Ts](jep._PyJObject): ...

class ManageReferralControl[**Ts](jep._PyJObject): ...

class ExtendedRequest[**Ts](jep._PyJObject): ...

class PagedResultsControl[**Ts](jep._PyJObject): ...

class UnsolicitedNotification[**Ts](jep._PyJObject): ...

