import jep

class Rdn(jep.PyJObject): ...

class UnsolicitedNotificationEvent(jep.PyJObject): ...

class ManageReferralControl(jep.PyJObject): ...

class HasControls(jep.PyJObject): ...

class BasicControl(jep.PyJObject): ...

class LdapContext(jep.PyJObject): ...

class LdapReferralException(jep.PyJObject): ...

class Control(jep.PyJObject): ...

class SortResponseControl(jep.PyJObject): ...

class ExtendedRequest(jep.PyJObject): ...

class LdapName(jep.PyJObject): ...

class SortKey(jep.PyJObject): ...

class StartTlsRequest(jep.PyJObject): ...

class ExtendedResponse(jep.PyJObject): ...

class InitialLdapContext(jep.PyJObject): ...

class PagedResultsResponseControl(jep.PyJObject): ...

class UnsolicitedNotificationListener(jep.PyJObject): ...

class StartTlsResponse(jep.PyJObject): ...

class SortControl(jep.PyJObject): ...

class UnsolicitedNotification(jep.PyJObject): ...

class ControlFactory(jep.PyJObject): ...

class PagedResultsControl(jep.PyJObject): ...

