import jep

class Rdn(jep._PyJObject): ...

class UnsolicitedNotificationEvent(jep._PyJObject): ...

class ManageReferralControl(jep._PyJObject): ...

class HasControls(jep._PyJObject): ...

class BasicControl(jep._PyJObject): ...

class LdapContext(jep._PyJObject): ...

class LdapReferralException(jep._PyJObject): ...

class Control(jep._PyJObject): ...

class SortResponseControl(jep._PyJObject): ...

class ExtendedRequest(jep._PyJObject): ...

class LdapName(jep._PyJObject): ...

class SortKey(jep._PyJObject): ...

class StartTlsRequest(jep._PyJObject): ...

class ExtendedResponse(jep._PyJObject): ...

class InitialLdapContext(jep._PyJObject): ...

class PagedResultsResponseControl(jep._PyJObject): ...

class UnsolicitedNotificationListener(jep._PyJObject): ...

class StartTlsResponse(jep._PyJObject): ...

class SortControl(jep._PyJObject): ...

class UnsolicitedNotification(jep._PyJObject): ...

class ControlFactory(jep._PyJObject): ...

class PagedResultsControl(jep._PyJObject): ...

