# pyright: reportPrivateUsage = none

import jep

class ResolveResult[**Ts](jep._PyJObject): ...

class ObjectFactoryBuilder[**Ts](jep._PyJObject): ...

class DirectoryManager[**Ts](jep._PyJObject): ...

class Resolver[**Ts](jep._PyJObject): ...

class ObjectFactory[**Ts](jep._PyJObject): ...

class DirStateFactory[**Ts](jep._PyJObject): ...

class InitialContextFactoryBuilder[**Ts](jep._PyJObject): ...

class InitialContextFactory[**Ts](jep._PyJObject): ...

class NamingManager[**Ts](jep._PyJObject): ...

class DirObjectFactory[**Ts](jep._PyJObject): ...

class StateFactory[**Ts](jep._PyJObject): ...

