import jep

class ObjectFactoryBuilder(jep.PyJObject): ...

class InitialContextFactoryBuilder(jep.PyJObject): ...

class StateFactory(jep.PyJObject): ...

class ObjectFactory(jep.PyJObject): ...

class NamingManager(jep.PyJObject): ...

class DirStateFactory(jep.PyJObject): ...

class InitialContextFactory(jep.PyJObject): ...

class DirObjectFactory(jep.PyJObject): ...

class ResolveResult(jep.PyJObject): ...

class DirectoryManager(jep.PyJObject): ...

