import jep

class ObjectFactoryBuilder(jep._PyJObject): ...

class InitialContextFactoryBuilder(jep._PyJObject): ...

class StateFactory(jep._PyJObject): ...

class ObjectFactory(jep._PyJObject): ...

class NamingManager(jep._PyJObject): ...

class DirStateFactory(jep._PyJObject): ...

class InitialContextFactory(jep._PyJObject): ...

class DirObjectFactory(jep._PyJObject): ...

class ResolveResult(jep._PyJObject): ...

class DirectoryManager(jep._PyJObject): ...

