# pyright: reportPrivateUsage = none

import jep

class XMLEventFactory[**Ts](jep._PyJObject): ...

class XMLInputFactory[**Ts](jep._PyJObject): ...

class XMLResolver[**Ts](jep._PyJObject): ...

class EventFilter[**Ts](jep._PyJObject): ...

class FactoryConfigurationError[**Ts](jep._PyJObject): ...

class Location[**Ts](jep._PyJObject): ...

class XMLEventReader[**Ts](jep._PyJObject): ...

class XMLStreamException[**Ts](jep._PyJObject): ...

class XMLStreamWriter[**Ts](jep._PyJObject): ...

class StreamFilter[**Ts](jep._PyJObject): ...

class XMLEventWriter[**Ts](jep._PyJObject): ...

class XMLStreamReader[**Ts](jep._PyJObject): ...

class XMLReporter[**Ts](jep._PyJObject): ...

class XMLOutputFactory[**Ts](jep._PyJObject): ...

class XMLStreamConstants[**Ts](jep._PyJObject): ...

