import jep

class XMLInputFactory(jep._PyJObject): ...

class XMLResolver(jep._PyJObject): ...

class XMLStreamConstants(jep._PyJObject): ...

class XMLStreamWriter(jep._PyJObject): ...

class XMLStreamReader(jep._PyJObject): ...

class XMLOutputFactory(jep._PyJObject): ...

class XMLReporter(jep._PyJObject): ...

class StreamFilter(jep._PyJObject): ...

class FactoryConfigurationError(jep._PyJObject): ...

class XMLEventReader(jep._PyJObject): ...

class XMLStreamException(jep._PyJObject): ...

class XMLEventFactory(jep._PyJObject): ...

class XMLEventWriter(jep._PyJObject): ...

class EventFilter(jep._PyJObject): ...

class Location(jep._PyJObject): ...

