import jep

class XMLInputFactory(jep.PyJObject): ...

class XMLResolver(jep.PyJObject): ...

class XMLStreamConstants(jep.PyJObject): ...

class XMLStreamWriter(jep.PyJObject): ...

class XMLStreamReader(jep.PyJObject): ...

class XMLOutputFactory(jep.PyJObject): ...

class XMLReporter(jep.PyJObject): ...

class StreamFilter(jep.PyJObject): ...

class FactoryConfigurationError(jep.PyJObject): ...

class XMLEventReader(jep.PyJObject): ...

class XMLStreamException(jep.PyJObject): ...

class XMLEventFactory(jep.PyJObject): ...

class XMLEventWriter(jep.PyJObject): ...

class EventFilter(jep.PyJObject): ...

class Location(jep.PyJObject): ...

