import jep

class Comment(jep.PyJObject): ...

class EntityReference(jep.PyJObject): ...

class EndDocument(jep.PyJObject): ...

class XMLEvent(jep.PyJObject): ...

class Namespace(jep.PyJObject): ...

class EndElement(jep.PyJObject): ...

class EntityDeclaration(jep.PyJObject): ...

class ProcessingInstruction(jep.PyJObject): ...

class NotationDeclaration(jep.PyJObject): ...

class StartElement(jep.PyJObject): ...

class Characters(jep.PyJObject): ...

class DTD(jep.PyJObject): ...

class StartDocument(jep.PyJObject): ...

