# pyright: reportPrivateUsage = none

import jep

class NotationDeclaration[**Ts](jep._PyJObject): ...

class StartDocument[**Ts](jep._PyJObject): ...

class Attribute[**Ts](jep._PyJObject): ...

class EntityDeclaration[**Ts](jep._PyJObject): ...

class XMLEvent[**Ts](jep._PyJObject): ...

class DTD[**Ts](jep._PyJObject): ...

class Characters[**Ts](jep._PyJObject): ...

class EntityReference[**Ts](jep._PyJObject): ...

class StartElement[**Ts](jep._PyJObject): ...

class EndElement[**Ts](jep._PyJObject): ...

class Comment[**Ts](jep._PyJObject): ...

class EndDocument[**Ts](jep._PyJObject): ...

class Namespace[**Ts](jep._PyJObject): ...

