import jep

class Comment(jep._PyJObject): ...

class EntityReference(jep._PyJObject): ...

class EndDocument(jep._PyJObject): ...

class XMLEvent(jep._PyJObject): ...

class Namespace(jep._PyJObject): ...

class EndElement(jep._PyJObject): ...

class EntityDeclaration(jep._PyJObject): ...

class ProcessingInstruction(jep._PyJObject): ...

class NotationDeclaration(jep._PyJObject): ...

class StartElement(jep._PyJObject): ...

class Characters(jep._PyJObject): ...

class DTD(jep._PyJObject): ...

class StartDocument(jep._PyJObject): ...

