# pyright: reportPrivateUsage = none

import jep

class EventReaderDelegate[**Ts](jep._PyJObject): ...

class StreamReaderDelegate[**Ts](jep._PyJObject): ...

class XMLEventConsumer[**Ts](jep._PyJObject): ...

class XMLEventAllocator[**Ts](jep._PyJObject): ...

