import jep

class EventReaderDelegate(jep._PyJObject): ...

class XMLEventAllocator(jep._PyJObject): ...

class XMLEventConsumer(jep._PyJObject): ...

class StreamReaderDelegate(jep._PyJObject): ...

