# pyright: reportPrivateUsage = none

import jep

class PrintException[**Ts](jep._PyJObject): ...

class PrintService[**Ts](jep._PyJObject): ...

class StreamPrintServiceFactory[**Ts](jep._PyJObject): ...

class Doc[**Ts](jep._PyJObject): ...

class AttributeException[**Ts](jep._PyJObject): ...

class FlavorException[**Ts](jep._PyJObject): ...

class URIException[**Ts](jep._PyJObject): ...

class DocPrintJob[**Ts](jep._PyJObject): ...

class ServiceUI[**Ts](jep._PyJObject): ...

class SimpleDoc[**Ts](jep._PyJObject): ...

class CancelablePrintJob[**Ts](jep._PyJObject): ...

class DocFlavor[**Ts](jep._PyJObject): ...

class ServiceUIFactory[**Ts](jep._PyJObject): ...

class PrintServiceLookup[**Ts](jep._PyJObject): ...

class MultiDoc[**Ts](jep._PyJObject): ...

class StreamPrintService[**Ts](jep._PyJObject): ...

class MultiDocPrintService[**Ts](jep._PyJObject): ...

class MultiDocPrintJob[**Ts](jep._PyJObject): ...

