import jep

class ServiceUIFactory(jep.PyJObject): ...

class PrintServiceLookup(jep.PyJObject): ...

class AttributeException(jep.PyJObject): ...

class CancelablePrintJob(jep.PyJObject): ...

class MultiDocPrintJob(jep.PyJObject): ...

class FlavorException(jep.PyJObject): ...

class PrintService(jep.PyJObject): ...

class PrintException(jep.PyJObject): ...

class DocFlavor(jep.PyJObject): ...

class StreamPrintService(jep.PyJObject): ...

class SimpleDoc(jep.PyJObject): ...

class Doc(jep.PyJObject): ...

class MultiDocPrintService(jep.PyJObject): ...

class StreamPrintServiceFactory(jep.PyJObject): ...

class URIException(jep.PyJObject): ...

class ServiceUI(jep.PyJObject): ...

class MultiDoc(jep.PyJObject): ...

class DocPrintJob(jep.PyJObject): ...

