import jep

class ServiceUIFactory(jep._PyJObject): ...

class PrintServiceLookup(jep._PyJObject): ...

class AttributeException(jep._PyJObject): ...

class CancelablePrintJob(jep._PyJObject): ...

class MultiDocPrintJob(jep._PyJObject): ...

class FlavorException(jep._PyJObject): ...

class PrintService(jep._PyJObject): ...

class PrintException(jep._PyJObject): ...

class DocFlavor(jep._PyJObject): ...

class StreamPrintService(jep._PyJObject): ...

class SimpleDoc(jep._PyJObject): ...

class Doc(jep._PyJObject): ...

class MultiDocPrintService(jep._PyJObject): ...

class StreamPrintServiceFactory(jep._PyJObject): ...

class URIException(jep._PyJObject): ...

class ServiceUI(jep._PyJObject): ...

class MultiDoc(jep._PyJObject): ...

class DocPrintJob(jep._PyJObject): ...

