import jep

class PrintJobAttributeEvent(jep._PyJObject): ...

class PrintJobAdapter(jep._PyJObject): ...

class PrintServiceAttributeEvent(jep._PyJObject): ...

class PrintJobListener(jep._PyJObject): ...

class PrintEvent(jep._PyJObject): ...

class PrintJobEvent(jep._PyJObject): ...

class PrintServiceAttributeListener(jep._PyJObject): ...

