# pyright: reportPrivateUsage = none

import jep

class PrintJobAttributeEvent[**Ts](jep._PyJObject): ...

class PrintJobEvent[**Ts](jep._PyJObject): ...

class PrintServiceAttributeEvent[**Ts](jep._PyJObject): ...

class PrintEvent[**Ts](jep._PyJObject): ...

class PrintJobAdapter[**Ts](jep._PyJObject): ...

class PrintJobAttributeListener[**Ts](jep._PyJObject): ...

class PrintJobListener[**Ts](jep._PyJObject): ...

class PrintServiceAttributeListener[**Ts](jep._PyJObject): ...

