import jep

class PrintJobAttributeEvent(jep.PyJObject): ...

class PrintJobAdapter(jep.PyJObject): ...

class PrintServiceAttributeEvent(jep.PyJObject): ...

class PrintJobListener(jep.PyJObject): ...

class PrintEvent(jep.PyJObject): ...

class PrintJobEvent(jep.PyJObject): ...

class PrintServiceAttributeListener(jep.PyJObject): ...

