import jep

class ResponseWrapper(jep._PyJObject): ...

class RequestWrapper(jep._PyJObject): ...

class LogicalMessage(jep._PyJObject): ...

class WebServiceProvider(jep._PyJObject): ...

class BindingProvider(jep._PyJObject): ...

class EndpointContext(jep._PyJObject): ...

class FaultAction(jep._PyJObject): ...

class Response(jep._PyJObject): ...

class WebServiceException(jep._PyJObject): ...

class ProtocolException(jep._PyJObject): ...

class Dispatch(jep._PyJObject): ...

class Endpoint(jep._PyJObject): ...

class Service(jep._PyJObject): ...

class WebServiceRef(jep._PyJObject): ...

class WebServiceContext(jep._PyJObject): ...

class AsyncHandler(jep._PyJObject): ...

class WebEndpoint(jep._PyJObject): ...

class Action(jep._PyJObject): ...

class WebFault(jep._PyJObject): ...

class WebServiceRefs(jep._PyJObject): ...

class ServiceMode(jep._PyJObject): ...

class Provider(jep._PyJObject): ...

class EndpointReference(jep._PyJObject): ...

class BindingType(jep._PyJObject): ...

class WebServicePermission(jep._PyJObject): ...

class Holder(jep._PyJObject): ...

class RespectBinding(jep._PyJObject): ...

class Binding(jep._PyJObject): ...

class RespectBindingFeature(jep._PyJObject): ...

class WebServiceFeature(jep._PyJObject): ...

class WebServiceClient(jep._PyJObject): ...

