import jep

class ResponseWrapper(jep.PyJObject): ...

class RequestWrapper(jep.PyJObject): ...

class LogicalMessage(jep.PyJObject): ...

class WebServiceProvider(jep.PyJObject): ...

class BindingProvider(jep.PyJObject): ...

class EndpointContext(jep.PyJObject): ...

class FaultAction(jep.PyJObject): ...

class Response(jep.PyJObject): ...

class WebServiceException(jep.PyJObject): ...

class ProtocolException(jep.PyJObject): ...

class Dispatch(jep.PyJObject): ...

class Endpoint(jep.PyJObject): ...

class Service(jep.PyJObject): ...

class WebServiceRef(jep.PyJObject): ...

class WebServiceContext(jep.PyJObject): ...

class AsyncHandler(jep.PyJObject): ...

class WebEndpoint(jep.PyJObject): ...

class Action(jep.PyJObject): ...

class WebFault(jep.PyJObject): ...

class WebServiceRefs(jep.PyJObject): ...

class ServiceMode(jep.PyJObject): ...

class Provider(jep.PyJObject): ...

class EndpointReference(jep.PyJObject): ...

class BindingType(jep.PyJObject): ...

class WebServicePermission(jep.PyJObject): ...

class Holder(jep.PyJObject): ...

class RespectBinding(jep.PyJObject): ...

class Binding(jep.PyJObject): ...

class RespectBindingFeature(jep.PyJObject): ...

class WebServiceFeature(jep.PyJObject): ...

class WebServiceClient(jep.PyJObject): ...

