# pyright: reportPrivateUsage = none

import jep

class ResponseWrapper[**Ts](jep._PyJObject): ...

class BindingType[**Ts](jep._PyJObject): ...

class FaultAction[**Ts](jep._PyJObject): ...

class ServiceMode[**Ts](jep._PyJObject): ...

class AsyncHandler[**Ts](jep._PyJObject): ...

class WebServicePermission[**Ts](jep._PyJObject): ...

class WebFault[**Ts](jep._PyJObject): ...

class WebServiceRef[**Ts](jep._PyJObject): ...

class WebEndpoint[**Ts](jep._PyJObject): ...

class WebServiceFeature[**Ts](jep._PyJObject): ...

class Action[**Ts](jep._PyJObject): ...

class BindingProvider[**Ts](jep._PyJObject): ...

class Service[**Ts](jep._PyJObject): ...

class EndpointReference[**Ts](jep._PyJObject): ...

class WebServiceException[**Ts](jep._PyJObject): ...

class Endpoint[**Ts](jep._PyJObject): ...

class EndpointContext[**Ts](jep._PyJObject): ...

class ProtocolException[**Ts](jep._PyJObject): ...

class RespectBindingFeature[**Ts](jep._PyJObject): ...

class WebServiceClient[**Ts](jep._PyJObject): ...

class Provider[**Ts](jep._PyJObject): ...

class Holder[**Ts](jep._PyJObject): ...

class Response[**Ts](jep._PyJObject): ...

class WebServiceContext[**Ts](jep._PyJObject): ...

class WebServiceRefs[**Ts](jep._PyJObject): ...

class LogicalMessage[**Ts](jep._PyJObject): ...

class Dispatch[**Ts](jep._PyJObject): ...

class RespectBinding[**Ts](jep._PyJObject): ...

class WebServiceProvider[**Ts](jep._PyJObject): ...

class Binding[**Ts](jep._PyJObject): ...

class RequestWrapper[**Ts](jep._PyJObject): ...

