# pyright: reportPrivateUsage = none

import jep

class SOAPFaultException[**Ts](jep._PyJObject): ...

class MTOM[**Ts](jep._PyJObject): ...

class AddressingFeature[**Ts](jep._PyJObject): ...

class SOAPBinding[**Ts](jep._PyJObject): ...

class MTOMFeature[**Ts](jep._PyJObject): ...

