import jep

class MTOM(jep._PyJObject): ...

class AddressingFeature(jep._PyJObject): ...

class SOAPFaultException(jep._PyJObject): ...

class Addressing(jep._PyJObject): ...

class SOAPBinding(jep._PyJObject): ...

class MTOMFeature(jep._PyJObject): ...

