import jep

class MTOM(jep.PyJObject): ...

class AddressingFeature(jep.PyJObject): ...

class SOAPFaultException(jep.PyJObject): ...

class Addressing(jep.PyJObject): ...

class SOAPBinding(jep.PyJObject): ...

class MTOMFeature(jep.PyJObject): ...

