import jep

class InvalidSlotHelper(jep._PyJObject): ...

class IORInterceptor_3_0Helper(jep._PyJObject): ...

class IORInfoOperations(jep._PyJObject): ...

class Current(jep._PyJObject): ...

class IORInterceptor_3_0Holder(jep._PyJObject): ...

class ObjectIdHelper(jep._PyJObject): ...

class ObjectReferenceTemplate(jep._PyJObject): ...

class ServerRequestInterceptorOperations(jep._PyJObject): ...

class ServerRequestInfo(jep._PyJObject): ...

class ObjectReferenceFactoryHolder(jep._PyJObject): ...

class DISCARDING(jep._PyJObject): ...

class RequestInfo(jep._PyJObject): ...

class InterceptorOperations(jep._PyJObject): ...

class NON_EXISTENT(jep._PyJObject): ...

class ServerRequestInterceptor(jep._PyJObject): ...

class SYSTEM_EXCEPTION(jep._PyJObject): ...

class IORInfo(jep._PyJObject): ...

class IORInterceptorOperations(jep._PyJObject): ...

class ForwardRequestHelper(jep._PyJObject): ...

class SUCCESSFUL(jep._PyJObject): ...

class ServerIdHelper(jep._PyJObject): ...

class PolicyFactory(jep._PyJObject): ...

class ObjectReferenceFactoryHelper(jep._PyJObject): ...

class TRANSPORT_RETRY(jep._PyJObject): ...

class ORBIdHelper(jep._PyJObject): ...

class ObjectReferenceFactory(jep._PyJObject): ...

class IORInterceptor(jep._PyJObject): ...

class ORBInitInfoOperations(jep._PyJObject): ...

class IORInterceptor_3_0Operations(jep._PyJObject): ...

class UNKNOWN(jep._PyJObject): ...

class ORBInitializerOperations(jep._PyJObject): ...

class AdapterStateHelper(jep._PyJObject): ...

class ClientRequestInterceptor(jep._PyJObject): ...

class ObjectReferenceTemplateHelper(jep._PyJObject): ...

class AdapterNameHelper(jep._PyJObject): ...

class ClientRequestInfoOperations(jep._PyJObject): ...

class ClientRequestInterceptorOperations(jep._PyJObject): ...

class Interceptor(jep._PyJObject): ...

class USER_EXCEPTION(jep._PyJObject): ...

class ClientRequestInfo(jep._PyJObject): ...

class PolicyFactoryOperations(jep._PyJObject): ...

class ORBInitializer(jep._PyJObject): ...

class ServerRequestInfoOperations(jep._PyJObject): ...

class CurrentOperations(jep._PyJObject): ...

class ACTIVE(jep._PyJObject): ...

class CurrentHelper(jep._PyJObject): ...

class ObjectReferenceTemplateHolder(jep._PyJObject): ...

class AdapterManagerIdHelper(jep._PyJObject): ...

class RequestInfoOperations(jep._PyJObject): ...

class LOCATION_FORWARD(jep._PyJObject): ...

class InvalidSlot(jep._PyJObject): ...

class ObjectReferenceTemplateSeqHolder(jep._PyJObject): ...

class INACTIVE(jep._PyJObject): ...

class HOLDING(jep._PyJObject): ...

class ObjectReferenceTemplateSeqHelper(jep._PyJObject): ...

class IORInterceptor_3_0(jep._PyJObject): ...

class ForwardRequest(jep._PyJObject): ...

class ORBInitInfo(jep._PyJObject): ...

