import jep

class InvalidSlotHelper(jep.PyJObject): ...

class IORInterceptor_3_0Helper(jep.PyJObject): ...

class IORInfoOperations(jep.PyJObject): ...

class Current(jep.PyJObject): ...

class IORInterceptor_3_0Holder(jep.PyJObject): ...

class ObjectIdHelper(jep.PyJObject): ...

class ObjectReferenceTemplate(jep.PyJObject): ...

class ServerRequestInterceptorOperations(jep.PyJObject): ...

class ServerRequestInfo(jep.PyJObject): ...

class ObjectReferenceFactoryHolder(jep.PyJObject): ...

class DISCARDING(jep.PyJObject): ...

class RequestInfo(jep.PyJObject): ...

class InterceptorOperations(jep.PyJObject): ...

class NON_EXISTENT(jep.PyJObject): ...

class ServerRequestInterceptor(jep.PyJObject): ...

class SYSTEM_EXCEPTION(jep.PyJObject): ...

class IORInfo(jep.PyJObject): ...

class IORInterceptorOperations(jep.PyJObject): ...

class ForwardRequestHelper(jep.PyJObject): ...

class SUCCESSFUL(jep.PyJObject): ...

class ServerIdHelper(jep.PyJObject): ...

class PolicyFactory(jep.PyJObject): ...

class ObjectReferenceFactoryHelper(jep.PyJObject): ...

class TRANSPORT_RETRY(jep.PyJObject): ...

class ORBIdHelper(jep.PyJObject): ...

class ObjectReferenceFactory(jep.PyJObject): ...

class IORInterceptor(jep.PyJObject): ...

class ORBInitInfoOperations(jep.PyJObject): ...

class IORInterceptor_3_0Operations(jep.PyJObject): ...

class UNKNOWN(jep.PyJObject): ...

class ORBInitializerOperations(jep.PyJObject): ...

class AdapterStateHelper(jep.PyJObject): ...

class ClientRequestInterceptor(jep.PyJObject): ...

class ObjectReferenceTemplateHelper(jep.PyJObject): ...

class AdapterNameHelper(jep.PyJObject): ...

class ClientRequestInfoOperations(jep.PyJObject): ...

class ClientRequestInterceptorOperations(jep.PyJObject): ...

class Interceptor(jep.PyJObject): ...

class USER_EXCEPTION(jep.PyJObject): ...

class ClientRequestInfo(jep.PyJObject): ...

class PolicyFactoryOperations(jep.PyJObject): ...

class ORBInitializer(jep.PyJObject): ...

class ServerRequestInfoOperations(jep.PyJObject): ...

class CurrentOperations(jep.PyJObject): ...

class ACTIVE(jep.PyJObject): ...

class CurrentHelper(jep.PyJObject): ...

class ObjectReferenceTemplateHolder(jep.PyJObject): ...

class AdapterManagerIdHelper(jep.PyJObject): ...

class RequestInfoOperations(jep.PyJObject): ...

class LOCATION_FORWARD(jep.PyJObject): ...

class InvalidSlot(jep.PyJObject): ...

class ObjectReferenceTemplateSeqHolder(jep.PyJObject): ...

class INACTIVE(jep.PyJObject): ...

class HOLDING(jep.PyJObject): ...

class ObjectReferenceTemplateSeqHelper(jep.PyJObject): ...

class IORInterceptor_3_0(jep.PyJObject): ...

class ForwardRequest(jep.PyJObject): ...

class ORBInitInfo(jep.PyJObject): ...

