# pyright: reportPrivateUsage = none

import jep

class DISCARDING[**Ts](jep._PyJObject): ...

class ServerRequestInfoOperations[**Ts](jep._PyJObject): ...

class PolicyFactory[**Ts](jep._PyJObject): ...

class IORInterceptorOperations[**Ts](jep._PyJObject): ...

class TRANSPORT_RETRY[**Ts](jep._PyJObject): ...

class IORInterceptor_3_0Helper[**Ts](jep._PyJObject): ...

class ClientRequestInfo[**Ts](jep._PyJObject): ...

class ObjectReferenceFactoryHelper[**Ts](jep._PyJObject): ...

class CurrentHelper[**Ts](jep._PyJObject): ...

class ObjectIdHelper[**Ts](jep._PyJObject): ...

class ORBIdHelper[**Ts](jep._PyJObject): ...

class IORInterceptor_3_0Operations[**Ts](jep._PyJObject): ...

class IORInterceptor[**Ts](jep._PyJObject): ...

class ObjectReferenceTemplateSeqHolder[**Ts](jep._PyJObject): ...

class ServerIdHelper[**Ts](jep._PyJObject): ...

class LOCATION_FORWARD[**Ts](jep._PyJObject): ...

class InvalidSlot[**Ts](jep._PyJObject): ...

class SUCCESSFUL[**Ts](jep._PyJObject): ...

class ServerRequestInterceptorOperations[**Ts](jep._PyJObject): ...

class USER_EXCEPTION[**Ts](jep._PyJObject): ...

class INACTIVE[**Ts](jep._PyJObject): ...

class PolicyFactoryOperations[**Ts](jep._PyJObject): ...

class ObjectReferenceTemplateHolder[**Ts](jep._PyJObject): ...

class AdapterManagerIdHelper[**Ts](jep._PyJObject): ...

class Current[**Ts](jep._PyJObject): ...

class IORInterceptor_3_0Holder[**Ts](jep._PyJObject): ...

class ObjectReferenceTemplateHelper[**Ts](jep._PyJObject): ...

class IORInterceptor_3_0[**Ts](jep._PyJObject): ...

class RequestInfo[**Ts](jep._PyJObject): ...

class ObjectReferenceFactory[**Ts](jep._PyJObject): ...

class ObjectReferenceTemplate[**Ts](jep._PyJObject): ...

class ForwardRequestHelper[**Ts](jep._PyJObject): ...

class ORBInitializer[**Ts](jep._PyJObject): ...

class ClientRequestInfoOperations[**Ts](jep._PyJObject): ...

class UNKNOWN[**Ts](jep._PyJObject): ...

class AdapterStateHelper[**Ts](jep._PyJObject): ...

class ForwardRequest[**Ts](jep._PyJObject): ...

class ObjectReferenceTemplateSeqHelper[**Ts](jep._PyJObject): ...

class ClientRequestInterceptorOperations[**Ts](jep._PyJObject): ...

class IORInfo[**Ts](jep._PyJObject): ...

class ServerRequestInterceptor[**Ts](jep._PyJObject): ...

class HOLDING[**Ts](jep._PyJObject): ...

class NON_EXISTENT[**Ts](jep._PyJObject): ...

class ServerRequestInfo[**Ts](jep._PyJObject): ...

class SYSTEM_EXCEPTION[**Ts](jep._PyJObject): ...

class Interceptor[**Ts](jep._PyJObject): ...

class AdapterNameHelper[**Ts](jep._PyJObject): ...

class ObjectReferenceFactoryHolder[**Ts](jep._PyJObject): ...

class CurrentOperations[**Ts](jep._PyJObject): ...

class InterceptorOperations[**Ts](jep._PyJObject): ...

class RequestInfoOperations[**Ts](jep._PyJObject): ...

class ORBInitInfoOperations[**Ts](jep._PyJObject): ...

class ACTIVE[**Ts](jep._PyJObject): ...

class ORBInitializerOperations[**Ts](jep._PyJObject): ...

class IORInfoOperations[**Ts](jep._PyJObject): ...

class ORBInitInfo[**Ts](jep._PyJObject): ...

class ClientRequestInterceptor[**Ts](jep._PyJObject): ...

class InvalidSlotHelper[**Ts](jep._PyJObject): ...

