# pyright: reportPrivateUsage = none

import jep

class InvalidName[**Ts](jep._PyJObject): ...

class DuplicateName[**Ts](jep._PyJObject): ...

class InvalidNameHelper[**Ts](jep._PyJObject): ...

class DuplicateNameHelper[**Ts](jep._PyJObject): ...

