import jep

class CharsetEncoder(jep.PyJObject): ...

class IllegalCharsetNameException(jep.PyJObject): ...

class CharsetDecoder(jep.PyJObject): ...

class UnsupportedCharsetException(jep.PyJObject): ...

class StandardCharsets(jep.PyJObject): ...

class CharacterCodingException(jep.PyJObject): ...

class CoderResult(jep.PyJObject): ...

class CoderMalfunctionError(jep.PyJObject): ...

class UnmappableCharacterException(jep.PyJObject): ...

class CodingErrorAction(jep.PyJObject): ...

class MalformedInputException(jep.PyJObject): ...

