# pyright: reportPrivateUsage = none

import jep

class CharsetDecoder[**Ts](jep._PyJObject): ...

class CharsetEncoder[**Ts](jep._PyJObject): ...

class CodingErrorAction[**Ts](jep._PyJObject): ...

class IllegalCharsetNameException[**Ts](jep._PyJObject): ...

class StandardCharsets[**Ts](jep._PyJObject): ...

class MalformedInputException[**Ts](jep._PyJObject): ...

class CoderMalfunctionError[**Ts](jep._PyJObject): ...

class UnmappableCharacterException[**Ts](jep._PyJObject): ...

class Charset[**Ts](jep._PyJObject): ...

class CharacterCodingException[**Ts](jep._PyJObject): ...

class UnsupportedCharsetException[**Ts](jep._PyJObject): ...

class CoderResult[**Ts](jep._PyJObject): ...

