import jep

class CharsetEncoder(jep._PyJObject): ...

class IllegalCharsetNameException(jep._PyJObject): ...

class CharsetDecoder(jep._PyJObject): ...

class UnsupportedCharsetException(jep._PyJObject): ...

class StandardCharsets(jep._PyJObject): ...

class CharacterCodingException(jep._PyJObject): ...

class CoderResult(jep._PyJObject): ...

class CoderMalfunctionError(jep._PyJObject): ...

class UnmappableCharacterException(jep._PyJObject): ...

class CodingErrorAction(jep._PyJObject): ...

class MalformedInputException(jep._PyJObject): ...

