# pyright: reportPrivateUsage = none

import jep

class WritableByteChannel[**Ts](jep._PyJObject): ...

class Pipe[**Ts](jep._PyJObject): ...

class ConnectionPendingException[**Ts](jep._PyJObject): ...

class AsynchronousByteChannel[**Ts](jep._PyJObject): ...

class ByteChannel[**Ts](jep._PyJObject): ...

class GatheringByteChannel[**Ts](jep._PyJObject): ...

class ClosedByInterruptException[**Ts](jep._PyJObject): ...

class AsynchronousChannelGroup[**Ts](jep._PyJObject): ...

class IllegalBlockingModeException[**Ts](jep._PyJObject): ...

class ReadableByteChannel[**Ts](jep._PyJObject): ...

class IllegalSelectorException[**Ts](jep._PyJObject): ...

class Selector[**Ts](jep._PyJObject): ...

class FileChannel[**Ts](jep._PyJObject): ...

class NotYetConnectedException[**Ts](jep._PyJObject): ...

class CancelledKeyException[**Ts](jep._PyJObject): ...

class OverlappingFileLockException[**Ts](jep._PyJObject): ...

class Channels[**Ts](jep._PyJObject): ...

class AsynchronousSocketChannel[**Ts](jep._PyJObject): ...

class WritePendingException[**Ts](jep._PyJObject): ...

class DatagramChannel[**Ts](jep._PyJObject): ...

class ClosedChannelException[**Ts](jep._PyJObject): ...

class SelectableChannel[**Ts](jep._PyJObject): ...

class AsynchronousServerSocketChannel[**Ts](jep._PyJObject): ...

class AlreadyBoundException[**Ts](jep._PyJObject): ...

class NoConnectionPendingException[**Ts](jep._PyJObject): ...

class MembershipKey[**Ts](jep._PyJObject): ...

class ShutdownChannelGroupException[**Ts](jep._PyJObject): ...

class InterruptedByTimeoutException[**Ts](jep._PyJObject): ...

class SocketChannel[**Ts](jep._PyJObject): ...

class ClosedSelectorException[**Ts](jep._PyJObject): ...

class AsynchronousFileChannel[**Ts](jep._PyJObject): ...

class AsynchronousChannel[**Ts](jep._PyJObject): ...

class FileLock[**Ts](jep._PyJObject): ...

class Channel[**Ts](jep._PyJObject): ...

class MulticastChannel[**Ts](jep._PyJObject): ...

class UnresolvedAddressException[**Ts](jep._PyJObject): ...

class InterruptibleChannel[**Ts](jep._PyJObject): ...

class SelectionKey[**Ts](jep._PyJObject): ...

class FileLockInterruptionException[**Ts](jep._PyJObject): ...

class NonReadableChannelException[**Ts](jep._PyJObject): ...

class ScatteringByteChannel[**Ts](jep._PyJObject): ...

class SeekableByteChannel[**Ts](jep._PyJObject): ...

class UnsupportedAddressTypeException[**Ts](jep._PyJObject): ...

class ServerSocketChannel[**Ts](jep._PyJObject): ...

class NotYetBoundException[**Ts](jep._PyJObject): ...

class CompletionHandler[**Ts](jep._PyJObject): ...

class NetworkChannel[**Ts](jep._PyJObject): ...

class NonWritableChannelException[**Ts](jep._PyJObject): ...

class AlreadyConnectedException[**Ts](jep._PyJObject): ...

class IllegalChannelGroupException[**Ts](jep._PyJObject): ...

class ReadPendingException[**Ts](jep._PyJObject): ...

class AsynchronousCloseException[**Ts](jep._PyJObject): ...

