import jep

class SelectorProvider(jep.PyJObject): ...

class AbstractSelectionKey(jep.PyJObject): ...

class AbstractSelectableChannel(jep.PyJObject): ...

class AsynchronousChannelProvider(jep.PyJObject): ...

class AbstractInterruptibleChannel(jep.PyJObject): ...

