import jep

class SelectorProvider(jep._PyJObject): ...

class AbstractSelectionKey(jep._PyJObject): ...

class AbstractSelectableChannel(jep._PyJObject): ...

class AsynchronousChannelProvider(jep._PyJObject): ...

class AbstractInterruptibleChannel(jep._PyJObject): ...

