# pyright: reportPrivateUsage = none

import jep

class AbstractSelectableChannel[**Ts](jep._PyJObject): ...

class AsynchronousChannelProvider[**Ts](jep._PyJObject): ...

class AbstractInterruptibleChannel[**Ts](jep._PyJObject): ...

class SelectorProvider[**Ts](jep._PyJObject): ...

class AbstractSelector[**Ts](jep._PyJObject): ...

