# pyright: reportPrivateUsage = none

import jep

class Stub[**Ts](jep._PyJObject): ...

class Tie[**Ts](jep._PyJObject): ...

class ValueHandler[**Ts](jep._PyJObject): ...

class UtilDelegate[**Ts](jep._PyJObject): ...

class PortableRemoteObjectDelegate[**Ts](jep._PyJObject): ...

class Util[**Ts](jep._PyJObject): ...

class StubDelegate[**Ts](jep._PyJObject): ...

class ClassDesc[**Ts](jep._PyJObject): ...

