import jep

class Tie(jep.PyJObject): ...

class StubDelegate(jep.PyJObject): ...

class UtilDelegate(jep.PyJObject): ...

class Stub(jep.PyJObject): ...

class ValueHandlerMultiFormat(jep.PyJObject): ...

class ValueHandler(jep.PyJObject): ...

class ClassDesc(jep.PyJObject): ...

class PortableRemoteObjectDelegate(jep.PyJObject): ...

