import jep

class Tie(jep._PyJObject): ...

class StubDelegate(jep._PyJObject): ...

class UtilDelegate(jep._PyJObject): ...

class Stub(jep._PyJObject): ...

class ValueHandlerMultiFormat(jep._PyJObject): ...

class ValueHandler(jep._PyJObject): ...

class ClassDesc(jep._PyJObject): ...

class PortableRemoteObjectDelegate(jep._PyJObject): ...

