import jep

class SecureDirectoryStream(jep.PyJObject): ...

class StandardCopyOption(jep.PyJObject): ...

class FileStore(jep.PyJObject): ...

class FileAlreadyExistsException(jep.PyJObject): ...

class WatchService(jep.PyJObject): ...

class Paths(jep.PyJObject): ...

class FileSystemAlreadyExistsException(jep.PyJObject): ...

class FileSystemNotFoundException(jep.PyJObject): ...

class FileVisitResult(jep.PyJObject): ...

class LinkOption(jep.PyJObject): ...

class InvalidPathException(jep.PyJObject): ...

class ClosedWatchServiceException(jep.PyJObject): ...

class StandardWatchEventKinds(jep.PyJObject): ...

class FileSystemLoopException(jep.PyJObject): ...

class NotDirectoryException(jep.PyJObject): ...

class FileSystem(jep.PyJObject): ...

class SimpleFileVisitor(jep.PyJObject): ...

class Files(jep.PyJObject): ...

class OpenOption(jep.PyJObject): ...

class AccessDeniedException(jep.PyJObject): ...

class StandardOpenOption(jep.PyJObject): ...

class AtomicMoveNotSupportedException(jep.PyJObject): ...

class PathMatcher(jep.PyJObject): ...

class Watchable(jep.PyJObject): ...

class DirectoryNotEmptyException(jep.PyJObject): ...

class CopyOption(jep.PyJObject): ...

class DirectoryIteratorException(jep.PyJObject): ...

class ClosedFileSystemException(jep.PyJObject): ...

class FileVisitor(jep.PyJObject): ...

class WatchKey(jep.PyJObject): ...

class DirectoryStream(jep.PyJObject): ...

class LinkPermission(jep.PyJObject): ...

class FileSystems(jep.PyJObject): ...

class NoSuchFileException(jep.PyJObject): ...

class FileVisitOption(jep.PyJObject): ...

class FileSystemException(jep.PyJObject): ...

class Path(jep.PyJObject): ...

class ClosedDirectoryStreamException(jep.PyJObject): ...

class ProviderMismatchException(jep.PyJObject): ...

class ProviderNotFoundException(jep.PyJObject): ...

class WatchEvent(jep.PyJObject): ...

class NotLinkException(jep.PyJObject): ...

class AccessMode(jep.PyJObject): ...

class ReadOnlyFileSystemException(jep.PyJObject): ...

