# pyright: reportPrivateUsage = none

import jep

class StandardWatchEventKinds[**Ts](jep._PyJObject): ...

class ClosedFileSystemException[**Ts](jep._PyJObject): ...

class ProviderMismatchException[**Ts](jep._PyJObject): ...

class FileSystemLoopException[**Ts](jep._PyJObject): ...

class AccessMode[**Ts](jep._PyJObject): ...

class DirectoryNotEmptyException[**Ts](jep._PyJObject): ...

class ProviderNotFoundException[**Ts](jep._PyJObject): ...

class NotDirectoryException[**Ts](jep._PyJObject): ...

class ClosedWatchServiceException[**Ts](jep._PyJObject): ...

class FileSystemAlreadyExistsException[**Ts](jep._PyJObject): ...

class DirectoryStream[**Ts](jep._PyJObject): ...

class AtomicMoveNotSupportedException[**Ts](jep._PyJObject): ...

class PathMatcher[**Ts](jep._PyJObject): ...

class NoSuchFileException[**Ts](jep._PyJObject): ...

class SecureDirectoryStream[**Ts](jep._PyJObject): ...

class InvalidPathException[**Ts](jep._PyJObject): ...

class WatchEvent[**Ts](jep._PyJObject): ...

class FileSystems[**Ts](jep._PyJObject): ...

class CopyOption[**Ts](jep._PyJObject): ...

class FileSystemException[**Ts](jep._PyJObject): ...

class ClosedDirectoryStreamException[**Ts](jep._PyJObject): ...

class AccessDeniedException[**Ts](jep._PyJObject): ...

class LinkPermission[**Ts](jep._PyJObject): ...

class StandardOpenOption[**Ts](jep._PyJObject): ...

class Path[**Ts](jep._PyJObject): ...

class WatchService[**Ts](jep._PyJObject): ...

class FileVisitResult[**Ts](jep._PyJObject): ...

class SimpleFileVisitor[**Ts](jep._PyJObject): ...

class FileSystem[**Ts](jep._PyJObject): ...

class ReadOnlyFileSystemException[**Ts](jep._PyJObject): ...

class Watchable[**Ts](jep._PyJObject): ...

class FileVisitor[**Ts](jep._PyJObject): ...

class WatchKey[**Ts](jep._PyJObject): ...

class StandardCopyOption[**Ts](jep._PyJObject): ...

class FileAlreadyExistsException[**Ts](jep._PyJObject): ...

class Paths[**Ts](jep._PyJObject): ...

class OpenOption[**Ts](jep._PyJObject): ...

class FileSystemNotFoundException[**Ts](jep._PyJObject): ...

class DirectoryIteratorException[**Ts](jep._PyJObject): ...

class Files[**Ts](jep._PyJObject): ...

class LinkOption[**Ts](jep._PyJObject): ...

class NotLinkException[**Ts](jep._PyJObject): ...

class FileStore[**Ts](jep._PyJObject): ...

class FileVisitOption[**Ts](jep._PyJObject): ...

