import jep

class SecureDirectoryStream(jep._PyJObject): ...

class StandardCopyOption(jep._PyJObject): ...

class FileStore(jep._PyJObject): ...

class FileAlreadyExistsException(jep._PyJObject): ...

class WatchService(jep._PyJObject): ...

class Paths(jep._PyJObject): ...

class FileSystemAlreadyExistsException(jep._PyJObject): ...

class FileSystemNotFoundException(jep._PyJObject): ...

class FileVisitResult(jep._PyJObject): ...

class LinkOption(jep._PyJObject): ...

class InvalidPathException(jep._PyJObject): ...

class ClosedWatchServiceException(jep._PyJObject): ...

class StandardWatchEventKinds(jep._PyJObject): ...

class FileSystemLoopException(jep._PyJObject): ...

class NotDirectoryException(jep._PyJObject): ...

class FileSystem(jep._PyJObject): ...

class SimpleFileVisitor(jep._PyJObject): ...

class Files(jep._PyJObject): ...

class OpenOption(jep._PyJObject): ...

class AccessDeniedException(jep._PyJObject): ...

class StandardOpenOption(jep._PyJObject): ...

class AtomicMoveNotSupportedException(jep._PyJObject): ...

class PathMatcher(jep._PyJObject): ...

class Watchable(jep._PyJObject): ...

class DirectoryNotEmptyException(jep._PyJObject): ...

class CopyOption(jep._PyJObject): ...

class DirectoryIteratorException(jep._PyJObject): ...

class ClosedFileSystemException(jep._PyJObject): ...

class FileVisitor(jep._PyJObject): ...

class WatchKey(jep._PyJObject): ...

class DirectoryStream(jep._PyJObject): ...

class LinkPermission(jep._PyJObject): ...

class FileSystems(jep._PyJObject): ...

class NoSuchFileException(jep._PyJObject): ...

class FileVisitOption(jep._PyJObject): ...

class FileSystemException(jep._PyJObject): ...

class Path(jep._PyJObject): ...

class ClosedDirectoryStreamException(jep._PyJObject): ...

class ProviderMismatchException(jep._PyJObject): ...

class ProviderNotFoundException(jep._PyJObject): ...

class WatchEvent(jep._PyJObject): ...

class NotLinkException(jep._PyJObject): ...

class AccessMode(jep._PyJObject): ...

class ReadOnlyFileSystemException(jep._PyJObject): ...

