import jep

class UserPrincipalNotFoundException(jep._PyJObject): ...

class FileStoreAttributeView(jep._PyJObject): ...

class PosixFilePermissions(jep._PyJObject): ...

class DosFileAttributes(jep._PyJObject): ...

class UserDefinedFileAttributeView(jep._PyJObject): ...

class AclEntry(jep._PyJObject): ...

class FileOwnerAttributeView(jep._PyJObject): ...

class AttributeView(jep._PyJObject): ...

class AclFileAttributeView(jep._PyJObject): ...

class BasicFileAttributes(jep._PyJObject): ...

class PosixFilePermission(jep._PyJObject): ...

class UserPrincipal(jep._PyJObject): ...

class GroupPrincipal(jep._PyJObject): ...

class BasicFileAttributeView(jep._PyJObject): ...

class DosFileAttributeView(jep._PyJObject): ...

class AclEntryType(jep._PyJObject): ...

class UserPrincipalLookupService(jep._PyJObject): ...

class FileAttributeView(jep._PyJObject): ...

class AclEntryPermission(jep._PyJObject): ...

class PosixFileAttributeView(jep._PyJObject): ...

class AclEntryFlag(jep._PyJObject): ...

class FileTime(jep._PyJObject): ...

class FileAttribute(jep._PyJObject): ...

