import jep

class UserPrincipalNotFoundException(jep.PyJObject): ...

class FileStoreAttributeView(jep.PyJObject): ...

class PosixFilePermissions(jep.PyJObject): ...

class DosFileAttributes(jep.PyJObject): ...

class UserDefinedFileAttributeView(jep.PyJObject): ...

class AclEntry(jep.PyJObject): ...

class FileOwnerAttributeView(jep.PyJObject): ...

class AttributeView(jep.PyJObject): ...

class AclFileAttributeView(jep.PyJObject): ...

class BasicFileAttributes(jep.PyJObject): ...

class PosixFilePermission(jep.PyJObject): ...

class UserPrincipal(jep.PyJObject): ...

class GroupPrincipal(jep.PyJObject): ...

class BasicFileAttributeView(jep.PyJObject): ...

class DosFileAttributeView(jep.PyJObject): ...

class AclEntryType(jep.PyJObject): ...

class UserPrincipalLookupService(jep.PyJObject): ...

class FileAttributeView(jep.PyJObject): ...

class AclEntryPermission(jep.PyJObject): ...

class PosixFileAttributeView(jep.PyJObject): ...

class AclEntryFlag(jep.PyJObject): ...

class FileTime(jep.PyJObject): ...

class FileAttribute(jep.PyJObject): ...

