# pyright: reportPrivateUsage = none

import jep

class FileOwnerAttributeView[**Ts](jep._PyJObject): ...

class AclEntryType[**Ts](jep._PyJObject): ...

class AttributeView[**Ts](jep._PyJObject): ...

class FileAttributeView[**Ts](jep._PyJObject): ...

class GroupPrincipal[**Ts](jep._PyJObject): ...

class DosFileAttributeView[**Ts](jep._PyJObject): ...

class PosixFilePermission[**Ts](jep._PyJObject): ...

class AclFileAttributeView[**Ts](jep._PyJObject): ...

class BasicFileAttributes[**Ts](jep._PyJObject): ...

class PosixFilePermissions[**Ts](jep._PyJObject): ...

class UserPrincipalLookupService[**Ts](jep._PyJObject): ...

class PosixFileAttributeView[**Ts](jep._PyJObject): ...

class FileTime[**Ts](jep._PyJObject): ...

class AclEntry[**Ts](jep._PyJObject): ...

class UserPrincipalNotFoundException[**Ts](jep._PyJObject): ...

class UserDefinedFileAttributeView[**Ts](jep._PyJObject): ...

class AclEntryFlag[**Ts](jep._PyJObject): ...

class PosixFileAttributes[**Ts](jep._PyJObject): ...

class FileAttribute[**Ts](jep._PyJObject): ...

class FileStoreAttributeView[**Ts](jep._PyJObject): ...

class AclEntryPermission[**Ts](jep._PyJObject): ...

class BasicFileAttributeView[**Ts](jep._PyJObject): ...

class UserPrincipal[**Ts](jep._PyJObject): ...

