import jep

class RGBImageFilter(jep._PyJObject): ...

class Kernel(jep._PyJObject): ...

class ComponentColorModel(jep._PyJObject): ...

class LookupOp(jep._PyJObject): ...

class ImageProducer(jep._PyJObject): ...

class SampleModel(jep._PyJObject): ...

class BufferStrategy(jep._PyJObject): ...

class BufferedImageFilter(jep._PyJObject): ...

class AbstractMultiResolutionImage(jep._PyJObject): ...

class ColorModel(jep._PyJObject): ...

class RescaleOp(jep._PyJObject): ...

class MemoryImageSource(jep._PyJObject): ...

class DirectColorModel(jep._PyJObject): ...

class ImageObserver(jep._PyJObject): ...

class PixelInterleavedSampleModel(jep._PyJObject): ...

class IndexColorModel(jep._PyJObject): ...

class TileObserver(jep._PyJObject): ...

class BaseMultiResolutionImage(jep._PyJObject): ...

class ConvolveOp(jep._PyJObject): ...

class DataBufferInt(jep._PyJObject): ...

class WritableRaster(jep._PyJObject): ...

class BufferedImageOp(jep._PyJObject): ...

class VolatileImage(jep._PyJObject): ...

class DataBufferFloat(jep._PyJObject): ...

class DataBufferDouble(jep._PyJObject): ...

class PixelGrabber(jep._PyJObject): ...

class BufferedImage(jep._PyJObject): ...

class SinglePixelPackedSampleModel(jep._PyJObject): ...

class ComponentSampleModel(jep._PyJObject): ...

class Raster(jep._PyJObject): ...

class WritableRenderedImage(jep._PyJObject): ...

class DataBuffer(jep._PyJObject): ...

class ShortLookupTable(jep._PyJObject): ...

class DataBufferShort(jep._PyJObject): ...

class AreaAveragingScaleFilter(jep._PyJObject): ...

class BandedSampleModel(jep._PyJObject): ...

class PackedColorModel(jep._PyJObject): ...

class ImageConsumer(jep._PyJObject): ...

class AffineTransformOp(jep._PyJObject): ...

class MultiResolutionImage(jep._PyJObject): ...

class ImageFilter(jep._PyJObject): ...

class ColorConvertOp(jep._PyJObject): ...

class DataBufferByte(jep._PyJObject): ...

class RasterOp(jep._PyJObject): ...

class BandCombineOp(jep._PyJObject): ...

class DataBufferUShort(jep._PyJObject): ...

class LookupTable(jep._PyJObject): ...

class MultiPixelPackedSampleModel(jep._PyJObject): ...

class ImagingOpException(jep._PyJObject): ...

class ReplicateScaleFilter(jep._PyJObject): ...

class ByteLookupTable(jep._PyJObject): ...

class FilteredImageSource(jep._PyJObject): ...

class CropImageFilter(jep._PyJObject): ...

class RenderedImage(jep._PyJObject): ...

class RasterFormatException(jep._PyJObject): ...

