import jep

class RGBImageFilter(jep.PyJObject): ...

class Kernel(jep.PyJObject): ...

class ComponentColorModel(jep.PyJObject): ...

class LookupOp(jep.PyJObject): ...

class ImageProducer(jep.PyJObject): ...

class SampleModel(jep.PyJObject): ...

class BufferStrategy(jep.PyJObject): ...

class BufferedImageFilter(jep.PyJObject): ...

class AbstractMultiResolutionImage(jep.PyJObject): ...

class ColorModel(jep.PyJObject): ...

class RescaleOp(jep.PyJObject): ...

class MemoryImageSource(jep.PyJObject): ...

class DirectColorModel(jep.PyJObject): ...

class ImageObserver(jep.PyJObject): ...

class PixelInterleavedSampleModel(jep.PyJObject): ...

class IndexColorModel(jep.PyJObject): ...

class TileObserver(jep.PyJObject): ...

class BaseMultiResolutionImage(jep.PyJObject): ...

class ConvolveOp(jep.PyJObject): ...

class DataBufferInt(jep.PyJObject): ...

class WritableRaster(jep.PyJObject): ...

class BufferedImageOp(jep.PyJObject): ...

class VolatileImage(jep.PyJObject): ...

class DataBufferFloat(jep.PyJObject): ...

class DataBufferDouble(jep.PyJObject): ...

class PixelGrabber(jep.PyJObject): ...

class BufferedImage(jep.PyJObject): ...

class SinglePixelPackedSampleModel(jep.PyJObject): ...

class ComponentSampleModel(jep.PyJObject): ...

class Raster(jep.PyJObject): ...

class WritableRenderedImage(jep.PyJObject): ...

class DataBuffer(jep.PyJObject): ...

class ShortLookupTable(jep.PyJObject): ...

class DataBufferShort(jep.PyJObject): ...

class AreaAveragingScaleFilter(jep.PyJObject): ...

class BandedSampleModel(jep.PyJObject): ...

class PackedColorModel(jep.PyJObject): ...

class ImageConsumer(jep.PyJObject): ...

class AffineTransformOp(jep.PyJObject): ...

class MultiResolutionImage(jep.PyJObject): ...

class ImageFilter(jep.PyJObject): ...

class ColorConvertOp(jep.PyJObject): ...

class DataBufferByte(jep.PyJObject): ...

class RasterOp(jep.PyJObject): ...

class BandCombineOp(jep.PyJObject): ...

class DataBufferUShort(jep.PyJObject): ...

class LookupTable(jep.PyJObject): ...

class MultiPixelPackedSampleModel(jep.PyJObject): ...

class ImagingOpException(jep.PyJObject): ...

class ReplicateScaleFilter(jep.PyJObject): ...

class ByteLookupTable(jep.PyJObject): ...

class FilteredImageSource(jep.PyJObject): ...

class CropImageFilter(jep.PyJObject): ...

class RenderedImage(jep.PyJObject): ...

class RasterFormatException(jep.PyJObject): ...

