# pyright: reportPrivateUsage = none

import jep

class ConvolveOp[**Ts](jep._PyJObject): ...

class RGBImageFilter[**Ts](jep._PyJObject): ...

class PackedColorModel[**Ts](jep._PyJObject): ...

class ImageFilter[**Ts](jep._PyJObject): ...

class ReplicateScaleFilter[**Ts](jep._PyJObject): ...

class IndexColorModel[**Ts](jep._PyJObject): ...

class MultiPixelPackedSampleModel[**Ts](jep._PyJObject): ...

class LookupTable[**Ts](jep._PyJObject): ...

class WritableRaster[**Ts](jep._PyJObject): ...

class Kernel[**Ts](jep._PyJObject): ...

class DataBufferFloat[**Ts](jep._PyJObject): ...

class TileObserver[**Ts](jep._PyJObject): ...

class ImageConsumer[**Ts](jep._PyJObject): ...

class FilteredImageSource[**Ts](jep._PyJObject): ...

class AreaAveragingScaleFilter[**Ts](jep._PyJObject): ...

class BufferStrategy[**Ts](jep._PyJObject): ...

class DirectColorModel[**Ts](jep._PyJObject): ...

class RescaleOp[**Ts](jep._PyJObject): ...

class ImageProducer[**Ts](jep._PyJObject): ...

class ColorModel[**Ts](jep._PyJObject): ...

class CropImageFilter[**Ts](jep._PyJObject): ...

class BufferedImageOp[**Ts](jep._PyJObject): ...

class WritableRenderedImage[**Ts](jep._PyJObject): ...

class RasterFormatException[**Ts](jep._PyJObject): ...

class DataBufferDouble[**Ts](jep._PyJObject): ...

class AffineTransformOp[**Ts](jep._PyJObject): ...

class PixelInterleavedSampleModel[**Ts](jep._PyJObject): ...

class AbstractMultiResolutionImage[**Ts](jep._PyJObject): ...

class DataBufferByte[**Ts](jep._PyJObject): ...

class DataBufferShort[**Ts](jep._PyJObject): ...

class BandedSampleModel[**Ts](jep._PyJObject): ...

class ImagingOpException[**Ts](jep._PyJObject): ...

class RasterOp[**Ts](jep._PyJObject): ...

class DataBuffer[**Ts](jep._PyJObject): ...

class ByteLookupTable[**Ts](jep._PyJObject): ...

class MemoryImageSource[**Ts](jep._PyJObject): ...

class ComponentColorModel[**Ts](jep._PyJObject): ...

class LookupOp[**Ts](jep._PyJObject): ...

class PixelGrabber[**Ts](jep._PyJObject): ...

class SinglePixelPackedSampleModel[**Ts](jep._PyJObject): ...

class BufferedImage[**Ts](jep._PyJObject): ...

class Raster[**Ts](jep._PyJObject): ...

class BaseMultiResolutionImage[**Ts](jep._PyJObject): ...

class ColorConvertOp[**Ts](jep._PyJObject): ...

class MultiResolutionImage[**Ts](jep._PyJObject): ...

class RenderedImage[**Ts](jep._PyJObject): ...

class VolatileImage[**Ts](jep._PyJObject): ...

class BufferedImageFilter[**Ts](jep._PyJObject): ...

class ImageObserver[**Ts](jep._PyJObject): ...

class BandCombineOp[**Ts](jep._PyJObject): ...

class ComponentSampleModel[**Ts](jep._PyJObject): ...

class SampleModel[**Ts](jep._PyJObject): ...

class DataBufferInt[**Ts](jep._PyJObject): ...

class ShortLookupTable[**Ts](jep._PyJObject): ...

class DataBufferUShort[**Ts](jep._PyJObject): ...

