import jep

class ParameterBlock(jep._PyJObject): ...

class RenderedImageFactory(jep._PyJObject): ...

class RenderableImageProducer(jep._PyJObject): ...

class RenderContext(jep._PyJObject): ...

class ContextualRenderedImageFactory(jep._PyJObject): ...

class RenderableImage(jep._PyJObject): ...

