import jep

class ParameterBlock(jep.PyJObject): ...

class RenderedImageFactory(jep.PyJObject): ...

class RenderableImageProducer(jep.PyJObject): ...

class RenderContext(jep.PyJObject): ...

class ContextualRenderedImageFactory(jep.PyJObject): ...

class RenderableImage(jep.PyJObject): ...

