# pyright: reportPrivateUsage = none

import jep

class RenderableImageProducer[**Ts](jep._PyJObject): ...

class RenderableImage[**Ts](jep._PyJObject): ...

class RenderContext[**Ts](jep._PyJObject): ...

class ContextualRenderedImageFactory[**Ts](jep._PyJObject): ...

class ParameterBlock[**Ts](jep._PyJObject): ...

class RenderableImageOp[**Ts](jep._PyJObject): ...

