# pyright: reportPrivateUsage = none

import jep

class WebResult[**Ts](jep._PyJObject): ...

class HandlerChain[**Ts](jep._PyJObject): ...

class WebService[**Ts](jep._PyJObject): ...

class WebMethod[**Ts](jep._PyJObject): ...

class WebParam[**Ts](jep._PyJObject): ...

class Oneway[**Ts](jep._PyJObject): ...

