import jep

class Oneway(jep.PyJObject): ...

class WebMethod(jep.PyJObject): ...

class WebService(jep.PyJObject): ...

class WebParam(jep.PyJObject): ...

class HandlerChain(jep.PyJObject): ...

class WebResult(jep.PyJObject): ...

