import jep

class Oneway(jep._PyJObject): ...

class WebMethod(jep._PyJObject): ...

class WebService(jep._PyJObject): ...

class WebParam(jep._PyJObject): ...

class HandlerChain(jep._PyJObject): ...

class WebResult(jep._PyJObject): ...

