import jep

class UnknownHostException(jep.PyJObject): ...

class ContentHandler(jep.PyJObject): ...

class URISyntaxException(jep.PyJObject): ...

class HttpURLConnection(jep.PyJObject): ...

class HttpRetryException(jep.PyJObject): ...

class URLDecoder(jep.PyJObject): ...

class ServerSocket(jep.PyJObject): ...

class NetworkInterface(jep.PyJObject): ...

class SocketPermission(jep.PyJObject): ...

class DatagramSocket(jep.PyJObject): ...

class CookiePolicy(jep.PyJObject): ...

class StandardProtocolFamily(jep.PyJObject): ...

class MulticastSocket(jep.PyJObject): ...

class NoRouteToHostException(jep.PyJObject): ...

class DatagramPacket(jep.PyJObject): ...

class SocketAddress(jep.PyJObject): ...

class StandardSocketOptions(jep.PyJObject): ...

class PasswordAuthentication(jep.PyJObject): ...

class ResponseCache(jep.PyJObject): ...

class URL(jep.PyJObject): ...

class URI(jep.PyJObject): ...

class DatagramSocketImpl(jep.PyJObject): ...

class SocketOptions(jep.PyJObject): ...

class ProtocolFamily(jep.PyJObject): ...

class IDN(jep.PyJObject): ...

class InterfaceAddress(jep.PyJObject): ...

class SocketImpl(jep.PyJObject): ...

class PortUnreachableException(jep.PyJObject): ...

class UnknownServiceException(jep.PyJObject): ...

class Authenticator(jep.PyJObject): ...

class HttpCookie(jep.PyJObject): ...

class URLConnection(jep.PyJObject): ...

class Socket(jep.PyJObject): ...

class URLPermission(jep.PyJObject): ...

class ContentHandlerFactory(jep.PyJObject): ...

class CookieHandler(jep.PyJObject): ...

class ProtocolException(jep.PyJObject): ...

class URLClassLoader(jep.PyJObject): ...

class CookieStore(jep.PyJObject): ...

class CacheRequest(jep.PyJObject): ...

class NetPermission(jep.PyJObject): ...

class URLStreamHandler(jep.PyJObject): ...

class Inet6Address(jep.PyJObject): ...

class URLStreamHandlerFactory(jep.PyJObject): ...

class MalformedURLException(jep.PyJObject): ...

class ProxySelector(jep.PyJObject): ...

class JarURLConnection(jep.PyJObject): ...

class URLEncoder(jep.PyJObject): ...

class CacheResponse(jep.PyJObject): ...

class SocketOption(jep.PyJObject): ...

class Inet4Address(jep.PyJObject): ...

class BindException(jep.PyJObject): ...

class FileNameMap(jep.PyJObject): ...

class CookieManager(jep.PyJObject): ...

class ConnectException(jep.PyJObject): ...

class InetAddress(jep.PyJObject): ...

class InetSocketAddress(jep.PyJObject): ...

class SocketException(jep.PyJObject): ...

class SecureCacheResponse(jep.PyJObject): ...

class SocketTimeoutException(jep.PyJObject): ...

class Proxy(jep.PyJObject): ...

class DatagramSocketImplFactory(jep.PyJObject): ...

class SocketImplFactory(jep.PyJObject): ...

