# pyright: reportPrivateUsage = none

import jep

class SocketPermission[**Ts](jep._PyJObject): ...

class CookieHandler[**Ts](jep._PyJObject): ...

class BindException[**Ts](jep._PyJObject): ...

class MulticastSocket[**Ts](jep._PyJObject): ...

class SocketException[**Ts](jep._PyJObject): ...

class URLEncoder[**Ts](jep._PyJObject): ...

class DatagramSocketImplFactory[**Ts](jep._PyJObject): ...

class InterfaceAddress[**Ts](jep._PyJObject): ...

class URL[**Ts](jep._PyJObject): ...

class ContentHandlerFactory[**Ts](jep._PyJObject): ...

class SocketImplFactory[**Ts](jep._PyJObject): ...

class InetSocketAddress[**Ts](jep._PyJObject): ...

class HttpRetryException[**Ts](jep._PyJObject): ...

class HttpURLConnection[**Ts](jep._PyJObject): ...

class DatagramSocketImpl[**Ts](jep._PyJObject): ...

class SecureCacheResponse[**Ts](jep._PyJObject): ...

class DatagramPacket[**Ts](jep._PyJObject): ...

class IDN[**Ts](jep._PyJObject): ...

class DatagramSocket[**Ts](jep._PyJObject): ...

class ServerSocket[**Ts](jep._PyJObject): ...

class SocketOptions[**Ts](jep._PyJObject): ...

class SocketAddress[**Ts](jep._PyJObject): ...

class CookiePolicy[**Ts](jep._PyJObject): ...

class NoRouteToHostException[**Ts](jep._PyJObject): ...

class URLClassLoader[**Ts](jep._PyJObject): ...

class ResponseCache[**Ts](jep._PyJObject): ...

class URLStreamHandler[**Ts](jep._PyJObject): ...

class Inet4Address[**Ts](jep._PyJObject): ...

class URLDecoder[**Ts](jep._PyJObject): ...

class PasswordAuthentication[**Ts](jep._PyJObject): ...

class PortUnreachableException[**Ts](jep._PyJObject): ...

class MalformedURLException[**Ts](jep._PyJObject): ...

class ProtocolException[**Ts](jep._PyJObject): ...

class InetAddress[**Ts](jep._PyJObject): ...

class NetworkInterface[**Ts](jep._PyJObject): ...

class Inet6Address[**Ts](jep._PyJObject): ...

class UnknownHostException[**Ts](jep._PyJObject): ...

class StandardSocketOptions[**Ts](jep._PyJObject): ...

class Proxy[**Ts](jep._PyJObject): ...

class CookieManager[**Ts](jep._PyJObject): ...

class UnknownServiceException[**Ts](jep._PyJObject): ...

class HttpCookie[**Ts](jep._PyJObject): ...

class SocketImpl[**Ts](jep._PyJObject): ...

class URLPermission[**Ts](jep._PyJObject): ...

class CacheResponse[**Ts](jep._PyJObject): ...

class ConnectException[**Ts](jep._PyJObject): ...

class SocketTimeoutException[**Ts](jep._PyJObject): ...

class FileNameMap[**Ts](jep._PyJObject): ...

class Socket[**Ts](jep._PyJObject): ...

class StandardProtocolFamily[**Ts](jep._PyJObject): ...

class URLConnection[**Ts](jep._PyJObject): ...

class NetPermission[**Ts](jep._PyJObject): ...

class CacheRequest[**Ts](jep._PyJObject): ...

class URLStreamHandlerFactory[**Ts](jep._PyJObject): ...

class ProtocolFamily[**Ts](jep._PyJObject): ...

class CookieStore[**Ts](jep._PyJObject): ...

class ProxySelector[**Ts](jep._PyJObject): ...

class ContentHandler[**Ts](jep._PyJObject): ...

class JarURLConnection[**Ts](jep._PyJObject): ...

class URISyntaxException[**Ts](jep._PyJObject): ...

class Authenticator[**Ts](jep._PyJObject): ...

class URI[**Ts](jep._PyJObject): ...

class SocketOption[**Ts](jep._PyJObject): ...

