import jep

class UnknownHostException(jep._PyJObject): ...

class ContentHandler(jep._PyJObject): ...

class URISyntaxException(jep._PyJObject): ...

class HttpURLConnection(jep._PyJObject): ...

class HttpRetryException(jep._PyJObject): ...

class URLDecoder(jep._PyJObject): ...

class ServerSocket(jep._PyJObject): ...

class NetworkInterface(jep._PyJObject): ...

class SocketPermission(jep._PyJObject): ...

class DatagramSocket(jep._PyJObject): ...

class CookiePolicy(jep._PyJObject): ...

class StandardProtocolFamily(jep._PyJObject): ...

class MulticastSocket(jep._PyJObject): ...

class NoRouteToHostException(jep._PyJObject): ...

class DatagramPacket(jep._PyJObject): ...

class SocketAddress(jep._PyJObject): ...

class StandardSocketOptions(jep._PyJObject): ...

class PasswordAuthentication(jep._PyJObject): ...

class ResponseCache(jep._PyJObject): ...

class URL(jep._PyJObject): ...

class URI(jep._PyJObject): ...

class DatagramSocketImpl(jep._PyJObject): ...

class SocketOptions(jep._PyJObject): ...

class ProtocolFamily(jep._PyJObject): ...

class IDN(jep._PyJObject): ...

class InterfaceAddress(jep._PyJObject): ...

class SocketImpl(jep._PyJObject): ...

class PortUnreachableException(jep._PyJObject): ...

class UnknownServiceException(jep._PyJObject): ...

class Authenticator(jep._PyJObject): ...

class HttpCookie(jep._PyJObject): ...

class URLConnection(jep._PyJObject): ...

class Socket(jep._PyJObject): ...

class URLPermission(jep._PyJObject): ...

class ContentHandlerFactory(jep._PyJObject): ...

class CookieHandler(jep._PyJObject): ...

class ProtocolException(jep._PyJObject): ...

class URLClassLoader(jep._PyJObject): ...

class CookieStore(jep._PyJObject): ...

class CacheRequest(jep._PyJObject): ...

class NetPermission(jep._PyJObject): ...

class URLStreamHandler(jep._PyJObject): ...

class Inet6Address(jep._PyJObject): ...

class URLStreamHandlerFactory(jep._PyJObject): ...

class MalformedURLException(jep._PyJObject): ...

class ProxySelector(jep._PyJObject): ...

class JarURLConnection(jep._PyJObject): ...

class URLEncoder(jep._PyJObject): ...

class CacheResponse(jep._PyJObject): ...

class SocketOption(jep._PyJObject): ...

class Inet4Address(jep._PyJObject): ...

class BindException(jep._PyJObject): ...

class FileNameMap(jep._PyJObject): ...

class CookieManager(jep._PyJObject): ...

class ConnectException(jep._PyJObject): ...

class InetAddress(jep._PyJObject): ...

class InetSocketAddress(jep._PyJObject): ...

class SocketException(jep._PyJObject): ...

class SecureCacheResponse(jep._PyJObject): ...

class SocketTimeoutException(jep._PyJObject): ...

class Proxy(jep._PyJObject): ...

class DatagramSocketImplFactory(jep._PyJObject): ...

class SocketImplFactory(jep._PyJObject): ...

