import jep

class WebSocketHandshakeException(jep.PyJObject): ...

class HttpTimeoutException(jep.PyJObject): ...

class HttpHeaders(jep.PyJObject): ...

class HttpConnectTimeoutException(jep.PyJObject): ...

class WebSocket(jep.PyJObject): ...

class HttpResponse(jep.PyJObject): ...

class HttpRequest(jep.PyJObject): ...

class HttpClient(jep.PyJObject): ...

