# pyright: reportPrivateUsage = none

import jep

class WebSocketHandshakeException[**Ts](jep._PyJObject): ...

class HttpTimeoutException[**Ts](jep._PyJObject): ...

class HttpHeaders[**Ts](jep._PyJObject): ...

class HttpResponse[**Ts](jep._PyJObject): ...

class WebSocket[**Ts](jep._PyJObject): ...

class HttpClient[**Ts](jep._PyJObject): ...

class HttpConnectTimeoutException[**Ts](jep._PyJObject): ...

