import jep

class WebSocketHandshakeException(jep._PyJObject): ...

class HttpTimeoutException(jep._PyJObject): ...

class HttpHeaders(jep._PyJObject): ...

class HttpConnectTimeoutException(jep._PyJObject): ...

class WebSocket(jep._PyJObject): ...

class HttpResponse(jep._PyJObject): ...

class HttpRequest(jep._PyJObject): ...

class HttpClient(jep._PyJObject): ...

