# pyright: reportPrivateUsage = none

import jep

class Doc[**Ts](jep._PyJObject): ...

class Type[**Ts](jep._PyJObject): ...

class AnnotatedType[**Ts](jep._PyJObject): ...

class MemberDoc[**Ts](jep._PyJObject): ...

class SerialFieldTag[**Ts](jep._PyJObject): ...

class WildcardType[**Ts](jep._PyJObject): ...

class ParamTag[**Ts](jep._PyJObject): ...

class Doclet[**Ts](jep._PyJObject): ...

class ThrowsTag[**Ts](jep._PyJObject): ...

class ExecutableMemberDoc[**Ts](jep._PyJObject): ...

class ConstructorDoc[**Ts](jep._PyJObject): ...

class ProgramElementDoc[**Ts](jep._PyJObject): ...

class DocErrorReporter[**Ts](jep._PyJObject): ...

class MethodDoc[**Ts](jep._PyJObject): ...

class AnnotationTypeElementDoc[**Ts](jep._PyJObject): ...

class AnnotationDesc[**Ts](jep._PyJObject): ...

class SeeTag[**Ts](jep._PyJObject): ...

class AnnotationTypeDoc[**Ts](jep._PyJObject): ...

class PackageDoc[**Ts](jep._PyJObject): ...

class TypeVariable[**Ts](jep._PyJObject): ...

class ClassDoc[**Ts](jep._PyJObject): ...

class RootDoc[**Ts](jep._PyJObject): ...

class FieldDoc[**Ts](jep._PyJObject): ...

class SourcePosition[**Ts](jep._PyJObject): ...

class AnnotationValue[**Ts](jep._PyJObject): ...

class LanguageVersion[**Ts](jep._PyJObject): ...

class ParameterizedType[**Ts](jep._PyJObject): ...

class Parameter[**Ts](jep._PyJObject): ...

class Tag[**Ts](jep._PyJObject): ...

