import jep

class FieldDoc(jep.PyJObject): ...

class Tag(jep.PyJObject): ...

class ConstructorDoc(jep.PyJObject): ...

class MethodDoc(jep.PyJObject): ...

class Type(jep.PyJObject): ...

class DocErrorReporter(jep.PyJObject): ...

class Doc(jep.PyJObject): ...

class AnnotationTypeDoc(jep.PyJObject): ...

class WildcardType(jep.PyJObject): ...

class MemberDoc(jep.PyJObject): ...

class ThrowsTag(jep.PyJObject): ...

class TypeVariable(jep.PyJObject): ...

class SerialFieldTag(jep.PyJObject): ...

class PackageDoc(jep.PyJObject): ...

class AnnotationTypeElementDoc(jep.PyJObject): ...

class ClassDoc(jep.PyJObject): ...

class LanguageVersion(jep.PyJObject): ...

class ExecutableMemberDoc(jep.PyJObject): ...

class ProgramElementDoc(jep.PyJObject): ...

class Doclet(jep.PyJObject): ...

class ParameterizedType(jep.PyJObject): ...

class SourcePosition(jep.PyJObject): ...

class AnnotatedType(jep.PyJObject): ...

class AnnotationValue(jep.PyJObject): ...

class RootDoc(jep.PyJObject): ...

class Parameter(jep.PyJObject): ...

class AnnotationDesc(jep.PyJObject): ...

class SeeTag(jep.PyJObject): ...

class ParamTag(jep.PyJObject): ...

