import jep

class FieldDoc(jep._PyJObject): ...

class Tag(jep._PyJObject): ...

class ConstructorDoc(jep._PyJObject): ...

class MethodDoc(jep._PyJObject): ...

class Type(jep._PyJObject): ...

class DocErrorReporter(jep._PyJObject): ...

class Doc(jep._PyJObject): ...

class AnnotationTypeDoc(jep._PyJObject): ...

class WildcardType(jep._PyJObject): ...

class MemberDoc(jep._PyJObject): ...

class ThrowsTag(jep._PyJObject): ...

class TypeVariable(jep._PyJObject): ...

class SerialFieldTag(jep._PyJObject): ...

class PackageDoc(jep._PyJObject): ...

class AnnotationTypeElementDoc(jep._PyJObject): ...

class ClassDoc(jep._PyJObject): ...

class LanguageVersion(jep._PyJObject): ...

class ExecutableMemberDoc(jep._PyJObject): ...

class ProgramElementDoc(jep._PyJObject): ...

class Doclet(jep._PyJObject): ...

class ParameterizedType(jep._PyJObject): ...

class SourcePosition(jep._PyJObject): ...

class AnnotatedType(jep._PyJObject): ...

class AnnotationValue(jep._PyJObject): ...

class RootDoc(jep._PyJObject): ...

class Parameter(jep._PyJObject): ...

class AnnotationDesc(jep._PyJObject): ...

class SeeTag(jep._PyJObject): ...

class ParamTag(jep._PyJObject): ...

