import jep

class GcInfo(jep.PyJObject): ...

class VMOption(jep.PyJObject): ...

class GarbageCollectorMXBean(jep.PyJObject): ...

class OperatingSystemMXBean(jep.PyJObject): ...

class UnixOperatingSystemMXBean(jep.PyJObject): ...

class HotSpotDiagnosticMXBean(jep.PyJObject): ...

class ThreadMXBean(jep.PyJObject): ...

class DiagnosticCommandMBean(jep.PyJObject): ...

class GarbageCollectionNotificationInfo(jep.PyJObject): ...

