# pyright: reportPrivateUsage = none

import jep

class GarbageCollectorMXBean[**Ts](jep._PyJObject): ...

class OperatingSystemMXBean[**Ts](jep._PyJObject): ...

class VMOption[**Ts](jep._PyJObject): ...

class GcInfo[**Ts](jep._PyJObject): ...

class UnixOperatingSystemMXBean[**Ts](jep._PyJObject): ...

class HotSpotDiagnosticMXBean[**Ts](jep._PyJObject): ...

class DiagnosticCommandMBean[**Ts](jep._PyJObject): ...

class ThreadMXBean[**Ts](jep._PyJObject): ...

class GarbageCollectionNotificationInfo[**Ts](jep._PyJObject): ...

