import jep

class GcInfo(jep._PyJObject): ...

class VMOption(jep._PyJObject): ...

class GarbageCollectorMXBean(jep._PyJObject): ...

class OperatingSystemMXBean(jep._PyJObject): ...

class UnixOperatingSystemMXBean(jep._PyJObject): ...

class HotSpotDiagnosticMXBean(jep._PyJObject): ...

class ThreadMXBean(jep._PyJObject): ...

class DiagnosticCommandMBean(jep._PyJObject): ...

class GarbageCollectionNotificationInfo(jep._PyJObject): ...

