# pyright: reportPrivateUsage = none

import jep

class AttributedCharacterIterator[**Ts](jep._PyJObject): ...

class SimpleDateFormat[**Ts](jep._PyJObject): ...

class DateFormatSymbols[**Ts](jep._PyJObject): ...

class ChoiceFormat[**Ts](jep._PyJObject): ...

class CharacterIterator[**Ts](jep._PyJObject): ...

class AttributedString[**Ts](jep._PyJObject): ...

class BreakIterator[**Ts](jep._PyJObject): ...

class RuleBasedCollator[**Ts](jep._PyJObject): ...

class Collator[**Ts](jep._PyJObject): ...

class Format[**Ts](jep._PyJObject): ...

class DecimalFormat[**Ts](jep._PyJObject): ...

class Annotation[**Ts](jep._PyJObject): ...

class Normalizer[**Ts](jep._PyJObject): ...

class CollationKey[**Ts](jep._PyJObject): ...

class MessageFormat[**Ts](jep._PyJObject): ...

class DateFormat[**Ts](jep._PyJObject): ...

class CollationElementIterator[**Ts](jep._PyJObject): ...

class DecimalFormatSymbols[**Ts](jep._PyJObject): ...

class FieldPosition[**Ts](jep._PyJObject): ...

class ParseException[**Ts](jep._PyJObject): ...

class Bidi[**Ts](jep._PyJObject): ...

class StringCharacterIterator[**Ts](jep._PyJObject): ...

class NumberFormat[**Ts](jep._PyJObject): ...

class ParsePosition[**Ts](jep._PyJObject): ...

