# pyright: reportPrivateUsage = none

import jep

class BreakIteratorProvider[**Ts](jep._PyJObject): ...

class DecimalFormatSymbolsProvider[**Ts](jep._PyJObject): ...

class DateFormatProvider[**Ts](jep._PyJObject): ...

class NumberFormatProvider[**Ts](jep._PyJObject): ...

class CollatorProvider[**Ts](jep._PyJObject): ...

