import jep

class BreakIteratorProvider(jep.PyJObject): ...

class DateFormatSymbolsProvider(jep.PyJObject): ...

class CollatorProvider(jep.PyJObject): ...

class NumberFormatProvider(jep.PyJObject): ...

class DecimalFormatSymbolsProvider(jep.PyJObject): ...

