import jep

class BreakIteratorProvider(jep._PyJObject): ...

class DateFormatSymbolsProvider(jep._PyJObject): ...

class CollatorProvider(jep._PyJObject): ...

class NumberFormatProvider(jep._PyJObject): ...

class DecimalFormatSymbolsProvider(jep._PyJObject): ...

