import jep

class ParameterModeHelper(jep.PyJObject): ...

class VM_ABSTRACT(jep.PyJObject): ...

class ServiceInformation(jep.PyJObject): ...

class WCharSeqHelper(jep.PyJObject): ...

class CharSeqHolder(jep.PyJObject): ...

class WStringSeqHolder(jep.PyJObject): ...

class PolicyErrorCodeHelper(jep.PyJObject): ...

class UShortSeqHelper(jep.PyJObject): ...

class ParameterMode(jep.PyJObject): ...

class FixedHolder(jep.PyJObject): ...

class UnionMemberHelper(jep.PyJObject): ...

class CTX_RESTRICT_SCOPE(jep.PyJObject): ...

class TCKind(jep.PyJObject): ...

class BAD_POLICY_VALUE(jep.PyJObject): ...

class PERSIST_STORE(jep.PyJObject): ...

class LongSeqHelper(jep.PyJObject): ...

class ARG_IN(jep.PyJObject): ...

class IDLTypeHelper(jep.PyJObject): ...

class UnknownUserExceptionHelper(jep.PyJObject): ...

class ContextList(jep.PyJObject): ...

class PolicyOperations(jep.PyJObject): ...

class ValueMember(jep.PyJObject): ...

class PRIVATE_MEMBER(jep.PyJObject): ...

class FieldNameHelper(jep.PyJObject): ...

class VisibilityHelper(jep.PyJObject): ...

class NameValuePairHelper(jep.PyJObject): ...

class DataOutputStream(jep.PyJObject): ...

class LongLongSeqHelper(jep.PyJObject): ...

class FloatSeqHelper(jep.PyJObject): ...

class DoubleSeqHolder(jep.PyJObject): ...

class DomainManager(jep.PyJObject): ...

class ObjectHelper(jep.PyJObject): ...

class OMGVMCID(jep.PyJObject): ...

class WrongTransaction(jep.PyJObject): ...

class ARG_INOUT(jep.PyJObject): ...

class AnySeqHelper(jep.PyJObject): ...

class ACTIVITY_COMPLETED(jep.PyJObject): ...

class Policy(jep.PyJObject): ...

class PolicyErrorHelper(jep.PyJObject): ...

class VM_CUSTOM(jep.PyJObject): ...

class BAD_POLICY(jep.PyJObject): ...

class CODESET_INCOMPATIBLE(jep.PyJObject): ...

class StringHolder(jep.PyJObject): ...

class ValueBaseHelper(jep.PyJObject): ...

class INTERNAL(jep.PyJObject): ...

class TypeCodeHolder(jep.PyJObject): ...

class SetOverrideType(jep.PyJObject): ...

class NO_IMPLEMENT(jep.PyJObject): ...

class INVALID_TRANSACTION(jep.PyJObject): ...

class AnySeqHolder(jep.PyJObject): ...

class ACTIVITY_REQUIRED(jep.PyJObject): ...

class _IDLTypeStub(jep.PyJObject): ...

class BAD_POLICY_TYPE(jep.PyJObject): ...

class Object(jep.PyJObject): ...

class TIMEOUT(jep.PyJObject): ...

class StringValueHelper(jep.PyJObject): ...

class TRANSACTION_REQUIRED(jep.PyJObject): ...

class DomainManagerOperations(jep.PyJObject): ...

class DoubleSeqHelper(jep.PyJObject): ...

class IDLType(jep.PyJObject): ...

class Any(jep.PyJObject): ...

class ServerRequest(jep.PyJObject): ...

class DynUnion(jep.PyJObject): ...

class NVList(jep.PyJObject): ...

class UNSUPPORTED_POLICY(jep.PyJObject): ...

class DynArray(jep.PyJObject): ...

class UnionMember(jep.PyJObject): ...

class ByteHolder(jep.PyJObject): ...

class PolicyHelper(jep.PyJObject): ...

class UShortSeqHolder(jep.PyJObject): ...

class ULongSeqHelper(jep.PyJObject): ...

class WCharSeqHolder(jep.PyJObject): ...

class INTF_REPOS(jep.PyJObject): ...

class IRObject(jep.PyJObject): ...

class TRANSACTION_UNAVAILABLE(jep.PyJObject): ...

class ARG_OUT(jep.PyJObject): ...

class PrincipalHolder(jep.PyJObject): ...

class PolicyErrorHolder(jep.PyJObject): ...

class Principal(jep.PyJObject): ...

class RepositoryIdHelper(jep.PyJObject): ...

class PolicyTypeHelper(jep.PyJObject): ...

class BooleanHolder(jep.PyJObject): ...

class REBIND(jep.PyJObject): ...

class PolicyListHolder(jep.PyJObject): ...

class INITIALIZE(jep.PyJObject): ...

class TRANSIENT(jep.PyJObject): ...

class IMP_LIMIT(jep.PyJObject): ...

class CharHolder(jep.PyJObject): ...

class IRObjectOperations(jep.PyJObject): ...

class ULongLongSeqHelper(jep.PyJObject): ...

class ShortHolder(jep.PyJObject): ...

class ParameterModeHolder(jep.PyJObject): ...

class VersionSpecHelper(jep.PyJObject): ...

class LongLongSeqHolder(jep.PyJObject): ...

class CharSeqHelper(jep.PyJObject): ...

class TRANSACTION_MODE(jep.PyJObject): ...

class DynStruct(jep.PyJObject): ...

class NO_RESOURCES(jep.PyJObject): ...

class INV_IDENT(jep.PyJObject): ...

class WStringSeqHelper(jep.PyJObject): ...

class NO_RESPONSE(jep.PyJObject): ...

class ShortSeqHolder(jep.PyJObject): ...

class DATA_CONVERSION(jep.PyJObject): ...

class INVALID_ACTIVITY(jep.PyJObject): ...

class FloatSeqHolder(jep.PyJObject): ...

class ObjectHolder(jep.PyJObject): ...

class SystemException(jep.PyJObject): ...

class LongSeqHolder(jep.PyJObject): ...

class VM_NONE(jep.PyJObject): ...

class _PolicyStub(jep.PyJObject): ...

class ORB(jep.PyJObject): ...

class BAD_INV_ORDER(jep.PyJObject): ...

class INV_POLICY(jep.PyJObject): ...

class Request(jep.PyJObject): ...

class ExceptionList(jep.PyJObject): ...

class OctetSeqHolder(jep.PyJObject): ...

class VM_TRUNCATABLE(jep.PyJObject): ...

class Context(jep.PyJObject): ...

class INV_OBJREF(jep.PyJObject): ...

class DefinitionKind(jep.PyJObject): ...

class BAD_CONTEXT(jep.PyJObject): ...

class BAD_PARAM(jep.PyJObject): ...

class CompletionStatusHelper(jep.PyJObject): ...

class ValueMemberHelper(jep.PyJObject): ...

class DefinitionKindHelper(jep.PyJObject): ...

class BAD_QOS(jep.PyJObject): ...

class NamedValue(jep.PyJObject): ...

class Environment(jep.PyJObject): ...

class LocalObject(jep.PyJObject): ...

class DynValue(jep.PyJObject): ...

class BooleanSeqHolder(jep.PyJObject): ...

class BooleanSeqHelper(jep.PyJObject): ...

class TypeCode(jep.PyJObject): ...

class PolicyListHelper(jep.PyJObject): ...

class COMM_FAILURE(jep.PyJObject): ...

class UserException(jep.PyJObject): ...

class INV_FLAG(jep.PyJObject): ...

class StringSeqHelper(jep.PyJObject): ...

class ULongSeqHolder(jep.PyJObject): ...

class IDLTypeOperations(jep.PyJObject): ...

class DynEnum(jep.PyJObject): ...

class ServiceDetail(jep.PyJObject): ...

class UNKNOWN(jep.PyJObject): ...

class CurrentHolder(jep.PyJObject): ...

class IdentifierHelper(jep.PyJObject): ...

class DynamicImplementation(jep.PyJObject): ...

class PolicyHolder(jep.PyJObject): ...

class CompletionStatus(jep.PyJObject): ...

class ShortSeqHelper(jep.PyJObject): ...

class UnknownUserException(jep.PyJObject): ...

class PolicyError(jep.PyJObject): ...

class StringSeqHolder(jep.PyJObject): ...

class CurrentHelper(jep.PyJObject): ...

class ServiceDetailHelper(jep.PyJObject): ...

class WStringValueHelper(jep.PyJObject): ...

class Bounds(jep.PyJObject): ...

class ServiceInformationHelper(jep.PyJObject): ...

class NO_PERMISSION(jep.PyJObject): ...

class PUBLIC_MEMBER(jep.PyJObject): ...

class CustomMarshal(jep.PyJObject): ...

class NameValuePair(jep.PyJObject): ...

class BoundsHelper(jep.PyJObject): ...

class DoubleHolder(jep.PyJObject): ...

class Current(jep.PyJObject): ...

class DataInputStream(jep.PyJObject): ...

class FREE_MEM(jep.PyJObject): ...

class SetOverrideTypeHelper(jep.PyJObject): ...

class DynFixed(jep.PyJObject): ...

class LongHolder(jep.PyJObject): ...

class StructMemberHelper(jep.PyJObject): ...

class AnyHolder(jep.PyJObject): ...

class UnknownUserExceptionHolder(jep.PyJObject): ...

class WrongTransactionHolder(jep.PyJObject): ...

class OBJ_ADAPTER(jep.PyJObject): ...

class BAD_OPERATION(jep.PyJObject): ...

class DynSequence(jep.PyJObject): ...

class BAD_TYPECODE(jep.PyJObject): ...

class NO_MEMORY(jep.PyJObject): ...

class CurrentOperations(jep.PyJObject): ...

class UNSUPPORTED_POLICY_VALUE(jep.PyJObject): ...

class ValueBaseHolder(jep.PyJObject): ...

class FloatHolder(jep.PyJObject): ...

class MARSHAL(jep.PyJObject): ...

class ServiceInformationHolder(jep.PyJObject): ...

class OctetSeqHelper(jep.PyJObject): ...

class WrongTransactionHelper(jep.PyJObject): ...

class TRANSACTION_ROLLEDBACK(jep.PyJObject): ...

class OBJECT_NOT_EXIST(jep.PyJObject): ...

class StructMember(jep.PyJObject): ...

class IntHolder(jep.PyJObject): ...

class ULongLongSeqHolder(jep.PyJObject): ...

class DynAny(jep.PyJObject): ...

