# pyright: reportPrivateUsage = none

import jep

class INV_POLICY[**Ts](jep._PyJObject): ...

class LongLongSeqHelper[**Ts](jep._PyJObject): ...

class FloatSeqHolder[**Ts](jep._PyJObject): ...

class WrongTransactionHolder[**Ts](jep._PyJObject): ...

class IRObjectOperations[**Ts](jep._PyJObject): ...

class TRANSACTION_REQUIRED[**Ts](jep._PyJObject): ...

class StructMemberHelper[**Ts](jep._PyJObject): ...

class INITIALIZE[**Ts](jep._PyJObject): ...

class UnknownUserException[**Ts](jep._PyJObject): ...

class ACTIVITY_COMPLETED[**Ts](jep._PyJObject): ...

class INTERNAL[**Ts](jep._PyJObject): ...

class TRANSACTION_ROLLEDBACK[**Ts](jep._PyJObject): ...

class IDLTypeOperations[**Ts](jep._PyJObject): ...

class PrincipalHolder[**Ts](jep._PyJObject): ...

class LongSeqHolder[**Ts](jep._PyJObject): ...

class ServiceInformation[**Ts](jep._PyJObject): ...

class DATA_CONVERSION[**Ts](jep._PyJObject): ...

class INV_OBJREF[**Ts](jep._PyJObject): ...

class FREE_MEM[**Ts](jep._PyJObject): ...

class DynSequence[**Ts](jep._PyJObject): ...

class INVALID_TRANSACTION[**Ts](jep._PyJObject): ...

class UnknownUserExceptionHolder[**Ts](jep._PyJObject): ...

class ValueBaseHelper[**Ts](jep._PyJObject): ...

class WStringSeqHolder[**Ts](jep._PyJObject): ...

class FieldNameHelper[**Ts](jep._PyJObject): ...

class BAD_QOS[**Ts](jep._PyJObject): ...

class ORB[**Ts](jep._PyJObject): ...

class TRANSACTION_MODE[**Ts](jep._PyJObject): ...

class TCKind[**Ts](jep._PyJObject): ...

class DoubleSeqHolder[**Ts](jep._PyJObject): ...

class NO_MEMORY[**Ts](jep._PyJObject): ...

class CharHolder[**Ts](jep._PyJObject): ...

class ParameterModeHolder[**Ts](jep._PyJObject): ...

class DomainManagerOperations[**Ts](jep._PyJObject): ...

class NO_RESPONSE[**Ts](jep._PyJObject): ...

class DynamicImplementation[**Ts](jep._PyJObject): ...

class PolicyHolder[**Ts](jep._PyJObject): ...

class TRANSACTION_UNAVAILABLE[**Ts](jep._PyJObject): ...

class OMGVMCID[**Ts](jep._PyJObject): ...

class UShortSeqHelper[**Ts](jep._PyJObject): ...

class BAD_TYPECODE[**Ts](jep._PyJObject): ...

class RepositoryIdHelper[**Ts](jep._PyJObject): ...

class CurrentHolder[**Ts](jep._PyJObject): ...

class ValueMember[**Ts](jep._PyJObject): ...

class SetOverrideTypeHelper[**Ts](jep._PyJObject): ...

class IRObject[**Ts](jep._PyJObject): ...

class CompletionStatusHelper[**Ts](jep._PyJObject): ...

class PolicyOperations[**Ts](jep._PyJObject): ...

class ParameterMode[**Ts](jep._PyJObject): ...

class CharSeqHolder[**Ts](jep._PyJObject): ...

class FloatHolder[**Ts](jep._PyJObject): ...

class IdentifierHelper[**Ts](jep._PyJObject): ...

class UnknownUserExceptionHelper[**Ts](jep._PyJObject): ...

class WStringSeqHelper[**Ts](jep._PyJObject): ...

class LocalObject[**Ts](jep._PyJObject): ...

class StringValueHelper[**Ts](jep._PyJObject): ...

class _IDLTypeStub[**Ts](jep._PyJObject): ...

class ByteHolder[**Ts](jep._PyJObject): ...

class BAD_POLICY[**Ts](jep._PyJObject): ...

class PolicyErrorHelper[**Ts](jep._PyJObject): ...

class TIMEOUT[**Ts](jep._PyJObject): ...

class NamedValue[**Ts](jep._PyJObject): ...

class UNSUPPORTED_POLICY[**Ts](jep._PyJObject): ...

class DoubleHolder[**Ts](jep._PyJObject): ...

class IMP_LIMIT[**Ts](jep._PyJObject): ...

class DynValue[**Ts](jep._PyJObject): ...

class LongSeqHelper[**Ts](jep._PyJObject): ...

class DynUnion[**Ts](jep._PyJObject): ...

class FixedHolder[**Ts](jep._PyJObject): ...

class DefinitionKindHelper[**Ts](jep._PyJObject): ...

class CTX_RESTRICT_SCOPE[**Ts](jep._PyJObject): ...

class PolicyTypeHelper[**Ts](jep._PyJObject): ...

class AnyHolder[**Ts](jep._PyJObject): ...

class VM_ABSTRACT[**Ts](jep._PyJObject): ...

class PolicyErrorCodeHelper[**Ts](jep._PyJObject): ...

class WrongTransactionHelper[**Ts](jep._PyJObject): ...

class UserException[**Ts](jep._PyJObject): ...

class DefinitionKind[**Ts](jep._PyJObject): ...

class DynFixed[**Ts](jep._PyJObject): ...

class MARSHAL[**Ts](jep._PyJObject): ...

class PRIVATE_MEMBER[**Ts](jep._PyJObject): ...

class ShortSeqHelper[**Ts](jep._PyJObject): ...

class SystemException[**Ts](jep._PyJObject): ...

class OBJECT_NOT_EXIST[**Ts](jep._PyJObject): ...

class SetOverrideType[**Ts](jep._PyJObject): ...

class StructMember[**Ts](jep._PyJObject): ...

class OctetSeqHelper[**Ts](jep._PyJObject): ...

class FloatSeqHelper[**Ts](jep._PyJObject): ...

class ServerRequest[**Ts](jep._PyJObject): ...

class VisibilityHelper[**Ts](jep._PyJObject): ...

class COMM_FAILURE[**Ts](jep._PyJObject): ...

class NVList[**Ts](jep._PyJObject): ...

class IDLType[**Ts](jep._PyJObject): ...

class ShortSeqHolder[**Ts](jep._PyJObject): ...

class PERSIST_STORE[**Ts](jep._PyJObject): ...

class INV_FLAG[**Ts](jep._PyJObject): ...

class DynArray[**Ts](jep._PyJObject): ...

class ObjectHolder[**Ts](jep._PyJObject): ...

class CharSeqHelper[**Ts](jep._PyJObject): ...

class _PolicyStub[**Ts](jep._PyJObject): ...

class ValueBaseHolder[**Ts](jep._PyJObject): ...

class NO_IMPLEMENT[**Ts](jep._PyJObject): ...

class NO_PERMISSION[**Ts](jep._PyJObject): ...

class PolicyListHelper[**Ts](jep._PyJObject): ...

class CurrentHelper[**Ts](jep._PyJObject): ...

class VM_TRUNCATABLE[**Ts](jep._PyJObject): ...

class OctetSeqHolder[**Ts](jep._PyJObject): ...

class AnySeqHolder[**Ts](jep._PyJObject): ...

class ARG_OUT[**Ts](jep._PyJObject): ...

class Object[**Ts](jep._PyJObject): ...

class Context[**Ts](jep._PyJObject): ...

class LongLongSeqHolder[**Ts](jep._PyJObject): ...

class BAD_INV_ORDER[**Ts](jep._PyJObject): ...

class ShortHolder[**Ts](jep._PyJObject): ...

class NameValuePairHelper[**Ts](jep._PyJObject): ...

class ValueMemberHelper[**Ts](jep._PyJObject): ...

class REBIND[**Ts](jep._PyJObject): ...

class BooleanSeqHolder[**Ts](jep._PyJObject): ...

class CompletionStatus[**Ts](jep._PyJObject): ...

class ULongSeqHolder[**Ts](jep._PyJObject): ...

class INTF_REPOS[**Ts](jep._PyJObject): ...

class ParameterModeHelper[**Ts](jep._PyJObject): ...

class ServiceDetailHelper[**Ts](jep._PyJObject): ...

class Principal[**Ts](jep._PyJObject): ...

class WCharSeqHelper[**Ts](jep._PyJObject): ...

class ARG_INOUT[**Ts](jep._PyJObject): ...

class StringSeqHelper[**Ts](jep._PyJObject): ...

class NameValuePair[**Ts](jep._PyJObject): ...

class UNSUPPORTED_POLICY_VALUE[**Ts](jep._PyJObject): ...

class Bounds[**Ts](jep._PyJObject): ...

class Current[**Ts](jep._PyJObject): ...

class PUBLIC_MEMBER[**Ts](jep._PyJObject): ...

class CurrentOperations[**Ts](jep._PyJObject): ...

class INVALID_ACTIVITY[**Ts](jep._PyJObject): ...

class CustomMarshal[**Ts](jep._PyJObject): ...

class DataInputStream[**Ts](jep._PyJObject): ...

class IDLTypeHelper[**Ts](jep._PyJObject): ...

class TypeCode[**Ts](jep._PyJObject): ...

class ULongSeqHelper[**Ts](jep._PyJObject): ...

class DynAny[**Ts](jep._PyJObject): ...

class PolicyListHolder[**Ts](jep._PyJObject): ...

class Any[**Ts](jep._PyJObject): ...

class VM_CUSTOM[**Ts](jep._PyJObject): ...

class NO_RESOURCES[**Ts](jep._PyJObject): ...

class WStringValueHelper[**Ts](jep._PyJObject): ...

class ServiceInformationHelper[**Ts](jep._PyJObject): ...

class OBJ_ADAPTER[**Ts](jep._PyJObject): ...

class BAD_POLICY_TYPE[**Ts](jep._PyJObject): ...

class TRANSIENT[**Ts](jep._PyJObject): ...

class ObjectHelper[**Ts](jep._PyJObject): ...

class ULongLongSeqHolder[**Ts](jep._PyJObject): ...

class CODESET_INCOMPATIBLE[**Ts](jep._PyJObject): ...

class Environment[**Ts](jep._PyJObject): ...

class ULongLongSeqHelper[**Ts](jep._PyJObject): ...

class UnionMember[**Ts](jep._PyJObject): ...

class ContextList[**Ts](jep._PyJObject): ...

class PolicyHelper[**Ts](jep._PyJObject): ...

class VM_NONE[**Ts](jep._PyJObject): ...

class DomainManager[**Ts](jep._PyJObject): ...

class ACTIVITY_REQUIRED[**Ts](jep._PyJObject): ...

class DynEnum[**Ts](jep._PyJObject): ...

class UnionMemberHelper[**Ts](jep._PyJObject): ...

class VersionSpecHelper[**Ts](jep._PyJObject): ...

class DataOutputStream[**Ts](jep._PyJObject): ...

class BAD_PARAM[**Ts](jep._PyJObject): ...

class PolicyErrorHolder[**Ts](jep._PyJObject): ...

class BooleanHolder[**Ts](jep._PyJObject): ...

class ExceptionList[**Ts](jep._PyJObject): ...

class BooleanSeqHelper[**Ts](jep._PyJObject): ...

class BAD_POLICY_VALUE[**Ts](jep._PyJObject): ...

class PolicyError[**Ts](jep._PyJObject): ...

class UNKNOWN[**Ts](jep._PyJObject): ...

class ServiceInformationHolder[**Ts](jep._PyJObject): ...

class BAD_OPERATION[**Ts](jep._PyJObject): ...

class WrongTransaction[**Ts](jep._PyJObject): ...

class ARG_IN[**Ts](jep._PyJObject): ...

class BAD_CONTEXT[**Ts](jep._PyJObject): ...

class StringHolder[**Ts](jep._PyJObject): ...

class DynStruct[**Ts](jep._PyJObject): ...

class INV_IDENT[**Ts](jep._PyJObject): ...

class Request[**Ts](jep._PyJObject): ...

class BoundsHelper[**Ts](jep._PyJObject): ...

class TypeCodeHolder[**Ts](jep._PyJObject): ...

class IntHolder[**Ts](jep._PyJObject): ...

class DoubleSeqHelper[**Ts](jep._PyJObject): ...

class LongHolder[**Ts](jep._PyJObject): ...

class UShortSeqHolder[**Ts](jep._PyJObject): ...

class WCharSeqHolder[**Ts](jep._PyJObject): ...

class ServiceDetail[**Ts](jep._PyJObject): ...

class StringSeqHolder[**Ts](jep._PyJObject): ...

class Policy[**Ts](jep._PyJObject): ...

class AnySeqHelper[**Ts](jep._PyJObject): ...

