import jep

class ParameterModeHelper(jep._PyJObject): ...

class VM_ABSTRACT(jep._PyJObject): ...

class ServiceInformation(jep._PyJObject): ...

class WCharSeqHelper(jep._PyJObject): ...

class CharSeqHolder(jep._PyJObject): ...

class WStringSeqHolder(jep._PyJObject): ...

class PolicyErrorCodeHelper(jep._PyJObject): ...

class UShortSeqHelper(jep._PyJObject): ...

class ParameterMode(jep._PyJObject): ...

class FixedHolder(jep._PyJObject): ...

class UnionMemberHelper(jep._PyJObject): ...

class CTX_RESTRICT_SCOPE(jep._PyJObject): ...

class TCKind(jep._PyJObject): ...

class BAD_POLICY_VALUE(jep._PyJObject): ...

class PERSIST_STORE(jep._PyJObject): ...

class LongSeqHelper(jep._PyJObject): ...

class ARG_IN(jep._PyJObject): ...

class IDLTypeHelper(jep._PyJObject): ...

class UnknownUserExceptionHelper(jep._PyJObject): ...

class ContextList(jep._PyJObject): ...

class PolicyOperations(jep._PyJObject): ...

class ValueMember(jep._PyJObject): ...

class PRIVATE_MEMBER(jep._PyJObject): ...

class FieldNameHelper(jep._PyJObject): ...

class VisibilityHelper(jep._PyJObject): ...

class NameValuePairHelper(jep._PyJObject): ...

class DataOutputStream(jep._PyJObject): ...

class LongLongSeqHelper(jep._PyJObject): ...

class FloatSeqHelper(jep._PyJObject): ...

class DoubleSeqHolder(jep._PyJObject): ...

class DomainManager(jep._PyJObject): ...

class ObjectHelper(jep._PyJObject): ...

class OMGVMCID(jep._PyJObject): ...

class WrongTransaction(jep._PyJObject): ...

class ARG_INOUT(jep._PyJObject): ...

class AnySeqHelper(jep._PyJObject): ...

class ACTIVITY_COMPLETED(jep._PyJObject): ...

class Policy(jep._PyJObject): ...

class PolicyErrorHelper(jep._PyJObject): ...

class VM_CUSTOM(jep._PyJObject): ...

class BAD_POLICY(jep._PyJObject): ...

class CODESET_INCOMPATIBLE(jep._PyJObject): ...

class StringHolder(jep._PyJObject): ...

class ValueBaseHelper(jep._PyJObject): ...

class INTERNAL(jep._PyJObject): ...

class TypeCodeHolder(jep._PyJObject): ...

class SetOverrideType(jep._PyJObject): ...

class NO_IMPLEMENT(jep._PyJObject): ...

class INVALID_TRANSACTION(jep._PyJObject): ...

class AnySeqHolder(jep._PyJObject): ...

class ACTIVITY_REQUIRED(jep._PyJObject): ...

class _IDLTypeStub(jep._PyJObject): ...

class BAD_POLICY_TYPE(jep._PyJObject): ...

class Object(jep._PyJObject): ...

class TIMEOUT(jep._PyJObject): ...

class StringValueHelper(jep._PyJObject): ...

class TRANSACTION_REQUIRED(jep._PyJObject): ...

class DomainManagerOperations(jep._PyJObject): ...

class DoubleSeqHelper(jep._PyJObject): ...

class IDLType(jep._PyJObject): ...

class Any(jep._PyJObject): ...

class ServerRequest(jep._PyJObject): ...

class DynUnion(jep._PyJObject): ...

class NVList(jep._PyJObject): ...

class UNSUPPORTED_POLICY(jep._PyJObject): ...

class DynArray(jep._PyJObject): ...

class UnionMember(jep._PyJObject): ...

class ByteHolder(jep._PyJObject): ...

class PolicyHelper(jep._PyJObject): ...

class UShortSeqHolder(jep._PyJObject): ...

class ULongSeqHelper(jep._PyJObject): ...

class WCharSeqHolder(jep._PyJObject): ...

class INTF_REPOS(jep._PyJObject): ...

class IRObject(jep._PyJObject): ...

class TRANSACTION_UNAVAILABLE(jep._PyJObject): ...

class ARG_OUT(jep._PyJObject): ...

class PrincipalHolder(jep._PyJObject): ...

class PolicyErrorHolder(jep._PyJObject): ...

class Principal(jep._PyJObject): ...

class RepositoryIdHelper(jep._PyJObject): ...

class PolicyTypeHelper(jep._PyJObject): ...

class BooleanHolder(jep._PyJObject): ...

class REBIND(jep._PyJObject): ...

class PolicyListHolder(jep._PyJObject): ...

class INITIALIZE(jep._PyJObject): ...

class TRANSIENT(jep._PyJObject): ...

class IMP_LIMIT(jep._PyJObject): ...

class CharHolder(jep._PyJObject): ...

class IRObjectOperations(jep._PyJObject): ...

class ULongLongSeqHelper(jep._PyJObject): ...

class ShortHolder(jep._PyJObject): ...

class ParameterModeHolder(jep._PyJObject): ...

class VersionSpecHelper(jep._PyJObject): ...

class LongLongSeqHolder(jep._PyJObject): ...

class CharSeqHelper(jep._PyJObject): ...

class TRANSACTION_MODE(jep._PyJObject): ...

class DynStruct(jep._PyJObject): ...

class NO_RESOURCES(jep._PyJObject): ...

class INV_IDENT(jep._PyJObject): ...

class WStringSeqHelper(jep._PyJObject): ...

class NO_RESPONSE(jep._PyJObject): ...

class ShortSeqHolder(jep._PyJObject): ...

class DATA_CONVERSION(jep._PyJObject): ...

class INVALID_ACTIVITY(jep._PyJObject): ...

class FloatSeqHolder(jep._PyJObject): ...

class ObjectHolder(jep._PyJObject): ...

class SystemException(jep._PyJObject): ...

class LongSeqHolder(jep._PyJObject): ...

class VM_NONE(jep._PyJObject): ...

class _PolicyStub(jep._PyJObject): ...

class ORB(jep._PyJObject): ...

class BAD_INV_ORDER(jep._PyJObject): ...

class INV_POLICY(jep._PyJObject): ...

class Request(jep._PyJObject): ...

class ExceptionList(jep._PyJObject): ...

class OctetSeqHolder(jep._PyJObject): ...

class VM_TRUNCATABLE(jep._PyJObject): ...

class Context(jep._PyJObject): ...

class INV_OBJREF(jep._PyJObject): ...

class DefinitionKind(jep._PyJObject): ...

class BAD_CONTEXT(jep._PyJObject): ...

class BAD_PARAM(jep._PyJObject): ...

class CompletionStatusHelper(jep._PyJObject): ...

class ValueMemberHelper(jep._PyJObject): ...

class DefinitionKindHelper(jep._PyJObject): ...

class BAD_QOS(jep._PyJObject): ...

class NamedValue(jep._PyJObject): ...

class Environment(jep._PyJObject): ...

class LocalObject(jep._PyJObject): ...

class DynValue(jep._PyJObject): ...

class BooleanSeqHolder(jep._PyJObject): ...

class BooleanSeqHelper(jep._PyJObject): ...

class TypeCode(jep._PyJObject): ...

class PolicyListHelper(jep._PyJObject): ...

class COMM_FAILURE(jep._PyJObject): ...

class UserException(jep._PyJObject): ...

class INV_FLAG(jep._PyJObject): ...

class StringSeqHelper(jep._PyJObject): ...

class ULongSeqHolder(jep._PyJObject): ...

class IDLTypeOperations(jep._PyJObject): ...

class DynEnum(jep._PyJObject): ...

class ServiceDetail(jep._PyJObject): ...

class UNKNOWN(jep._PyJObject): ...

class CurrentHolder(jep._PyJObject): ...

class IdentifierHelper(jep._PyJObject): ...

class DynamicImplementation(jep._PyJObject): ...

class PolicyHolder(jep._PyJObject): ...

class CompletionStatus(jep._PyJObject): ...

class ShortSeqHelper(jep._PyJObject): ...

class UnknownUserException(jep._PyJObject): ...

class PolicyError(jep._PyJObject): ...

class StringSeqHolder(jep._PyJObject): ...

class CurrentHelper(jep._PyJObject): ...

class ServiceDetailHelper(jep._PyJObject): ...

class WStringValueHelper(jep._PyJObject): ...

class Bounds(jep._PyJObject): ...

class ServiceInformationHelper(jep._PyJObject): ...

class NO_PERMISSION(jep._PyJObject): ...

class PUBLIC_MEMBER(jep._PyJObject): ...

class CustomMarshal(jep._PyJObject): ...

class NameValuePair(jep._PyJObject): ...

class BoundsHelper(jep._PyJObject): ...

class DoubleHolder(jep._PyJObject): ...

class Current(jep._PyJObject): ...

class DataInputStream(jep._PyJObject): ...

class FREE_MEM(jep._PyJObject): ...

class SetOverrideTypeHelper(jep._PyJObject): ...

class DynFixed(jep._PyJObject): ...

class LongHolder(jep._PyJObject): ...

class StructMemberHelper(jep._PyJObject): ...

class AnyHolder(jep._PyJObject): ...

class UnknownUserExceptionHolder(jep._PyJObject): ...

class WrongTransactionHolder(jep._PyJObject): ...

class OBJ_ADAPTER(jep._PyJObject): ...

class BAD_OPERATION(jep._PyJObject): ...

class DynSequence(jep._PyJObject): ...

class BAD_TYPECODE(jep._PyJObject): ...

class NO_MEMORY(jep._PyJObject): ...

class CurrentOperations(jep._PyJObject): ...

class UNSUPPORTED_POLICY_VALUE(jep._PyJObject): ...

class ValueBaseHolder(jep._PyJObject): ...

class FloatHolder(jep._PyJObject): ...

class MARSHAL(jep._PyJObject): ...

class ServiceInformationHolder(jep._PyJObject): ...

class OctetSeqHelper(jep._PyJObject): ...

class WrongTransactionHelper(jep._PyJObject): ...

class TRANSACTION_ROLLEDBACK(jep._PyJObject): ...

class OBJECT_NOT_EXIST(jep._PyJObject): ...

class StructMember(jep._PyJObject): ...

class IntHolder(jep._PyJObject): ...

class ULongLongSeqHolder(jep._PyJObject): ...

class DynAny(jep._PyJObject): ...

