# pyright: reportPrivateUsage = none

import jep

class InvalidValue[**Ts](jep._PyJObject): ...

class InvalidSeq[**Ts](jep._PyJObject): ...

class TypeMismatch[**Ts](jep._PyJObject): ...

class Invalid[**Ts](jep._PyJObject): ...

