import jep

class BoxedValueHelper(jep._PyJObject): ...

class ValueInputStream(jep._PyJObject): ...

class ValueBase(jep._PyJObject): ...

class ResponseHandler(jep._PyJObject): ...

class CustomValue(jep._PyJObject): ...

class ValueFactory(jep._PyJObject): ...

class UnknownException(jep._PyJObject): ...

class ApplicationException(jep._PyJObject): ...

class Streamable(jep._PyJObject): ...

class IndirectionException(jep._PyJObject): ...

class InputStream(jep._PyJObject): ...

class ObjectImpl(jep._PyJObject): ...

class IDLEntity(jep._PyJObject): ...

class InvokeHandler(jep._PyJObject): ...

class ServantObject(jep._PyJObject): ...

class StreamableValue(jep._PyJObject): ...

class RemarshalException(jep._PyJObject): ...

class OutputStream(jep._PyJObject): ...

class Delegate(jep._PyJObject): ...

