import jep

class BoxedValueHelper(jep.PyJObject): ...

class ValueInputStream(jep.PyJObject): ...

class ValueBase(jep.PyJObject): ...

class ResponseHandler(jep.PyJObject): ...

class CustomValue(jep.PyJObject): ...

class ValueFactory(jep.PyJObject): ...

class UnknownException(jep.PyJObject): ...

class ApplicationException(jep.PyJObject): ...

class Streamable(jep.PyJObject): ...

class IndirectionException(jep.PyJObject): ...

class InputStream(jep.PyJObject): ...

class ObjectImpl(jep.PyJObject): ...

class IDLEntity(jep.PyJObject): ...

class InvokeHandler(jep.PyJObject): ...

class ServantObject(jep.PyJObject): ...

class StreamableValue(jep.PyJObject): ...

class RemarshalException(jep.PyJObject): ...

class OutputStream(jep.PyJObject): ...

class Delegate(jep.PyJObject): ...

