# pyright: reportPrivateUsage = none

import jep

class IDLEntity[**Ts](jep._PyJObject): ...

class Streamable[**Ts](jep._PyJObject): ...

class ServantObject[**Ts](jep._PyJObject): ...

class ObjectImpl[**Ts](jep._PyJObject): ...

class InvokeHandler[**Ts](jep._PyJObject): ...

class OutputStream[**Ts](jep._PyJObject): ...

class IndirectionException[**Ts](jep._PyJObject): ...

class StreamableValue[**Ts](jep._PyJObject): ...

class ResponseHandler[**Ts](jep._PyJObject): ...

class RemarshalException[**Ts](jep._PyJObject): ...

class ValueInputStream[**Ts](jep._PyJObject): ...

class ApplicationException[**Ts](jep._PyJObject): ...

class BoxedValueHelper[**Ts](jep._PyJObject): ...

class ValueBase[**Ts](jep._PyJObject): ...

class Delegate[**Ts](jep._PyJObject): ...

class ValueFactory[**Ts](jep._PyJObject): ...

class ValueOutputStream[**Ts](jep._PyJObject): ...

class CustomValue[**Ts](jep._PyJObject): ...

class UnknownException[**Ts](jep._PyJObject): ...

