# pyright: reportPrivateUsage = none

import jep

class BadKind[**Ts](jep._PyJObject): ...

class Bounds[**Ts](jep._PyJObject): ...

class BadKindHelper[**Ts](jep._PyJObject): ...

class BoundsHelper[**Ts](jep._PyJObject): ...

