import jep

class ImageReader(jep._PyJObject): ...

class IIOException(jep._PyJObject): ...

class IIOParam(jep._PyJObject): ...

class ImageWriter(jep._PyJObject): ...

class ImageWriteParam(jep._PyJObject): ...

class ImageIO(jep._PyJObject): ...

class IIOImage(jep._PyJObject): ...

class ImageTypeSpecifier(jep._PyJObject): ...

class ImageReadParam(jep._PyJObject): ...

class ImageTranscoder(jep._PyJObject): ...

class IIOParamController(jep._PyJObject): ...

