# pyright: reportPrivateUsage = none

import jep

class ImageReadParam[**Ts](jep._PyJObject): ...

class IIOParamController[**Ts](jep._PyJObject): ...

class ImageIO[**Ts](jep._PyJObject): ...

class ImageWriter[**Ts](jep._PyJObject): ...

class IIOParam[**Ts](jep._PyJObject): ...

class ImageTranscoder[**Ts](jep._PyJObject): ...

class ImageReader[**Ts](jep._PyJObject): ...

class IIOImage[**Ts](jep._PyJObject): ...

class ImageWriteParam[**Ts](jep._PyJObject): ...

class ImageTypeSpecifier[**Ts](jep._PyJObject): ...

class IIOException[**Ts](jep._PyJObject): ...

