import jep

class ImageReader(jep.PyJObject): ...

class IIOException(jep.PyJObject): ...

class IIOParam(jep.PyJObject): ...

class ImageWriter(jep.PyJObject): ...

class ImageWriteParam(jep.PyJObject): ...

class ImageIO(jep.PyJObject): ...

class IIOImage(jep.PyJObject): ...

class ImageTypeSpecifier(jep.PyJObject): ...

class ImageReadParam(jep.PyJObject): ...

class ImageTranscoder(jep.PyJObject): ...

class IIOParamController(jep.PyJObject): ...

