# pyright: reportPrivateUsage = none

import jep

class IIOReadProgressListener[**Ts](jep._PyJObject): ...

class IIOWriteWarningListener[**Ts](jep._PyJObject): ...

class IIOReadUpdateListener[**Ts](jep._PyJObject): ...

class IIOReadWarningListener[**Ts](jep._PyJObject): ...

class IIOWriteProgressListener[**Ts](jep._PyJObject): ...

