import jep

class IIOReadUpdateListener(jep._PyJObject): ...

class IIOReadProgressListener(jep._PyJObject): ...

class IIOReadWarningListener(jep._PyJObject): ...

class IIOWriteProgressListener(jep._PyJObject): ...

class IIOWriteWarningListener(jep._PyJObject): ...

