import jep

class IIOReadUpdateListener(jep.PyJObject): ...

class IIOReadProgressListener(jep.PyJObject): ...

class IIOReadWarningListener(jep.PyJObject): ...

class IIOWriteProgressListener(jep.PyJObject): ...

class IIOWriteWarningListener(jep.PyJObject): ...

