# pyright: reportPrivateUsage = none

import jep

class IIOMetadataFormat[**Ts](jep._PyJObject): ...

class IIOMetadataController[**Ts](jep._PyJObject): ...

class IIOMetadataNode[**Ts](jep._PyJObject): ...

class IIOMetadata[**Ts](jep._PyJObject): ...

class IIOMetadataFormatImpl[**Ts](jep._PyJObject): ...

class IIOInvalidTreeException[**Ts](jep._PyJObject): ...

