import jep

class IIOMetadata(jep.PyJObject): ...

class IIOMetadataFormat(jep.PyJObject): ...

class IIOMetadataNode(jep.PyJObject): ...

class IIOMetadataFormatImpl(jep.PyJObject): ...

class IIOMetadataController(jep.PyJObject): ...

