import jep

class IIOMetadata(jep._PyJObject): ...

class IIOMetadataFormat(jep._PyJObject): ...

class IIOMetadataNode(jep._PyJObject): ...

class IIOMetadataFormatImpl(jep._PyJObject): ...

class IIOMetadataController(jep._PyJObject): ...

