import jep

class ImageTranscoderSpi(jep.PyJObject): ...

class ImageOutputStreamSpi(jep.PyJObject): ...

class ImageWriterSpi(jep.PyJObject): ...

class ServiceRegistry(jep.PyJObject): ...

class RegisterableService(jep.PyJObject): ...

class ImageInputStreamSpi(jep.PyJObject): ...

class ImageReaderSpi(jep.PyJObject): ...

class IIOServiceProvider(jep.PyJObject): ...

class ImageReaderWriterSpi(jep.PyJObject): ...

class IIORegistry(jep.PyJObject): ...

