import jep

class ImageTranscoderSpi(jep._PyJObject): ...

class ImageOutputStreamSpi(jep._PyJObject): ...

class ImageWriterSpi(jep._PyJObject): ...

class ServiceRegistry(jep._PyJObject): ...

class RegisterableService(jep._PyJObject): ...

class ImageInputStreamSpi(jep._PyJObject): ...

class ImageReaderSpi(jep._PyJObject): ...

class IIOServiceProvider(jep._PyJObject): ...

class ImageReaderWriterSpi(jep._PyJObject): ...

class IIORegistry(jep._PyJObject): ...

