# pyright: reportPrivateUsage = none

import jep

class ImageTranscoderSpi[**Ts](jep._PyJObject): ...

class RegisterableService[**Ts](jep._PyJObject): ...

class ImageWriterSpi[**Ts](jep._PyJObject): ...

class ImageReaderSpi[**Ts](jep._PyJObject): ...

class ServiceRegistry[**Ts](jep._PyJObject): ...

class IIORegistry[**Ts](jep._PyJObject): ...

class ImageOutputStreamSpi[**Ts](jep._PyJObject): ...

class ImageInputStreamSpi[**Ts](jep._PyJObject): ...

class ImageReaderWriterSpi[**Ts](jep._PyJObject): ...

