import jep

class MemoryCacheImageInputStream(jep.PyJObject): ...

class ImageInputStreamImpl(jep.PyJObject): ...

class IIOByteBuffer(jep.PyJObject): ...

class FileCacheImageInputStream(jep.PyJObject): ...

class FileImageInputStream(jep.PyJObject): ...

class MemoryCacheImageOutputStream(jep.PyJObject): ...

class ImageInputStream(jep.PyJObject): ...

class ImageOutputStreamImpl(jep.PyJObject): ...

class FileImageOutputStream(jep.PyJObject): ...

class ImageOutputStream(jep.PyJObject): ...

class FileCacheImageOutputStream(jep.PyJObject): ...

