import jep

class MemoryCacheImageInputStream(jep._PyJObject): ...

class ImageInputStreamImpl(jep._PyJObject): ...

class IIOByteBuffer(jep._PyJObject): ...

class FileCacheImageInputStream(jep._PyJObject): ...

class FileImageInputStream(jep._PyJObject): ...

class MemoryCacheImageOutputStream(jep._PyJObject): ...

class ImageInputStream(jep._PyJObject): ...

class ImageOutputStreamImpl(jep._PyJObject): ...

class FileImageOutputStream(jep._PyJObject): ...

class ImageOutputStream(jep._PyJObject): ...

class FileCacheImageOutputStream(jep._PyJObject): ...

