# pyright: reportPrivateUsage = none

import jep

class ImageInputStreamImpl[**Ts](jep._PyJObject): ...

class ImageOutputStreamImpl[**Ts](jep._PyJObject): ...

class FileCacheImageOutputStream[**Ts](jep._PyJObject): ...

class FileImageInputStream[**Ts](jep._PyJObject): ...

class ImageInputStream[**Ts](jep._PyJObject): ...

class IIOByteBuffer[**Ts](jep._PyJObject): ...

class MemoryCacheImageOutputStream[**Ts](jep._PyJObject): ...

class FileImageOutputStream[**Ts](jep._PyJObject): ...

class ImageOutputStream[**Ts](jep._PyJObject): ...

class FileCacheImageInputStream[**Ts](jep._PyJObject): ...

class MemoryCacheImageInputStream[**Ts](jep._PyJObject): ...

