import jep

class SealedObject(jep._PyJObject): ...

class MacSpi(jep._PyJObject): ...

class SecretKey(jep._PyJObject): ...

class Cipher(jep._PyJObject): ...

class SecretKeyFactory(jep._PyJObject): ...

class KeyGeneratorSpi(jep._PyJObject): ...

class EncryptedPrivateKeyInfo(jep._PyJObject): ...

class ExemptionMechanismException(jep._PyJObject): ...

class BadPaddingException(jep._PyJObject): ...

class CipherSpi(jep._PyJObject): ...

class ExemptionMechanismSpi(jep._PyJObject): ...

class KeyAgreementSpi(jep._PyJObject): ...

class KeyGenerator(jep._PyJObject): ...

class NullCipher(jep._PyJObject): ...

class Mac(jep._PyJObject): ...

class KeyAgreement(jep._PyJObject): ...

class AEADBadTagException(jep._PyJObject): ...

class ShortBufferException(jep._PyJObject): ...

class ExemptionMechanism(jep._PyJObject): ...

class SecretKeyFactorySpi(jep._PyJObject): ...

class NoSuchPaddingException(jep._PyJObject): ...

class CipherOutputStream(jep._PyJObject): ...

class CipherInputStream(jep._PyJObject): ...

class IllegalBlockSizeException(jep._PyJObject): ...

