# pyright: reportPrivateUsage = none

import jep

class KeyAgreement[**Ts](jep._PyJObject): ...

class IllegalBlockSizeException[**Ts](jep._PyJObject): ...

class ExemptionMechanismException[**Ts](jep._PyJObject): ...

class KeyGenerator[**Ts](jep._PyJObject): ...

class MacSpi[**Ts](jep._PyJObject): ...

class ExemptionMechanismSpi[**Ts](jep._PyJObject): ...

class KeyGeneratorSpi[**Ts](jep._PyJObject): ...

class SecretKeyFactorySpi[**Ts](jep._PyJObject): ...

class SecretKeyFactory[**Ts](jep._PyJObject): ...

class SecretKey[**Ts](jep._PyJObject): ...

class BadPaddingException[**Ts](jep._PyJObject): ...

class CipherOutputStream[**Ts](jep._PyJObject): ...

class NullCipher[**Ts](jep._PyJObject): ...

class SealedObject[**Ts](jep._PyJObject): ...

class AEADBadTagException[**Ts](jep._PyJObject): ...

class Cipher[**Ts](jep._PyJObject): ...

class CipherSpi[**Ts](jep._PyJObject): ...

class ExemptionMechanism[**Ts](jep._PyJObject): ...

class Mac[**Ts](jep._PyJObject): ...

class EncryptedPrivateKeyInfo[**Ts](jep._PyJObject): ...

class ShortBufferException[**Ts](jep._PyJObject): ...

class NoSuchPaddingException[**Ts](jep._PyJObject): ...

class KeyAgreementSpi[**Ts](jep._PyJObject): ...

class CipherInputStream[**Ts](jep._PyJObject): ...

