# pyright: reportPrivateUsage = none

import jep

class DHPrivateKey[**Ts](jep._PyJObject): ...

class DHKey[**Ts](jep._PyJObject): ...

class PBEKey[**Ts](jep._PyJObject): ...

class DHPublicKey[**Ts](jep._PyJObject): ...

