import jep

class PBEParameterSpec(jep.PyJObject): ...

class PSource(jep.PyJObject): ...

class GCMParameterSpec(jep.PyJObject): ...

class DHPrivateKeySpec(jep.PyJObject): ...

class OAEPParameterSpec(jep.PyJObject): ...

class DHParameterSpec(jep.PyJObject): ...

class DESedeKeySpec(jep.PyJObject): ...

class RC2ParameterSpec(jep.PyJObject): ...

class ChaCha20ParameterSpec(jep.PyJObject): ...

class IvParameterSpec(jep.PyJObject): ...

class DHGenParameterSpec(jep.PyJObject): ...

class PBEKeySpec(jep.PyJObject): ...

class SecretKeySpec(jep.PyJObject): ...

class DESKeySpec(jep.PyJObject): ...

class DHPublicKeySpec(jep.PyJObject): ...

