# pyright: reportPrivateUsage = none

import jep

class PBEParameterSpec[**Ts](jep._PyJObject): ...

class DHPublicKeySpec[**Ts](jep._PyJObject): ...

class PBEKeySpec[**Ts](jep._PyJObject): ...

class DESKeySpec[**Ts](jep._PyJObject): ...

class RC5ParameterSpec[**Ts](jep._PyJObject): ...

class DHPrivateKeySpec[**Ts](jep._PyJObject): ...

class DESedeKeySpec[**Ts](jep._PyJObject): ...

class OAEPParameterSpec[**Ts](jep._PyJObject): ...

class RC2ParameterSpec[**Ts](jep._PyJObject): ...

class PSource[**Ts](jep._PyJObject): ...

class DHGenParameterSpec[**Ts](jep._PyJObject): ...

class GCMParameterSpec[**Ts](jep._PyJObject): ...

class SecretKeySpec[**Ts](jep._PyJObject): ...

class ChaCha20ParameterSpec[**Ts](jep._PyJObject): ...

class IvParameterSpec[**Ts](jep._PyJObject): ...

