import jep

class PBEParameterSpec(jep._PyJObject): ...

class PSource(jep._PyJObject): ...

class GCMParameterSpec(jep._PyJObject): ...

class DHPrivateKeySpec(jep._PyJObject): ...

class OAEPParameterSpec(jep._PyJObject): ...

class DHParameterSpec(jep._PyJObject): ...

class DESedeKeySpec(jep._PyJObject): ...

class RC2ParameterSpec(jep._PyJObject): ...

class ChaCha20ParameterSpec(jep._PyJObject): ...

class IvParameterSpec(jep._PyJObject): ...

class DHGenParameterSpec(jep._PyJObject): ...

class PBEKeySpec(jep._PyJObject): ...

class SecretKeySpec(jep._PyJObject): ...

class DESKeySpec(jep._PyJObject): ...

class DHPublicKeySpec(jep._PyJObject): ...

