import jep

class TooManyListenersException(jep.PyJObject): ...

class List(jep.PyJObject): ...

class Stack(jep.PyJObject): ...

class SortedMap(jep.PyJObject): ...

class ArrayDeque(jep.PyJObject): ...

class Enumeration(jep.PyJObject): ...

class MissingFormatWidthException(jep.PyJObject): ...

class EnumMap(jep.PyJObject): ...

class EmptyStackException(jep.PyJObject): ...

class HashMap(jep.PyJObject): ...

class PrimitiveIterator(jep.PyJObject): ...

class Hashtable(jep.PyJObject): ...

class Formatter(jep.PyJObject): ...

class PropertyPermission(jep.PyJObject): ...

class UnknownFormatFlagsException(jep.PyJObject): ...

class ServiceLoader(jep.PyJObject): ...

class FormatterClosedException(jep.PyJObject): ...

class GregorianCalendar(jep.PyJObject): ...

class Collections(jep.PyJObject): ...

class AbstractQueue(jep.PyJObject): ...

class LinkedHashMap(jep.PyJObject): ...

class Observable(jep.PyJObject): ...

class Timer(jep.PyJObject): ...

class ServiceConfigurationError(jep.PyJObject): ...

class ListIterator(jep.PyJObject): ...

class Date(jep.PyJObject): ...

class MissingResourceException(jep.PyJObject): ...

class RandomAccess(jep.PyJObject): ...

class InputMismatchException(jep.PyJObject): ...

class Objects(jep.PyJObject): ...

class AbstractCollection(jep.PyJObject): ...

class Base64(jep.PyJObject): ...

class IdentityHashMap(jep.PyJObject): ...

class EventListener(jep.PyJObject): ...

class NoSuchElementException(jep.PyJObject): ...

class SplittableRandom(jep.PyJObject): ...

class Comparator(jep.PyJObject): ...

class IllformedLocaleException(jep.PyJObject): ...

class LongSummaryStatistics(jep.PyJObject): ...

class Vector(jep.PyJObject): ...

class HashSet(jep.PyJObject): ...

class Spliterator(jep.PyJObject): ...

class UUID(jep.PyJObject): ...

class Calendar(jep.PyJObject): ...

class MissingFormatArgumentException(jep.PyJObject): ...

class WeakHashMap(jep.PyJObject): ...

class Scanner(jep.PyJObject): ...

class TimerTask(jep.PyJObject): ...

class NavigableMap(jep.PyJObject): ...

class StringTokenizer(jep.PyJObject): ...

class BitSet(jep.PyJObject): ...

class EnumSet(jep.PyJObject): ...

class FormattableFlags(jep.PyJObject): ...

class SortedSet(jep.PyJObject): ...

class Dictionary(jep.PyJObject): ...

class EventObject(jep.PyJObject): ...

class IllegalFormatFlagsException(jep.PyJObject): ...

class AbstractMap(jep.PyJObject): ...

class FormatFlagsConversionMismatchException(jep.PyJObject): ...

class SimpleTimeZone(jep.PyJObject): ...

class Deque(jep.PyJObject): ...

class ConcurrentModificationException(jep.PyJObject): ...

class StringJoiner(jep.PyJObject): ...

class Formattable(jep.PyJObject): ...

class NavigableSet(jep.PyJObject): ...

class IntSummaryStatistics(jep.PyJObject): ...

class IllegalFormatWidthException(jep.PyJObject): ...

class Queue(jep.PyJObject): ...

class DuplicateFormatFlagsException(jep.PyJObject): ...

class Currency(jep.PyJObject): ...

class Arrays(jep.PyJObject): ...

class IllegalFormatConversionException(jep.PyJObject): ...

class AbstractSequentialList(jep.PyJObject): ...

class EventListenerProxy(jep.PyJObject): ...

class Optional(jep.PyJObject): ...

class InvalidPropertiesFormatException(jep.PyJObject): ...

class IllegalFormatException(jep.PyJObject): ...

class Spliterators(jep.PyJObject): ...

class IllegalFormatCodePointException(jep.PyJObject): ...

class Properties(jep.PyJObject): ...

class Iterator(jep.PyJObject): ...

class ArrayList(jep.PyJObject): ...

class Random(jep.PyJObject): ...

class Locale(jep.PyJObject): ...

class PropertyResourceBundle(jep.PyJObject): ...

class TreeSet(jep.PyJObject): ...

class AbstractSet(jep.PyJObject): ...

class ListResourceBundle(jep.PyJObject): ...

class TimeZone(jep.PyJObject): ...

class IllegalFormatPrecisionException(jep.PyJObject): ...

class DoubleSummaryStatistics(jep.PyJObject): ...

class Collection(jep.PyJObject): ...

class LinkedList(jep.PyJObject): ...

class LinkedHashSet(jep.PyJObject): ...

class Observer(jep.PyJObject): ...

class AbstractList(jep.PyJObject): ...

class PriorityQueue(jep.PyJObject): ...

class OptionalDouble(jep.PyJObject): ...

class UnknownFormatConversionException(jep.PyJObject): ...

class OptionalInt(jep.PyJObject): ...

class OptionalLong(jep.PyJObject): ...

class Map(jep.PyJObject): ...

class ResourceBundle(jep.PyJObject): ...

class Set(jep.PyJObject): ...

class TreeMap(jep.PyJObject): ...

