import jep

class TooManyListenersException(jep._PyJObject): ...

class List(jep._PyJObject): ...

class Stack(jep._PyJObject): ...

class SortedMap(jep._PyJObject): ...

class ArrayDeque(jep._PyJObject): ...

class Enumeration(jep._PyJObject): ...

class MissingFormatWidthException(jep._PyJObject): ...

class EnumMap(jep._PyJObject): ...

class EmptyStackException(jep._PyJObject): ...

class HashMap(jep._PyJObject): ...

class PrimitiveIterator(jep._PyJObject): ...

class Hashtable(jep._PyJObject): ...

class Formatter(jep._PyJObject): ...

class PropertyPermission(jep._PyJObject): ...

class UnknownFormatFlagsException(jep._PyJObject): ...

class ServiceLoader(jep._PyJObject): ...

class FormatterClosedException(jep._PyJObject): ...

class GregorianCalendar(jep._PyJObject): ...

class Collections(jep._PyJObject): ...

class AbstractQueue(jep._PyJObject): ...

class LinkedHashMap(jep._PyJObject): ...

class Observable(jep._PyJObject): ...

class Timer(jep._PyJObject): ...

class ServiceConfigurationError(jep._PyJObject): ...

class ListIterator(jep._PyJObject): ...

class Date(jep._PyJObject): ...

class MissingResourceException(jep._PyJObject): ...

class RandomAccess(jep._PyJObject): ...

class InputMismatchException(jep._PyJObject): ...

class Objects(jep._PyJObject): ...

class AbstractCollection(jep._PyJObject): ...

class Base64(jep._PyJObject): ...

class IdentityHashMap(jep._PyJObject): ...

class EventListener(jep._PyJObject): ...

class NoSuchElementException(jep._PyJObject): ...

class SplittableRandom(jep._PyJObject): ...

class Comparator(jep._PyJObject): ...

class IllformedLocaleException(jep._PyJObject): ...

class LongSummaryStatistics(jep._PyJObject): ...

class Vector(jep._PyJObject): ...

class HashSet(jep._PyJObject): ...

class Spliterator(jep._PyJObject): ...

class UUID(jep._PyJObject): ...

class Calendar(jep._PyJObject): ...

class MissingFormatArgumentException(jep._PyJObject): ...

class WeakHashMap(jep._PyJObject): ...

class Scanner(jep._PyJObject): ...

class TimerTask(jep._PyJObject): ...

class NavigableMap(jep._PyJObject): ...

class StringTokenizer(jep._PyJObject): ...

class BitSet(jep._PyJObject): ...

class EnumSet(jep._PyJObject): ...

class FormattableFlags(jep._PyJObject): ...

class SortedSet(jep._PyJObject): ...

class Dictionary(jep._PyJObject): ...

class EventObject(jep._PyJObject): ...

class IllegalFormatFlagsException(jep._PyJObject): ...

class AbstractMap(jep._PyJObject): ...

class FormatFlagsConversionMismatchException(jep._PyJObject): ...

class SimpleTimeZone(jep._PyJObject): ...

class Deque(jep._PyJObject): ...

class ConcurrentModificationException(jep._PyJObject): ...

class StringJoiner(jep._PyJObject): ...

class Formattable(jep._PyJObject): ...

class NavigableSet(jep._PyJObject): ...

class IntSummaryStatistics(jep._PyJObject): ...

class IllegalFormatWidthException(jep._PyJObject): ...

class Queue(jep._PyJObject): ...

class DuplicateFormatFlagsException(jep._PyJObject): ...

class Currency(jep._PyJObject): ...

class Arrays(jep._PyJObject): ...

class IllegalFormatConversionException(jep._PyJObject): ...

class AbstractSequentialList(jep._PyJObject): ...

class EventListenerProxy(jep._PyJObject): ...

class Optional(jep._PyJObject): ...

class InvalidPropertiesFormatException(jep._PyJObject): ...

class IllegalFormatException(jep._PyJObject): ...

class Spliterators(jep._PyJObject): ...

class IllegalFormatCodePointException(jep._PyJObject): ...

class Properties(jep._PyJObject): ...

class Iterator(jep._PyJObject): ...

class ArrayList(jep._PyJObject): ...

class Random(jep._PyJObject): ...

class Locale(jep._PyJObject): ...

class PropertyResourceBundle(jep._PyJObject): ...

class TreeSet(jep._PyJObject): ...

class AbstractSet(jep._PyJObject): ...

class ListResourceBundle(jep._PyJObject): ...

class TimeZone(jep._PyJObject): ...

class IllegalFormatPrecisionException(jep._PyJObject): ...

class DoubleSummaryStatistics(jep._PyJObject): ...

class Collection(jep._PyJObject): ...

class LinkedList(jep._PyJObject): ...

class LinkedHashSet(jep._PyJObject): ...

class Observer(jep._PyJObject): ...

class AbstractList(jep._PyJObject): ...

class PriorityQueue(jep._PyJObject): ...

class OptionalDouble(jep._PyJObject): ...

class UnknownFormatConversionException(jep._PyJObject): ...

class OptionalInt(jep._PyJObject): ...

class OptionalLong(jep._PyJObject): ...

class Map(jep._PyJObject): ...

class ResourceBundle(jep._PyJObject): ...

class Set(jep._PyJObject): ...

class TreeMap(jep._PyJObject): ...

