# pyright: reportPrivateUsage = none

import jep

class ServiceLoader[**Ts](jep._PyJObject): ...

class EventObject[**Ts](jep._PyJObject): ...

class Map[**Ts](jep._PyJObject): ...

class InvalidPropertiesFormatException[**Ts](jep._PyJObject): ...

class FormatterClosedException[**Ts](jep._PyJObject): ...

class AbstractMap[**Ts](jep._PyJObject): ...

class PropertyPermission[**Ts](jep._PyJObject): ...

class Locale[**Ts](jep._PyJObject): ...

class SimpleTimeZone[**Ts](jep._PyJObject): ...

class MissingFormatArgumentException[**Ts](jep._PyJObject): ...

class SortedMap[**Ts](jep._PyJObject): ...

class LinkedHashSet[**Ts](jep._PyJObject): ...

class Timer[**Ts](jep._PyJObject): ...

class LinkedList[**Ts](jep._PyJObject): ...

class TimerTask[**Ts](jep._PyJObject): ...

class Date[**Ts](jep._PyJObject): ...

class ListIterator[**Ts](jep._PyJObject): ...

class Currency[**Ts](jep._PyJObject): ...

class EmptyStackException[**Ts](jep._PyJObject): ...

class TimeZone[**Ts](jep._PyJObject): ...

class Enumeration[**Ts](jep._PyJObject): ...

class IllegalFormatCodePointException[**Ts](jep._PyJObject): ...

class UnknownFormatFlagsException[**Ts](jep._PyJObject): ...

class IllegalFormatException[**Ts](jep._PyJObject): ...

class HashSet[**Ts](jep._PyJObject): ...

class Set[**Ts](jep._PyJObject): ...

class IllegalFormatFlagsException[**Ts](jep._PyJObject): ...

class OptionalDouble[**Ts](jep._PyJObject): ...

class Deque[**Ts](jep._PyJObject): ...

class Hashtable[**Ts](jep._PyJObject): ...

class EventListener[**Ts](jep._PyJObject): ...

class LongSummaryStatistics[**Ts](jep._PyJObject): ...

class HashMap[**Ts](jep._PyJObject): ...

class LinkedHashMap[**Ts](jep._PyJObject): ...

class Dictionary[**Ts](jep._PyJObject): ...

class UUID[**Ts](jep._PyJObject): ...

class NavigableSet[**Ts](jep._PyJObject): ...

class IdentityHashMap[**Ts](jep._PyJObject): ...

class Spliterators[**Ts](jep._PyJObject): ...

class Observer[**Ts](jep._PyJObject): ...

class PriorityQueue[**Ts](jep._PyJObject): ...

class MissingFormatWidthException[**Ts](jep._PyJObject): ...

class EventListenerProxy[**Ts](jep._PyJObject): ...

class TreeSet[**Ts](jep._PyJObject): ...

class MissingResourceException[**Ts](jep._PyJObject): ...

class FormatFlagsConversionMismatchException[**Ts](jep._PyJObject): ...

class UnknownFormatConversionException[**Ts](jep._PyJObject): ...

class DoubleSummaryStatistics[**Ts](jep._PyJObject): ...

class RandomAccess[**Ts](jep._PyJObject): ...

class Objects[**Ts](jep._PyJObject): ...

class ResourceBundle[**Ts](jep._PyJObject): ...

class AbstractSet[**Ts](jep._PyJObject): ...

class AbstractQueue[**Ts](jep._PyJObject): ...

class ConcurrentModificationException[**Ts](jep._PyJObject): ...

class GregorianCalendar[**Ts](jep._PyJObject): ...

class Stack[**Ts](jep._PyJObject): ...

class PropertyResourceBundle[**Ts](jep._PyJObject): ...

class List[**Ts](jep._PyJObject): ...

class InputMismatchException[**Ts](jep._PyJObject): ...

class Collections[**Ts](jep._PyJObject): ...

class Random[**Ts](jep._PyJObject): ...

class NavigableMap[**Ts](jep._PyJObject): ...

class IntSummaryStatistics[**Ts](jep._PyJObject): ...

class Spliterator[**Ts](jep._PyJObject): ...

class Queue[**Ts](jep._PyJObject): ...

class EnumMap[**Ts](jep._PyJObject): ...

class StringTokenizer[**Ts](jep._PyJObject): ...

class Observable[**Ts](jep._PyJObject): ...

class TooManyListenersException[**Ts](jep._PyJObject): ...

class FormattableFlags[**Ts](jep._PyJObject): ...

class Optional[**Ts](jep._PyJObject): ...

class Base64[**Ts](jep._PyJObject): ...

class TreeMap[**Ts](jep._PyJObject): ...

class AbstractCollection[**Ts](jep._PyJObject): ...

class OptionalLong[**Ts](jep._PyJObject): ...

class StringJoiner[**Ts](jep._PyJObject): ...

class Formattable[**Ts](jep._PyJObject): ...

class ArrayList[**Ts](jep._PyJObject): ...

class IllformedLocaleException[**Ts](jep._PyJObject): ...

class IllegalFormatPrecisionException[**Ts](jep._PyJObject): ...

class Vector[**Ts](jep._PyJObject): ...

class AbstractList[**Ts](jep._PyJObject): ...

class SortedSet[**Ts](jep._PyJObject): ...

class Properties[**Ts](jep._PyJObject): ...

class PrimitiveIterator[**Ts](jep._PyJObject): ...

class SplittableRandom[**Ts](jep._PyJObject): ...

class DuplicateFormatFlagsException[**Ts](jep._PyJObject): ...

class ListResourceBundle[**Ts](jep._PyJObject): ...

class OptionalInt[**Ts](jep._PyJObject): ...

class ArrayDeque[**Ts](jep._PyJObject): ...

class Arrays[**Ts](jep._PyJObject): ...

class WeakHashMap[**Ts](jep._PyJObject): ...

class NoSuchElementException[**Ts](jep._PyJObject): ...

class Calendar[**Ts](jep._PyJObject): ...

class ServiceConfigurationError[**Ts](jep._PyJObject): ...

class Scanner[**Ts](jep._PyJObject): ...

class Formatter[**Ts](jep._PyJObject): ...

class IllegalFormatConversionException[**Ts](jep._PyJObject): ...

class AbstractSequentialList[**Ts](jep._PyJObject): ...

class Collection[**Ts](jep._PyJObject): ...

class IllegalFormatWidthException[**Ts](jep._PyJObject): ...

class BitSet[**Ts](jep._PyJObject): ...

class Iterator[**Ts](jep._PyJObject): ...

class EnumSet[**Ts](jep._PyJObject): ...

class Comparator[**Ts](jep._PyJObject): ...

