# pyright: reportPrivateUsage = none

import jep

class DoubleBinaryOperator[**Ts](jep._PyJObject): ...

class LongFunction[**Ts](jep._PyJObject): ...

class BooleanSupplier[**Ts](jep._PyJObject): ...

class DoubleConsumer[**Ts](jep._PyJObject): ...

class IntBinaryOperator[**Ts](jep._PyJObject): ...

class ObjLongConsumer[**Ts](jep._PyJObject): ...

class Predicate[**Ts](jep._PyJObject): ...

class DoubleFunction[**Ts](jep._PyJObject): ...

class IntToLongFunction[**Ts](jep._PyJObject): ...

class ToLongBiFunction[**Ts](jep._PyJObject): ...

class LongSupplier[**Ts](jep._PyJObject): ...

class ToIntFunction[**Ts](jep._PyJObject): ...

class LongConsumer[**Ts](jep._PyJObject): ...

class LongPredicate[**Ts](jep._PyJObject): ...

class ToIntBiFunction[**Ts](jep._PyJObject): ...

class ToDoubleFunction[**Ts](jep._PyJObject): ...

class ObjIntConsumer[**Ts](jep._PyJObject): ...

class DoubleToIntFunction[**Ts](jep._PyJObject): ...

class IntConsumer[**Ts](jep._PyJObject): ...

class Consumer[**Ts](jep._PyJObject): ...

class DoublePredicate[**Ts](jep._PyJObject): ...

class BiFunction[**Ts](jep._PyJObject): ...

class IntSupplier[**Ts](jep._PyJObject): ...

class IntUnaryOperator[**Ts](jep._PyJObject): ...

class LongUnaryOperator[**Ts](jep._PyJObject): ...

class Supplier[**Ts](jep._PyJObject): ...

class ToLongFunction[**Ts](jep._PyJObject): ...

class LongToDoubleFunction[**Ts](jep._PyJObject): ...

class LongBinaryOperator[**Ts](jep._PyJObject): ...

class LongToIntFunction[**Ts](jep._PyJObject): ...

class UnaryOperator[**Ts](jep._PyJObject): ...

class ToDoubleBiFunction[**Ts](jep._PyJObject): ...

class BinaryOperator[**Ts](jep._PyJObject): ...

class ObjDoubleConsumer[**Ts](jep._PyJObject): ...

class IntFunction[**Ts](jep._PyJObject): ...

class IntPredicate[**Ts](jep._PyJObject): ...

class BiConsumer[**Ts](jep._PyJObject): ...

class DoubleSupplier[**Ts](jep._PyJObject): ...

class DoubleUnaryOperator[**Ts](jep._PyJObject): ...

class Function[**Ts](jep._PyJObject): ...

class BiPredicate[**Ts](jep._PyJObject): ...

class DoubleToLongFunction[**Ts](jep._PyJObject): ...

class IntToDoubleFunction[**Ts](jep._PyJObject): ...

