import jep

class ToLongBiFunction(jep.PyJObject): ...

class IntUnaryOperator(jep.PyJObject): ...

class ToIntBiFunction(jep.PyJObject): ...

class IntFunction(jep.PyJObject): ...

class IntToDoubleFunction(jep.PyJObject): ...

class UnaryOperator(jep.PyJObject): ...

class ToDoubleFunction(jep.PyJObject): ...

class LongSupplier(jep.PyJObject): ...

class DoubleToLongFunction(jep.PyJObject): ...

class DoubleFunction(jep.PyJObject): ...

class IntBinaryOperator(jep.PyJObject): ...

class IntConsumer(jep.PyJObject): ...

class ToLongFunction(jep.PyJObject): ...

class Supplier(jep.PyJObject): ...

class IntPredicate(jep.PyJObject): ...

class IntToLongFunction(jep.PyJObject): ...

class Consumer(jep.PyJObject): ...

class DoubleBinaryOperator(jep.PyJObject): ...

class LongBinaryOperator(jep.PyJObject): ...

class ToDoubleBiFunction(jep.PyJObject): ...

class BiFunction(jep.PyJObject): ...

class DoubleSupplier(jep.PyJObject): ...

class LongPredicate(jep.PyJObject): ...

class LongToIntFunction(jep.PyJObject): ...

class Function(jep.PyJObject): ...

class DoubleConsumer(jep.PyJObject): ...

class BinaryOperator(jep.PyJObject): ...

class LongUnaryOperator(jep.PyJObject): ...

class DoublePredicate(jep.PyJObject): ...

class DoubleToIntFunction(jep.PyJObject): ...

class ObjLongConsumer(jep.PyJObject): ...

class BiPredicate(jep.PyJObject): ...

class ObjIntConsumer(jep.PyJObject): ...

class DoubleUnaryOperator(jep.PyJObject): ...

class BooleanSupplier(jep.PyJObject): ...

class Predicate(jep.PyJObject): ...

class BiConsumer(jep.PyJObject): ...

class LongConsumer(jep.PyJObject): ...

class ObjDoubleConsumer(jep.PyJObject): ...

class ToIntFunction(jep.PyJObject): ...

class LongToDoubleFunction(jep.PyJObject): ...

class IntSupplier(jep.PyJObject): ...

