import jep

class ToLongBiFunction(jep._PyJObject): ...

class IntUnaryOperator(jep._PyJObject): ...

class ToIntBiFunction(jep._PyJObject): ...

class IntFunction(jep._PyJObject): ...

class IntToDoubleFunction(jep._PyJObject): ...

class UnaryOperator(jep._PyJObject): ...

class ToDoubleFunction(jep._PyJObject): ...

class LongSupplier(jep._PyJObject): ...

class DoubleToLongFunction(jep._PyJObject): ...

class DoubleFunction(jep._PyJObject): ...

class IntBinaryOperator(jep._PyJObject): ...

class IntConsumer(jep._PyJObject): ...

class ToLongFunction(jep._PyJObject): ...

class Supplier(jep._PyJObject): ...

class IntPredicate(jep._PyJObject): ...

class IntToLongFunction(jep._PyJObject): ...

class Consumer(jep._PyJObject): ...

class DoubleBinaryOperator(jep._PyJObject): ...

class LongBinaryOperator(jep._PyJObject): ...

class ToDoubleBiFunction(jep._PyJObject): ...

class BiFunction(jep._PyJObject): ...

class DoubleSupplier(jep._PyJObject): ...

class LongPredicate(jep._PyJObject): ...

class LongToIntFunction(jep._PyJObject): ...

class Function(jep._PyJObject): ...

class DoubleConsumer(jep._PyJObject): ...

class BinaryOperator(jep._PyJObject): ...

class LongUnaryOperator(jep._PyJObject): ...

class DoublePredicate(jep._PyJObject): ...

class DoubleToIntFunction(jep._PyJObject): ...

class ObjLongConsumer(jep._PyJObject): ...

class BiPredicate(jep._PyJObject): ...

class ObjIntConsumer(jep._PyJObject): ...

class DoubleUnaryOperator(jep._PyJObject): ...

class BooleanSupplier(jep._PyJObject): ...

class Predicate(jep._PyJObject): ...

class BiConsumer(jep._PyJObject): ...

class LongConsumer(jep._PyJObject): ...

class ObjDoubleConsumer(jep._PyJObject): ...

class ToIntFunction(jep._PyJObject): ...

class LongToDoubleFunction(jep._PyJObject): ...

class IntSupplier(jep._PyJObject): ...

