import jep

class JarInputStream(jep._PyJObject): ...

class JarException(jep._PyJObject): ...

class JarOutputStream(jep._PyJObject): ...

class Attributes(jep._PyJObject): ...

class Manifest(jep._PyJObject): ...

class JarFile(jep._PyJObject): ...

class Pack200(jep._PyJObject): ...

class JarEntry(jep._PyJObject): ...

