import jep

class JarInputStream(jep.PyJObject): ...

class JarException(jep.PyJObject): ...

class JarOutputStream(jep.PyJObject): ...

class Attributes(jep.PyJObject): ...

class Manifest(jep.PyJObject): ...

class JarFile(jep.PyJObject): ...

class Pack200(jep.PyJObject): ...

class JarEntry(jep.PyJObject): ...

