# pyright: reportPrivateUsage = none

import jep

class JarOutputStream[**Ts](jep._PyJObject): ...

class Pack200[**Ts](jep._PyJObject): ...

class Attributes[**Ts](jep._PyJObject): ...

class JarInputStream[**Ts](jep._PyJObject): ...

class JarEntry[**Ts](jep._PyJObject): ...

class JarFile[**Ts](jep._PyJObject): ...

class JarException[**Ts](jep._PyJObject): ...

class Manifest[**Ts](jep._PyJObject): ...

