# pyright: reportPrivateUsage = none

import jep

class StreamHandler[**Ts](jep._PyJObject): ...

class MemoryHandler[**Ts](jep._PyJObject): ...

class ErrorManager[**Ts](jep._PyJObject): ...

class LoggingPermission[**Ts](jep._PyJObject): ...

class XMLFormatter[**Ts](jep._PyJObject): ...

class LogRecord[**Ts](jep._PyJObject): ...

class Logger[**Ts](jep._PyJObject): ...

class Formatter[**Ts](jep._PyJObject): ...

class SocketHandler[**Ts](jep._PyJObject): ...

class Handler[**Ts](jep._PyJObject): ...

class SimpleFormatter[**Ts](jep._PyJObject): ...

class LogManager[**Ts](jep._PyJObject): ...

class FileHandler[**Ts](jep._PyJObject): ...

class Filter[**Ts](jep._PyJObject): ...

class Level[**Ts](jep._PyJObject): ...

class LoggingMXBean[**Ts](jep._PyJObject): ...

class ConsoleHandler[**Ts](jep._PyJObject): ...

