import jep

class Logger(jep.PyJObject): ...

class SocketHandler(jep.PyJObject): ...

class XMLFormatter(jep.PyJObject): ...

class ConsoleHandler(jep.PyJObject): ...

class ErrorManager(jep.PyJObject): ...

class StreamHandler(jep.PyJObject): ...

class LogManager(jep.PyJObject): ...

class Level(jep.PyJObject): ...

class FileHandler(jep.PyJObject): ...

class Formatter(jep.PyJObject): ...

class Handler(jep.PyJObject): ...

class LoggingPermission(jep.PyJObject): ...

class MemoryHandler(jep.PyJObject): ...

class LoggingMXBean(jep.PyJObject): ...

class Filter(jep.PyJObject): ...

class SimpleFormatter(jep.PyJObject): ...

class LogRecord(jep.PyJObject): ...

