import jep

class Logger(jep._PyJObject): ...

class SocketHandler(jep._PyJObject): ...

class XMLFormatter(jep._PyJObject): ...

class ConsoleHandler(jep._PyJObject): ...

class ErrorManager(jep._PyJObject): ...

class StreamHandler(jep._PyJObject): ...

class LogManager(jep._PyJObject): ...

class Level(jep._PyJObject): ...

class FileHandler(jep._PyJObject): ...

class Formatter(jep._PyJObject): ...

class Handler(jep._PyJObject): ...

class LoggingPermission(jep._PyJObject): ...

class MemoryHandler(jep._PyJObject): ...

class LoggingMXBean(jep._PyJObject): ...

class Filter(jep._PyJObject): ...

class SimpleFormatter(jep._PyJObject): ...

class LogRecord(jep._PyJObject): ...

