import jep

class InvalidPreferencesFormatException(jep.PyJObject): ...

class NodeChangeEvent(jep.PyJObject): ...

class PreferenceChangeEvent(jep.PyJObject): ...

class Preferences(jep.PyJObject): ...

class AbstractPreferences(jep.PyJObject): ...

class PreferencesFactory(jep.PyJObject): ...

class BackingStoreException(jep.PyJObject): ...

class PreferenceChangeListener(jep.PyJObject): ...

class NodeChangeListener(jep.PyJObject): ...

