# pyright: reportPrivateUsage = none

import jep

class BackingStoreException[**Ts](jep._PyJObject): ...

class AbstractPreferences[**Ts](jep._PyJObject): ...

class NodeChangeListener[**Ts](jep._PyJObject): ...

class InvalidPreferencesFormatException[**Ts](jep._PyJObject): ...

class PreferenceChangeListener[**Ts](jep._PyJObject): ...

class NodeChangeEvent[**Ts](jep._PyJObject): ...

class Preferences[**Ts](jep._PyJObject): ...

class PreferencesFactory[**Ts](jep._PyJObject): ...

class PreferenceChangeEvent[**Ts](jep._PyJObject): ...

