import jep

class InvalidPreferencesFormatException(jep._PyJObject): ...

class NodeChangeEvent(jep._PyJObject): ...

class PreferenceChangeEvent(jep._PyJObject): ...

class Preferences(jep._PyJObject): ...

class AbstractPreferences(jep._PyJObject): ...

class PreferencesFactory(jep._PyJObject): ...

class BackingStoreException(jep._PyJObject): ...

class PreferenceChangeListener(jep._PyJObject): ...

class NodeChangeListener(jep._PyJObject): ...

