# pyright: reportPrivateUsage = none

import jep

class Matcher[**Ts](jep._PyJObject): ...

class MatchResult[**Ts](jep._PyJObject): ...

class PatternSyntaxException[**Ts](jep._PyJObject): ...

class Pattern[**Ts](jep._PyJObject): ...

