import jep

class CalendarNameProvider(jep.PyJObject): ...

class LocaleServiceProvider(jep.PyJObject): ...

class TimeZoneNameProvider(jep.PyJObject): ...

class CalendarDataProvider(jep.PyJObject): ...

class CurrencyNameProvider(jep.PyJObject): ...

class AbstractResourceBundleProvider(jep.PyJObject): ...

class LocaleNameProvider(jep.PyJObject): ...

class ResourceBundleControlProvider(jep.PyJObject): ...

class ToolProvider(jep.PyJObject): ...

class ResourceBundleProvider(jep.PyJObject): ...

