import jep

class CalendarNameProvider(jep._PyJObject): ...

class LocaleServiceProvider(jep._PyJObject): ...

class TimeZoneNameProvider(jep._PyJObject): ...

class CalendarDataProvider(jep._PyJObject): ...

class CurrencyNameProvider(jep._PyJObject): ...

class AbstractResourceBundleProvider(jep._PyJObject): ...

class LocaleNameProvider(jep._PyJObject): ...

class ResourceBundleControlProvider(jep._PyJObject): ...

class ToolProvider(jep._PyJObject): ...

class ResourceBundleProvider(jep._PyJObject): ...

