# pyright: reportPrivateUsage = none

import jep

class ToolProvider[**Ts](jep._PyJObject): ...

class ResourceBundleControlProvider[**Ts](jep._PyJObject): ...

class CurrencyNameProvider[**Ts](jep._PyJObject): ...

class ResourceBundleProvider[**Ts](jep._PyJObject): ...

class CalendarNameProvider[**Ts](jep._PyJObject): ...

class AbstractResourceBundleProvider[**Ts](jep._PyJObject): ...

class CalendarDataProvider[**Ts](jep._PyJObject): ...

class LocaleNameProvider[**Ts](jep._PyJObject): ...

class TimeZoneNameProvider[**Ts](jep._PyJObject): ...

class LocaleServiceProvider[**Ts](jep._PyJObject): ...

