import jep

class StreamSupport(jep._PyJObject): ...

class Collectors(jep._PyJObject): ...

class BaseStream(jep._PyJObject): ...

class Stream(jep._PyJObject): ...

class DoubleStream(jep._PyJObject): ...

class IntStream(jep._PyJObject): ...

class Collector(jep._PyJObject): ...

class LongStream(jep._PyJObject): ...

