import jep

class StreamSupport(jep.PyJObject): ...

class Collectors(jep.PyJObject): ...

class BaseStream(jep.PyJObject): ...

class Stream(jep.PyJObject): ...

class DoubleStream(jep.PyJObject): ...

class IntStream(jep.PyJObject): ...

class Collector(jep.PyJObject): ...

class LongStream(jep.PyJObject): ...

