# pyright: reportPrivateUsage = none

import jep

class Stream[**Ts](jep._PyJObject): ...

class Collector[**Ts](jep._PyJObject): ...

class DoubleStream[**Ts](jep._PyJObject): ...

class Collectors[**Ts](jep._PyJObject): ...

class BaseStream[**Ts](jep._PyJObject): ...

class StreamSupport[**Ts](jep._PyJObject): ...

class IntStream[**Ts](jep._PyJObject): ...

class LongStream[**Ts](jep._PyJObject): ...

