import jep

class Inflater(jep.PyJObject): ...

class GZIPOutputStream(jep.PyJObject): ...

class ZipOutputStream(jep.PyJObject): ...

class ZipInputStream(jep.PyJObject): ...

class CRC32C(jep.PyJObject): ...

class DeflaterOutputStream(jep.PyJObject): ...

class ZipFile(jep.PyJObject): ...

class ZipError(jep.PyJObject): ...

class CheckedOutputStream(jep.PyJObject): ...

class CRC32(jep.PyJObject): ...

class CheckedInputStream(jep.PyJObject): ...

class Adler32(jep.PyJObject): ...

class ZipException(jep.PyJObject): ...

class ZipEntry(jep.PyJObject): ...

class Deflater(jep.PyJObject): ...

class Checksum(jep.PyJObject): ...

class DeflaterInputStream(jep.PyJObject): ...

class DataFormatException(jep.PyJObject): ...

class GZIPInputStream(jep.PyJObject): ...

class InflaterOutputStream(jep.PyJObject): ...

class InflaterInputStream(jep.PyJObject): ...

