# pyright: reportPrivateUsage = none

import jep

class DataFormatException[**Ts](jep._PyJObject): ...

class ZipEntry[**Ts](jep._PyJObject): ...

class DeflaterOutputStream[**Ts](jep._PyJObject): ...

class ZipError[**Ts](jep._PyJObject): ...

class Inflater[**Ts](jep._PyJObject): ...

class DeflaterInputStream[**Ts](jep._PyJObject): ...

class CheckedInputStream[**Ts](jep._PyJObject): ...

class CheckedOutputStream[**Ts](jep._PyJObject): ...

class Checksum[**Ts](jep._PyJObject): ...

class InflaterOutputStream[**Ts](jep._PyJObject): ...

class Deflater[**Ts](jep._PyJObject): ...

class Adler32[**Ts](jep._PyJObject): ...

class CRC32C[**Ts](jep._PyJObject): ...

class ZipInputStream[**Ts](jep._PyJObject): ...

class CRC32[**Ts](jep._PyJObject): ...

class GZIPInputStream[**Ts](jep._PyJObject): ...

class ZipFile[**Ts](jep._PyJObject): ...

class ZipOutputStream[**Ts](jep._PyJObject): ...

class ZipException[**Ts](jep._PyJObject): ...

class InflaterInputStream[**Ts](jep._PyJObject): ...

