import jep

class Inflater(jep._PyJObject): ...

class GZIPOutputStream(jep._PyJObject): ...

class ZipOutputStream(jep._PyJObject): ...

class ZipInputStream(jep._PyJObject): ...

class CRC32C(jep._PyJObject): ...

class DeflaterOutputStream(jep._PyJObject): ...

class ZipFile(jep._PyJObject): ...

class ZipError(jep._PyJObject): ...

class CheckedOutputStream(jep._PyJObject): ...

class CRC32(jep._PyJObject): ...

class CheckedInputStream(jep._PyJObject): ...

class Adler32(jep._PyJObject): ...

class ZipException(jep._PyJObject): ...

class ZipEntry(jep._PyJObject): ...

class Deflater(jep._PyJObject): ...

class Checksum(jep._PyJObject): ...

class DeflaterInputStream(jep._PyJObject): ...

class DataFormatException(jep._PyJObject): ...

class GZIPInputStream(jep._PyJObject): ...

class InflaterOutputStream(jep._PyJObject): ...

class InflaterInputStream(jep._PyJObject): ...

