# pyright: reportPrivateUsage = none

import jep

class OffsetDateTime[**Ts](jep._PyJObject): ...

class DayOfWeek[**Ts](jep._PyJObject): ...

class Year[**Ts](jep._PyJObject): ...

class Instant[**Ts](jep._PyJObject): ...

class ZonedDateTime[**Ts](jep._PyJObject): ...

class OffsetTime[**Ts](jep._PyJObject): ...

class MonthDay[**Ts](jep._PyJObject): ...

class ZoneOffset[**Ts](jep._PyJObject): ...

class LocalDateTime[**Ts](jep._PyJObject): ...

class Duration[**Ts](jep._PyJObject): ...

class LocalDate[**Ts](jep._PyJObject): ...

class Period[**Ts](jep._PyJObject): ...

class LocalTime[**Ts](jep._PyJObject): ...

class YearMonth[**Ts](jep._PyJObject): ...

class ZoneId[**Ts](jep._PyJObject): ...

class Clock[**Ts](jep._PyJObject): ...

class DateTimeException[**Ts](jep._PyJObject): ...

class Month[**Ts](jep._PyJObject): ...

