import jep

class OffsetDateTime(jep.PyJObject): ...

class LocalTime(jep.PyJObject): ...

class Year(jep.PyJObject): ...

class DayOfWeek(jep.PyJObject): ...

class DateTimeException(jep.PyJObject): ...

class Period(jep.PyJObject): ...

class ZoneId(jep.PyJObject): ...

class ZoneOffset(jep.PyJObject): ...

class Clock(jep.PyJObject): ...

class YearMonth(jep.PyJObject): ...

class Month(jep.PyJObject): ...

class Duration(jep.PyJObject): ...

class Instant(jep.PyJObject): ...

class MonthDay(jep.PyJObject): ...

class OffsetTime(jep.PyJObject): ...

class LocalDate(jep.PyJObject): ...

class ZonedDateTime(jep.PyJObject): ...

class LocalDateTime(jep.PyJObject): ...

