import jep

class OffsetDateTime(jep._PyJObject): ...

class LocalTime(jep._PyJObject): ...

class Year(jep._PyJObject): ...

class DayOfWeek(jep._PyJObject): ...

class DateTimeException(jep._PyJObject): ...

class Period(jep._PyJObject): ...

class ZoneId(jep._PyJObject): ...

class ZoneOffset(jep._PyJObject): ...

class Clock(jep._PyJObject): ...

class YearMonth(jep._PyJObject): ...

class Month(jep._PyJObject): ...

class Duration(jep._PyJObject): ...

class Instant(jep._PyJObject): ...

class MonthDay(jep._PyJObject): ...

class OffsetTime(jep._PyJObject): ...

class LocalDate(jep._PyJObject): ...

class ZonedDateTime(jep._PyJObject): ...

class LocalDateTime(jep._PyJObject): ...

