# pyright: reportPrivateUsage = none

import jep

class IsoChronology[**Ts](jep._PyJObject): ...

class HijrahEra[**Ts](jep._PyJObject): ...

class Era[**Ts](jep._PyJObject): ...

class ChronoLocalDate[**Ts](jep._PyJObject): ...

class ChronoZonedDateTime[**Ts](jep._PyJObject): ...

class ThaiBuddhistChronology[**Ts](jep._PyJObject): ...

class ChronoLocalDateTime[**Ts](jep._PyJObject): ...

class ChronoPeriod[**Ts](jep._PyJObject): ...

class HijrahDate[**Ts](jep._PyJObject): ...

class AbstractChronology[**Ts](jep._PyJObject): ...

class JapaneseChronology[**Ts](jep._PyJObject): ...

class MinguoDate[**Ts](jep._PyJObject): ...

class MinguoEra[**Ts](jep._PyJObject): ...

class ThaiBuddhistEra[**Ts](jep._PyJObject): ...

class HijrahChronology[**Ts](jep._PyJObject): ...

class Chronology[**Ts](jep._PyJObject): ...

class IsoEra[**Ts](jep._PyJObject): ...

class MinguoChronology[**Ts](jep._PyJObject): ...

class JapaneseEra[**Ts](jep._PyJObject): ...

class JapaneseDate[**Ts](jep._PyJObject): ...

class ThaiBuddhistDate[**Ts](jep._PyJObject): ...

