import jep

class ChronoLocalDate(jep._PyJObject): ...

class ThaiBuddhistEra(jep._PyJObject): ...

class HijrahChronology(jep._PyJObject): ...

class JapaneseChronology(jep._PyJObject): ...

class IsoEra(jep._PyJObject): ...

class ThaiBuddhistDate(jep._PyJObject): ...

class HijrahDate(jep._PyJObject): ...

class MinguoChronology(jep._PyJObject): ...

class MinguoDate(jep._PyJObject): ...

class IsoChronology(jep._PyJObject): ...

class JapaneseDate(jep._PyJObject): ...

class AbstractChronology(jep._PyJObject): ...

class Era(jep._PyJObject): ...

class Chronology(jep._PyJObject): ...

class ChronoZonedDateTime(jep._PyJObject): ...

class JapaneseEra(jep._PyJObject): ...

class ChronoPeriod(jep._PyJObject): ...

class ChronoLocalDateTime(jep._PyJObject): ...

class MinguoEra(jep._PyJObject): ...

class ThaiBuddhistChronology(jep._PyJObject): ...

