import jep

class ChronoLocalDate(jep.PyJObject): ...

class ThaiBuddhistEra(jep.PyJObject): ...

class HijrahChronology(jep.PyJObject): ...

class JapaneseChronology(jep.PyJObject): ...

class IsoEra(jep.PyJObject): ...

class ThaiBuddhistDate(jep.PyJObject): ...

class HijrahDate(jep.PyJObject): ...

class MinguoChronology(jep.PyJObject): ...

class MinguoDate(jep.PyJObject): ...

class IsoChronology(jep.PyJObject): ...

class JapaneseDate(jep.PyJObject): ...

class AbstractChronology(jep.PyJObject): ...

class Era(jep.PyJObject): ...

class Chronology(jep.PyJObject): ...

class ChronoZonedDateTime(jep.PyJObject): ...

class JapaneseEra(jep.PyJObject): ...

class ChronoPeriod(jep.PyJObject): ...

class ChronoLocalDateTime(jep.PyJObject): ...

class MinguoEra(jep.PyJObject): ...

class ThaiBuddhistChronology(jep.PyJObject): ...

