# pyright: reportPrivateUsage = none

import jep

class TextStyle[**Ts](jep._PyJObject): ...

class SignStyle[**Ts](jep._PyJObject): ...

class ResolverStyle[**Ts](jep._PyJObject): ...

class FormatStyle[**Ts](jep._PyJObject): ...

class DateTimeFormatter[**Ts](jep._PyJObject): ...

class DateTimeFormatterBuilder[**Ts](jep._PyJObject): ...

class DateTimeParseException[**Ts](jep._PyJObject): ...

class DecimalStyle[**Ts](jep._PyJObject): ...

