# pyright: reportPrivateUsage = none

import jep

class ChronoField[**Ts](jep._PyJObject): ...

class TemporalField[**Ts](jep._PyJObject): ...

class TemporalAdjusters[**Ts](jep._PyJObject): ...

class JulianFields[**Ts](jep._PyJObject): ...

class TemporalAdjuster[**Ts](jep._PyJObject): ...

class TemporalQuery[**Ts](jep._PyJObject): ...

class IsoFields[**Ts](jep._PyJObject): ...

class WeekFields[**Ts](jep._PyJObject): ...

class ValueRange[**Ts](jep._PyJObject): ...

class TemporalAmount[**Ts](jep._PyJObject): ...

class ChronoUnit[**Ts](jep._PyJObject): ...

class UnsupportedTemporalTypeException[**Ts](jep._PyJObject): ...

class TemporalQueries[**Ts](jep._PyJObject): ...

class TemporalUnit[**Ts](jep._PyJObject): ...

class TemporalAccessor[**Ts](jep._PyJObject): ...

class Temporal[**Ts](jep._PyJObject): ...

