import jep

class JulianFields(jep._PyJObject): ...

class TemporalUnit(jep._PyJObject): ...

class IsoFields(jep._PyJObject): ...

class TemporalField(jep._PyJObject): ...

class ChronoUnit(jep._PyJObject): ...

class TemporalQueries(jep._PyJObject): ...

class TemporalQuery(jep._PyJObject): ...

class TemporalAdjuster(jep._PyJObject): ...

class Temporal(jep._PyJObject): ...

class TemporalAccessor(jep._PyJObject): ...

class WeekFields(jep._PyJObject): ...

class ChronoField(jep._PyJObject): ...

class TemporalAdjusters(jep._PyJObject): ...

class ValueRange(jep._PyJObject): ...

class UnsupportedTemporalTypeException(jep._PyJObject): ...

class TemporalAmount(jep._PyJObject): ...

