import jep

class JulianFields(jep.PyJObject): ...

class TemporalUnit(jep.PyJObject): ...

class IsoFields(jep.PyJObject): ...

class TemporalField(jep.PyJObject): ...

class ChronoUnit(jep.PyJObject): ...

class TemporalQueries(jep.PyJObject): ...

class TemporalQuery(jep.PyJObject): ...

class TemporalAdjuster(jep.PyJObject): ...

class Temporal(jep.PyJObject): ...

class TemporalAccessor(jep.PyJObject): ...

class WeekFields(jep.PyJObject): ...

class ChronoField(jep.PyJObject): ...

class TemporalAdjusters(jep.PyJObject): ...

class ValueRange(jep.PyJObject): ...

class UnsupportedTemporalTypeException(jep.PyJObject): ...

class TemporalAmount(jep.PyJObject): ...

