import jep

class ZoneOffsetTransitionRule(jep._PyJObject): ...

class ZoneRules(jep._PyJObject): ...

class ZoneRulesProvider(jep._PyJObject): ...

class ZoneRulesException(jep._PyJObject): ...

class ZoneOffsetTransition(jep._PyJObject): ...

