import jep

class ZoneOffsetTransitionRule(jep.PyJObject): ...

class ZoneRules(jep.PyJObject): ...

class ZoneRulesProvider(jep.PyJObject): ...

class ZoneRulesException(jep.PyJObject): ...

class ZoneOffsetTransition(jep.PyJObject): ...

