# pyright: reportPrivateUsage = none

import jep

class ZoneOffsetTransition[**Ts](jep._PyJObject): ...

class ZoneRulesProvider[**Ts](jep._PyJObject): ...

class ZoneRules[**Ts](jep._PyJObject): ...

class ZoneRulesException[**Ts](jep._PyJObject): ...

