# pyright: reportPrivateUsage = none

import jep

class GuardingTypeConverterFactory[**Ts](jep._PyJObject): ...

class MethodTypeConversionStrategy[**Ts](jep._PyJObject): ...

class TypeBasedGuardingDynamicLinker[**Ts](jep._PyJObject): ...

class GuardedInvocationTransformer[**Ts](jep._PyJObject): ...

class ConversionComparator[**Ts](jep._PyJObject): ...

class MethodHandleTransformer[**Ts](jep._PyJObject): ...

class LinkRequest[**Ts](jep._PyJObject): ...

class GuardingDynamicLinkerExporter[**Ts](jep._PyJObject): ...

class GuardedInvocation[**Ts](jep._PyJObject): ...

class LinkerServices[**Ts](jep._PyJObject): ...

