import jep

class GuardingDynamicLinkerExporter(jep._PyJObject): ...

class TypeBasedGuardingDynamicLinker(jep._PyJObject): ...

class ConversionComparator(jep._PyJObject): ...

class MethodHandleTransformer(jep._PyJObject): ...

class MethodTypeConversionStrategy(jep._PyJObject): ...

class GuardedInvocation(jep._PyJObject): ...

class LinkRequest(jep._PyJObject): ...

class GuardingDynamicLinker(jep._PyJObject): ...

class LinkerServices(jep._PyJObject): ...

class GuardedInvocationTransformer(jep._PyJObject): ...

