import jep

class GuardingDynamicLinkerExporter(jep.PyJObject): ...

class TypeBasedGuardingDynamicLinker(jep.PyJObject): ...

class ConversionComparator(jep.PyJObject): ...

class MethodHandleTransformer(jep.PyJObject): ...

class MethodTypeConversionStrategy(jep.PyJObject): ...

class GuardedInvocation(jep.PyJObject): ...

class LinkRequest(jep.PyJObject): ...

class GuardingDynamicLinker(jep.PyJObject): ...

class LinkerServices(jep.PyJObject): ...

class GuardedInvocationTransformer(jep.PyJObject): ...

