import jep

class TypeUtilities(jep._PyJObject): ...

class Lookup(jep._PyJObject): ...

class DefaultInternalObjectFilter(jep._PyJObject): ...

class CompositeTypeBasedGuardingDynamicLinker(jep._PyJObject): ...

class CompositeGuardingDynamicLinker(jep._PyJObject): ...

class SimpleLinkRequest(jep._PyJObject): ...

