import jep

class TypeUtilities(jep.PyJObject): ...

class Lookup(jep.PyJObject): ...

class DefaultInternalObjectFilter(jep.PyJObject): ...

class CompositeTypeBasedGuardingDynamicLinker(jep.PyJObject): ...

class CompositeGuardingDynamicLinker(jep.PyJObject): ...

class SimpleLinkRequest(jep.PyJObject): ...

