# pyright: reportPrivateUsage = none

import jep

class CompositeGuardingDynamicLinker[**Ts](jep._PyJObject): ...

class TypeUtilities[**Ts](jep._PyJObject): ...

class Guards[**Ts](jep._PyJObject): ...

class SimpleLinkRequest[**Ts](jep._PyJObject): ...

class CompositeTypeBasedGuardingDynamicLinker[**Ts](jep._PyJObject): ...

class DefaultInternalObjectFilter[**Ts](jep._PyJObject): ...

