# pyright: reportPrivateUsage = none

import jep

class DocletEnvironment[**Ts](jep._PyJObject): ...

class Doclet[**Ts](jep._PyJObject): ...

class Taglet[**Ts](jep._PyJObject): ...

class StandardDoclet[**Ts](jep._PyJObject): ...

class Reporter[**Ts](jep._PyJObject): ...

