import jep

class DocletEnvironment(jep._PyJObject): ...

class Doclet(jep._PyJObject): ...

class StandardDoclet(jep._PyJObject): ...

class Taglet(jep._PyJObject): ...

class Reporter(jep._PyJObject): ...

