import jep

class DocletEnvironment(jep.PyJObject): ...

class Doclet(jep.PyJObject): ...

class StandardDoclet(jep.PyJObject): ...

class Taglet(jep.PyJObject): ...

class Reporter(jep.PyJObject): ...

