import jep

class DateTimeSyntax(jep.PyJObject): ...

class AttributeSetUtilities(jep.PyJObject): ...

class SetOfIntegerSyntax(jep.PyJObject): ...

class TextSyntax(jep.PyJObject): ...

class UnmodifiableSetException(jep.PyJObject): ...

class PrintJobAttributeSet(jep.PyJObject): ...

class Size2DSyntax(jep.PyJObject): ...

class PrintServiceAttribute(jep.PyJObject): ...

class PrintRequestAttributeSet(jep.PyJObject): ...

class AttributeSet(jep.PyJObject): ...

class PrintRequestAttribute(jep.PyJObject): ...

class DocAttributeSet(jep.PyJObject): ...

class IntegerSyntax(jep.PyJObject): ...

class HashAttributeSet(jep.PyJObject): ...

class SupportedValuesAttribute(jep.PyJObject): ...

class HashDocAttributeSet(jep.PyJObject): ...

class EnumSyntax(jep.PyJObject): ...

class HashPrintServiceAttributeSet(jep.PyJObject): ...

class PrintServiceAttributeSet(jep.PyJObject): ...

class Attribute(jep.PyJObject): ...

class DocAttribute(jep.PyJObject): ...

class HashPrintRequestAttributeSet(jep.PyJObject): ...

class PrintJobAttribute(jep.PyJObject): ...

class HashPrintJobAttributeSet(jep.PyJObject): ...

class URISyntax(jep.PyJObject): ...

class ResolutionSyntax(jep.PyJObject): ...

