# pyright: reportPrivateUsage = none

import jep

class HashAttributeSet[**Ts](jep._PyJObject): ...

class HashPrintRequestAttributeSet[**Ts](jep._PyJObject): ...

class Attribute[**Ts](jep._PyJObject): ...

class PrintRequestAttribute[**Ts](jep._PyJObject): ...

class UnmodifiableSetException[**Ts](jep._PyJObject): ...

class AttributeSet[**Ts](jep._PyJObject): ...

class DocAttributeSet[**Ts](jep._PyJObject): ...

class Size2DSyntax[**Ts](jep._PyJObject): ...

class PrintServiceAttribute[**Ts](jep._PyJObject): ...

class PrintJobAttributeSet[**Ts](jep._PyJObject): ...

class HashPrintJobAttributeSet[**Ts](jep._PyJObject): ...

class HashDocAttributeSet[**Ts](jep._PyJObject): ...

class IntegerSyntax[**Ts](jep._PyJObject): ...

class DateTimeSyntax[**Ts](jep._PyJObject): ...

class PrintRequestAttributeSet[**Ts](jep._PyJObject): ...

class PrintServiceAttributeSet[**Ts](jep._PyJObject): ...

class SupportedValuesAttribute[**Ts](jep._PyJObject): ...

class AttributeSetUtilities[**Ts](jep._PyJObject): ...

class URISyntax[**Ts](jep._PyJObject): ...

class TextSyntax[**Ts](jep._PyJObject): ...

class DocAttribute[**Ts](jep._PyJObject): ...

class HashPrintServiceAttributeSet[**Ts](jep._PyJObject): ...

class PrintJobAttribute[**Ts](jep._PyJObject): ...

class ResolutionSyntax[**Ts](jep._PyJObject): ...

class SetOfIntegerSyntax[**Ts](jep._PyJObject): ...

