import jep

class DateTimeSyntax(jep._PyJObject): ...

class AttributeSetUtilities(jep._PyJObject): ...

class SetOfIntegerSyntax(jep._PyJObject): ...

class TextSyntax(jep._PyJObject): ...

class UnmodifiableSetException(jep._PyJObject): ...

class PrintJobAttributeSet(jep._PyJObject): ...

class Size2DSyntax(jep._PyJObject): ...

class PrintServiceAttribute(jep._PyJObject): ...

class PrintRequestAttributeSet(jep._PyJObject): ...

class AttributeSet(jep._PyJObject): ...

class PrintRequestAttribute(jep._PyJObject): ...

class DocAttributeSet(jep._PyJObject): ...

class IntegerSyntax(jep._PyJObject): ...

class HashAttributeSet(jep._PyJObject): ...

class SupportedValuesAttribute(jep._PyJObject): ...

class HashDocAttributeSet(jep._PyJObject): ...

class EnumSyntax(jep._PyJObject): ...

class HashPrintServiceAttributeSet(jep._PyJObject): ...

class PrintServiceAttributeSet(jep._PyJObject): ...

class Attribute(jep._PyJObject): ...

class DocAttribute(jep._PyJObject): ...

class HashPrintRequestAttributeSet(jep._PyJObject): ...

class PrintJobAttribute(jep._PyJObject): ...

class HashPrintJobAttributeSet(jep._PyJObject): ...

class URISyntax(jep._PyJObject): ...

class ResolutionSyntax(jep._PyJObject): ...

