import jep

class Finishings(jep.PyJObject): ...

class JobSheets(jep.PyJObject): ...

class MediaSizeName(jep.PyJObject): ...

class JobKOctetsProcessed(jep.PyJObject): ...

class SheetCollate(jep.PyJObject): ...

class PageRanges(jep.PyJObject): ...

class DateTimeAtCompleted(jep.PyJObject): ...

class JobStateReason(jep.PyJObject): ...

class ReferenceUriSchemesSupported(jep.PyJObject): ...

class JobMediaSheetsSupported(jep.PyJObject): ...

class DateTimeAtCreation(jep.PyJObject): ...

class PrintQuality(jep.PyJObject): ...

class PDLOverrideSupported(jep.PyJObject): ...

class JobOriginatingUserName(jep.PyJObject): ...

class MultipleDocumentHandling(jep.PyJObject): ...

class Compression(jep.PyJObject): ...

class Destination(jep.PyJObject): ...

class PrinterMessageFromOperator(jep.PyJObject): ...

class Severity(jep.PyJObject): ...

class PrinterLocation(jep.PyJObject): ...

class NumberOfInterveningJobs(jep.PyJObject): ...

class JobMediaSheetsCompleted(jep.PyJObject): ...

class Fidelity(jep.PyJObject): ...

class Sides(jep.PyJObject): ...

class NumberUp(jep.PyJObject): ...

class OutputDeviceAssigned(jep.PyJObject): ...

class JobName(jep.PyJObject): ...

class DocumentName(jep.PyJObject): ...

class PagesPerMinuteColor(jep.PyJObject): ...

class QueuedJobCount(jep.PyJObject): ...

class JobPriority(jep.PyJObject): ...

class DateTimeAtProcessing(jep.PyJObject): ...

class NumberUpSupported(jep.PyJObject): ...

class JobImpressionsSupported(jep.PyJObject): ...

class Chromaticity(jep.PyJObject): ...

class PagesPerMinute(jep.PyJObject): ...

class PrinterResolution(jep.PyJObject): ...

class ColorSupported(jep.PyJObject): ...

class JobPrioritySupported(jep.PyJObject): ...

class PrinterIsAcceptingJobs(jep.PyJObject): ...

class JobState(jep.PyJObject): ...

class JobImpressionsCompleted(jep.PyJObject): ...

class JobMediaSheets(jep.PyJObject): ...

class PrinterMoreInfo(jep.PyJObject): ...

class CopiesSupported(jep.PyJObject): ...

class JobMessageFromOperator(jep.PyJObject): ...

class JobKOctetsSupported(jep.PyJObject): ...

class PrinterInfo(jep.PyJObject): ...

class PrinterStateReasons(jep.PyJObject): ...

class JobImpressions(jep.PyJObject): ...

class OrientationRequested(jep.PyJObject): ...

class DialogOwner(jep.PyJObject): ...

class PrinterName(jep.PyJObject): ...

class RequestingUserName(jep.PyJObject): ...

class Copies(jep.PyJObject): ...

class DialogTypeSelection(jep.PyJObject): ...

class JobKOctets(jep.PyJObject): ...

class PrinterMakeAndModel(jep.PyJObject): ...

class MediaTray(jep.PyJObject): ...

class MediaSize(jep.PyJObject): ...

class MediaName(jep.PyJObject): ...

class NumberOfDocuments(jep.PyJObject): ...

class JobHoldUntil(jep.PyJObject): ...

class PrinterURI(jep.PyJObject): ...

class PrinterMoreInfoManufacturer(jep.PyJObject): ...

class JobStateReasons(jep.PyJObject): ...

class PresentationDirection(jep.PyJObject): ...

class Media(jep.PyJObject): ...

class PrinterStateReason(jep.PyJObject): ...

class PrinterState(jep.PyJObject): ...

