# pyright: reportPrivateUsage = none

import jep

class NumberUpSupported[**Ts](jep._PyJObject): ...

class MediaTray[**Ts](jep._PyJObject): ...

class JobState[**Ts](jep._PyJObject): ...

class NumberUp[**Ts](jep._PyJObject): ...

class Finishings[**Ts](jep._PyJObject): ...

class NumberOfDocuments[**Ts](jep._PyJObject): ...

class OutputDeviceAssigned[**Ts](jep._PyJObject): ...

class Severity[**Ts](jep._PyJObject): ...

class PrinterName[**Ts](jep._PyJObject): ...

class Fidelity[**Ts](jep._PyJObject): ...

class JobPrioritySupported[**Ts](jep._PyJObject): ...

class PrinterResolution[**Ts](jep._PyJObject): ...

class PrinterStateReason[**Ts](jep._PyJObject): ...

class JobImpressions[**Ts](jep._PyJObject): ...

class PrinterState[**Ts](jep._PyJObject): ...

class DocumentName[**Ts](jep._PyJObject): ...

class PrinterMoreInfoManufacturer[**Ts](jep._PyJObject): ...

class PDLOverrideSupported[**Ts](jep._PyJObject): ...

class DialogTypeSelection[**Ts](jep._PyJObject): ...

class JobName[**Ts](jep._PyJObject): ...

class JobImpressionsCompleted[**Ts](jep._PyJObject): ...

class JobMediaSheetsCompleted[**Ts](jep._PyJObject): ...

class Chromaticity[**Ts](jep._PyJObject): ...

class MediaPrintableArea[**Ts](jep._PyJObject): ...

class MediaSize[**Ts](jep._PyJObject): ...

class PrinterURI[**Ts](jep._PyJObject): ...

class JobMediaSheets[**Ts](jep._PyJObject): ...

class Sides[**Ts](jep._PyJObject): ...

class Copies[**Ts](jep._PyJObject): ...

class JobImpressionsSupported[**Ts](jep._PyJObject): ...

class Compression[**Ts](jep._PyJObject): ...

class JobKOctetsSupported[**Ts](jep._PyJObject): ...

class DateTimeAtProcessing[**Ts](jep._PyJObject): ...

class PrinterMoreInfo[**Ts](jep._PyJObject): ...

class PrinterLocation[**Ts](jep._PyJObject): ...

class DialogOwner[**Ts](jep._PyJObject): ...

class JobStateReasons[**Ts](jep._PyJObject): ...

class JobMessageFromOperator[**Ts](jep._PyJObject): ...

class PagesPerMinute[**Ts](jep._PyJObject): ...

class MultipleDocumentHandling[**Ts](jep._PyJObject): ...

class NumberOfInterveningJobs[**Ts](jep._PyJObject): ...

class QueuedJobCount[**Ts](jep._PyJObject): ...

class SheetCollate[**Ts](jep._PyJObject): ...

class PrinterStateReasons[**Ts](jep._PyJObject): ...

class MediaName[**Ts](jep._PyJObject): ...

class JobStateReason[**Ts](jep._PyJObject): ...

class PagesPerMinuteColor[**Ts](jep._PyJObject): ...

class JobHoldUntil[**Ts](jep._PyJObject): ...

class Media[**Ts](jep._PyJObject): ...

class PrintQuality[**Ts](jep._PyJObject): ...

class DateTimeAtCreation[**Ts](jep._PyJObject): ...

class PrinterMakeAndModel[**Ts](jep._PyJObject): ...

class RequestingUserName[**Ts](jep._PyJObject): ...

class PageRanges[**Ts](jep._PyJObject): ...

class DateTimeAtCompleted[**Ts](jep._PyJObject): ...

class Destination[**Ts](jep._PyJObject): ...

class JobKOctets[**Ts](jep._PyJObject): ...

class JobMediaSheetsSupported[**Ts](jep._PyJObject): ...

class PrinterInfo[**Ts](jep._PyJObject): ...

class ColorSupported[**Ts](jep._PyJObject): ...

class JobSheets[**Ts](jep._PyJObject): ...

class MediaSizeName[**Ts](jep._PyJObject): ...

class JobPriority[**Ts](jep._PyJObject): ...

class OrientationRequested[**Ts](jep._PyJObject): ...

class JobKOctetsProcessed[**Ts](jep._PyJObject): ...

class JobOriginatingUserName[**Ts](jep._PyJObject): ...

class PresentationDirection[**Ts](jep._PyJObject): ...

class ReferenceUriSchemesSupported[**Ts](jep._PyJObject): ...

class PrinterIsAcceptingJobs[**Ts](jep._PyJObject): ...

class PrinterMessageFromOperator[**Ts](jep._PyJObject): ...

