import jep

class Finishings(jep._PyJObject): ...

class JobSheets(jep._PyJObject): ...

class MediaSizeName(jep._PyJObject): ...

class JobKOctetsProcessed(jep._PyJObject): ...

class SheetCollate(jep._PyJObject): ...

class PageRanges(jep._PyJObject): ...

class DateTimeAtCompleted(jep._PyJObject): ...

class JobStateReason(jep._PyJObject): ...

class ReferenceUriSchemesSupported(jep._PyJObject): ...

class JobMediaSheetsSupported(jep._PyJObject): ...

class DateTimeAtCreation(jep._PyJObject): ...

class PrintQuality(jep._PyJObject): ...

class PDLOverrideSupported(jep._PyJObject): ...

class JobOriginatingUserName(jep._PyJObject): ...

class MultipleDocumentHandling(jep._PyJObject): ...

class Compression(jep._PyJObject): ...

class Destination(jep._PyJObject): ...

class PrinterMessageFromOperator(jep._PyJObject): ...

class Severity(jep._PyJObject): ...

class PrinterLocation(jep._PyJObject): ...

class NumberOfInterveningJobs(jep._PyJObject): ...

class JobMediaSheetsCompleted(jep._PyJObject): ...

class Fidelity(jep._PyJObject): ...

class Sides(jep._PyJObject): ...

class NumberUp(jep._PyJObject): ...

class OutputDeviceAssigned(jep._PyJObject): ...

class JobName(jep._PyJObject): ...

class DocumentName(jep._PyJObject): ...

class PagesPerMinuteColor(jep._PyJObject): ...

class QueuedJobCount(jep._PyJObject): ...

class JobPriority(jep._PyJObject): ...

class DateTimeAtProcessing(jep._PyJObject): ...

class NumberUpSupported(jep._PyJObject): ...

class JobImpressionsSupported(jep._PyJObject): ...

class Chromaticity(jep._PyJObject): ...

class PagesPerMinute(jep._PyJObject): ...

class PrinterResolution(jep._PyJObject): ...

class ColorSupported(jep._PyJObject): ...

class JobPrioritySupported(jep._PyJObject): ...

class PrinterIsAcceptingJobs(jep._PyJObject): ...

class JobState(jep._PyJObject): ...

class JobImpressionsCompleted(jep._PyJObject): ...

class JobMediaSheets(jep._PyJObject): ...

class PrinterMoreInfo(jep._PyJObject): ...

class CopiesSupported(jep._PyJObject): ...

class JobMessageFromOperator(jep._PyJObject): ...

class JobKOctetsSupported(jep._PyJObject): ...

class PrinterInfo(jep._PyJObject): ...

class PrinterStateReasons(jep._PyJObject): ...

class JobImpressions(jep._PyJObject): ...

class OrientationRequested(jep._PyJObject): ...

class DialogOwner(jep._PyJObject): ...

class PrinterName(jep._PyJObject): ...

class RequestingUserName(jep._PyJObject): ...

class Copies(jep._PyJObject): ...

class DialogTypeSelection(jep._PyJObject): ...

class JobKOctets(jep._PyJObject): ...

class PrinterMakeAndModel(jep._PyJObject): ...

class MediaTray(jep._PyJObject): ...

class MediaSize(jep._PyJObject): ...

class MediaName(jep._PyJObject): ...

class NumberOfDocuments(jep._PyJObject): ...

class JobHoldUntil(jep._PyJObject): ...

class PrinterURI(jep._PyJObject): ...

class PrinterMoreInfoManufacturer(jep._PyJObject): ...

class JobStateReasons(jep._PyJObject): ...

class PresentationDirection(jep._PyJObject): ...

class Media(jep._PyJObject): ...

class PrinterStateReason(jep._PyJObject): ...

class PrinterState(jep._PyJObject): ...

