import jep

class ToolBarUI(jep._PyJObject): ...

class DimensionUIResource(jep._PyJObject): ...

class SplitPaneUI(jep._PyJObject): ...

class LayerUI(jep._PyJObject): ...

class FileChooserUI(jep._PyJObject): ...

class BorderUIResource(jep._PyJObject): ...

class InsetsUIResource(jep._PyJObject): ...

class ButtonUI(jep._PyJObject): ...

class ScrollBarUI(jep._PyJObject): ...

class DesktopIconUI(jep._PyJObject): ...

class PopupMenuUI(jep._PyJObject): ...

class TableUI(jep._PyJObject): ...

class ToolTipUI(jep._PyJObject): ...

class RootPaneUI(jep._PyJObject): ...

class ProgressBarUI(jep._PyJObject): ...

class ComboBoxUI(jep._PyJObject): ...

class ComponentUI(jep._PyJObject): ...

class SliderUI(jep._PyJObject): ...

class TabbedPaneUI(jep._PyJObject): ...

class MenuBarUI(jep._PyJObject): ...

class IconUIResource(jep._PyJObject): ...

class ViewportUI(jep._PyJObject): ...

class ListUI(jep._PyJObject): ...

class TextUI(jep._PyJObject): ...

class InternalFrameUI(jep._PyJObject): ...

class MenuItemUI(jep._PyJObject): ...

class SpinnerUI(jep._PyJObject): ...

class LabelUI(jep._PyJObject): ...

class ScrollPaneUI(jep._PyJObject): ...

class OptionPaneUI(jep._PyJObject): ...

class ActionMapUIResource(jep._PyJObject): ...

class DesktopPaneUI(jep._PyJObject): ...

class ColorChooserUI(jep._PyJObject): ...

class ComponentInputMapUIResource(jep._PyJObject): ...

class PanelUI(jep._PyJObject): ...

class TreeUI(jep._PyJObject): ...

class InputMapUIResource(jep._PyJObject): ...

class FontUIResource(jep._PyJObject): ...

class ColorUIResource(jep._PyJObject): ...

class TableHeaderUI(jep._PyJObject): ...

class SeparatorUI(jep._PyJObject): ...

class UIResource(jep._PyJObject): ...

