import jep

class ToolBarUI(jep.PyJObject): ...

class DimensionUIResource(jep.PyJObject): ...

class SplitPaneUI(jep.PyJObject): ...

class LayerUI(jep.PyJObject): ...

class FileChooserUI(jep.PyJObject): ...

class BorderUIResource(jep.PyJObject): ...

class InsetsUIResource(jep.PyJObject): ...

class ButtonUI(jep.PyJObject): ...

class ScrollBarUI(jep.PyJObject): ...

class DesktopIconUI(jep.PyJObject): ...

class PopupMenuUI(jep.PyJObject): ...

class TableUI(jep.PyJObject): ...

class ToolTipUI(jep.PyJObject): ...

class RootPaneUI(jep.PyJObject): ...

class ProgressBarUI(jep.PyJObject): ...

class ComboBoxUI(jep.PyJObject): ...

class ComponentUI(jep.PyJObject): ...

class SliderUI(jep.PyJObject): ...

class TabbedPaneUI(jep.PyJObject): ...

class MenuBarUI(jep.PyJObject): ...

class IconUIResource(jep.PyJObject): ...

class ViewportUI(jep.PyJObject): ...

class ListUI(jep.PyJObject): ...

class TextUI(jep.PyJObject): ...

class InternalFrameUI(jep.PyJObject): ...

class MenuItemUI(jep.PyJObject): ...

class SpinnerUI(jep.PyJObject): ...

class LabelUI(jep.PyJObject): ...

class ScrollPaneUI(jep.PyJObject): ...

class OptionPaneUI(jep.PyJObject): ...

class ActionMapUIResource(jep.PyJObject): ...

class DesktopPaneUI(jep.PyJObject): ...

class ColorChooserUI(jep.PyJObject): ...

class ComponentInputMapUIResource(jep.PyJObject): ...

class PanelUI(jep.PyJObject): ...

class TreeUI(jep.PyJObject): ...

class InputMapUIResource(jep.PyJObject): ...

class FontUIResource(jep.PyJObject): ...

class ColorUIResource(jep.PyJObject): ...

class TableHeaderUI(jep.PyJObject): ...

class SeparatorUI(jep.PyJObject): ...

class UIResource(jep.PyJObject): ...

