# pyright: reportPrivateUsage = none

import jep

class ToolTipUI[**Ts](jep._PyJObject): ...

class ProgressBarUI[**Ts](jep._PyJObject): ...

class InsetsUIResource[**Ts](jep._PyJObject): ...

class MenuItemUI[**Ts](jep._PyJObject): ...

class ViewportUI[**Ts](jep._PyJObject): ...

class SeparatorUI[**Ts](jep._PyJObject): ...

class ColorUIResource[**Ts](jep._PyJObject): ...

class IconUIResource[**Ts](jep._PyJObject): ...

class ToolBarUI[**Ts](jep._PyJObject): ...

class LabelUI[**Ts](jep._PyJObject): ...

class TreeUI[**Ts](jep._PyJObject): ...

class ComboBoxUI[**Ts](jep._PyJObject): ...

class BorderUIResource[**Ts](jep._PyJObject): ...

class TabbedPaneUI[**Ts](jep._PyJObject): ...

class InternalFrameUI[**Ts](jep._PyJObject): ...

class FontUIResource[**Ts](jep._PyJObject): ...

class TextUI[**Ts](jep._PyJObject): ...

class ListUI[**Ts](jep._PyJObject): ...

class DesktopIconUI[**Ts](jep._PyJObject): ...

class ColorChooserUI[**Ts](jep._PyJObject): ...

class InputMapUIResource[**Ts](jep._PyJObject): ...

class DesktopPaneUI[**Ts](jep._PyJObject): ...

class DimensionUIResource[**Ts](jep._PyJObject): ...

class ButtonUI[**Ts](jep._PyJObject): ...

class RootPaneUI[**Ts](jep._PyJObject): ...

class TableHeaderUI[**Ts](jep._PyJObject): ...

class ScrollPaneUI[**Ts](jep._PyJObject): ...

class FileChooserUI[**Ts](jep._PyJObject): ...

class ComponentInputMapUIResource[**Ts](jep._PyJObject): ...

class OptionPaneUI[**Ts](jep._PyJObject): ...

class PopupMenuUI[**Ts](jep._PyJObject): ...

class PanelUI[**Ts](jep._PyJObject): ...

class ScrollBarUI[**Ts](jep._PyJObject): ...

class LayerUI[**Ts](jep._PyJObject): ...

class UIResource[**Ts](jep._PyJObject): ...

class SliderUI[**Ts](jep._PyJObject): ...

class ActionMapUIResource[**Ts](jep._PyJObject): ...

class SpinnerUI[**Ts](jep._PyJObject): ...

class TableUI[**Ts](jep._PyJObject): ...

class ComponentUI[**Ts](jep._PyJObject): ...

class SplitPaneUI[**Ts](jep._PyJObject): ...

class MenuBarUI[**Ts](jep._PyJObject): ...

