# pyright: reportPrivateUsage = none

import jep

class BasicTreeUI[**Ts](jep._PyJObject): ...

class BasicListUI[**Ts](jep._PyJObject): ...

class BasicGraphicsUtils[**Ts](jep._PyJObject): ...

class BasicButtonListener[**Ts](jep._PyJObject): ...

class BasicRootPaneUI[**Ts](jep._PyJObject): ...

class BasicDesktopIconUI[**Ts](jep._PyJObject): ...

class BasicColorChooserUI[**Ts](jep._PyJObject): ...

class BasicPasswordFieldUI[**Ts](jep._PyJObject): ...

class BasicBorders[**Ts](jep._PyJObject): ...

class BasicArrowButton[**Ts](jep._PyJObject): ...

class BasicLookAndFeel[**Ts](jep._PyJObject): ...

class BasicToolTipUI[**Ts](jep._PyJObject): ...

class BasicMenuBarUI[**Ts](jep._PyJObject): ...

class DefaultMenuLayout[**Ts](jep._PyJObject): ...

class BasicScrollPaneUI[**Ts](jep._PyJObject): ...

class BasicFileChooserUI[**Ts](jep._PyJObject): ...

class BasicDirectoryModel[**Ts](jep._PyJObject): ...

class BasicDesktopPaneUI[**Ts](jep._PyJObject): ...

class BasicTextUI[**Ts](jep._PyJObject): ...

class BasicProgressBarUI[**Ts](jep._PyJObject): ...

class BasicEditorPaneUI[**Ts](jep._PyJObject): ...

class BasicPopupMenuSeparatorUI[**Ts](jep._PyJObject): ...

class BasicPopupMenuUI[**Ts](jep._PyJObject): ...

class BasicHTML[**Ts](jep._PyJObject): ...

class BasicComboBoxUI[**Ts](jep._PyJObject): ...

class BasicComboBoxEditor[**Ts](jep._PyJObject): ...

class BasicLabelUI[**Ts](jep._PyJObject): ...

class BasicToolBarUI[**Ts](jep._PyJObject): ...

class BasicInternalFrameUI[**Ts](jep._PyJObject): ...

class BasicMenuItemUI[**Ts](jep._PyJObject): ...

class BasicToolBarSeparatorUI[**Ts](jep._PyJObject): ...

class BasicRadioButtonUI[**Ts](jep._PyJObject): ...

class BasicRadioButtonMenuItemUI[**Ts](jep._PyJObject): ...

class BasicFormattedTextFieldUI[**Ts](jep._PyJObject): ...

class BasicTextPaneUI[**Ts](jep._PyJObject): ...

class BasicSeparatorUI[**Ts](jep._PyJObject): ...

class BasicOptionPaneUI[**Ts](jep._PyJObject): ...

class BasicScrollBarUI[**Ts](jep._PyJObject): ...

class BasicCheckBoxMenuItemUI[**Ts](jep._PyJObject): ...

class BasicToggleButtonUI[**Ts](jep._PyJObject): ...

class BasicTableUI[**Ts](jep._PyJObject): ...

class BasicInternalFrameTitlePane[**Ts](jep._PyJObject): ...

class BasicViewportUI[**Ts](jep._PyJObject): ...

class BasicTextFieldUI[**Ts](jep._PyJObject): ...

class BasicMenuUI[**Ts](jep._PyJObject): ...

class BasicPanelUI[**Ts](jep._PyJObject): ...

class BasicComboPopup[**Ts](jep._PyJObject): ...

class BasicComboBoxRenderer[**Ts](jep._PyJObject): ...

class BasicTableHeaderUI[**Ts](jep._PyJObject): ...

class BasicSpinnerUI[**Ts](jep._PyJObject): ...

class BasicTextAreaUI[**Ts](jep._PyJObject): ...

class BasicSplitPaneDivider[**Ts](jep._PyJObject): ...

class BasicButtonUI[**Ts](jep._PyJObject): ...

class BasicCheckBoxUI[**Ts](jep._PyJObject): ...

class BasicIconFactory[**Ts](jep._PyJObject): ...

class BasicSliderUI[**Ts](jep._PyJObject): ...

class BasicSplitPaneUI[**Ts](jep._PyJObject): ...

class ComboPopup[**Ts](jep._PyJObject): ...

class BasicTabbedPaneUI[**Ts](jep._PyJObject): ...

