# pyright: reportPrivateUsage = none

import jep

class MetalTreeUI[**Ts](jep._PyJObject): ...

class MetalMenuBarUI[**Ts](jep._PyJObject): ...

class MetalDesktopIconUI[**Ts](jep._PyJObject): ...

class MetalFileChooserUI[**Ts](jep._PyJObject): ...

class MetalToolBarUI[**Ts](jep._PyJObject): ...

class MetalComboBoxButton[**Ts](jep._PyJObject): ...

class MetalSeparatorUI[**Ts](jep._PyJObject): ...

class MetalBorders[**Ts](jep._PyJObject): ...

class MetalTabbedPaneUI[**Ts](jep._PyJObject): ...

class MetalScrollBarUI[**Ts](jep._PyJObject): ...

class OceanTheme[**Ts](jep._PyJObject): ...

class MetalSliderUI[**Ts](jep._PyJObject): ...

class MetalButtonUI[**Ts](jep._PyJObject): ...

class DefaultMetalTheme[**Ts](jep._PyJObject): ...

class MetalScrollPaneUI[**Ts](jep._PyJObject): ...

class MetalTextFieldUI[**Ts](jep._PyJObject): ...

class MetalInternalFrameTitlePane[**Ts](jep._PyJObject): ...

class MetalToggleButtonUI[**Ts](jep._PyJObject): ...

class MetalProgressBarUI[**Ts](jep._PyJObject): ...

class MetalInternalFrameUI[**Ts](jep._PyJObject): ...

class MetalComboBoxIcon[**Ts](jep._PyJObject): ...

class MetalLookAndFeel[**Ts](jep._PyJObject): ...

class MetalRootPaneUI[**Ts](jep._PyJObject): ...

class MetalToolTipUI[**Ts](jep._PyJObject): ...

class MetalCheckBoxUI[**Ts](jep._PyJObject): ...

class MetalTheme[**Ts](jep._PyJObject): ...

class MetalCheckBoxIcon[**Ts](jep._PyJObject): ...

class MetalLabelUI[**Ts](jep._PyJObject): ...

class MetalComboBoxEditor[**Ts](jep._PyJObject): ...

class MetalComboBoxUI[**Ts](jep._PyJObject): ...

class MetalRadioButtonUI[**Ts](jep._PyJObject): ...

class MetalPopupMenuSeparatorUI[**Ts](jep._PyJObject): ...

class MetalScrollButton[**Ts](jep._PyJObject): ...

class MetalSplitPaneUI[**Ts](jep._PyJObject): ...

class MetalIconFactory[**Ts](jep._PyJObject): ...

