# pyright: reportPrivateUsage = none

import jep

class MultiSliderUI[**Ts](jep._PyJObject): ...

class MultiScrollPaneUI[**Ts](jep._PyJObject): ...

class MultiColorChooserUI[**Ts](jep._PyJObject): ...

class MultiTabbedPaneUI[**Ts](jep._PyJObject): ...

class MultiScrollBarUI[**Ts](jep._PyJObject): ...

class MultiPanelUI[**Ts](jep._PyJObject): ...

class MultiInternalFrameUI[**Ts](jep._PyJObject): ...

class MultiDesktopIconUI[**Ts](jep._PyJObject): ...

class MultiMenuItemUI[**Ts](jep._PyJObject): ...

class MultiDesktopPaneUI[**Ts](jep._PyJObject): ...

class MultiSplitPaneUI[**Ts](jep._PyJObject): ...

class MultiToolTipUI[**Ts](jep._PyJObject): ...

class MultiToolBarUI[**Ts](jep._PyJObject): ...

class MultiRootPaneUI[**Ts](jep._PyJObject): ...

class MultiViewportUI[**Ts](jep._PyJObject): ...

class MultiSpinnerUI[**Ts](jep._PyJObject): ...

class MultiButtonUI[**Ts](jep._PyJObject): ...

class MultiFileChooserUI[**Ts](jep._PyJObject): ...

class MultiSeparatorUI[**Ts](jep._PyJObject): ...

class MultiMenuBarUI[**Ts](jep._PyJObject): ...

class MultiTableUI[**Ts](jep._PyJObject): ...

class MultiProgressBarUI[**Ts](jep._PyJObject): ...

class MultiPopupMenuUI[**Ts](jep._PyJObject): ...

class MultiLookAndFeel[**Ts](jep._PyJObject): ...

class MultiListUI[**Ts](jep._PyJObject): ...

class MultiTreeUI[**Ts](jep._PyJObject): ...

class MultiOptionPaneUI[**Ts](jep._PyJObject): ...

class MultiLabelUI[**Ts](jep._PyJObject): ...

class MultiTableHeaderUI[**Ts](jep._PyJObject): ...

class MultiComboBoxUI[**Ts](jep._PyJObject): ...

class MultiTextUI[**Ts](jep._PyJObject): ...

