# pyright: reportPrivateUsage = none

import jep

class NimbusLookAndFeel[**Ts](jep._PyJObject): ...

class NimbusStyle[**Ts](jep._PyJObject): ...

class AbstractRegionPainter[**Ts](jep._PyJObject): ...

class State[**Ts](jep._PyJObject): ...

