# pyright: reportPrivateUsage = none

import jep

class SynthScrollBarUI[**Ts](jep._PyJObject): ...

class SynthTabbedPaneUI[**Ts](jep._PyJObject): ...

class SynthTableHeaderUI[**Ts](jep._PyJObject): ...

class SynthStyleFactory[**Ts](jep._PyJObject): ...

class SynthButtonUI[**Ts](jep._PyJObject): ...

class SynthSeparatorUI[**Ts](jep._PyJObject): ...

class SynthTextAreaUI[**Ts](jep._PyJObject): ...

class SynthConstants[**Ts](jep._PyJObject): ...

class SynthIcon[**Ts](jep._PyJObject): ...

class SynthMenuUI[**Ts](jep._PyJObject): ...

class SynthCheckBoxUI[**Ts](jep._PyJObject): ...

class SynthRadioButtonUI[**Ts](jep._PyJObject): ...

class SynthToolTipUI[**Ts](jep._PyJObject): ...

class SynthRadioButtonMenuItemUI[**Ts](jep._PyJObject): ...

class SynthListUI[**Ts](jep._PyJObject): ...

class SynthPasswordFieldUI[**Ts](jep._PyJObject): ...

class SynthTreeUI[**Ts](jep._PyJObject): ...

class SynthFormattedTextFieldUI[**Ts](jep._PyJObject): ...

class SynthPainter[**Ts](jep._PyJObject): ...

class SynthContext[**Ts](jep._PyJObject): ...

class SynthSliderUI[**Ts](jep._PyJObject): ...

class SynthDesktopPaneUI[**Ts](jep._PyJObject): ...

class SynthMenuItemUI[**Ts](jep._PyJObject): ...

class SynthProgressBarUI[**Ts](jep._PyJObject): ...

class SynthToolBarUI[**Ts](jep._PyJObject): ...

class SynthPopupMenuUI[**Ts](jep._PyJObject): ...

class ColorType[**Ts](jep._PyJObject): ...

class SynthColorChooserUI[**Ts](jep._PyJObject): ...

class SynthUI[**Ts](jep._PyJObject): ...

class SynthToggleButtonUI[**Ts](jep._PyJObject): ...

class SynthDesktopIconUI[**Ts](jep._PyJObject): ...

class SynthSpinnerUI[**Ts](jep._PyJObject): ...

class SynthComboBoxUI[**Ts](jep._PyJObject): ...

class SynthTextFieldUI[**Ts](jep._PyJObject): ...

class SynthInternalFrameUI[**Ts](jep._PyJObject): ...

class SynthLookAndFeel[**Ts](jep._PyJObject): ...

class SynthGraphicsUtils[**Ts](jep._PyJObject): ...

class SynthEditorPaneUI[**Ts](jep._PyJObject): ...

class SynthOptionPaneUI[**Ts](jep._PyJObject): ...

class SynthPanelUI[**Ts](jep._PyJObject): ...

class Region[**Ts](jep._PyJObject): ...

class SynthScrollPaneUI[**Ts](jep._PyJObject): ...

class SynthTextPaneUI[**Ts](jep._PyJObject): ...

class SynthMenuBarUI[**Ts](jep._PyJObject): ...

class SynthRootPaneUI[**Ts](jep._PyJObject): ...

class SynthTableUI[**Ts](jep._PyJObject): ...

class SynthSplitPaneUI[**Ts](jep._PyJObject): ...

class SynthViewportUI[**Ts](jep._PyJObject): ...

class SynthLabelUI[**Ts](jep._PyJObject): ...

class SynthStyle[**Ts](jep._PyJObject): ...

