# pyright: reportPrivateUsage = none

import jep

class CellRendererPane[**Ts](jep._PyJObject): ...

class Renderer[**Ts](jep._PyJObject): ...

class DefaultListCellRenderer[**Ts](jep._PyJObject): ...

class JProgressBar[**Ts](jep._PyJObject): ...

class UIClientPropertyKey[**Ts](jep._PyJObject): ...

class Box[**Ts](jep._PyJObject): ...

class JLayeredPane[**Ts](jep._PyJObject): ...

class LookAndFeel[**Ts](jep._PyJObject): ...

class Painter[**Ts](jep._PyJObject): ...

class DefaultBoundedRangeModel[**Ts](jep._PyJObject): ...

class JComponent[**Ts](jep._PyJObject): ...

class ButtonGroup[**Ts](jep._PyJObject): ...

class ComboBoxModel[**Ts](jep._PyJObject): ...

class ButtonModel[**Ts](jep._PyJObject): ...

class JFrame[**Ts](jep._PyJObject): ...

class InputMap[**Ts](jep._PyJObject): ...

class UIDefaults[**Ts](jep._PyJObject): ...

class SpinnerDateModel[**Ts](jep._PyJObject): ...

class JSplitPane[**Ts](jep._PyJObject): ...

class ImageIcon[**Ts](jep._PyJObject): ...

class DefaultDesktopManager[**Ts](jep._PyJObject): ...

class GroupLayout[**Ts](jep._PyJObject): ...

class Action[**Ts](jep._PyJObject): ...

class Spring[**Ts](jep._PyJObject): ...

class RootPaneContainer[**Ts](jep._PyJObject): ...

class JSeparator[**Ts](jep._PyJObject): ...

class SpinnerModel[**Ts](jep._PyJObject): ...

class JTextArea[**Ts](jep._PyJObject): ...

class JApplet[**Ts](jep._PyJObject): ...

class JPopupMenu[**Ts](jep._PyJObject): ...

class AbstractCellEditor[**Ts](jep._PyJObject): ...

class JWindow[**Ts](jep._PyJObject): ...

class Icon[**Ts](jep._PyJObject): ...

class DefaultFocusManager[**Ts](jep._PyJObject): ...

class DefaultListModel[**Ts](jep._PyJObject): ...

class MutableComboBoxModel[**Ts](jep._PyJObject): ...

class JRootPane[**Ts](jep._PyJObject): ...

class CellEditor[**Ts](jep._PyJObject): ...

class ListSelectionModel[**Ts](jep._PyJObject): ...

class SwingConstants[**Ts](jep._PyJObject): ...

class JColorChooser[**Ts](jep._PyJObject): ...

class JLabel[**Ts](jep._PyJObject): ...

class JFileChooser[**Ts](jep._PyJObject): ...

class FocusManager[**Ts](jep._PyJObject): ...

class JLayer[**Ts](jep._PyJObject): ...

class JTree[**Ts](jep._PyJObject): ...

class RowFilter[**Ts](jep._PyJObject): ...

class RepaintManager[**Ts](jep._PyJObject): ...

class JViewport[**Ts](jep._PyJObject): ...

class JRadioButtonMenuItem[**Ts](jep._PyJObject): ...

class SpringLayout[**Ts](jep._PyJObject): ...

class BoxLayout[**Ts](jep._PyJObject): ...

class JCheckBoxMenuItem[**Ts](jep._PyJObject): ...

class JCheckBox[**Ts](jep._PyJObject): ...

class SwingContainer[**Ts](jep._PyJObject): ...

class JFormattedTextField[**Ts](jep._PyJObject): ...

class PopupFactory[**Ts](jep._PyJObject): ...

class DefaultListSelectionModel[**Ts](jep._PyJObject): ...

class SortingFocusTraversalPolicy[**Ts](jep._PyJObject): ...

class AbstractSpinnerModel[**Ts](jep._PyJObject): ...

class JScrollBar[**Ts](jep._PyJObject): ...

class JEditorPane[**Ts](jep._PyJObject): ...

class DropMode[**Ts](jep._PyJObject): ...

class ComponentInputMap[**Ts](jep._PyJObject): ...

class JDialog[**Ts](jep._PyJObject): ...

class JOptionPane[**Ts](jep._PyJObject): ...

class TransferHandler[**Ts](jep._PyJObject): ...

class JPasswordField[**Ts](jep._PyJObject): ...

class JToolTip[**Ts](jep._PyJObject): ...

class JTable[**Ts](jep._PyJObject): ...

class SizeSequence[**Ts](jep._PyJObject): ...

class UnsupportedLookAndFeelException[**Ts](jep._PyJObject): ...

class SizeRequirements[**Ts](jep._PyJObject): ...

class JComboBox[**Ts](jep._PyJObject): ...

class InternalFrameFocusTraversalPolicy[**Ts](jep._PyJObject): ...

class Popup[**Ts](jep._PyJObject): ...

class SingleSelectionModel[**Ts](jep._PyJObject): ...

class SortOrder[**Ts](jep._PyJObject): ...

class SpinnerListModel[**Ts](jep._PyJObject): ...

class JTextField[**Ts](jep._PyJObject): ...

class MenuSelectionManager[**Ts](jep._PyJObject): ...

class DebugGraphics[**Ts](jep._PyJObject): ...

class JList[**Ts](jep._PyJObject): ...

class Scrollable[**Ts](jep._PyJObject): ...

class JPanel[**Ts](jep._PyJObject): ...

class JToolBar[**Ts](jep._PyJObject): ...

class InputVerifier[**Ts](jep._PyJObject): ...

class ComboBoxEditor[**Ts](jep._PyJObject): ...

class ToolTipManager[**Ts](jep._PyJObject): ...

class DesktopManager[**Ts](jep._PyJObject): ...

class JToggleButton[**Ts](jep._PyJObject): ...

class MenuElement[**Ts](jep._PyJObject): ...

class RowSorter[**Ts](jep._PyJObject): ...

class UIManager[**Ts](jep._PyJObject): ...

class JTabbedPane[**Ts](jep._PyJObject): ...

class JMenuItem[**Ts](jep._PyJObject): ...

class JButton[**Ts](jep._PyJObject): ...

class JDesktopPane[**Ts](jep._PyJObject): ...

class ScrollPaneLayout[**Ts](jep._PyJObject): ...

class ScrollPaneConstants[**Ts](jep._PyJObject): ...

class JRadioButton[**Ts](jep._PyJObject): ...

class KeyStroke[**Ts](jep._PyJObject): ...

class ProgressMonitor[**Ts](jep._PyJObject): ...

class ActionMap[**Ts](jep._PyJObject): ...

class LayoutFocusTraversalPolicy[**Ts](jep._PyJObject): ...

class BorderFactory[**Ts](jep._PyJObject): ...

class JMenu[**Ts](jep._PyJObject): ...

class DefaultRowSorter[**Ts](jep._PyJObject): ...

class AbstractAction[**Ts](jep._PyJObject): ...

class Timer[**Ts](jep._PyJObject): ...

class SwingUtilities[**Ts](jep._PyJObject): ...

class JMenuBar[**Ts](jep._PyJObject): ...

class ProgressMonitorInputStream[**Ts](jep._PyJObject): ...

class JSpinner[**Ts](jep._PyJObject): ...

class LayoutStyle[**Ts](jep._PyJObject): ...

class JSlider[**Ts](jep._PyJObject): ...

class GrayFilter[**Ts](jep._PyJObject): ...

class JInternalFrame[**Ts](jep._PyJObject): ...

class ListCellRenderer[**Ts](jep._PyJObject): ...

class DefaultCellEditor[**Ts](jep._PyJObject): ...

class AbstractButton[**Ts](jep._PyJObject): ...

class DefaultSingleSelectionModel[**Ts](jep._PyJObject): ...

class ListModel[**Ts](jep._PyJObject): ...

class ViewportLayout[**Ts](jep._PyJObject): ...

class OverlayLayout[**Ts](jep._PyJObject): ...

class DefaultButtonModel[**Ts](jep._PyJObject): ...

class SpinnerNumberModel[**Ts](jep._PyJObject): ...

class AbstractListModel[**Ts](jep._PyJObject): ...

class JScrollPane[**Ts](jep._PyJObject): ...

class WindowConstants[**Ts](jep._PyJObject): ...

class JTextPane[**Ts](jep._PyJObject): ...

class DefaultComboBoxModel[**Ts](jep._PyJObject): ...

class SwingWorker[**Ts](jep._PyJObject): ...

class BoundedRangeModel[**Ts](jep._PyJObject): ...

