import jep

class EtchedBorder(jep._PyJObject): ...

class TitledBorder(jep._PyJObject): ...

class AbstractBorder(jep._PyJObject): ...

class CompoundBorder(jep._PyJObject): ...

class EmptyBorder(jep._PyJObject): ...

class StrokeBorder(jep._PyJObject): ...

class BevelBorder(jep._PyJObject): ...

class MatteBorder(jep._PyJObject): ...

class Border(jep._PyJObject): ...

class LineBorder(jep._PyJObject): ...

class SoftBevelBorder(jep._PyJObject): ...

