import jep

class EtchedBorder(jep.PyJObject): ...

class TitledBorder(jep.PyJObject): ...

class AbstractBorder(jep.PyJObject): ...

class CompoundBorder(jep.PyJObject): ...

class EmptyBorder(jep.PyJObject): ...

class StrokeBorder(jep.PyJObject): ...

class BevelBorder(jep.PyJObject): ...

class MatteBorder(jep.PyJObject): ...

class Border(jep.PyJObject): ...

class LineBorder(jep.PyJObject): ...

class SoftBevelBorder(jep.PyJObject): ...

