# pyright: reportPrivateUsage = none

import jep

class TitledBorder[**Ts](jep._PyJObject): ...

class CompoundBorder[**Ts](jep._PyJObject): ...

class AbstractBorder[**Ts](jep._PyJObject): ...

class LineBorder[**Ts](jep._PyJObject): ...

class StrokeBorder[**Ts](jep._PyJObject): ...

class EmptyBorder[**Ts](jep._PyJObject): ...

class BevelBorder[**Ts](jep._PyJObject): ...

class SoftBevelBorder[**Ts](jep._PyJObject): ...

class EtchedBorder[**Ts](jep._PyJObject): ...

class Border[**Ts](jep._PyJObject): ...

class MatteBorder[**Ts](jep._PyJObject): ...

