import jep

class ColorChooserComponentFactory(jep._PyJObject): ...

class DefaultColorSelectionModel(jep._PyJObject): ...

class ColorSelectionModel(jep._PyJObject): ...

class AbstractColorChooserPanel(jep._PyJObject): ...

