# pyright: reportPrivateUsage = none

import jep

class ColorChooserComponentFactory[**Ts](jep._PyJObject): ...

class ColorSelectionModel[**Ts](jep._PyJObject): ...

class DefaultColorSelectionModel[**Ts](jep._PyJObject): ...

class AbstractColorChooserPanel[**Ts](jep._PyJObject): ...

