import jep

class ColorChooserComponentFactory(jep.PyJObject): ...

class DefaultColorSelectionModel(jep.PyJObject): ...

class ColorSelectionModel(jep.PyJObject): ...

class AbstractColorChooserPanel(jep.PyJObject): ...

