# pyright: reportPrivateUsage = none

import jep

class CellEditorListener[**Ts](jep._PyJObject): ...

class ChangeListener[**Ts](jep._PyJObject): ...

class CaretListener[**Ts](jep._PyJObject): ...

class TreeModelListener[**Ts](jep._PyJObject): ...

class MenuKeyEvent[**Ts](jep._PyJObject): ...

class DocumentEvent[**Ts](jep._PyJObject): ...

class TreeWillExpandListener[**Ts](jep._PyJObject): ...

class InternalFrameListener[**Ts](jep._PyJObject): ...

class TableModelEvent[**Ts](jep._PyJObject): ...

class ListSelectionEvent[**Ts](jep._PyJObject): ...

class PopupMenuEvent[**Ts](jep._PyJObject): ...

class EventListenerList[**Ts](jep._PyJObject): ...

class MenuKeyListener[**Ts](jep._PyJObject): ...

class RowSorterEvent[**Ts](jep._PyJObject): ...

class AncestorEvent[**Ts](jep._PyJObject): ...

class TreeModelEvent[**Ts](jep._PyJObject): ...

class DocumentListener[**Ts](jep._PyJObject): ...

class TableModelListener[**Ts](jep._PyJObject): ...

class ListDataListener[**Ts](jep._PyJObject): ...

class MenuDragMouseListener[**Ts](jep._PyJObject): ...

class TableColumnModelListener[**Ts](jep._PyJObject): ...

class ListDataEvent[**Ts](jep._PyJObject): ...

class MenuDragMouseEvent[**Ts](jep._PyJObject): ...

class MouseInputListener[**Ts](jep._PyJObject): ...

class UndoableEditEvent[**Ts](jep._PyJObject): ...

class MenuEvent[**Ts](jep._PyJObject): ...

class PopupMenuListener[**Ts](jep._PyJObject): ...

class TreeSelectionEvent[**Ts](jep._PyJObject): ...

class SwingPropertyChangeSupport[**Ts](jep._PyJObject): ...

class AncestorListener[**Ts](jep._PyJObject): ...

class TreeExpansionListener[**Ts](jep._PyJObject): ...

class TreeSelectionListener[**Ts](jep._PyJObject): ...

class CaretEvent[**Ts](jep._PyJObject): ...

class InternalFrameAdapter[**Ts](jep._PyJObject): ...

class HyperlinkEvent[**Ts](jep._PyJObject): ...

class UndoableEditListener[**Ts](jep._PyJObject): ...

class InternalFrameEvent[**Ts](jep._PyJObject): ...

class MenuListener[**Ts](jep._PyJObject): ...

class MouseInputAdapter[**Ts](jep._PyJObject): ...

class ListSelectionListener[**Ts](jep._PyJObject): ...

class RowSorterListener[**Ts](jep._PyJObject): ...

class TreeExpansionEvent[**Ts](jep._PyJObject): ...

class HyperlinkListener[**Ts](jep._PyJObject): ...

class ChangeEvent[**Ts](jep._PyJObject): ...

class TableColumnModelEvent[**Ts](jep._PyJObject): ...

