# pyright: reportPrivateUsage = none

import jep

class FileView[**Ts](jep._PyJObject): ...

class FileNameExtensionFilter[**Ts](jep._PyJObject): ...

class FileSystemView[**Ts](jep._PyJObject): ...

class FileFilter[**Ts](jep._PyJObject): ...

