# pyright: reportPrivateUsage = none

import jep

class DefaultTableCellRenderer[**Ts](jep._PyJObject): ...

class DefaultTableColumnModel[**Ts](jep._PyJObject): ...

class AbstractTableModel[**Ts](jep._PyJObject): ...

class TableColumn[**Ts](jep._PyJObject): ...

class JTableHeader[**Ts](jep._PyJObject): ...

class TableCellEditor[**Ts](jep._PyJObject): ...

class DefaultTableModel[**Ts](jep._PyJObject): ...

class TableCellRenderer[**Ts](jep._PyJObject): ...

class TableColumnModel[**Ts](jep._PyJObject): ...

class TableModel[**Ts](jep._PyJObject): ...

class TableRowSorter[**Ts](jep._PyJObject): ...

class TableStringConverter[**Ts](jep._PyJObject): ...

