import jep

class TableCellEditor(jep._PyJObject): ...

class TableColumnModel(jep._PyJObject): ...

class TableCellRenderer(jep._PyJObject): ...

class DefaultTableCellRenderer(jep._PyJObject): ...

class DefaultTableColumnModel(jep._PyJObject): ...

class AbstractTableModel(jep._PyJObject): ...

class DefaultTableModel(jep._PyJObject): ...

class TableStringConverter(jep._PyJObject): ...

class TableColumn(jep._PyJObject): ...

class TableRowSorter(jep._PyJObject): ...

class TableModel(jep._PyJObject): ...

class JTableHeader(jep._PyJObject): ...

