import jep

class TableCellEditor(jep.PyJObject): ...

class TableColumnModel(jep.PyJObject): ...

class TableCellRenderer(jep.PyJObject): ...

class DefaultTableCellRenderer(jep.PyJObject): ...

class DefaultTableColumnModel(jep.PyJObject): ...

class AbstractTableModel(jep.PyJObject): ...

class DefaultTableModel(jep.PyJObject): ...

class TableStringConverter(jep.PyJObject): ...

class TableColumn(jep.PyJObject): ...

class TableRowSorter(jep.PyJObject): ...

class TableModel(jep.PyJObject): ...

class JTableHeader(jep.PyJObject): ...

