# pyright: reportPrivateUsage = none

import jep

class DefaultTreeModel[**Ts](jep._PyJObject): ...

class TreeModel[**Ts](jep._PyJObject): ...

class RowMapper[**Ts](jep._PyJObject): ...

class TreeNode[**Ts](jep._PyJObject): ...

class DefaultTreeCellEditor[**Ts](jep._PyJObject): ...

class AbstractLayoutCache[**Ts](jep._PyJObject): ...

class MutableTreeNode[**Ts](jep._PyJObject): ...

class TreePath[**Ts](jep._PyJObject): ...

class DefaultMutableTreeNode[**Ts](jep._PyJObject): ...

class DefaultTreeSelectionModel[**Ts](jep._PyJObject): ...

class TreeSelectionModel[**Ts](jep._PyJObject): ...

class TreeCellRenderer[**Ts](jep._PyJObject): ...

class TreeCellEditor[**Ts](jep._PyJObject): ...

class DefaultTreeCellRenderer[**Ts](jep._PyJObject): ...

class ExpandVetoException[**Ts](jep._PyJObject): ...

class VariableHeightLayoutCache[**Ts](jep._PyJObject): ...

class FixedHeightLayoutCache[**Ts](jep._PyJObject): ...

