import jep

class UndoableEdit(jep._PyJObject): ...

class StateEdit(jep._PyJObject): ...

class StateEditable(jep._PyJObject): ...

class CannotRedoException(jep._PyJObject): ...

class UndoableEditSupport(jep._PyJObject): ...

class AbstractUndoableEdit(jep._PyJObject): ...

class UndoManager(jep._PyJObject): ...

class CannotUndoException(jep._PyJObject): ...

class CompoundEdit(jep._PyJObject): ...

