# pyright: reportPrivateUsage = none

import jep

class StateEdit[**Ts](jep._PyJObject): ...

class UndoManager[**Ts](jep._PyJObject): ...

class CompoundEdit[**Ts](jep._PyJObject): ...

class CannotRedoException[**Ts](jep._PyJObject): ...

class StateEditable[**Ts](jep._PyJObject): ...

class UndoableEditSupport[**Ts](jep._PyJObject): ...

class CannotUndoException[**Ts](jep._PyJObject): ...

class AbstractUndoableEdit[**Ts](jep._PyJObject): ...

class UndoableEdit[**Ts](jep._PyJObject): ...

