import jep

class UndoableEdit(jep.PyJObject): ...

class StateEdit(jep.PyJObject): ...

class StateEditable(jep.PyJObject): ...

class CannotRedoException(jep.PyJObject): ...

class UndoableEditSupport(jep.PyJObject): ...

class AbstractUndoableEdit(jep.PyJObject): ...

class UndoManager(jep.PyJObject): ...

class CannotUndoException(jep.PyJObject): ...

class CompoundEdit(jep.PyJObject): ...

