# pyright: reportPrivateUsage = none

import jep

class Certificate[**Ts](jep._PyJObject): ...

class CertificateParsingException[**Ts](jep._PyJObject): ...

class CertificateException[**Ts](jep._PyJObject): ...

class CertificateEncodingException[**Ts](jep._PyJObject): ...

class CertificateExpiredException[**Ts](jep._PyJObject): ...

class CertificateNotYetValidException[**Ts](jep._PyJObject): ...

class X509Certificate[**Ts](jep._PyJObject): ...

