import jep

class CertificateException(jep.PyJObject): ...

class CertificateExpiredException(jep.PyJObject): ...

class Certificate(jep.PyJObject): ...

class CertificateEncodingException(jep.PyJObject): ...

class X509Certificate(jep.PyJObject): ...

class CertificateNotYetValidException(jep.PyJObject): ...

class CertificateParsingException(jep.PyJObject): ...

