import jep

class CertificateException(jep._PyJObject): ...

class CertificateExpiredException(jep._PyJObject): ...

class Certificate(jep._PyJObject): ...

class CertificateEncodingException(jep._PyJObject): ...

class X509Certificate(jep._PyJObject): ...

class CertificateNotYetValidException(jep._PyJObject): ...

class CertificateParsingException(jep._PyJObject): ...

