import jep

class RealmCallback(jep.PyJObject): ...

class RealmChoiceCallback(jep.PyJObject): ...

class SaslClient(jep.PyJObject): ...

class SaslServerFactory(jep.PyJObject): ...

class Sasl(jep.PyJObject): ...

class AuthenticationException(jep.PyJObject): ...

class AuthorizeCallback(jep.PyJObject): ...

class SaslClientFactory(jep.PyJObject): ...

class SaslException(jep.PyJObject): ...

class SaslServer(jep.PyJObject): ...

