import jep

class RealmCallback(jep._PyJObject): ...

class RealmChoiceCallback(jep._PyJObject): ...

class SaslClient(jep._PyJObject): ...

class SaslServerFactory(jep._PyJObject): ...

class Sasl(jep._PyJObject): ...

class AuthenticationException(jep._PyJObject): ...

class AuthorizeCallback(jep._PyJObject): ...

class SaslClientFactory(jep._PyJObject): ...

class SaslException(jep._PyJObject): ...

class SaslServer(jep._PyJObject): ...

