# pyright: reportPrivateUsage = none

import jep

class AuthorizeCallback[**Ts](jep._PyJObject): ...

class SaslClientFactory[**Ts](jep._PyJObject): ...

class SaslServer[**Ts](jep._PyJObject): ...

class SaslServerFactory[**Ts](jep._PyJObject): ...

class AuthenticationException[**Ts](jep._PyJObject): ...

class Sasl[**Ts](jep._PyJObject): ...

class SaslException[**Ts](jep._PyJObject): ...

class RealmCallback[**Ts](jep._PyJObject): ...

class SaslClient[**Ts](jep._PyJObject): ...

class RealmChoiceCallback[**Ts](jep._PyJObject): ...

