import jep

class AccessibilityEventMonitor(jep._PyJObject): ...

class SwingEventMonitor(jep._PyJObject): ...

class Translator(jep._PyJObject): ...

class TopLevelWindowListener(jep._PyJObject): ...

class EventQueueMonitor(jep._PyJObject): ...

class AWTEventMonitor(jep._PyJObject): ...

class AccessibilityListenerList(jep._PyJObject): ...

class EventID(jep._PyJObject): ...

class GUIInitializedListener(jep._PyJObject): ...

