# pyright: reportPrivateUsage = none

import jep

class AccessibilityEventMonitor[**Ts](jep._PyJObject): ...

class AWTEventMonitor[**Ts](jep._PyJObject): ...

class SwingEventMonitor[**Ts](jep._PyJObject): ...

class Translator[**Ts](jep._PyJObject): ...

class EventQueueMonitor[**Ts](jep._PyJObject): ...

class AccessibilityListenerList[**Ts](jep._PyJObject): ...

class EventID[**Ts](jep._PyJObject): ...

class GUIInitializedListener[**Ts](jep._PyJObject): ...

class TopLevelWindowListener[**Ts](jep._PyJObject): ...

