import jep

class AccessibilityEventMonitor(jep.PyJObject): ...

class SwingEventMonitor(jep.PyJObject): ...

class Translator(jep.PyJObject): ...

class TopLevelWindowListener(jep.PyJObject): ...

class EventQueueMonitor(jep.PyJObject): ...

class AWTEventMonitor(jep.PyJObject): ...

class AccessibilityListenerList(jep.PyJObject): ...

class EventID(jep.PyJObject): ...

class GUIInitializedListener(jep.PyJObject): ...

