import jep

class EventTypeInfo(jep.PyJObject): ...

class FlightRecorderMXBean(jep.PyJObject): ...

class SettingDescriptorInfo(jep.PyJObject): ...

class ConfigurationInfo(jep.PyJObject): ...

class RecordingInfo(jep.PyJObject): ...

