import jep

class EventTypeInfo(jep._PyJObject): ...

class FlightRecorderMXBean(jep._PyJObject): ...

class SettingDescriptorInfo(jep._PyJObject): ...

class ConfigurationInfo(jep._PyJObject): ...

class RecordingInfo(jep._PyJObject): ...

