# pyright: reportPrivateUsage = none

import jep

class SettingDescriptorInfo[**Ts](jep._PyJObject): ...

class EventTypeInfo[**Ts](jep._PyJObject): ...

class FlightRecorderMXBean[**Ts](jep._PyJObject): ...

class RecordingInfo[**Ts](jep._PyJObject): ...

class ConfigurationInfo[**Ts](jep._PyJObject): ...

