import jep

class ResourceRequest(jep.PyJObject): ...

class BoundedMeter(jep.PyJObject): ...

class ResourceAccuracy(jep.PyJObject): ...

class ResourceApprover(jep.PyJObject): ...

class ResourceContextFactory(jep.PyJObject): ...

class ResourceType(jep.PyJObject): ...

class ThrottledMeter(jep.PyJObject): ...

class ResourceId(jep.PyJObject): ...

class SimpleMeter(jep.PyJObject): ...

class ResourceMeter(jep.PyJObject): ...

class ResourceRequestDeniedException(jep.PyJObject): ...

class NotifyingMeter(jep.PyJObject): ...

class ResourceContext(jep.PyJObject): ...

