# pyright: reportPrivateUsage = none

import jep

class ResourceAccuracy[**Ts](jep._PyJObject): ...

class NotifyingMeter[**Ts](jep._PyJObject): ...

class ResourceType[**Ts](jep._PyJObject): ...

class ResourceApprover[**Ts](jep._PyJObject): ...

class ResourceRequestDeniedException[**Ts](jep._PyJObject): ...

class ResourceId[**Ts](jep._PyJObject): ...

class ThrottledMeter[**Ts](jep._PyJObject): ...

class BoundedMeter[**Ts](jep._PyJObject): ...

class ResourceContext[**Ts](jep._PyJObject): ...

class SimpleMeter[**Ts](jep._PyJObject): ...

class ResourceContextFactory[**Ts](jep._PyJObject): ...

class ResourceMeter[**Ts](jep._PyJObject): ...

class ResourceRequest[**Ts](jep._PyJObject): ...

