import jep

class ResourceRequest(jep._PyJObject): ...

class BoundedMeter(jep._PyJObject): ...

class ResourceAccuracy(jep._PyJObject): ...

class ResourceApprover(jep._PyJObject): ...

class ResourceContextFactory(jep._PyJObject): ...

class ResourceType(jep._PyJObject): ...

class ThrottledMeter(jep._PyJObject): ...

class ResourceId(jep._PyJObject): ...

class SimpleMeter(jep._PyJObject): ...

class ResourceMeter(jep._PyJObject): ...

class ResourceRequestDeniedException(jep._PyJObject): ...

class NotifyingMeter(jep._PyJObject): ...

class ResourceContext(jep._PyJObject): ...

