import jep

class InputSource(jep.PyJObject): ...

class ErrorHandler(jep.PyJObject): ...

class SAXException(jep.PyJObject): ...

class HandlerBase(jep.PyJObject): ...

class Parser(jep.PyJObject): ...

class AttributeList(jep.PyJObject): ...

class DTDHandler(jep.PyJObject): ...

class SAXNotSupportedException(jep.PyJObject): ...

class DocumentHandler(jep.PyJObject): ...

class Attributes(jep.PyJObject): ...

class ContentHandler(jep.PyJObject): ...

class EntityResolver(jep.PyJObject): ...

class XMLReader(jep.PyJObject): ...

class Locator(jep.PyJObject): ...

class XMLFilter(jep.PyJObject): ...

class SAXNotRecognizedException(jep.PyJObject): ...

class SAXParseException(jep.PyJObject): ...

