# pyright: reportPrivateUsage = none

import jep

class AttributeList[**Ts](jep._PyJObject): ...

class Attributes[**Ts](jep._PyJObject): ...

class DocumentHandler[**Ts](jep._PyJObject): ...

class Locator[**Ts](jep._PyJObject): ...

class SAXException[**Ts](jep._PyJObject): ...

class EntityResolver[**Ts](jep._PyJObject): ...

class SAXNotRecognizedException[**Ts](jep._PyJObject): ...

class XMLReader[**Ts](jep._PyJObject): ...

class ContentHandler[**Ts](jep._PyJObject): ...

class XMLFilter[**Ts](jep._PyJObject): ...

class HandlerBase[**Ts](jep._PyJObject): ...

class DTDHandler[**Ts](jep._PyJObject): ...

class SAXParseException[**Ts](jep._PyJObject): ...

class InputSource[**Ts](jep._PyJObject): ...

class SAXNotSupportedException[**Ts](jep._PyJObject): ...

class ErrorHandler[**Ts](jep._PyJObject): ...

class Parser[**Ts](jep._PyJObject): ...

