import jep

class InputSource(jep._PyJObject): ...

class ErrorHandler(jep._PyJObject): ...

class SAXException(jep._PyJObject): ...

class HandlerBase(jep._PyJObject): ...

class Parser(jep._PyJObject): ...

class AttributeList(jep._PyJObject): ...

class DTDHandler(jep._PyJObject): ...

class SAXNotSupportedException(jep._PyJObject): ...

class DocumentHandler(jep._PyJObject): ...

class Attributes(jep._PyJObject): ...

class ContentHandler(jep._PyJObject): ...

class EntityResolver(jep._PyJObject): ...

class XMLReader(jep._PyJObject): ...

class Locator(jep._PyJObject): ...

class XMLFilter(jep._PyJObject): ...

class SAXNotRecognizedException(jep._PyJObject): ...

class SAXParseException(jep._PyJObject): ...

