# pyright: reportPrivateUsage = none

import jep

class Locator2Impl[**Ts](jep._PyJObject): ...

class DeclHandler[**Ts](jep._PyJObject): ...

class EntityResolver2[**Ts](jep._PyJObject): ...

class DefaultHandler2[**Ts](jep._PyJObject): ...

class Locator2[**Ts](jep._PyJObject): ...

class LexicalHandler[**Ts](jep._PyJObject): ...

class Attributes2[**Ts](jep._PyJObject): ...

class Attributes2Impl[**Ts](jep._PyJObject): ...

