import jep

class DeclHandler(jep._PyJObject): ...

class DefaultHandler2(jep._PyJObject): ...

class Attributes2Impl(jep._PyJObject): ...

class Locator2(jep._PyJObject): ...

class LexicalHandler(jep._PyJObject): ...

class Locator2Impl(jep._PyJObject): ...

class EntityResolver2(jep._PyJObject): ...

class Attributes2(jep._PyJObject): ...

