import jep

class DeclHandler(jep.PyJObject): ...

class DefaultHandler2(jep.PyJObject): ...

class Attributes2Impl(jep.PyJObject): ...

class Locator2(jep.PyJObject): ...

class LexicalHandler(jep.PyJObject): ...

class Locator2Impl(jep.PyJObject): ...

class EntityResolver2(jep.PyJObject): ...

class Attributes2(jep.PyJObject): ...

