# pyright: reportPrivateUsage = none

import jep

class XMLReaderAdapter[**Ts](jep._PyJObject): ...

class XMLReaderFactory[**Ts](jep._PyJObject): ...

class LocatorImpl[**Ts](jep._PyJObject): ...

class DefaultHandler[**Ts](jep._PyJObject): ...

class AttributesImpl[**Ts](jep._PyJObject): ...

class ParserFactory[**Ts](jep._PyJObject): ...

class ParserAdapter[**Ts](jep._PyJObject): ...

class AttributeListImpl[**Ts](jep._PyJObject): ...

class XMLFilterImpl[**Ts](jep._PyJObject): ...

