import jep

class LocatorImpl(jep._PyJObject): ...

class XMLReaderFactory(jep._PyJObject): ...

class AttributesImpl(jep._PyJObject): ...

class DefaultHandler(jep._PyJObject): ...

class AttributeListImpl(jep._PyJObject): ...

class XMLReaderAdapter(jep._PyJObject): ...

class ParserAdapter(jep._PyJObject): ...

class ParserFactory(jep._PyJObject): ...

class XMLFilterImpl(jep._PyJObject): ...

