import jep

class LocatorImpl(jep.PyJObject): ...

class XMLReaderFactory(jep.PyJObject): ...

class AttributesImpl(jep.PyJObject): ...

class DefaultHandler(jep.PyJObject): ...

class AttributeListImpl(jep.PyJObject): ...

class XMLReaderAdapter(jep.PyJObject): ...

class ParserAdapter(jep.PyJObject): ...

class ParserFactory(jep.PyJObject): ...

class XMLFilterImpl(jep.PyJObject): ...

