import jep

class SignatureProperties(jep.PyJObject): ...

class XMLSignatureFactory(jep.PyJObject): ...

class Reference(jep.PyJObject): ...

class XMLObject(jep.PyJObject): ...

class TransformException(jep.PyJObject): ...

class Transform(jep.PyJObject): ...

class XMLSignature(jep.PyJObject): ...

class TransformService(jep.PyJObject): ...

class SignatureMethod(jep.PyJObject): ...

class SignatureProperty(jep.PyJObject): ...

class CanonicalizationMethod(jep.PyJObject): ...

class Manifest(jep.PyJObject): ...

class DigestMethod(jep.PyJObject): ...

class SignedInfo(jep.PyJObject): ...

class XMLSignContext(jep.PyJObject): ...

class XMLSignatureException(jep.PyJObject): ...

class XMLValidateContext(jep.PyJObject): ...

