# pyright: reportPrivateUsage = none

import jep

class XMLValidateContext[**Ts](jep._PyJObject): ...

class Manifest[**Ts](jep._PyJObject): ...

class XMLSignatureException[**Ts](jep._PyJObject): ...

class SignatureProperties[**Ts](jep._PyJObject): ...

class DigestMethod[**Ts](jep._PyJObject): ...

class CanonicalizationMethod[**Ts](jep._PyJObject): ...

class SignatureMethod[**Ts](jep._PyJObject): ...

class XMLSignature[**Ts](jep._PyJObject): ...

class TransformException[**Ts](jep._PyJObject): ...

class TransformService[**Ts](jep._PyJObject): ...

class XMLSignContext[**Ts](jep._PyJObject): ...

class SignatureProperty[**Ts](jep._PyJObject): ...

class Transform[**Ts](jep._PyJObject): ...

class XMLObject[**Ts](jep._PyJObject): ...

class Reference[**Ts](jep._PyJObject): ...

class SignedInfo[**Ts](jep._PyJObject): ...

class XMLSignatureFactory[**Ts](jep._PyJObject): ...

