import jep

class SignatureProperties(jep._PyJObject): ...

class XMLSignatureFactory(jep._PyJObject): ...

class Reference(jep._PyJObject): ...

class XMLObject(jep._PyJObject): ...

class TransformException(jep._PyJObject): ...

class Transform(jep._PyJObject): ...

class XMLSignature(jep._PyJObject): ...

class TransformService(jep._PyJObject): ...

class SignatureMethod(jep._PyJObject): ...

class SignatureProperty(jep._PyJObject): ...

class CanonicalizationMethod(jep._PyJObject): ...

class Manifest(jep._PyJObject): ...

class DigestMethod(jep._PyJObject): ...

class SignedInfo(jep._PyJObject): ...

class XMLSignContext(jep._PyJObject): ...

class XMLSignatureException(jep._PyJObject): ...

class XMLValidateContext(jep._PyJObject): ...

