# pyright: reportPrivateUsage = none

import jep

class PGPData[**Ts](jep._PyJObject): ...

class X509Data[**Ts](jep._PyJObject): ...

class RetrievalMethod[**Ts](jep._PyJObject): ...

class X509IssuerSerial[**Ts](jep._PyJObject): ...

class KeyValue[**Ts](jep._PyJObject): ...

class KeyName[**Ts](jep._PyJObject): ...

class KeyInfoFactory[**Ts](jep._PyJObject): ...

class KeyInfo[**Ts](jep._PyJObject): ...

