import jep

class KeyValue(jep._PyJObject): ...

class KeyInfo(jep._PyJObject): ...

class RetrievalMethod(jep._PyJObject): ...

class X509Data(jep._PyJObject): ...

class KeyName(jep._PyJObject): ...

class KeyInfoFactory(jep._PyJObject): ...

class X509IssuerSerial(jep._PyJObject): ...

