import jep

class KeyValue(jep.PyJObject): ...

class KeyInfo(jep.PyJObject): ...

class RetrievalMethod(jep.PyJObject): ...

class X509Data(jep.PyJObject): ...

class KeyName(jep.PyJObject): ...

class KeyInfoFactory(jep.PyJObject): ...

class X509IssuerSerial(jep.PyJObject): ...

