import jep

class TransformParameterSpec(jep._PyJObject): ...

class SignatureMethodParameterSpec(jep._PyJObject): ...

class HMACParameterSpec(jep._PyJObject): ...

class XPathFilterParameterSpec(jep._PyJObject): ...

class ExcC14NParameterSpec(jep._PyJObject): ...

class C14NMethodParameterSpec(jep._PyJObject): ...

class XPathFilter2ParameterSpec(jep._PyJObject): ...

class XSLTTransformParameterSpec(jep._PyJObject): ...

class XPathType(jep._PyJObject): ...

class DigestMethodParameterSpec(jep._PyJObject): ...

