import jep

class TransformParameterSpec(jep.PyJObject): ...

class SignatureMethodParameterSpec(jep.PyJObject): ...

class HMACParameterSpec(jep.PyJObject): ...

class XPathFilterParameterSpec(jep.PyJObject): ...

class ExcC14NParameterSpec(jep.PyJObject): ...

class C14NMethodParameterSpec(jep.PyJObject): ...

class XPathFilter2ParameterSpec(jep.PyJObject): ...

class XSLTTransformParameterSpec(jep.PyJObject): ...

class XPathType(jep.PyJObject): ...

class DigestMethodParameterSpec(jep.PyJObject): ...

