# pyright: reportPrivateUsage = none

import jep

class XPathType[**Ts](jep._PyJObject): ...

class SignatureMethodParameterSpec[**Ts](jep._PyJObject): ...

class C14NMethodParameterSpec[**Ts](jep._PyJObject): ...

class XPathFilter2ParameterSpec[**Ts](jep._PyJObject): ...

class XPathFilterParameterSpec[**Ts](jep._PyJObject): ...

class TransformParameterSpec[**Ts](jep._PyJObject): ...

class XSLTTransformParameterSpec[**Ts](jep._PyJObject): ...

class HMACParameterSpec[**Ts](jep._PyJObject): ...

class DigestMethodParameterSpec[**Ts](jep._PyJObject): ...

