# pyright: reportPrivateUsage = none

import jep

class IllegalConnectorArgumentsException[**Ts](jep._PyJObject): ...

class Connector[**Ts](jep._PyJObject): ...

class LaunchingConnector[**Ts](jep._PyJObject): ...

class AttachingConnector[**Ts](jep._PyJObject): ...

class Transport[**Ts](jep._PyJObject): ...

class VMStartException[**Ts](jep._PyJObject): ...

class TransportTimeoutException[**Ts](jep._PyJObject): ...

class ListeningConnector[**Ts](jep._PyJObject): ...

