import jep

class ListeningConnector(jep.PyJObject): ...

class TransportTimeoutException(jep.PyJObject): ...

class LaunchingConnector(jep.PyJObject): ...

class Connector(jep.PyJObject): ...

class IllegalConnectorArgumentsException(jep.PyJObject): ...

class AttachingConnector(jep.PyJObject): ...

class Transport(jep.PyJObject): ...

class VMStartException(jep.PyJObject): ...

