import jep

class ListeningConnector(jep._PyJObject): ...

class TransportTimeoutException(jep._PyJObject): ...

class LaunchingConnector(jep._PyJObject): ...

class Connector(jep._PyJObject): ...

class IllegalConnectorArgumentsException(jep._PyJObject): ...

class AttachingConnector(jep._PyJObject): ...

class Transport(jep._PyJObject): ...

class VMStartException(jep._PyJObject): ...

