import jep

class NashornScriptEngineFactory(jep.PyJObject): ...

class URLReader(jep.PyJObject): ...

class NashornException(jep.PyJObject): ...

class JSObject(jep.PyJObject): ...

class NashornScriptEngine(jep.PyJObject): ...

class ClassFilter(jep.PyJObject): ...

class ScriptUtils(jep.PyJObject): ...

class ScriptObjectMirror(jep.PyJObject): ...

class AbstractJSObject(jep.PyJObject): ...

