import jep

class NashornScriptEngineFactory(jep._PyJObject): ...

class URLReader(jep._PyJObject): ...

class NashornException(jep._PyJObject): ...

class JSObject(jep._PyJObject): ...

class NashornScriptEngine(jep._PyJObject): ...

class ClassFilter(jep._PyJObject): ...

class ScriptUtils(jep._PyJObject): ...

class ScriptObjectMirror(jep._PyJObject): ...

class AbstractJSObject(jep._PyJObject): ...

