# pyright: reportPrivateUsage = none

import jep

class NashornException[**Ts](jep._PyJObject): ...

class AbstractJSObject[**Ts](jep._PyJObject): ...

class NashornScriptEngineFactory[**Ts](jep._PyJObject): ...

class NashornScriptEngine[**Ts](jep._PyJObject): ...

class ScriptUtils[**Ts](jep._PyJObject): ...

class URLReader[**Ts](jep._PyJObject): ...

class ScriptObjectMirror[**Ts](jep._PyJObject): ...

class JSObject[**Ts](jep._PyJObject): ...

class ClassFilter[**Ts](jep._PyJObject): ...

