import jep

class IdentifierTree(jep._PyJObject): ...

class ClassDeclarationTree(jep._PyJObject): ...

class SwitchTree(jep._PyJObject): ...

class PropertyTree(jep._PyJObject): ...

class ReturnTree(jep._PyJObject): ...

class ImportEntryTree(jep._PyJObject): ...

class ErroneousTree(jep._PyJObject): ...

class ForInLoopTree(jep._PyJObject): ...

class BlockTree(jep._PyJObject): ...

class ExpressionTree(jep._PyJObject): ...

class ConditionalLoopTree(jep._PyJObject): ...

class TryTree(jep._PyJObject): ...

class LineMap(jep._PyJObject): ...

class LabeledStatementTree(jep._PyJObject): ...

class ClassExpressionTree(jep._PyJObject): ...

class RegExpLiteralTree(jep._PyJObject): ...

class SimpleTreeVisitorES5_1(jep._PyJObject): ...

class DebuggerTree(jep._PyJObject): ...

class ModuleTree(jep._PyJObject): ...

class ParenthesizedTree(jep._PyJObject): ...

class WithTree(jep._PyJObject): ...

class VariableTree(jep._PyJObject): ...

class CaseTree(jep._PyJObject): ...

class ArrayLiteralTree(jep._PyJObject): ...

class ContinueTree(jep._PyJObject): ...

class CompoundAssignmentTree(jep._PyJObject): ...

class SimpleTreeVisitorES6(jep._PyJObject): ...

class ArrayAccessTree(jep._PyJObject): ...

class StatementTree(jep._PyJObject): ...

class ExpressionStatementTree(jep._PyJObject): ...

class YieldTree(jep._PyJObject): ...

class FunctionExpressionTree(jep._PyJObject): ...

class DoWhileLoopTree(jep._PyJObject): ...

class ConditionalExpressionTree(jep._PyJObject): ...

class LoopTree(jep._PyJObject): ...

class BreakTree(jep._PyJObject): ...

class ObjectLiteralTree(jep._PyJObject): ...

class FunctionDeclarationTree(jep._PyJObject): ...

class CatchTree(jep._PyJObject): ...

class ThrowTree(jep._PyJObject): ...

class GotoTree(jep._PyJObject): ...

class NewTree(jep._PyJObject): ...

class FunctionCallTree(jep._PyJObject): ...

class SpreadTree(jep._PyJObject): ...

class Parser(jep._PyJObject): ...

class BinaryTree(jep._PyJObject): ...

class Tree(jep._PyJObject): ...

class WhileLoopTree(jep._PyJObject): ...

class IfTree(jep._PyJObject): ...

class MemberSelectTree(jep._PyJObject): ...

class TreeVisitor(jep._PyJObject): ...

class ForLoopTree(jep._PyJObject): ...

class AssignmentTree(jep._PyJObject): ...

class ForOfLoopTree(jep._PyJObject): ...

class LiteralTree(jep._PyJObject): ...

class CompilationUnitTree(jep._PyJObject): ...

class EmptyStatementTree(jep._PyJObject): ...

class Diagnostic(jep._PyJObject): ...

class InstanceOfTree(jep._PyJObject): ...

class UnknownTreeException(jep._PyJObject): ...

class TemplateLiteralTree(jep._PyJObject): ...

class UnaryTree(jep._PyJObject): ...

class DiagnosticListener(jep._PyJObject): ...

class ExportEntryTree(jep._PyJObject): ...

