import jep

class IdentifierTree(jep.PyJObject): ...

class ClassDeclarationTree(jep.PyJObject): ...

class SwitchTree(jep.PyJObject): ...

class PropertyTree(jep.PyJObject): ...

class ReturnTree(jep.PyJObject): ...

class ImportEntryTree(jep.PyJObject): ...

class ErroneousTree(jep.PyJObject): ...

class ForInLoopTree(jep.PyJObject): ...

class BlockTree(jep.PyJObject): ...

class ExpressionTree(jep.PyJObject): ...

class ConditionalLoopTree(jep.PyJObject): ...

class TryTree(jep.PyJObject): ...

class LineMap(jep.PyJObject): ...

class LabeledStatementTree(jep.PyJObject): ...

class ClassExpressionTree(jep.PyJObject): ...

class RegExpLiteralTree(jep.PyJObject): ...

class SimpleTreeVisitorES5_1(jep.PyJObject): ...

class DebuggerTree(jep.PyJObject): ...

class ModuleTree(jep.PyJObject): ...

class ParenthesizedTree(jep.PyJObject): ...

class WithTree(jep.PyJObject): ...

class VariableTree(jep.PyJObject): ...

class CaseTree(jep.PyJObject): ...

class ArrayLiteralTree(jep.PyJObject): ...

class ContinueTree(jep.PyJObject): ...

class CompoundAssignmentTree(jep.PyJObject): ...

class SimpleTreeVisitorES6(jep.PyJObject): ...

class ArrayAccessTree(jep.PyJObject): ...

class StatementTree(jep.PyJObject): ...

class ExpressionStatementTree(jep.PyJObject): ...

class YieldTree(jep.PyJObject): ...

class FunctionExpressionTree(jep.PyJObject): ...

class DoWhileLoopTree(jep.PyJObject): ...

class ConditionalExpressionTree(jep.PyJObject): ...

class LoopTree(jep.PyJObject): ...

class BreakTree(jep.PyJObject): ...

class ObjectLiteralTree(jep.PyJObject): ...

class FunctionDeclarationTree(jep.PyJObject): ...

class CatchTree(jep.PyJObject): ...

class ThrowTree(jep.PyJObject): ...

class GotoTree(jep.PyJObject): ...

class NewTree(jep.PyJObject): ...

class FunctionCallTree(jep.PyJObject): ...

class SpreadTree(jep.PyJObject): ...

class Parser(jep.PyJObject): ...

class BinaryTree(jep.PyJObject): ...

class Tree(jep.PyJObject): ...

class WhileLoopTree(jep.PyJObject): ...

class IfTree(jep.PyJObject): ...

class MemberSelectTree(jep.PyJObject): ...

class TreeVisitor(jep.PyJObject): ...

class ForLoopTree(jep.PyJObject): ...

class AssignmentTree(jep.PyJObject): ...

class ForOfLoopTree(jep.PyJObject): ...

class LiteralTree(jep.PyJObject): ...

class CompilationUnitTree(jep.PyJObject): ...

class EmptyStatementTree(jep.PyJObject): ...

class Diagnostic(jep.PyJObject): ...

class InstanceOfTree(jep.PyJObject): ...

class UnknownTreeException(jep.PyJObject): ...

class TemplateLiteralTree(jep.PyJObject): ...

class UnaryTree(jep.PyJObject): ...

class DiagnosticListener(jep.PyJObject): ...

class ExportEntryTree(jep.PyJObject): ...

