# pyright: reportPrivateUsage = none

import jep

class WithTree[**Ts](jep._PyJObject): ...

class NewTree[**Ts](jep._PyJObject): ...

class ReturnTree[**Ts](jep._PyJObject): ...

class TryTree[**Ts](jep._PyJObject): ...

class InstanceOfTree[**Ts](jep._PyJObject): ...

class PropertyTree[**Ts](jep._PyJObject): ...

class UnknownTreeException[**Ts](jep._PyJObject): ...

class ArrayAccessTree[**Ts](jep._PyJObject): ...

class SwitchTree[**Ts](jep._PyJObject): ...

class ExpressionStatementTree[**Ts](jep._PyJObject): ...

class LoopTree[**Ts](jep._PyJObject): ...

class LineMap[**Ts](jep._PyJObject): ...

class TemplateLiteralTree[**Ts](jep._PyJObject): ...

class ExportEntryTree[**Ts](jep._PyJObject): ...

class UnaryTree[**Ts](jep._PyJObject): ...

class Parser[**Ts](jep._PyJObject): ...

class ParenthesizedTree[**Ts](jep._PyJObject): ...

class BlockTree[**Ts](jep._PyJObject): ...

class StatementTree[**Ts](jep._PyJObject): ...

class SimpleTreeVisitorES6[**Ts](jep._PyJObject): ...

class LiteralTree[**Ts](jep._PyJObject): ...

class YieldTree[**Ts](jep._PyJObject): ...

class ConditionalLoopTree[**Ts](jep._PyJObject): ...

class ThrowTree[**Ts](jep._PyJObject): ...

class ImportEntryTree[**Ts](jep._PyJObject): ...

class ContinueTree[**Ts](jep._PyJObject): ...

class ForLoopTree[**Ts](jep._PyJObject): ...

class IdentifierTree[**Ts](jep._PyJObject): ...

class CompilationUnitTree[**Ts](jep._PyJObject): ...

class EmptyStatementTree[**Ts](jep._PyJObject): ...

class DoWhileLoopTree[**Ts](jep._PyJObject): ...

class AssignmentTree[**Ts](jep._PyJObject): ...

class ConditionalExpressionTree[**Ts](jep._PyJObject): ...

class SimpleTreeVisitorES5_1[**Ts](jep._PyJObject): ...

class ObjectLiteralTree[**Ts](jep._PyJObject): ...

class RegExpLiteralTree[**Ts](jep._PyJObject): ...

class LabeledStatementTree[**Ts](jep._PyJObject): ...

class DebuggerTree[**Ts](jep._PyJObject): ...

class CaseTree[**Ts](jep._PyJObject): ...

class CatchTree[**Ts](jep._PyJObject): ...

class BreakTree[**Ts](jep._PyJObject): ...

class FunctionExpressionTree[**Ts](jep._PyJObject): ...

class VariableTree[**Ts](jep._PyJObject): ...

class GotoTree[**Ts](jep._PyJObject): ...

class ArrayLiteralTree[**Ts](jep._PyJObject): ...

class MemberSelectTree[**Ts](jep._PyJObject): ...

class ExpressionTree[**Ts](jep._PyJObject): ...

class ForInLoopTree[**Ts](jep._PyJObject): ...

class SpreadTree[**Ts](jep._PyJObject): ...

class FunctionDeclarationTree[**Ts](jep._PyJObject): ...

class TreeVisitor[**Ts](jep._PyJObject): ...

class ClassDeclarationTree[**Ts](jep._PyJObject): ...

class IfTree[**Ts](jep._PyJObject): ...

class ForOfLoopTree[**Ts](jep._PyJObject): ...

class ModuleTree[**Ts](jep._PyJObject): ...

class ClassExpressionTree[**Ts](jep._PyJObject): ...

class BinaryTree[**Ts](jep._PyJObject): ...

class FunctionCallTree[**Ts](jep._PyJObject): ...

class Diagnostic[**Ts](jep._PyJObject): ...

class WhileLoopTree[**Ts](jep._PyJObject): ...

class CompoundAssignmentTree[**Ts](jep._PyJObject): ...

class DiagnosticListener[**Ts](jep._PyJObject): ...

class ErroneousTree[**Ts](jep._PyJObject): ...

class Tree[**Ts](jep._PyJObject): ...

