import jep

class Predicate(jep._PyJObject): ...

class RowSetMetaDataImpl(jep._PyJObject): ...

class BaseRowSet(jep._PyJObject): ...

class JdbcRowSet(jep._PyJObject): ...

class FilteredRowSet(jep._PyJObject): ...

class RowSetFactory(jep._PyJObject): ...

class Joinable(jep._PyJObject): ...

class RowSetProvider(jep._PyJObject): ...

class WebRowSet(jep._PyJObject): ...

class CachedRowSet(jep._PyJObject): ...

class RowSetWarning(jep._PyJObject): ...

