import jep

class Predicate(jep.PyJObject): ...

class RowSetMetaDataImpl(jep.PyJObject): ...

class BaseRowSet(jep.PyJObject): ...

class JdbcRowSet(jep.PyJObject): ...

class FilteredRowSet(jep.PyJObject): ...

class RowSetFactory(jep.PyJObject): ...

class Joinable(jep.PyJObject): ...

class RowSetProvider(jep.PyJObject): ...

class WebRowSet(jep.PyJObject): ...

class CachedRowSet(jep.PyJObject): ...

class RowSetWarning(jep.PyJObject): ...

