# pyright: reportPrivateUsage = none

import jep

class JoinRowSet[**Ts](jep._PyJObject): ...

class Predicate[**Ts](jep._PyJObject): ...

class CachedRowSet[**Ts](jep._PyJObject): ...

class FilteredRowSet[**Ts](jep._PyJObject): ...

class WebRowSet[**Ts](jep._PyJObject): ...

class JdbcRowSet[**Ts](jep._PyJObject): ...

class BaseRowSet[**Ts](jep._PyJObject): ...

class RowSetFactory[**Ts](jep._PyJObject): ...

class RowSetWarning[**Ts](jep._PyJObject): ...

class Joinable[**Ts](jep._PyJObject): ...

class RowSetProvider[**Ts](jep._PyJObject): ...

class RowSetMetaDataImpl[**Ts](jep._PyJObject): ...

