# pyright: reportPrivateUsage = none

import jep

class SerialBlob[**Ts](jep._PyJObject): ...

class SQLOutputImpl[**Ts](jep._PyJObject): ...

class SerialJavaObject[**Ts](jep._PyJObject): ...

class SerialDatalink[**Ts](jep._PyJObject): ...

class SQLInputImpl[**Ts](jep._PyJObject): ...

class SerialException[**Ts](jep._PyJObject): ...

class SerialRef[**Ts](jep._PyJObject): ...

class SerialArray[**Ts](jep._PyJObject): ...

class SerialClob[**Ts](jep._PyJObject): ...

class SerialStruct[**Ts](jep._PyJObject): ...

