import jep

class SerialException(jep.PyJObject): ...

class SerialBlob(jep.PyJObject): ...

class SerialStruct(jep.PyJObject): ...

class SQLInputImpl(jep.PyJObject): ...

class SQLOutputImpl(jep.PyJObject): ...

class SerialArray(jep.PyJObject): ...

class SerialClob(jep.PyJObject): ...

class SerialJavaObject(jep.PyJObject): ...

class SerialDatalink(jep.PyJObject): ...

