import jep

class SerialException(jep._PyJObject): ...

class SerialBlob(jep._PyJObject): ...

class SerialStruct(jep._PyJObject): ...

class SQLInputImpl(jep._PyJObject): ...

class SQLOutputImpl(jep._PyJObject): ...

class SerialArray(jep._PyJObject): ...

class SerialClob(jep._PyJObject): ...

class SerialJavaObject(jep._PyJObject): ...

class SerialDatalink(jep._PyJObject): ...

