# pyright: reportPrivateUsage = none

import jep

class SyncFactoryException[**Ts](jep._PyJObject): ...

class TransactionalWriter[**Ts](jep._PyJObject): ...

class XmlReader[**Ts](jep._PyJObject): ...

class SyncFactory[**Ts](jep._PyJObject): ...

class SyncProviderException[**Ts](jep._PyJObject): ...

class SyncResolver[**Ts](jep._PyJObject): ...

class SyncProvider[**Ts](jep._PyJObject): ...

