import jep

class SyncProvider(jep._PyJObject): ...

class XmlWriter(jep._PyJObject): ...

class TransactionalWriter(jep._PyJObject): ...

class SyncResolver(jep._PyJObject): ...

class SyncFactoryException(jep._PyJObject): ...

class XmlReader(jep._PyJObject): ...

class SyncProviderException(jep._PyJObject): ...

class SyncFactory(jep._PyJObject): ...

