import jep

class SyncProvider(jep.PyJObject): ...

class XmlWriter(jep.PyJObject): ...

class TransactionalWriter(jep.PyJObject): ...

class SyncResolver(jep.PyJObject): ...

class SyncFactoryException(jep.PyJObject): ...

class XmlReader(jep.PyJObject): ...

class SyncProviderException(jep.PyJObject): ...

class SyncFactory(jep.PyJObject): ...

