# pyright: reportPrivateUsage = none

import jep

class AppletStub[**Ts](jep._PyJObject): ...

class Applet[**Ts](jep._PyJObject): ...

class AppletContext[**Ts](jep._PyJObject): ...

class AudioClip[**Ts](jep._PyJObject): ...

