import jep

class FileInputStream(jep._PyJObject): ...

class EOFException(jep._PyJObject): ...

class StringWriter(jep._PyJObject): ...

class CharArrayWriter(jep._PyJObject): ...

class OptionalDataException(jep._PyJObject): ...

class ObjectInput(jep._PyJObject): ...

class FilterInputStream(jep._PyJObject): ...

class InvalidClassException(jep._PyJObject): ...

class SequenceInputStream(jep._PyJObject): ...

class Console(jep._PyJObject): ...

class BufferedInputStream(jep._PyJObject): ...

class PipedOutputStream(jep._PyJObject): ...

class WriteAbortedException(jep._PyJObject): ...

class FileWriter(jep._PyJObject): ...

class Reader(jep._PyJObject): ...

class ObjectStreamClass(jep._PyJObject): ...

class ObjectInputStream(jep._PyJObject): ...

class SerializablePermission(jep._PyJObject): ...

class Closeable(jep._PyJObject): ...

class Externalizable(jep._PyJObject): ...

class InterruptedIOException(jep._PyJObject): ...

class FilenameFilter(jep._PyJObject): ...

class ByteArrayInputStream(jep._PyJObject): ...

class UncheckedIOException(jep._PyJObject): ...

class UnsupportedEncodingException(jep._PyJObject): ...

class FilterReader(jep._PyJObject): ...

class CharConversionException(jep._PyJObject): ...

class FileNotFoundException(jep._PyJObject): ...

class LineNumberInputStream(jep._PyJObject): ...

class PipedWriter(jep._PyJObject): ...

class StringReader(jep._PyJObject): ...

class InputStreamReader(jep._PyJObject): ...

class ByteArrayOutputStream(jep._PyJObject): ...

class CharArrayReader(jep._PyJObject): ...

class FilterWriter(jep._PyJObject): ...

class File(jep._PyJObject): ...

class OutputStreamWriter(jep._PyJObject): ...

class PrintWriter(jep._PyJObject): ...

class LineNumberReader(jep._PyJObject): ...

class DataOutput(jep._PyJObject): ...

class InputStream(jep._PyJObject): ...

class PrintStream(jep._PyJObject): ...

class PipedInputStream(jep._PyJObject): ...

class NotSerializableException(jep._PyJObject): ...

class BufferedOutputStream(jep._PyJObject): ...

class FileReader(jep._PyJObject): ...

class ObjectStreamException(jep._PyJObject): ...

class StringBufferInputStream(jep._PyJObject): ...

class SyncFailedException(jep._PyJObject): ...

class ObjectOutputStream(jep._PyJObject): ...

class Serializable(jep._PyJObject): ...

class Flushable(jep._PyJObject): ...

class DataInputStream(jep._PyJObject): ...

class PipedReader(jep._PyJObject): ...

class PushbackReader(jep._PyJObject): ...

class FilterOutputStream(jep._PyJObject): ...

class FileDescriptor(jep._PyJObject): ...

class InvalidObjectException(jep._PyJObject): ...

class FileOutputStream(jep._PyJObject): ...

class ObjectStreamField(jep._PyJObject): ...

class RandomAccessFile(jep._PyJObject): ...

class FileFilter(jep._PyJObject): ...

class StreamCorruptedException(jep._PyJObject): ...

class DataInput(jep._PyJObject): ...

class UTFDataFormatException(jep._PyJObject): ...

class FilePermission(jep._PyJObject): ...

class IOException(jep._PyJObject): ...

class ObjectInputFilter(jep._PyJObject): ...

class DataOutputStream(jep._PyJObject): ...

class NotActiveException(jep._PyJObject): ...

class BufferedReader(jep._PyJObject): ...

class StreamTokenizer(jep._PyJObject): ...

class PushbackInputStream(jep._PyJObject): ...

class ObjectOutput(jep._PyJObject): ...

class IOError(jep._PyJObject): ...

class OutputStream(jep._PyJObject): ...

class Writer(jep._PyJObject): ...

class BufferedWriter(jep._PyJObject): ...

class ObjectInputValidation(jep._PyJObject): ...

class ObjectStreamConstants(jep._PyJObject): ...

