import jep

class FileInputStream(jep.PyJObject): ...

class EOFException(jep.PyJObject): ...

class StringWriter(jep.PyJObject): ...

class CharArrayWriter(jep.PyJObject): ...

class OptionalDataException(jep.PyJObject): ...

class ObjectInput(jep.PyJObject): ...

class FilterInputStream(jep.PyJObject): ...

class InvalidClassException(jep.PyJObject): ...

class SequenceInputStream(jep.PyJObject): ...

class Console(jep.PyJObject): ...

class BufferedInputStream(jep.PyJObject): ...

class PipedOutputStream(jep.PyJObject): ...

class WriteAbortedException(jep.PyJObject): ...

class FileWriter(jep.PyJObject): ...

class Reader(jep.PyJObject): ...

class ObjectStreamClass(jep.PyJObject): ...

class ObjectInputStream(jep.PyJObject): ...

class SerializablePermission(jep.PyJObject): ...

class Closeable(jep.PyJObject): ...

class Externalizable(jep.PyJObject): ...

class InterruptedIOException(jep.PyJObject): ...

class FilenameFilter(jep.PyJObject): ...

class ByteArrayInputStream(jep.PyJObject): ...

class UncheckedIOException(jep.PyJObject): ...

class UnsupportedEncodingException(jep.PyJObject): ...

class FilterReader(jep.PyJObject): ...

class CharConversionException(jep.PyJObject): ...

class FileNotFoundException(jep.PyJObject): ...

class LineNumberInputStream(jep.PyJObject): ...

class PipedWriter(jep.PyJObject): ...

class StringReader(jep.PyJObject): ...

class InputStreamReader(jep.PyJObject): ...

class ByteArrayOutputStream(jep.PyJObject): ...

class CharArrayReader(jep.PyJObject): ...

class FilterWriter(jep.PyJObject): ...

class File(jep.PyJObject): ...

class OutputStreamWriter(jep.PyJObject): ...

class PrintWriter(jep.PyJObject): ...

class LineNumberReader(jep.PyJObject): ...

class DataOutput(jep.PyJObject): ...

class InputStream(jep.PyJObject): ...

class PrintStream(jep.PyJObject): ...

class PipedInputStream(jep.PyJObject): ...

class NotSerializableException(jep.PyJObject): ...

class BufferedOutputStream(jep.PyJObject): ...

class FileReader(jep.PyJObject): ...

class ObjectStreamException(jep.PyJObject): ...

class StringBufferInputStream(jep.PyJObject): ...

class SyncFailedException(jep.PyJObject): ...

class ObjectOutputStream(jep.PyJObject): ...

class Serializable(jep.PyJObject): ...

class Flushable(jep.PyJObject): ...

class DataInputStream(jep.PyJObject): ...

class PipedReader(jep.PyJObject): ...

class PushbackReader(jep.PyJObject): ...

class FilterOutputStream(jep.PyJObject): ...

class FileDescriptor(jep.PyJObject): ...

class InvalidObjectException(jep.PyJObject): ...

class FileOutputStream(jep.PyJObject): ...

class ObjectStreamField(jep.PyJObject): ...

class RandomAccessFile(jep.PyJObject): ...

class FileFilter(jep.PyJObject): ...

class StreamCorruptedException(jep.PyJObject): ...

class DataInput(jep.PyJObject): ...

class UTFDataFormatException(jep.PyJObject): ...

class FilePermission(jep.PyJObject): ...

class IOException(jep.PyJObject): ...

class ObjectInputFilter(jep.PyJObject): ...

class DataOutputStream(jep.PyJObject): ...

class NotActiveException(jep.PyJObject): ...

class BufferedReader(jep.PyJObject): ...

class StreamTokenizer(jep.PyJObject): ...

class PushbackInputStream(jep.PyJObject): ...

class ObjectOutput(jep.PyJObject): ...

class IOError(jep.PyJObject): ...

class OutputStream(jep.PyJObject): ...

class Writer(jep.PyJObject): ...

class BufferedWriter(jep.PyJObject): ...

class ObjectInputValidation(jep.PyJObject): ...

class ObjectStreamConstants(jep.PyJObject): ...

