# pyright: reportPrivateUsage = none

import jep

class StreamTokenizer[**Ts](jep._PyJObject): ...

class ObjectInputValidation[**Ts](jep._PyJObject): ...

class FileReader[**Ts](jep._PyJObject): ...

class ObjectInputFilter[**Ts](jep._PyJObject): ...

class SerializablePermission[**Ts](jep._PyJObject): ...

class FileOutputStream[**Ts](jep._PyJObject): ...

class Flushable[**Ts](jep._PyJObject): ...

class ObjectStreamException[**Ts](jep._PyJObject): ...

class BufferedWriter[**Ts](jep._PyJObject): ...

class UncheckedIOException[**Ts](jep._PyJObject): ...

class EOFException[**Ts](jep._PyJObject): ...

class PipedReader[**Ts](jep._PyJObject): ...

class NotSerializableException[**Ts](jep._PyJObject): ...

class PipedOutputStream[**Ts](jep._PyJObject): ...

class BufferedReader[**Ts](jep._PyJObject): ...

class ByteArrayOutputStream[**Ts](jep._PyJObject): ...

class FilterOutputStream[**Ts](jep._PyJObject): ...

class Closeable[**Ts](jep._PyJObject): ...

class FilenameFilter[**Ts](jep._PyJObject): ...

class Writer[**Ts](jep._PyJObject): ...

class CharArrayWriter[**Ts](jep._PyJObject): ...

class ObjectInput[**Ts](jep._PyJObject): ...

class File[**Ts](jep._PyJObject): ...

class StringWriter[**Ts](jep._PyJObject): ...

class DataOutput[**Ts](jep._PyJObject): ...

class FileDescriptor[**Ts](jep._PyJObject): ...

class FilterReader[**Ts](jep._PyJObject): ...

class UTFDataFormatException[**Ts](jep._PyJObject): ...

class PipedInputStream[**Ts](jep._PyJObject): ...

class LineNumberInputStream[**Ts](jep._PyJObject): ...

class CharArrayReader[**Ts](jep._PyJObject): ...

class DataInputStream[**Ts](jep._PyJObject): ...

class BufferedInputStream[**Ts](jep._PyJObject): ...

class InvalidObjectException[**Ts](jep._PyJObject): ...

class InvalidClassException[**Ts](jep._PyJObject): ...

class PushbackReader[**Ts](jep._PyJObject): ...

class ObjectInputStream[**Ts](jep._PyJObject): ...

class BufferedOutputStream[**Ts](jep._PyJObject): ...

class InputStreamReader[**Ts](jep._PyJObject): ...

class ObjectStreamField[**Ts](jep._PyJObject): ...

class FileWriter[**Ts](jep._PyJObject): ...

class Serializable[**Ts](jep._PyJObject): ...

class StringReader[**Ts](jep._PyJObject): ...

class InterruptedIOException[**Ts](jep._PyJObject): ...

class InputStream[**Ts](jep._PyJObject): ...

class FilterWriter[**Ts](jep._PyJObject): ...

class ObjectOutputStream[**Ts](jep._PyJObject): ...

class WriteAbortedException[**Ts](jep._PyJObject): ...

class PrintWriter[**Ts](jep._PyJObject): ...

class IOException[**Ts](jep._PyJObject): ...

class ObjectOutput[**Ts](jep._PyJObject): ...

class DataOutputStream[**Ts](jep._PyJObject): ...

class IOError[**Ts](jep._PyJObject): ...

class LineNumberReader[**Ts](jep._PyJObject): ...

class FilterInputStream[**Ts](jep._PyJObject): ...

class Externalizable[**Ts](jep._PyJObject): ...

class ObjectStreamConstants[**Ts](jep._PyJObject): ...

class OptionalDataException[**Ts](jep._PyJObject): ...

class ObjectStreamClass[**Ts](jep._PyJObject): ...

class DataInput[**Ts](jep._PyJObject): ...

class PrintStream[**Ts](jep._PyJObject): ...

class OutputStream[**Ts](jep._PyJObject): ...

class CharConversionException[**Ts](jep._PyJObject): ...

class NotActiveException[**Ts](jep._PyJObject): ...

class FileInputStream[**Ts](jep._PyJObject): ...

class ByteArrayInputStream[**Ts](jep._PyJObject): ...

class FileFilter[**Ts](jep._PyJObject): ...

class Console[**Ts](jep._PyJObject): ...

class StringBufferInputStream[**Ts](jep._PyJObject): ...

class PushbackInputStream[**Ts](jep._PyJObject): ...

class OutputStreamWriter[**Ts](jep._PyJObject): ...

class RandomAccessFile[**Ts](jep._PyJObject): ...

class FileNotFoundException[**Ts](jep._PyJObject): ...

class Reader[**Ts](jep._PyJObject): ...

class PipedWriter[**Ts](jep._PyJObject): ...

class FilePermission[**Ts](jep._PyJObject): ...

class StreamCorruptedException[**Ts](jep._PyJObject): ...

class UnsupportedEncodingException[**Ts](jep._PyJObject): ...

class SyncFailedException[**Ts](jep._PyJObject): ...

class SequenceInputStream[**Ts](jep._PyJObject): ...

