# pyright: reportPrivateUsage = none

import jep

class BigDecimal[**Ts](jep._PyJObject): ...

class BigInteger[**Ts](jep._PyJObject): ...

class RoundingMode[**Ts](jep._PyJObject): ...

class MathContext[**Ts](jep._PyJObject): ...

