import jep

class PseudoColumnUsage(jep.PyJObject): ...

class ShardingKeyBuilder(jep.PyJObject): ...

class ClientInfoStatus(jep.PyJObject): ...

class SQLNonTransientConnectionException(jep.PyJObject): ...

class CallableStatement(jep.PyJObject): ...

class Ref(jep.PyJObject): ...

class Time(jep.PyJObject): ...

class JDBCType(jep.PyJObject): ...

class SQLOutput(jep.PyJObject): ...

class DriverPropertyInfo(jep.PyJObject): ...

class SQLDataException(jep.PyJObject): ...

class ConnectionBuilder(jep.PyJObject): ...

class BatchUpdateException(jep.PyJObject): ...

class Types(jep.PyJObject): ...

class ResultSetMetaData(jep.PyJObject): ...

class SQLTimeoutException(jep.PyJObject): ...

class Struct(jep.PyJObject): ...

class DriverAction(jep.PyJObject): ...

class NClob(jep.PyJObject): ...

class SQLPermission(jep.PyJObject): ...

class SQLData(jep.PyJObject): ...

class SQLException(jep.PyJObject): ...

class Connection(jep.PyJObject): ...

class ParameterMetaData(jep.PyJObject): ...

class DatabaseMetaData(jep.PyJObject): ...

class SQLWarning(jep.PyJObject): ...

class Wrapper(jep.PyJObject): ...

class SQLXML(jep.PyJObject): ...

class SQLTransactionRollbackException(jep.PyJObject): ...

class Timestamp(jep.PyJObject): ...

class SQLNonTransientException(jep.PyJObject): ...

class Statement(jep.PyJObject): ...

class SQLSyntaxErrorException(jep.PyJObject): ...

class SQLInput(jep.PyJObject): ...

class SQLTransientException(jep.PyJObject): ...

class SQLTransientConnectionException(jep.PyJObject): ...

class RowIdLifetime(jep.PyJObject): ...

class Driver(jep.PyJObject): ...

class DriverManager(jep.PyJObject): ...

class Savepoint(jep.PyJObject): ...

class SQLRecoverableException(jep.PyJObject): ...

class SQLClientInfoException(jep.PyJObject): ...

class SQLInvalidAuthorizationSpecException(jep.PyJObject): ...

class ShardingKey(jep.PyJObject): ...

class DataTruncation(jep.PyJObject): ...

class Clob(jep.PyJObject): ...

class RowId(jep.PyJObject): ...

class SQLType(jep.PyJObject): ...

class ResultSet(jep.PyJObject): ...

class Date(jep.PyJObject): ...

class SQLFeatureNotSupportedException(jep.PyJObject): ...

class Array(jep.PyJObject): ...

class Blob(jep.PyJObject): ...

class SQLIntegrityConstraintViolationException(jep.PyJObject): ...

class PreparedStatement(jep.PyJObject): ...

