# pyright: reportPrivateUsage = none

import jep

class BatchUpdateException[**Ts](jep._PyJObject): ...

class DatabaseMetaData[**Ts](jep._PyJObject): ...

class CallableStatement[**Ts](jep._PyJObject): ...

class ResultSetMetaData[**Ts](jep._PyJObject): ...

class SQLPermission[**Ts](jep._PyJObject): ...

class SQLData[**Ts](jep._PyJObject): ...

class SQLInvalidAuthorizationSpecException[**Ts](jep._PyJObject): ...

class RowId[**Ts](jep._PyJObject): ...

class SQLTransientConnectionException[**Ts](jep._PyJObject): ...

class SQLException[**Ts](jep._PyJObject): ...

class ClientInfoStatus[**Ts](jep._PyJObject): ...

class ConnectionBuilder[**Ts](jep._PyJObject): ...

class Types[**Ts](jep._PyJObject): ...

class Time[**Ts](jep._PyJObject): ...

class PreparedStatement[**Ts](jep._PyJObject): ...

class SQLTimeoutException[**Ts](jep._PyJObject): ...

class Date[**Ts](jep._PyJObject): ...

class SQLDataException[**Ts](jep._PyJObject): ...

class DataTruncation[**Ts](jep._PyJObject): ...

class Statement[**Ts](jep._PyJObject): ...

class Timestamp[**Ts](jep._PyJObject): ...

class SQLXML[**Ts](jep._PyJObject): ...

class SQLNonTransientConnectionException[**Ts](jep._PyJObject): ...

class RowIdLifetime[**Ts](jep._PyJObject): ...

class SQLOutput[**Ts](jep._PyJObject): ...

class Wrapper[**Ts](jep._PyJObject): ...

class NClob[**Ts](jep._PyJObject): ...

class SQLType[**Ts](jep._PyJObject): ...

class Clob[**Ts](jep._PyJObject): ...

class ShardingKey[**Ts](jep._PyJObject): ...

class SQLWarning[**Ts](jep._PyJObject): ...

class JDBCType[**Ts](jep._PyJObject): ...

class SQLRecoverableException[**Ts](jep._PyJObject): ...

class SQLTransactionRollbackException[**Ts](jep._PyJObject): ...

class SQLInput[**Ts](jep._PyJObject): ...

class ResultSet[**Ts](jep._PyJObject): ...

class DriverPropertyInfo[**Ts](jep._PyJObject): ...

class Array[**Ts](jep._PyJObject): ...

class Driver[**Ts](jep._PyJObject): ...

class SQLTransientException[**Ts](jep._PyJObject): ...

class SQLClientInfoException[**Ts](jep._PyJObject): ...

class Savepoint[**Ts](jep._PyJObject): ...

class Connection[**Ts](jep._PyJObject): ...

class ShardingKeyBuilder[**Ts](jep._PyJObject): ...

class DriverManager[**Ts](jep._PyJObject): ...

class DriverAction[**Ts](jep._PyJObject): ...

class Blob[**Ts](jep._PyJObject): ...

class SQLNonTransientException[**Ts](jep._PyJObject): ...

class SQLIntegrityConstraintViolationException[**Ts](jep._PyJObject): ...

class ParameterMetaData[**Ts](jep._PyJObject): ...

class PseudoColumnUsage[**Ts](jep._PyJObject): ...

class Struct[**Ts](jep._PyJObject): ...

class SQLFeatureNotSupportedException[**Ts](jep._PyJObject): ...

class Ref[**Ts](jep._PyJObject): ...

class SQLSyntaxErrorException[**Ts](jep._PyJObject): ...

