import jep

class PseudoColumnUsage(jep._PyJObject): ...

class ShardingKeyBuilder(jep._PyJObject): ...

class ClientInfoStatus(jep._PyJObject): ...

class SQLNonTransientConnectionException(jep._PyJObject): ...

class CallableStatement(jep._PyJObject): ...

class Ref(jep._PyJObject): ...

class Time(jep._PyJObject): ...

class JDBCType(jep._PyJObject): ...

class SQLOutput(jep._PyJObject): ...

class DriverPropertyInfo(jep._PyJObject): ...

class SQLDataException(jep._PyJObject): ...

class ConnectionBuilder(jep._PyJObject): ...

class BatchUpdateException(jep._PyJObject): ...

class Types(jep._PyJObject): ...

class ResultSetMetaData(jep._PyJObject): ...

class SQLTimeoutException(jep._PyJObject): ...

class Struct(jep._PyJObject): ...

class DriverAction(jep._PyJObject): ...

class NClob(jep._PyJObject): ...

class SQLPermission(jep._PyJObject): ...

class SQLData(jep._PyJObject): ...

class SQLException(jep._PyJObject): ...

class Connection(jep._PyJObject): ...

class ParameterMetaData(jep._PyJObject): ...

class DatabaseMetaData(jep._PyJObject): ...

class SQLWarning(jep._PyJObject): ...

class Wrapper(jep._PyJObject): ...

class SQLXML(jep._PyJObject): ...

class SQLTransactionRollbackException(jep._PyJObject): ...

class Timestamp(jep._PyJObject): ...

class SQLNonTransientException(jep._PyJObject): ...

class Statement(jep._PyJObject): ...

class SQLSyntaxErrorException(jep._PyJObject): ...

class SQLInput(jep._PyJObject): ...

class SQLTransientException(jep._PyJObject): ...

class SQLTransientConnectionException(jep._PyJObject): ...

class RowIdLifetime(jep._PyJObject): ...

class Driver(jep._PyJObject): ...

class DriverManager(jep._PyJObject): ...

class Savepoint(jep._PyJObject): ...

class SQLRecoverableException(jep._PyJObject): ...

class SQLClientInfoException(jep._PyJObject): ...

class SQLInvalidAuthorizationSpecException(jep._PyJObject): ...

class ShardingKey(jep._PyJObject): ...

class DataTruncation(jep._PyJObject): ...

class Clob(jep._PyJObject): ...

class RowId(jep._PyJObject): ...

class SQLType(jep._PyJObject): ...

class ResultSet(jep._PyJObject): ...

class Date(jep._PyJObject): ...

class SQLFeatureNotSupportedException(jep._PyJObject): ...

class Array(jep._PyJObject): ...

class Blob(jep._PyJObject): ...

class SQLIntegrityConstraintViolationException(jep._PyJObject): ...

class PreparedStatement(jep._PyJObject): ...

