import jep

class ExceptionDetailMessage(jep.PyJObject): ...

class TAG_MULTIPLE_COMPONENTS(jep.PyJObject): ...

class TAG_POLICIES(jep.PyJObject): ...

class CodecFactory(jep.PyJObject): ...

class ServiceContextListHelper(jep.PyJObject): ...

class ENCODING_CDR_ENCAPS(jep.PyJObject): ...

class ComponentIdHelper(jep.PyJObject): ...

class CodecFactoryHelper(jep.PyJObject): ...

class TAG_CODE_SETS(jep.PyJObject): ...

class TaggedProfileHolder(jep.PyJObject): ...

class ServiceContextHelper(jep.PyJObject): ...

class ServiceContextHolder(jep.PyJObject): ...

class TAG_RMI_CUSTOM_MAX_STREAM_FORMAT(jep.PyJObject): ...

class TAG_INTERNET_IOP(jep.PyJObject): ...

class ProfileIdHelper(jep.PyJObject): ...

class IORHolder(jep.PyJObject): ...

class TaggedProfileHelper(jep.PyJObject): ...

class CodecOperations(jep.PyJObject): ...

class MultipleComponentProfileHelper(jep.PyJObject): ...

class ServiceIdHelper(jep.PyJObject): ...

class IOR(jep.PyJObject): ...

class TaggedComponent(jep.PyJObject): ...

class MultipleComponentProfileHolder(jep.PyJObject): ...

class TransactionService(jep.PyJObject): ...

class IORHelper(jep.PyJObject): ...

class TAG_JAVA_CODEBASE(jep.PyJObject): ...

class ServiceContextListHolder(jep.PyJObject): ...

class TaggedComponentHolder(jep.PyJObject): ...

class TaggedProfile(jep.PyJObject): ...

class ServiceContext(jep.PyJObject): ...

class TAG_ORB_TYPE(jep.PyJObject): ...

class Encoding(jep.PyJObject): ...

class TaggedComponentHelper(jep.PyJObject): ...

class CodecFactoryOperations(jep.PyJObject): ...

class RMICustomMaxStreamFormat(jep.PyJObject): ...

class Codec(jep.PyJObject): ...

class CodeSets(jep.PyJObject): ...

class TAG_ALTERNATE_IIOP_ADDRESS(jep.PyJObject): ...

