import jep

class ExceptionDetailMessage(jep._PyJObject): ...

class TAG_MULTIPLE_COMPONENTS(jep._PyJObject): ...

class TAG_POLICIES(jep._PyJObject): ...

class CodecFactory(jep._PyJObject): ...

class ServiceContextListHelper(jep._PyJObject): ...

class ENCODING_CDR_ENCAPS(jep._PyJObject): ...

class ComponentIdHelper(jep._PyJObject): ...

class CodecFactoryHelper(jep._PyJObject): ...

class TAG_CODE_SETS(jep._PyJObject): ...

class TaggedProfileHolder(jep._PyJObject): ...

class ServiceContextHelper(jep._PyJObject): ...

class ServiceContextHolder(jep._PyJObject): ...

class TAG_RMI_CUSTOM_MAX_STREAM_FORMAT(jep._PyJObject): ...

class TAG_INTERNET_IOP(jep._PyJObject): ...

class ProfileIdHelper(jep._PyJObject): ...

class IORHolder(jep._PyJObject): ...

class TaggedProfileHelper(jep._PyJObject): ...

class CodecOperations(jep._PyJObject): ...

class MultipleComponentProfileHelper(jep._PyJObject): ...

class ServiceIdHelper(jep._PyJObject): ...

class IOR(jep._PyJObject): ...

class TaggedComponent(jep._PyJObject): ...

class MultipleComponentProfileHolder(jep._PyJObject): ...

class TransactionService(jep._PyJObject): ...

class IORHelper(jep._PyJObject): ...

class TAG_JAVA_CODEBASE(jep._PyJObject): ...

class ServiceContextListHolder(jep._PyJObject): ...

class TaggedComponentHolder(jep._PyJObject): ...

class TaggedProfile(jep._PyJObject): ...

class ServiceContext(jep._PyJObject): ...

class TAG_ORB_TYPE(jep._PyJObject): ...

class Encoding(jep._PyJObject): ...

class TaggedComponentHelper(jep._PyJObject): ...

class CodecFactoryOperations(jep._PyJObject): ...

class RMICustomMaxStreamFormat(jep._PyJObject): ...

class Codec(jep._PyJObject): ...

class CodeSets(jep._PyJObject): ...

class TAG_ALTERNATE_IIOP_ADDRESS(jep._PyJObject): ...

