# pyright: reportPrivateUsage = none

import jep

class CodecOperations[**Ts](jep._PyJObject): ...

class ServiceIdHelper[**Ts](jep._PyJObject): ...

class TAG_POLICIES[**Ts](jep._PyJObject): ...

class Encoding[**Ts](jep._PyJObject): ...

class CodecFactoryOperations[**Ts](jep._PyJObject): ...

class RMICustomMaxStreamFormat[**Ts](jep._PyJObject): ...

class CodecFactory[**Ts](jep._PyJObject): ...

class TAG_INTERNET_IOP[**Ts](jep._PyJObject): ...

class TaggedComponent[**Ts](jep._PyJObject): ...

class ServiceContext[**Ts](jep._PyJObject): ...

class ComponentIdHelper[**Ts](jep._PyJObject): ...

class TAG_JAVA_CODEBASE[**Ts](jep._PyJObject): ...

class TAG_ORB_TYPE[**Ts](jep._PyJObject): ...

class IOR[**Ts](jep._PyJObject): ...

class TAG_ALTERNATE_IIOP_ADDRESS[**Ts](jep._PyJObject): ...

class ENCODING_CDR_ENCAPS[**Ts](jep._PyJObject): ...

class TaggedProfileHelper[**Ts](jep._PyJObject): ...

class TaggedProfileHolder[**Ts](jep._PyJObject): ...

class ExceptionDetailMessage[**Ts](jep._PyJObject): ...

class Codec[**Ts](jep._PyJObject): ...

class CodeSets[**Ts](jep._PyJObject): ...

class IORHolder[**Ts](jep._PyJObject): ...

class TaggedProfile[**Ts](jep._PyJObject): ...

class TransactionService[**Ts](jep._PyJObject): ...

class ServiceContextListHolder[**Ts](jep._PyJObject): ...

class TAG_RMI_CUSTOM_MAX_STREAM_FORMAT[**Ts](jep._PyJObject): ...

class CodecFactoryHelper[**Ts](jep._PyJObject): ...

class ServiceContextHelper[**Ts](jep._PyJObject): ...

class IORHelper[**Ts](jep._PyJObject): ...

class TaggedComponentHelper[**Ts](jep._PyJObject): ...

class MultipleComponentProfileHelper[**Ts](jep._PyJObject): ...

class TaggedComponentHolder[**Ts](jep._PyJObject): ...

class TAG_MULTIPLE_COMPONENTS[**Ts](jep._PyJObject): ...

class ProfileIdHelper[**Ts](jep._PyJObject): ...

class ServiceContextListHelper[**Ts](jep._PyJObject): ...

class TAG_CODE_SETS[**Ts](jep._PyJObject): ...

class MultipleComponentProfileHolder[**Ts](jep._PyJObject): ...

class ServiceContextHolder[**Ts](jep._PyJObject): ...

