import jep

class InvalidTypeForEncoding(jep._PyJObject): ...

class InvalidTypeForEncodingHelper(jep._PyJObject): ...

class FormatMismatchHelper(jep._PyJObject): ...

class TypeMismatch(jep._PyJObject): ...

class FormatMismatch(jep._PyJObject): ...

