import jep

class InvalidTypeForEncoding(jep.PyJObject): ...

class InvalidTypeForEncodingHelper(jep.PyJObject): ...

class FormatMismatchHelper(jep.PyJObject): ...

class TypeMismatch(jep.PyJObject): ...

class FormatMismatch(jep.PyJObject): ...

