# pyright: reportPrivateUsage = none

import jep

class TypeMismatchHelper[**Ts](jep._PyJObject): ...

class FormatMismatch[**Ts](jep._PyJObject): ...

class InvalidTypeForEncoding[**Ts](jep._PyJObject): ...

class InvalidTypeForEncodingHelper[**Ts](jep._PyJObject): ...

class TypeMismatch[**Ts](jep._PyJObject): ...

class FormatMismatchHelper[**Ts](jep._PyJObject): ...

