# pyright: reportPrivateUsage = none

import jep

class UnmarshalException[**Ts](jep._PyJObject): ...

class DatatypeConverter[**Ts](jep._PyJObject): ...

class ValidationEventHandler[**Ts](jep._PyJObject): ...

class TypeConstraintException[**Ts](jep._PyJObject): ...

class PropertyException[**Ts](jep._PyJObject): ...

class JAXBIntrospector[**Ts](jep._PyJObject): ...

class JAXBPermission[**Ts](jep._PyJObject): ...

class ValidationEvent[**Ts](jep._PyJObject): ...

class Element[**Ts](jep._PyJObject): ...

class MarshalException[**Ts](jep._PyJObject): ...

class ValidationException[**Ts](jep._PyJObject): ...

class Binder[**Ts](jep._PyJObject): ...

class Marshaller[**Ts](jep._PyJObject): ...

class JAXBException[**Ts](jep._PyJObject): ...

class DataBindingException[**Ts](jep._PyJObject): ...

class UnmarshallerHandler[**Ts](jep._PyJObject): ...

class JAXB[**Ts](jep._PyJObject): ...

class DatatypeConverterInterface[**Ts](jep._PyJObject): ...

class Validator[**Ts](jep._PyJObject): ...

class NotIdentifiableEvent[**Ts](jep._PyJObject): ...

class SchemaOutputResolver[**Ts](jep._PyJObject): ...

class Unmarshaller[**Ts](jep._PyJObject): ...

class JAXBContext[**Ts](jep._PyJObject): ...

class ParseConversionEvent[**Ts](jep._PyJObject): ...

class ValidationEventLocator[**Ts](jep._PyJObject): ...

class JAXBContextFactory[**Ts](jep._PyJObject): ...

class PrintConversionEvent[**Ts](jep._PyJObject): ...

class JAXBElement[**Ts](jep._PyJObject): ...

