import jep

class Binder(jep._PyJObject): ...

class JAXBIntrospector(jep._PyJObject): ...

class JAXBContextFactory(jep._PyJObject): ...

class ValidationEventHandler(jep._PyJObject): ...

class UnmarshallerHandler(jep._PyJObject): ...

class JAXBElement(jep._PyJObject): ...

class NotIdentifiableEvent(jep._PyJObject): ...

class Marshaller(jep._PyJObject): ...

class TypeConstraintException(jep._PyJObject): ...

class DatatypeConverterInterface(jep._PyJObject): ...

class Validator(jep._PyJObject): ...

class Element(jep._PyJObject): ...

class DatatypeConverter(jep._PyJObject): ...

class JAXBException(jep._PyJObject): ...

class DataBindingException(jep._PyJObject): ...

class ParseConversionEvent(jep._PyJObject): ...

class UnmarshalException(jep._PyJObject): ...

class PropertyException(jep._PyJObject): ...

class SchemaOutputResolver(jep._PyJObject): ...

class ValidationEvent(jep._PyJObject): ...

class JAXB(jep._PyJObject): ...

class JAXBContext(jep._PyJObject): ...

class MarshalException(jep._PyJObject): ...

class PrintConversionEvent(jep._PyJObject): ...

class ValidationEventLocator(jep._PyJObject): ...

class JAXBPermission(jep._PyJObject): ...

class ValidationException(jep._PyJObject): ...

class Unmarshaller(jep._PyJObject): ...

