import jep

class Binder(jep.PyJObject): ...

class JAXBIntrospector(jep.PyJObject): ...

class JAXBContextFactory(jep.PyJObject): ...

class ValidationEventHandler(jep.PyJObject): ...

class UnmarshallerHandler(jep.PyJObject): ...

class JAXBElement(jep.PyJObject): ...

class NotIdentifiableEvent(jep.PyJObject): ...

class Marshaller(jep.PyJObject): ...

class TypeConstraintException(jep.PyJObject): ...

class DatatypeConverterInterface(jep.PyJObject): ...

class Validator(jep.PyJObject): ...

class Element(jep.PyJObject): ...

class DatatypeConverter(jep.PyJObject): ...

class JAXBException(jep.PyJObject): ...

class DataBindingException(jep.PyJObject): ...

class ParseConversionEvent(jep.PyJObject): ...

class UnmarshalException(jep.PyJObject): ...

class PropertyException(jep.PyJObject): ...

class SchemaOutputResolver(jep.PyJObject): ...

class ValidationEvent(jep.PyJObject): ...

class JAXB(jep.PyJObject): ...

class JAXBContext(jep.PyJObject): ...

class MarshalException(jep.PyJObject): ...

class PrintConversionEvent(jep.PyJObject): ...

class ValidationEventLocator(jep.PyJObject): ...

class JAXBPermission(jep.PyJObject): ...

class ValidationException(jep.PyJObject): ...

class Unmarshaller(jep.PyJObject): ...

