import jep

class NotIdentifiableEventImpl(jep._PyJObject): ...

class AbstractMarshallerImpl(jep._PyJObject): ...

class AbstractUnmarshallerImpl(jep._PyJObject): ...

class PrintConversionEventImpl(jep._PyJObject): ...

class ValidationEventImpl(jep._PyJObject): ...

class DefaultValidationEventHandler(jep._PyJObject): ...

class ValidationEventLocatorImpl(jep._PyJObject): ...

class ParseConversionEventImpl(jep._PyJObject): ...

