import jep

class NotIdentifiableEventImpl(jep.PyJObject): ...

class AbstractMarshallerImpl(jep.PyJObject): ...

class AbstractUnmarshallerImpl(jep.PyJObject): ...

class PrintConversionEventImpl(jep.PyJObject): ...

class ValidationEventImpl(jep.PyJObject): ...

class DefaultValidationEventHandler(jep.PyJObject): ...

class ValidationEventLocatorImpl(jep.PyJObject): ...

class ParseConversionEventImpl(jep.PyJObject): ...

