# pyright: reportPrivateUsage = none

import jep

class ParseConversionEventImpl[**Ts](jep._PyJObject): ...

class AbstractUnmarshallerImpl[**Ts](jep._PyJObject): ...

class DefaultValidationEventHandler[**Ts](jep._PyJObject): ...

class ValidationEventImpl[**Ts](jep._PyJObject): ...

class NotIdentifiableEventImpl[**Ts](jep._PyJObject): ...

class PrintConversionEventImpl[**Ts](jep._PyJObject): ...

class ValidationEventLocatorImpl[**Ts](jep._PyJObject): ...

