# pyright: reportPrivateUsage = none

import jep

class InputContext[**Ts](jep._PyJObject): ...

class InputMethodHighlight[**Ts](jep._PyJObject): ...

class InputSubset[**Ts](jep._PyJObject): ...

class InputMethodRequests[**Ts](jep._PyJObject): ...

