import jep

class GSSCredential(jep.PyJObject): ...

class ChannelBinding(jep.PyJObject): ...

class GSSName(jep.PyJObject): ...

class GSSException(jep.PyJObject): ...

class Oid(jep.PyJObject): ...

class GSSManager(jep.PyJObject): ...

class GSSContext(jep.PyJObject): ...

class MessageProp(jep.PyJObject): ...

