import jep

class GSSCredential(jep._PyJObject): ...

class ChannelBinding(jep._PyJObject): ...

class GSSName(jep._PyJObject): ...

class GSSException(jep._PyJObject): ...

class Oid(jep._PyJObject): ...

class GSSManager(jep._PyJObject): ...

class GSSContext(jep._PyJObject): ...

class MessageProp(jep._PyJObject): ...

