# pyright: reportPrivateUsage = none

import jep

class GSSCredential[**Ts](jep._PyJObject): ...

class Oid[**Ts](jep._PyJObject): ...

class GSSContext[**Ts](jep._PyJObject): ...

class MessageProp[**Ts](jep._PyJObject): ...

class GSSManager[**Ts](jep._PyJObject): ...

class GSSException[**Ts](jep._PyJObject): ...

class GSSName[**Ts](jep._PyJObject): ...

class ChannelBinding[**Ts](jep._PyJObject): ...

