import jep

class XmlSchemaType(jep._PyJObject): ...

class XmlAttribute(jep._PyJObject): ...

class XmlElement(jep._PyJObject): ...

class XmlSchemaTypes(jep._PyJObject): ...

class XmlType(jep._PyJObject): ...

class XmlElementRefs(jep._PyJObject): ...

class XmlValue(jep._PyJObject): ...

class XmlTransient(jep._PyJObject): ...

class XmlAccessorType(jep._PyJObject): ...

class XmlID(jep._PyJObject): ...

class XmlAttachmentRef(jep._PyJObject): ...

class XmlAccessorOrder(jep._PyJObject): ...

class XmlNs(jep._PyJObject): ...

class XmlEnumValue(jep._PyJObject): ...

class XmlAnyAttribute(jep._PyJObject): ...

class XmlElementWrapper(jep._PyJObject): ...

class DomHandler(jep._PyJObject): ...

class XmlInlineBinaryData(jep._PyJObject): ...

class XmlAccessOrder(jep._PyJObject): ...

class XmlElementDecl(jep._PyJObject): ...

class XmlMimeType(jep._PyJObject): ...

class W3CDomHandler(jep._PyJObject): ...

class XmlMixed(jep._PyJObject): ...

class XmlRegistry(jep._PyJObject): ...

class XmlAnyElement(jep._PyJObject): ...

class XmlEnum(jep._PyJObject): ...

class XmlElements(jep._PyJObject): ...

class XmlSchema(jep._PyJObject): ...

class XmlSeeAlso(jep._PyJObject): ...

class XmlAccessType(jep._PyJObject): ...

class XmlList(jep._PyJObject): ...

class XmlIDREF(jep._PyJObject): ...

class XmlRootElement(jep._PyJObject): ...

class XmlNsForm(jep._PyJObject): ...

