# pyright: reportPrivateUsage = none

import jep

class XmlList[**Ts](jep._PyJObject): ...

class XmlElementRefs[**Ts](jep._PyJObject): ...

class W3CDomHandler[**Ts](jep._PyJObject): ...

class XmlElementDecl[**Ts](jep._PyJObject): ...

class XmlInlineBinaryData[**Ts](jep._PyJObject): ...

class XmlAccessType[**Ts](jep._PyJObject): ...

class XmlSchemaType[**Ts](jep._PyJObject): ...

class XmlSeeAlso[**Ts](jep._PyJObject): ...

class DomHandler[**Ts](jep._PyJObject): ...

class XmlValue[**Ts](jep._PyJObject): ...

class XmlAnyAttribute[**Ts](jep._PyJObject): ...

class XmlElementRef[**Ts](jep._PyJObject): ...

class XmlType[**Ts](jep._PyJObject): ...

class XmlMixed[**Ts](jep._PyJObject): ...

class XmlNsForm[**Ts](jep._PyJObject): ...

class XmlNs[**Ts](jep._PyJObject): ...

class XmlSchemaTypes[**Ts](jep._PyJObject): ...

class XmlElement[**Ts](jep._PyJObject): ...

class XmlRegistry[**Ts](jep._PyJObject): ...

class XmlSchema[**Ts](jep._PyJObject): ...

class XmlAttribute[**Ts](jep._PyJObject): ...

class XmlElements[**Ts](jep._PyJObject): ...

class XmlAttachmentRef[**Ts](jep._PyJObject): ...

class XmlAccessOrder[**Ts](jep._PyJObject): ...

class XmlEnumValue[**Ts](jep._PyJObject): ...

class XmlAccessorType[**Ts](jep._PyJObject): ...

class XmlMimeType[**Ts](jep._PyJObject): ...

class XmlEnum[**Ts](jep._PyJObject): ...

class XmlIDREF[**Ts](jep._PyJObject): ...

class XmlTransient[**Ts](jep._PyJObject): ...

class XmlElementWrapper[**Ts](jep._PyJObject): ...

class XmlID[**Ts](jep._PyJObject): ...

class XmlRootElement[**Ts](jep._PyJObject): ...

class XmlAnyElement[**Ts](jep._PyJObject): ...

class XmlAccessorOrder[**Ts](jep._PyJObject): ...

