import jep

class XmlSchemaType(jep.PyJObject): ...

class XmlAttribute(jep.PyJObject): ...

class XmlElement(jep.PyJObject): ...

class XmlSchemaTypes(jep.PyJObject): ...

class XmlType(jep.PyJObject): ...

class XmlElementRefs(jep.PyJObject): ...

class XmlValue(jep.PyJObject): ...

class XmlTransient(jep.PyJObject): ...

class XmlAccessorType(jep.PyJObject): ...

class XmlID(jep.PyJObject): ...

class XmlAttachmentRef(jep.PyJObject): ...

class XmlAccessorOrder(jep.PyJObject): ...

class XmlNs(jep.PyJObject): ...

class XmlEnumValue(jep.PyJObject): ...

class XmlAnyAttribute(jep.PyJObject): ...

class XmlElementWrapper(jep.PyJObject): ...

class DomHandler(jep.PyJObject): ...

class XmlInlineBinaryData(jep.PyJObject): ...

class XmlAccessOrder(jep.PyJObject): ...

class XmlElementDecl(jep.PyJObject): ...

class XmlMimeType(jep.PyJObject): ...

class W3CDomHandler(jep.PyJObject): ...

class XmlMixed(jep.PyJObject): ...

class XmlRegistry(jep.PyJObject): ...

class XmlAnyElement(jep.PyJObject): ...

class XmlEnum(jep.PyJObject): ...

class XmlElements(jep.PyJObject): ...

class XmlSchema(jep.PyJObject): ...

class XmlSeeAlso(jep.PyJObject): ...

class XmlAccessType(jep.PyJObject): ...

class XmlList(jep.PyJObject): ...

class XmlIDREF(jep.PyJObject): ...

class XmlRootElement(jep.PyJObject): ...

class XmlNsForm(jep.PyJObject): ...

