import jep

class XmlJavaTypeAdapters(jep.PyJObject): ...

class HexBinaryAdapter(jep.PyJObject): ...

class XmlJavaTypeAdapter(jep.PyJObject): ...

class XmlAdapter(jep.PyJObject): ...

class CollapsedStringAdapter(jep.PyJObject): ...

