import jep

class XmlJavaTypeAdapters(jep._PyJObject): ...

class HexBinaryAdapter(jep._PyJObject): ...

class XmlJavaTypeAdapter(jep._PyJObject): ...

class XmlAdapter(jep._PyJObject): ...

class CollapsedStringAdapter(jep._PyJObject): ...

