# pyright: reportPrivateUsage = none

import jep

class XmlJavaTypeAdapters[**Ts](jep._PyJObject): ...

class NormalizedStringAdapter[**Ts](jep._PyJObject): ...

class XmlJavaTypeAdapter[**Ts](jep._PyJObject): ...

class CollapsedStringAdapter[**Ts](jep._PyJObject): ...

class HexBinaryAdapter[**Ts](jep._PyJObject): ...

