# pyright: reportPrivateUsage = none

import jep

class RefreshFailedException[**Ts](jep._PyJObject): ...

class Destroyable[**Ts](jep._PyJObject): ...

class Subject[**Ts](jep._PyJObject): ...

class SubjectDomainCombiner[**Ts](jep._PyJObject): ...

class PrivateCredentialPermission[**Ts](jep._PyJObject): ...

class Refreshable[**Ts](jep._PyJObject): ...

class Policy[**Ts](jep._PyJObject): ...

class DestroyFailedException[**Ts](jep._PyJObject): ...

class AuthPermission[**Ts](jep._PyJObject): ...

