import jep

class DestroyFailedException(jep.PyJObject): ...

class Subject(jep.PyJObject): ...

class AuthPermission(jep.PyJObject): ...

class Policy(jep.PyJObject): ...

class PrivateCredentialPermission(jep.PyJObject): ...

class Destroyable(jep.PyJObject): ...

class RefreshFailedException(jep.PyJObject): ...

class Refreshable(jep.PyJObject): ...

class SubjectDomainCombiner(jep.PyJObject): ...

