import jep

class DestroyFailedException(jep._PyJObject): ...

class Subject(jep._PyJObject): ...

class AuthPermission(jep._PyJObject): ...

class Policy(jep._PyJObject): ...

class PrivateCredentialPermission(jep._PyJObject): ...

class Destroyable(jep._PyJObject): ...

class RefreshFailedException(jep._PyJObject): ...

class Refreshable(jep._PyJObject): ...

class SubjectDomainCombiner(jep._PyJObject): ...

