# pyright: reportPrivateUsage = none

import jep

class NameCallback[**Ts](jep._PyJObject): ...

class ChoiceCallback[**Ts](jep._PyJObject): ...

class UnsupportedCallbackException[**Ts](jep._PyJObject): ...

class PasswordCallback[**Ts](jep._PyJObject): ...

class CallbackHandler[**Ts](jep._PyJObject): ...

class ConfirmationCallback[**Ts](jep._PyJObject): ...

class TextOutputCallback[**Ts](jep._PyJObject): ...

class TextInputCallback[**Ts](jep._PyJObject): ...

class LanguageCallback[**Ts](jep._PyJObject): ...

class Callback[**Ts](jep._PyJObject): ...

