import jep

class CallbackHandler(jep.PyJObject): ...

class TextOutputCallback(jep.PyJObject): ...

class NameCallback(jep.PyJObject): ...

class Callback(jep.PyJObject): ...

class ConfirmationCallback(jep.PyJObject): ...

class PasswordCallback(jep.PyJObject): ...

class ChoiceCallback(jep.PyJObject): ...

class UnsupportedCallbackException(jep.PyJObject): ...

class LanguageCallback(jep.PyJObject): ...

class TextInputCallback(jep.PyJObject): ...

