import jep

class CallbackHandler(jep._PyJObject): ...

class TextOutputCallback(jep._PyJObject): ...

class NameCallback(jep._PyJObject): ...

class Callback(jep._PyJObject): ...

class ConfirmationCallback(jep._PyJObject): ...

class PasswordCallback(jep._PyJObject): ...

class ChoiceCallback(jep._PyJObject): ...

class UnsupportedCallbackException(jep._PyJObject): ...

class LanguageCallback(jep._PyJObject): ...

class TextInputCallback(jep._PyJObject): ...

