# pyright: reportPrivateUsage = none

import jep

class KerberosCredMessage[**Ts](jep._PyJObject): ...

class KerberosKey[**Ts](jep._PyJObject): ...

class KerberosTicket[**Ts](jep._PyJObject): ...

class KeyTab[**Ts](jep._PyJObject): ...

class DelegationPermission[**Ts](jep._PyJObject): ...

class EncryptionKey[**Ts](jep._PyJObject): ...

class KerberosPrincipal[**Ts](jep._PyJObject): ...

class ServicePermission[**Ts](jep._PyJObject): ...

