import jep

class KerberosCredMessage(jep.PyJObject): ...

class KerberosPrincipal(jep.PyJObject): ...

class ServicePermission(jep.PyJObject): ...

class KerberosTicket(jep.PyJObject): ...

class KerberosKey(jep.PyJObject): ...

class KeyTab(jep.PyJObject): ...

class EncryptionKey(jep.PyJObject): ...

