import jep

class KerberosCredMessage(jep._PyJObject): ...

class KerberosPrincipal(jep._PyJObject): ...

class ServicePermission(jep._PyJObject): ...

class KerberosTicket(jep._PyJObject): ...

class KerberosKey(jep._PyJObject): ...

class KeyTab(jep._PyJObject): ...

class EncryptionKey(jep._PyJObject): ...

