# pyright: reportPrivateUsage = none

import jep

class AppConfigurationEntry[**Ts](jep._PyJObject): ...

class AccountLockedException[**Ts](jep._PyJObject): ...

class Configuration[**Ts](jep._PyJObject): ...

class LoginException[**Ts](jep._PyJObject): ...

class FailedLoginException[**Ts](jep._PyJObject): ...

class LoginContext[**Ts](jep._PyJObject): ...

class CredentialException[**Ts](jep._PyJObject): ...

class AccountNotFoundException[**Ts](jep._PyJObject): ...

class CredentialNotFoundException[**Ts](jep._PyJObject): ...

class CredentialExpiredException[**Ts](jep._PyJObject): ...

class ConfigurationSpi[**Ts](jep._PyJObject): ...

class AccountException[**Ts](jep._PyJObject): ...

class AccountExpiredException[**Ts](jep._PyJObject): ...

