import jep

class LoginContext(jep._PyJObject): ...

class CredentialException(jep._PyJObject): ...

class CredentialNotFoundException(jep._PyJObject): ...

class FailedLoginException(jep._PyJObject): ...

class AccountExpiredException(jep._PyJObject): ...

class ConfigurationSpi(jep._PyJObject): ...

class AccountException(jep._PyJObject): ...

class AccountNotFoundException(jep._PyJObject): ...

class Configuration(jep._PyJObject): ...

class AppConfigurationEntry(jep._PyJObject): ...

class LoginException(jep._PyJObject): ...

class AccountLockedException(jep._PyJObject): ...

class CredentialExpiredException(jep._PyJObject): ...

