import jep

class LoginContext(jep.PyJObject): ...

class CredentialException(jep.PyJObject): ...

class CredentialNotFoundException(jep.PyJObject): ...

class FailedLoginException(jep.PyJObject): ...

class AccountExpiredException(jep.PyJObject): ...

class ConfigurationSpi(jep.PyJObject): ...

class AccountException(jep.PyJObject): ...

class AccountNotFoundException(jep.PyJObject): ...

class Configuration(jep.PyJObject): ...

class AppConfigurationEntry(jep.PyJObject): ...

class LoginException(jep.PyJObject): ...

class AccountLockedException(jep.PyJObject): ...

class CredentialExpiredException(jep.PyJObject): ...

