import jep

class SSLException(jep.PyJObject): ...

class SSLSessionBindingListener(jep.PyJObject): ...

class HostnameVerifier(jep.PyJObject): ...

class SSLSessionContext(jep.PyJObject): ...

class SSLSession(jep.PyJObject): ...

class HandshakeCompletedEvent(jep.PyJObject): ...

class X509ExtendedTrustManager(jep.PyJObject): ...

class X509ExtendedKeyManager(jep.PyJObject): ...

class TrustManagerFactorySpi(jep.PyJObject): ...

class TrustManager(jep.PyJObject): ...

class HandshakeCompletedListener(jep.PyJObject): ...

class SSLServerSocket(jep.PyJObject): ...

class SSLServerSocketFactory(jep.PyJObject): ...

class SSLKeyException(jep.PyJObject): ...

class SSLParameters(jep.PyJObject): ...

class ExtendedSSLSession(jep.PyJObject): ...

class SSLSessionBindingEvent(jep.PyJObject): ...

class SSLSocket(jep.PyJObject): ...

class SSLEngine(jep.PyJObject): ...

class SNIServerName(jep.PyJObject): ...

class SSLContextSpi(jep.PyJObject): ...

class HttpsURLConnection(jep.PyJObject): ...

class SSLPermission(jep.PyJObject): ...

class StandardConstants(jep.PyJObject): ...

class KeyManager(jep.PyJObject): ...

class SSLHandshakeException(jep.PyJObject): ...

class SNIHostName(jep.PyJObject): ...

class SSLSocketFactory(jep.PyJObject): ...

class KeyManagerFactorySpi(jep.PyJObject): ...

class SSLEngineResult(jep.PyJObject): ...

class ManagerFactoryParameters(jep.PyJObject): ...

class X509KeyManager(jep.PyJObject): ...

class TrustManagerFactory(jep.PyJObject): ...

class CertPathTrustManagerParameters(jep.PyJObject): ...

class X509TrustManager(jep.PyJObject): ...

class SNIMatcher(jep.PyJObject): ...

class SSLProtocolException(jep.PyJObject): ...

class KeyManagerFactory(jep.PyJObject): ...

class SSLContext(jep.PyJObject): ...

class KeyStoreBuilderParameters(jep.PyJObject): ...

