import jep

class SSLException(jep._PyJObject): ...

class SSLSessionBindingListener(jep._PyJObject): ...

class HostnameVerifier(jep._PyJObject): ...

class SSLSessionContext(jep._PyJObject): ...

class SSLSession(jep._PyJObject): ...

class HandshakeCompletedEvent(jep._PyJObject): ...

class X509ExtendedTrustManager(jep._PyJObject): ...

class X509ExtendedKeyManager(jep._PyJObject): ...

class TrustManagerFactorySpi(jep._PyJObject): ...

class TrustManager(jep._PyJObject): ...

class HandshakeCompletedListener(jep._PyJObject): ...

class SSLServerSocket(jep._PyJObject): ...

class SSLServerSocketFactory(jep._PyJObject): ...

class SSLKeyException(jep._PyJObject): ...

class SSLParameters(jep._PyJObject): ...

class ExtendedSSLSession(jep._PyJObject): ...

class SSLSessionBindingEvent(jep._PyJObject): ...

class SSLSocket(jep._PyJObject): ...

class SSLEngine(jep._PyJObject): ...

class SNIServerName(jep._PyJObject): ...

class SSLContextSpi(jep._PyJObject): ...

class HttpsURLConnection(jep._PyJObject): ...

class SSLPermission(jep._PyJObject): ...

class StandardConstants(jep._PyJObject): ...

class KeyManager(jep._PyJObject): ...

class SSLHandshakeException(jep._PyJObject): ...

class SNIHostName(jep._PyJObject): ...

class SSLSocketFactory(jep._PyJObject): ...

class KeyManagerFactorySpi(jep._PyJObject): ...

class SSLEngineResult(jep._PyJObject): ...

class ManagerFactoryParameters(jep._PyJObject): ...

class X509KeyManager(jep._PyJObject): ...

class TrustManagerFactory(jep._PyJObject): ...

class CertPathTrustManagerParameters(jep._PyJObject): ...

class X509TrustManager(jep._PyJObject): ...

class SNIMatcher(jep._PyJObject): ...

class SSLProtocolException(jep._PyJObject): ...

class KeyManagerFactory(jep._PyJObject): ...

class SSLContext(jep._PyJObject): ...

class KeyStoreBuilderParameters(jep._PyJObject): ...

