# pyright: reportPrivateUsage = none

import jep

class HostnameVerifier[**Ts](jep._PyJObject): ...

class CertPathTrustManagerParameters[**Ts](jep._PyJObject): ...

class SSLSessionContext[**Ts](jep._PyJObject): ...

class SSLPeerUnverifiedException[**Ts](jep._PyJObject): ...

class X509ExtendedKeyManager[**Ts](jep._PyJObject): ...

class SNIMatcher[**Ts](jep._PyJObject): ...

class HandshakeCompletedListener[**Ts](jep._PyJObject): ...

class SSLEngineResult[**Ts](jep._PyJObject): ...

class SNIServerName[**Ts](jep._PyJObject): ...

class SNIHostName[**Ts](jep._PyJObject): ...

class SSLEngine[**Ts](jep._PyJObject): ...

class HandshakeCompletedEvent[**Ts](jep._PyJObject): ...

class HttpsURLConnection[**Ts](jep._PyJObject): ...

class SSLKeyException[**Ts](jep._PyJObject): ...

class SSLProtocolException[**Ts](jep._PyJObject): ...

class SSLSession[**Ts](jep._PyJObject): ...

class ExtendedSSLSession[**Ts](jep._PyJObject): ...

class KeyManagerFactory[**Ts](jep._PyJObject): ...

class KeyManager[**Ts](jep._PyJObject): ...

class SSLHandshakeException[**Ts](jep._PyJObject): ...

class SSLServerSocketFactory[**Ts](jep._PyJObject): ...

class TrustManager[**Ts](jep._PyJObject): ...

class SSLSessionBindingEvent[**Ts](jep._PyJObject): ...

class KeyStoreBuilderParameters[**Ts](jep._PyJObject): ...

class SSLSocketFactory[**Ts](jep._PyJObject): ...

class X509ExtendedTrustManager[**Ts](jep._PyJObject): ...

class SSLSocket[**Ts](jep._PyJObject): ...

class KeyManagerFactorySpi[**Ts](jep._PyJObject): ...

class ManagerFactoryParameters[**Ts](jep._PyJObject): ...

class SSLSessionBindingListener[**Ts](jep._PyJObject): ...

class TrustManagerFactory[**Ts](jep._PyJObject): ...

class X509TrustManager[**Ts](jep._PyJObject): ...

class X509KeyManager[**Ts](jep._PyJObject): ...

class SSLParameters[**Ts](jep._PyJObject): ...

class StandardConstants[**Ts](jep._PyJObject): ...

class SSLException[**Ts](jep._PyJObject): ...

class SSLServerSocket[**Ts](jep._PyJObject): ...

class TrustManagerFactorySpi[**Ts](jep._PyJObject): ...

class SSLContextSpi[**Ts](jep._PyJObject): ...

class SSLContext[**Ts](jep._PyJObject): ...

