# pyright: reportPrivateUsage = none

import jep

class AllPermission[**Ts](jep._PyJObject): ...

class KeyStoreSpi[**Ts](jep._PyJObject): ...

class CodeSigner[**Ts](jep._PyJObject): ...

class KeyException[**Ts](jep._PyJObject): ...

class AlgorithmParameterGeneratorSpi[**Ts](jep._PyJObject): ...

class KeyManagementException[**Ts](jep._PyJObject): ...

class KeyPairGeneratorSpi[**Ts](jep._PyJObject): ...

class SignatureSpi[**Ts](jep._PyJObject): ...

class KeyStoreException[**Ts](jep._PyJObject): ...

class Certificate[**Ts](jep._PyJObject): ...

class Identity[**Ts](jep._PyJObject): ...

class KeyFactorySpi[**Ts](jep._PyJObject): ...

class Key[**Ts](jep._PyJObject): ...

class BasicPermission[**Ts](jep._PyJObject): ...

class AlgorithmParameterGenerator[**Ts](jep._PyJObject): ...

class GeneralSecurityException[**Ts](jep._PyJObject): ...

class PrivilegedActionException[**Ts](jep._PyJObject): ...

class MessageDigest[**Ts](jep._PyJObject): ...

class AuthProvider[**Ts](jep._PyJObject): ...

class DomainLoadStoreParameter[**Ts](jep._PyJObject): ...

class NoSuchProviderException[**Ts](jep._PyJObject): ...

class SignedObject[**Ts](jep._PyJObject): ...

class IdentityScope[**Ts](jep._PyJObject): ...

class PKCS12Attribute[**Ts](jep._PyJObject): ...

class NoSuchAlgorithmException[**Ts](jep._PyJObject): ...

class AlgorithmParameters[**Ts](jep._PyJObject): ...

class KeyStore[**Ts](jep._PyJObject): ...

class DigestException[**Ts](jep._PyJObject): ...

class KeyPairGenerator[**Ts](jep._PyJObject): ...

class InvalidParameterException[**Ts](jep._PyJObject): ...

class AlgorithmConstraints[**Ts](jep._PyJObject): ...

class AccessControlContext[**Ts](jep._PyJObject): ...

class UnrecoverableEntryException[**Ts](jep._PyJObject): ...

class AccessControlException[**Ts](jep._PyJObject): ...

class SecureClassLoader[**Ts](jep._PyJObject): ...

class InvalidAlgorithmParameterException[**Ts](jep._PyJObject): ...

class DomainCombiner[**Ts](jep._PyJObject): ...

class InvalidKeyException[**Ts](jep._PyJObject): ...

class SignatureException[**Ts](jep._PyJObject): ...

class KeyFactory[**Ts](jep._PyJObject): ...

class SecurityPermission[**Ts](jep._PyJObject): ...

class URIParameter[**Ts](jep._PyJObject): ...

class UnrecoverableKeyException[**Ts](jep._PyJObject): ...

class Signature[**Ts](jep._PyJObject): ...

class KeyRep[**Ts](jep._PyJObject): ...

class AccessController[**Ts](jep._PyJObject): ...

class KeyPair[**Ts](jep._PyJObject): ...

class DrbgParameters[**Ts](jep._PyJObject): ...

class Policy[**Ts](jep._PyJObject): ...

class UnresolvedPermission[**Ts](jep._PyJObject): ...

class CryptoPrimitive[**Ts](jep._PyJObject): ...

class Permissions[**Ts](jep._PyJObject): ...

class ProviderException[**Ts](jep._PyJObject): ...

class CodeSource[**Ts](jep._PyJObject): ...

class ProtectionDomain[**Ts](jep._PyJObject): ...

class GuardedObject[**Ts](jep._PyJObject): ...

class SecureRandom[**Ts](jep._PyJObject): ...

class Provider[**Ts](jep._PyJObject): ...

class PrivilegedAction[**Ts](jep._PyJObject): ...

class Permission[**Ts](jep._PyJObject): ...

class Principal[**Ts](jep._PyJObject): ...

class Security[**Ts](jep._PyJObject): ...

class DigestInputStream[**Ts](jep._PyJObject): ...

class PrivateKey[**Ts](jep._PyJObject): ...

class SecureRandomSpi[**Ts](jep._PyJObject): ...

class DigestOutputStream[**Ts](jep._PyJObject): ...

class Timestamp[**Ts](jep._PyJObject): ...

class MessageDigestSpi[**Ts](jep._PyJObject): ...

class PolicySpi[**Ts](jep._PyJObject): ...

class SecureRandomParameters[**Ts](jep._PyJObject): ...

class Guard[**Ts](jep._PyJObject): ...

class Signer[**Ts](jep._PyJObject): ...

class AlgorithmParametersSpi[**Ts](jep._PyJObject): ...

class PublicKey[**Ts](jep._PyJObject): ...

class PermissionCollection[**Ts](jep._PyJObject): ...

class PrivilegedExceptionAction[**Ts](jep._PyJObject): ...

