import jep

class InvalidKeyException(jep._PyJObject): ...

class PrivilegedActionException(jep._PyJObject): ...

class Key(jep._PyJObject): ...

class Timestamp(jep._PyJObject): ...

class SignatureSpi(jep._PyJObject): ...

class KeyException(jep._PyJObject): ...

class KeyStore(jep._PyJObject): ...

class KeyPairGenerator(jep._PyJObject): ...

class InvalidParameterException(jep._PyJObject): ...

class SignedObject(jep._PyJObject): ...

class AlgorithmConstraints(jep._PyJObject): ...

class PolicySpi(jep._PyJObject): ...

class NoSuchProviderException(jep._PyJObject): ...

class SignatureException(jep._PyJObject): ...

class CodeSource(jep._PyJObject): ...

class Signature(jep._PyJObject): ...

class SecureRandom(jep._PyJObject): ...

class CodeSigner(jep._PyJObject): ...

class SecureRandomParameters(jep._PyJObject): ...

class SecureRandomSpi(jep._PyJObject): ...

class AccessControlContext(jep._PyJObject): ...

class NoSuchAlgorithmException(jep._PyJObject): ...

class PrivilegedExceptionAction(jep._PyJObject): ...

class InvalidAlgorithmParameterException(jep._PyJObject): ...

class SecureClassLoader(jep._PyJObject): ...

class DomainLoadStoreParameter(jep._PyJObject): ...

class AccessControlException(jep._PyJObject): ...

class PrivilegedAction(jep._PyJObject): ...

class PrivateKey(jep._PyJObject): ...

class AlgorithmParameterGenerator(jep._PyJObject): ...

class AuthProvider(jep._PyJObject): ...

class DigestInputStream(jep._PyJObject): ...

class GeneralSecurityException(jep._PyJObject): ...

class AccessController(jep._PyJObject): ...

class UnrecoverableKeyException(jep._PyJObject): ...

class AllPermission(jep._PyJObject): ...

class Permissions(jep._PyJObject): ...

class Identity(jep._PyJObject): ...

class DomainCombiner(jep._PyJObject): ...

class Principal(jep._PyJObject): ...

class PermissionCollection(jep._PyJObject): ...

class Security(jep._PyJObject): ...

class KeyStoreException(jep._PyJObject): ...

class Permission(jep._PyJObject): ...

class KeyPair(jep._PyJObject): ...

class AlgorithmParameterGeneratorSpi(jep._PyJObject): ...

class CryptoPrimitive(jep._PyJObject): ...

class UnresolvedPermission(jep._PyJObject): ...

class KeyFactory(jep._PyJObject): ...

class KeyFactorySpi(jep._PyJObject): ...

class Signer(jep._PyJObject): ...

class Guard(jep._PyJObject): ...

class ProviderException(jep._PyJObject): ...

class ProtectionDomain(jep._PyJObject): ...

class DrbgParameters(jep._PyJObject): ...

class UnrecoverableEntryException(jep._PyJObject): ...

class BasicPermission(jep._PyJObject): ...

class PKCS12Attribute(jep._PyJObject): ...

class DigestOutputStream(jep._PyJObject): ...

class IdentityScope(jep._PyJObject): ...

class PublicKey(jep._PyJObject): ...

class MessageDigestSpi(jep._PyJObject): ...

class KeyPairGeneratorSpi(jep._PyJObject): ...

class KeyManagementException(jep._PyJObject): ...

class Certificate(jep._PyJObject): ...

class KeyRep(jep._PyJObject): ...

class Policy(jep._PyJObject): ...

class Provider(jep._PyJObject): ...

class SecurityPermission(jep._PyJObject): ...

class URIParameter(jep._PyJObject): ...

class DigestException(jep._PyJObject): ...

class AlgorithmParameters(jep._PyJObject): ...

class MessageDigest(jep._PyJObject): ...

class KeyStoreSpi(jep._PyJObject): ...

class AlgorithmParametersSpi(jep._PyJObject): ...

class GuardedObject(jep._PyJObject): ...

