import jep

class InvalidKeyException(jep.PyJObject): ...

class PrivilegedActionException(jep.PyJObject): ...

class Key(jep.PyJObject): ...

class Timestamp(jep.PyJObject): ...

class SignatureSpi(jep.PyJObject): ...

class KeyException(jep.PyJObject): ...

class KeyStore(jep.PyJObject): ...

class KeyPairGenerator(jep.PyJObject): ...

class InvalidParameterException(jep.PyJObject): ...

class SignedObject(jep.PyJObject): ...

class AlgorithmConstraints(jep.PyJObject): ...

class PolicySpi(jep.PyJObject): ...

class NoSuchProviderException(jep.PyJObject): ...

class SignatureException(jep.PyJObject): ...

class CodeSource(jep.PyJObject): ...

class Signature(jep.PyJObject): ...

class SecureRandom(jep.PyJObject): ...

class CodeSigner(jep.PyJObject): ...

class SecureRandomParameters(jep.PyJObject): ...

class SecureRandomSpi(jep.PyJObject): ...

class AccessControlContext(jep.PyJObject): ...

class NoSuchAlgorithmException(jep.PyJObject): ...

class PrivilegedExceptionAction(jep.PyJObject): ...

class InvalidAlgorithmParameterException(jep.PyJObject): ...

class SecureClassLoader(jep.PyJObject): ...

class DomainLoadStoreParameter(jep.PyJObject): ...

class AccessControlException(jep.PyJObject): ...

class PrivilegedAction(jep.PyJObject): ...

class PrivateKey(jep.PyJObject): ...

class AlgorithmParameterGenerator(jep.PyJObject): ...

class AuthProvider(jep.PyJObject): ...

class DigestInputStream(jep.PyJObject): ...

class GeneralSecurityException(jep.PyJObject): ...

class AccessController(jep.PyJObject): ...

class UnrecoverableKeyException(jep.PyJObject): ...

class AllPermission(jep.PyJObject): ...

class Permissions(jep.PyJObject): ...

class Identity(jep.PyJObject): ...

class DomainCombiner(jep.PyJObject): ...

class Principal(jep.PyJObject): ...

class PermissionCollection(jep.PyJObject): ...

class Security(jep.PyJObject): ...

class KeyStoreException(jep.PyJObject): ...

class Permission(jep.PyJObject): ...

class KeyPair(jep.PyJObject): ...

class AlgorithmParameterGeneratorSpi(jep.PyJObject): ...

class CryptoPrimitive(jep.PyJObject): ...

class UnresolvedPermission(jep.PyJObject): ...

class KeyFactory(jep.PyJObject): ...

class KeyFactorySpi(jep.PyJObject): ...

class Signer(jep.PyJObject): ...

class Guard(jep.PyJObject): ...

class ProviderException(jep.PyJObject): ...

class ProtectionDomain(jep.PyJObject): ...

class DrbgParameters(jep.PyJObject): ...

class UnrecoverableEntryException(jep.PyJObject): ...

class BasicPermission(jep.PyJObject): ...

class PKCS12Attribute(jep.PyJObject): ...

class DigestOutputStream(jep.PyJObject): ...

class IdentityScope(jep.PyJObject): ...

class PublicKey(jep.PyJObject): ...

class MessageDigestSpi(jep.PyJObject): ...

class KeyPairGeneratorSpi(jep.PyJObject): ...

class KeyManagementException(jep.PyJObject): ...

class Certificate(jep.PyJObject): ...

class KeyRep(jep.PyJObject): ...

class Policy(jep.PyJObject): ...

class Provider(jep.PyJObject): ...

class SecurityPermission(jep.PyJObject): ...

class URIParameter(jep.PyJObject): ...

class DigestException(jep.PyJObject): ...

class AlgorithmParameters(jep.PyJObject): ...

class MessageDigest(jep.PyJObject): ...

class KeyStoreSpi(jep.PyJObject): ...

class AlgorithmParametersSpi(jep.PyJObject): ...

class GuardedObject(jep.PyJObject): ...

