# pyright: reportPrivateUsage = none

import jep

class Group[**Ts](jep._PyJObject): ...

class AclNotFoundException[**Ts](jep._PyJObject): ...

class Owner[**Ts](jep._PyJObject): ...

class AclEntry[**Ts](jep._PyJObject): ...

class NotOwnerException[**Ts](jep._PyJObject): ...

class LastOwnerException[**Ts](jep._PyJObject): ...

class Permission[**Ts](jep._PyJObject): ...

class Acl[**Ts](jep._PyJObject): ...

