import jep

class Permission(jep.PyJObject): ...

class AclNotFoundException(jep.PyJObject): ...

class Group(jep.PyJObject): ...

class NotOwnerException(jep.PyJObject): ...

class LastOwnerException(jep.PyJObject): ...

class AclEntry(jep.PyJObject): ...

class Acl(jep.PyJObject): ...

class Owner(jep.PyJObject): ...

