import jep

class Permission(jep._PyJObject): ...

class AclNotFoundException(jep._PyJObject): ...

class Group(jep._PyJObject): ...

class NotOwnerException(jep._PyJObject): ...

class LastOwnerException(jep._PyJObject): ...

class AclEntry(jep._PyJObject): ...

class Acl(jep._PyJObject): ...

class Owner(jep._PyJObject): ...

