# pyright: reportPrivateUsage = none

import jep

class CRLReason[**Ts](jep._PyJObject): ...

class PKIXParameters[**Ts](jep._PyJObject): ...

class CertificateEncodingException[**Ts](jep._PyJObject): ...

class Certificate[**Ts](jep._PyJObject): ...

class PKIXCertPathChecker[**Ts](jep._PyJObject): ...

class X509Certificate[**Ts](jep._PyJObject): ...

class X509CRL[**Ts](jep._PyJObject): ...

class CertPath[**Ts](jep._PyJObject): ...

class CertPathValidatorSpi[**Ts](jep._PyJObject): ...

class TrustAnchor[**Ts](jep._PyJObject): ...

class X509CRLSelector[**Ts](jep._PyJObject): ...

class CertificateException[**Ts](jep._PyJObject): ...

class PKIXRevocationChecker[**Ts](jep._PyJObject): ...

class LDAPCertStoreParameters[**Ts](jep._PyJObject): ...

class PKIXBuilderParameters[**Ts](jep._PyJObject): ...

class CertSelector[**Ts](jep._PyJObject): ...

class CertPathBuilder[**Ts](jep._PyJObject): ...

class X509CertSelector[**Ts](jep._PyJObject): ...

class PKIXReason[**Ts](jep._PyJObject): ...

class CertStore[**Ts](jep._PyJObject): ...

class CRLException[**Ts](jep._PyJObject): ...

class X509CRLEntry[**Ts](jep._PyJObject): ...

class CRL[**Ts](jep._PyJObject): ...

class Extension[**Ts](jep._PyJObject): ...

class CertificateFactory[**Ts](jep._PyJObject): ...

class URICertStoreParameters[**Ts](jep._PyJObject): ...

class CertStoreException[**Ts](jep._PyJObject): ...

class CertPathValidatorException[**Ts](jep._PyJObject): ...

class CertificateParsingException[**Ts](jep._PyJObject): ...

class X509Extension[**Ts](jep._PyJObject): ...

class PKIXCertPathBuilderResult[**Ts](jep._PyJObject): ...

class CertificateNotYetValidException[**Ts](jep._PyJObject): ...

class CertStoreParameters[**Ts](jep._PyJObject): ...

class PolicyQualifierInfo[**Ts](jep._PyJObject): ...

class CertificateFactorySpi[**Ts](jep._PyJObject): ...

class CertPathParameters[**Ts](jep._PyJObject): ...

class PolicyNode[**Ts](jep._PyJObject): ...

class CertPathChecker[**Ts](jep._PyJObject): ...

class CRLSelector[**Ts](jep._PyJObject): ...

class CertPathValidatorResult[**Ts](jep._PyJObject): ...

class CertStoreSpi[**Ts](jep._PyJObject): ...

class CollectionCertStoreParameters[**Ts](jep._PyJObject): ...

class CertPathBuilderResult[**Ts](jep._PyJObject): ...

class CertPathValidator[**Ts](jep._PyJObject): ...

class CertPathBuilderException[**Ts](jep._PyJObject): ...

class CertPathBuilderSpi[**Ts](jep._PyJObject): ...

class PKIXCertPathValidatorResult[**Ts](jep._PyJObject): ...

class CertificateExpiredException[**Ts](jep._PyJObject): ...

