# pyright: reportPrivateUsage = none

import jep

class DSAKeyPairGenerator[**Ts](jep._PyJObject): ...

class XECPublicKey[**Ts](jep._PyJObject): ...

class RSAPrivateCrtKey[**Ts](jep._PyJObject): ...

class RSAPrivateKey[**Ts](jep._PyJObject): ...

class XECPrivateKey[**Ts](jep._PyJObject): ...

class RSAKey[**Ts](jep._PyJObject): ...

class RSAPublicKey[**Ts](jep._PyJObject): ...

class ECPrivateKey[**Ts](jep._PyJObject): ...

class DSAPublicKey[**Ts](jep._PyJObject): ...

class XECKey[**Ts](jep._PyJObject): ...

class RSAMultiPrimePrivateCrtKey[**Ts](jep._PyJObject): ...

class DSAKey[**Ts](jep._PyJObject): ...

class DSAPrivateKey[**Ts](jep._PyJObject): ...

class ECPublicKey[**Ts](jep._PyJObject): ...

class ECKey[**Ts](jep._PyJObject): ...

class DSAParams[**Ts](jep._PyJObject): ...

