import jep

class DSAPublicKeySpec(jep.PyJObject): ...

class ECParameterSpec(jep.PyJObject): ...

class MGF1ParameterSpec(jep.PyJObject): ...

class DSAPrivateKeySpec(jep.PyJObject): ...

class X509EncodedKeySpec(jep.PyJObject): ...

class RSAOtherPrimeInfo(jep.PyJObject): ...

class KeySpec(jep.PyJObject): ...

class ECFieldFp(jep.PyJObject): ...

class ECPublicKeySpec(jep.PyJObject): ...

class XECPublicKeySpec(jep.PyJObject): ...

class RSAKeyGenParameterSpec(jep.PyJObject): ...

class RSAPrivateCrtKeySpec(jep.PyJObject): ...

class PKCS8EncodedKeySpec(jep.PyJObject): ...

class ECGenParameterSpec(jep.PyJObject): ...

class DSAGenParameterSpec(jep.PyJObject): ...

class EncodedKeySpec(jep.PyJObject): ...

class ECPoint(jep.PyJObject): ...

class ECFieldF2m(jep.PyJObject): ...

class AlgorithmParameterSpec(jep.PyJObject): ...

class InvalidKeySpecException(jep.PyJObject): ...

class RSAPrivateKeySpec(jep.PyJObject): ...

class EllipticCurve(jep.PyJObject): ...

class RSAMultiPrimePrivateCrtKeySpec(jep.PyJObject): ...

class XECPrivateKeySpec(jep.PyJObject): ...

class PSSParameterSpec(jep.PyJObject): ...

class RSAPublicKeySpec(jep.PyJObject): ...

class DSAParameterSpec(jep.PyJObject): ...

class InvalidParameterSpecException(jep.PyJObject): ...

class NamedParameterSpec(jep.PyJObject): ...

class ECPrivateKeySpec(jep.PyJObject): ...

