# pyright: reportPrivateUsage = none

import jep

class DSAGenParameterSpec[**Ts](jep._PyJObject): ...

class NamedParameterSpec[**Ts](jep._PyJObject): ...

class KeySpec[**Ts](jep._PyJObject): ...

class ECParameterSpec[**Ts](jep._PyJObject): ...

class ECPublicKeySpec[**Ts](jep._PyJObject): ...

class RSAPrivateCrtKeySpec[**Ts](jep._PyJObject): ...

class AlgorithmParameterSpec[**Ts](jep._PyJObject): ...

class ECFieldFp[**Ts](jep._PyJObject): ...

class X509EncodedKeySpec[**Ts](jep._PyJObject): ...

class DSAParameterSpec[**Ts](jep._PyJObject): ...

class ECField[**Ts](jep._PyJObject): ...

class ECGenParameterSpec[**Ts](jep._PyJObject): ...

class PSSParameterSpec[**Ts](jep._PyJObject): ...

class DSAPublicKeySpec[**Ts](jep._PyJObject): ...

class PKCS8EncodedKeySpec[**Ts](jep._PyJObject): ...

class RSAPrivateKeySpec[**Ts](jep._PyJObject): ...

class RSAOtherPrimeInfo[**Ts](jep._PyJObject): ...

class DSAPrivateKeySpec[**Ts](jep._PyJObject): ...

class XECPrivateKeySpec[**Ts](jep._PyJObject): ...

class ECPrivateKeySpec[**Ts](jep._PyJObject): ...

class EllipticCurve[**Ts](jep._PyJObject): ...

class EncodedKeySpec[**Ts](jep._PyJObject): ...

class RSAMultiPrimePrivateCrtKeySpec[**Ts](jep._PyJObject): ...

class ECFieldF2m[**Ts](jep._PyJObject): ...

class InvalidKeySpecException[**Ts](jep._PyJObject): ...

class RSAPublicKeySpec[**Ts](jep._PyJObject): ...

class InvalidParameterSpecException[**Ts](jep._PyJObject): ...

class XECPublicKeySpec[**Ts](jep._PyJObject): ...

class RSAKeyGenParameterSpec[**Ts](jep._PyJObject): ...

class ECPoint[**Ts](jep._PyJObject): ...

class MGF1ParameterSpec[**Ts](jep._PyJObject): ...

