import jep

class DSAPublicKeySpec(jep._PyJObject): ...

class ECParameterSpec(jep._PyJObject): ...

class MGF1ParameterSpec(jep._PyJObject): ...

class DSAPrivateKeySpec(jep._PyJObject): ...

class X509EncodedKeySpec(jep._PyJObject): ...

class RSAOtherPrimeInfo(jep._PyJObject): ...

class KeySpec(jep._PyJObject): ...

class ECFieldFp(jep._PyJObject): ...

class ECPublicKeySpec(jep._PyJObject): ...

class XECPublicKeySpec(jep._PyJObject): ...

class RSAKeyGenParameterSpec(jep._PyJObject): ...

class RSAPrivateCrtKeySpec(jep._PyJObject): ...

class PKCS8EncodedKeySpec(jep._PyJObject): ...

class ECGenParameterSpec(jep._PyJObject): ...

class DSAGenParameterSpec(jep._PyJObject): ...

class EncodedKeySpec(jep._PyJObject): ...

class ECPoint(jep._PyJObject): ...

class ECFieldF2m(jep._PyJObject): ...

class AlgorithmParameterSpec(jep._PyJObject): ...

class InvalidKeySpecException(jep._PyJObject): ...

class RSAPrivateKeySpec(jep._PyJObject): ...

class EllipticCurve(jep._PyJObject): ...

class RSAMultiPrimePrivateCrtKeySpec(jep._PyJObject): ...

class XECPrivateKeySpec(jep._PyJObject): ...

class PSSParameterSpec(jep._PyJObject): ...

class RSAPublicKeySpec(jep._PyJObject): ...

class DSAParameterSpec(jep._PyJObject): ...

class InvalidParameterSpecException(jep._PyJObject): ...

class NamedParameterSpec(jep._PyJObject): ...

class ECPrivateKeySpec(jep._PyJObject): ...

