import jep

class NodeSetData(jep._PyJObject): ...

class AlgorithmMethod(jep._PyJObject): ...

class Data(jep._PyJObject): ...

class XMLCryptoContext(jep._PyJObject): ...

class MarshalException(jep._PyJObject): ...

class NoSuchMechanismException(jep._PyJObject): ...

class URIReference(jep._PyJObject): ...

class KeySelector(jep._PyJObject): ...

class XMLStructure(jep._PyJObject): ...

class KeySelectorException(jep._PyJObject): ...

class URIDereferencer(jep._PyJObject): ...

class OctetStreamData(jep._PyJObject): ...

class KeySelectorResult(jep._PyJObject): ...

class URIReferenceException(jep._PyJObject): ...

