# pyright: reportPrivateUsage = none

import jep

class NodeSetData[**Ts](jep._PyJObject): ...

class NoSuchMechanismException[**Ts](jep._PyJObject): ...

class MarshalException[**Ts](jep._PyJObject): ...

class KeySelectorException[**Ts](jep._PyJObject): ...

class URIReferenceException[**Ts](jep._PyJObject): ...

class AlgorithmMethod[**Ts](jep._PyJObject): ...

class URIReference[**Ts](jep._PyJObject): ...

class Data[**Ts](jep._PyJObject): ...

class XMLStructure[**Ts](jep._PyJObject): ...

class KeySelectorResult[**Ts](jep._PyJObject): ...

class KeySelector[**Ts](jep._PyJObject): ...

class OctetStreamData[**Ts](jep._PyJObject): ...

class URIDereferencer[**Ts](jep._PyJObject): ...

class XMLCryptoContext[**Ts](jep._PyJObject): ...

