import jep

class NodeSetData(jep.PyJObject): ...

class AlgorithmMethod(jep.PyJObject): ...

class Data(jep.PyJObject): ...

class XMLCryptoContext(jep.PyJObject): ...

class MarshalException(jep.PyJObject): ...

class NoSuchMechanismException(jep.PyJObject): ...

class URIReference(jep.PyJObject): ...

class KeySelector(jep.PyJObject): ...

class XMLStructure(jep.PyJObject): ...

class KeySelectorException(jep.PyJObject): ...

class URIDereferencer(jep.PyJObject): ...

class OctetStreamData(jep.PyJObject): ...

class KeySelectorResult(jep.PyJObject): ...

class URIReferenceException(jep.PyJObject): ...

