# pyright: reportPrivateUsage = none

import jep

class PasswordView[**Ts](jep._PyJObject): ...

class FieldView[**Ts](jep._PyJObject): ...

class DefaultStyledDocument[**Ts](jep._PyJObject): ...

class LabelView[**Ts](jep._PyJObject): ...

class BadLocationException[**Ts](jep._PyJObject): ...

class Style[**Ts](jep._PyJObject): ...

class ComponentView[**Ts](jep._PyJObject): ...

class StyledDocument[**Ts](jep._PyJObject): ...

class AttributeSet[**Ts](jep._PyJObject): ...

class Document[**Ts](jep._PyJObject): ...

class WrappedPlainView[**Ts](jep._PyJObject): ...

class FlowView[**Ts](jep._PyJObject): ...

class StyledEditorKit[**Ts](jep._PyJObject): ...

class AbstractWriter[**Ts](jep._PyJObject): ...

class EditorKit[**Ts](jep._PyJObject): ...

class DefaultCaret[**Ts](jep._PyJObject): ...

class PlainView[**Ts](jep._PyJObject): ...

class AbstractDocument[**Ts](jep._PyJObject): ...

class GlyphView[**Ts](jep._PyJObject): ...

class InternationalFormatter[**Ts](jep._PyJObject): ...

class TextAction[**Ts](jep._PyJObject): ...

class CompositeView[**Ts](jep._PyJObject): ...

class TabStop[**Ts](jep._PyJObject): ...

class DefaultHighlighter[**Ts](jep._PyJObject): ...

class DefaultFormatter[**Ts](jep._PyJObject): ...

class DateFormatter[**Ts](jep._PyJObject): ...

class BoxView[**Ts](jep._PyJObject): ...

class Position[**Ts](jep._PyJObject): ...

class ParagraphView[**Ts](jep._PyJObject): ...

class StyleConstants[**Ts](jep._PyJObject): ...

class ViewFactory[**Ts](jep._PyJObject): ...

class NumberFormatter[**Ts](jep._PyJObject): ...

class Highlighter[**Ts](jep._PyJObject): ...

class MaskFormatter[**Ts](jep._PyJObject): ...

class LayeredHighlighter[**Ts](jep._PyJObject): ...

class StyleContext[**Ts](jep._PyJObject): ...

class StringContent[**Ts](jep._PyJObject): ...

class SimpleAttributeSet[**Ts](jep._PyJObject): ...

class PlainDocument[**Ts](jep._PyJObject): ...

class LayoutQueue[**Ts](jep._PyJObject): ...

class DefaultFormatterFactory[**Ts](jep._PyJObject): ...

class MutableAttributeSet[**Ts](jep._PyJObject): ...

class Utilities[**Ts](jep._PyJObject): ...

class DefaultTextUI[**Ts](jep._PyJObject): ...

class TabExpander[**Ts](jep._PyJObject): ...

class ZoneView[**Ts](jep._PyJObject): ...

class TableView[**Ts](jep._PyJObject): ...

class DefaultEditorKit[**Ts](jep._PyJObject): ...

class Keymap[**Ts](jep._PyJObject): ...

class NavigationFilter[**Ts](jep._PyJObject): ...

class ChangedCharSetException[**Ts](jep._PyJObject): ...

class DocumentFilter[**Ts](jep._PyJObject): ...

class View[**Ts](jep._PyJObject): ...

class IconView[**Ts](jep._PyJObject): ...

class ElementIterator[**Ts](jep._PyJObject): ...

class Element[**Ts](jep._PyJObject): ...

class TabSet[**Ts](jep._PyJObject): ...

class Caret[**Ts](jep._PyJObject): ...

class JTextComponent[**Ts](jep._PyJObject): ...

class Segment[**Ts](jep._PyJObject): ...

class GapContent[**Ts](jep._PyJObject): ...

class AsyncBoxView[**Ts](jep._PyJObject): ...

