import jep

class LinearGradientPaint(jep.PyJObject): ...

class ScrollPaneAdjustable(jep.PyJObject): ...

class DefaultKeyboardFocusManager(jep.PyJObject): ...

class AWTException(jep.PyJObject): ...

class HeadlessException(jep.PyJObject): ...

class SystemTray(jep.PyJObject): ...

class TextArea(jep.PyJObject): ...

class GraphicsDevice(jep.PyJObject): ...

class Panel(jep.PyJObject): ...

class Cursor(jep.PyJObject): ...

class Container(jep.PyJObject): ...

class Rectangle(jep.PyJObject): ...

class AWTKeyStroke(jep.PyJObject): ...

class CheckboxGroup(jep.PyJObject): ...

class GradientPaint(jep.PyJObject): ...

class Choice(jep.PyJObject): ...

class EventQueue(jep.PyJObject): ...

class DefaultFocusTraversalPolicy(jep.PyJObject): ...

class FlowLayout(jep.PyJObject): ...

class RenderingHints(jep.PyJObject): ...

class GridBagConstraints(jep.PyJObject): ...

class CompositeContext(jep.PyJObject): ...

class MenuComponent(jep.PyJObject): ...

class FontMetrics(jep.PyJObject): ...

class ScrollPane(jep.PyJObject): ...

class Scrollbar(jep.PyJObject): ...

class KeyboardFocusManager(jep.PyJObject): ...

class Menu(jep.PyJObject): ...

class ContainerOrderFocusTraversalPolicy(jep.PyJObject): ...

class ImageCapabilities(jep.PyJObject): ...

class Component(jep.PyJObject): ...

class Adjustable(jep.PyJObject): ...

class Stroke(jep.PyJObject): ...

class Button(jep.PyJObject): ...

class TrayIcon(jep.PyJObject): ...

class RadialGradientPaint(jep.PyJObject): ...

class Graphics2D(jep.PyJObject): ...

class TextField(jep.PyJObject): ...

class Label(jep.PyJObject): ...

class AWTEventMulticaster(jep.PyJObject): ...

class Toolkit(jep.PyJObject): ...

class Transparency(jep.PyJObject): ...

class Dimension(jep.PyJObject): ...

class SystemColor(jep.PyJObject): ...

class ComponentOrientation(jep.PyJObject): ...

class MediaTracker(jep.PyJObject): ...

class LayoutManager(jep.PyJObject): ...

class PopupMenu(jep.PyJObject): ...

class Color(jep.PyJObject): ...

class BorderLayout(jep.PyJObject): ...

class Composite(jep.PyJObject): ...

class Font(jep.PyJObject): ...

class MenuContainer(jep.PyJObject): ...

class PaintContext(jep.PyJObject): ...

class PrintGraphics(jep.PyJObject): ...

class Graphics(jep.PyJObject): ...

class Canvas(jep.PyJObject): ...

class Image(jep.PyJObject): ...

class Window(jep.PyJObject): ...

class Insets(jep.PyJObject): ...

class JobAttributes(jep.PyJObject): ...

class GraphicsConfigTemplate(jep.PyJObject): ...

class GridBagLayoutInfo(jep.PyJObject): ...

class List(jep.PyJObject): ...

class FontFormatException(jep.PyJObject): ...

class Paint(jep.PyJObject): ...

class Checkbox(jep.PyJObject): ...

class TexturePaint(jep.PyJObject): ...

class BasicStroke(jep.PyJObject): ...

class Desktop(jep.PyJObject): ...

class Event(jep.PyJObject): ...

class PointerInfo(jep.PyJObject): ...

class GraphicsConfiguration(jep.PyJObject): ...

class MenuBar(jep.PyJObject): ...

class CheckboxMenuItem(jep.PyJObject): ...

class KeyEventPostProcessor(jep.PyJObject): ...

class ItemSelectable(jep.PyJObject): ...

class MenuShortcut(jep.PyJObject): ...

class MultipleGradientPaint(jep.PyJObject): ...

class PrintJob(jep.PyJObject): ...

class Shape(jep.PyJObject): ...

class Robot(jep.PyJObject): ...

class AlphaComposite(jep.PyJObject): ...

class KeyEventDispatcher(jep.PyJObject): ...

class TextComponent(jep.PyJObject): ...

class GridLayout(jep.PyJObject): ...

class IllegalComponentStateException(jep.PyJObject): ...

class BufferCapabilities(jep.PyJObject): ...

class Dialog(jep.PyJObject): ...

class ActiveEvent(jep.PyJObject): ...

class MenuItem(jep.PyJObject): ...

class Point(jep.PyJObject): ...

class AWTError(jep.PyJObject): ...

class FocusTraversalPolicy(jep.PyJObject): ...

class SplashScreen(jep.PyJObject): ...

class MouseInfo(jep.PyJObject): ...

class PageAttributes(jep.PyJObject): ...

class Frame(jep.PyJObject): ...

class SecondaryLoop(jep.PyJObject): ...

class FileDialog(jep.PyJObject): ...

class GraphicsEnvironment(jep.PyJObject): ...

class DisplayMode(jep.PyJObject): ...

class Taskbar(jep.PyJObject): ...

class CardLayout(jep.PyJObject): ...

class Polygon(jep.PyJObject): ...

class AWTEvent(jep.PyJObject): ...

class LayoutManager2(jep.PyJObject): ...

class AWTPermission(jep.PyJObject): ...

class GridBagLayout(jep.PyJObject): ...

