import jep

class LinearGradientPaint(jep._PyJObject): ...

class ScrollPaneAdjustable(jep._PyJObject): ...

class DefaultKeyboardFocusManager(jep._PyJObject): ...

class AWTException(jep._PyJObject): ...

class HeadlessException(jep._PyJObject): ...

class SystemTray(jep._PyJObject): ...

class TextArea(jep._PyJObject): ...

class GraphicsDevice(jep._PyJObject): ...

class Panel(jep._PyJObject): ...

class Cursor(jep._PyJObject): ...

class Container(jep._PyJObject): ...

class Rectangle(jep._PyJObject): ...

class AWTKeyStroke(jep._PyJObject): ...

class CheckboxGroup(jep._PyJObject): ...

class GradientPaint(jep._PyJObject): ...

class Choice(jep._PyJObject): ...

class EventQueue(jep._PyJObject): ...

class DefaultFocusTraversalPolicy(jep._PyJObject): ...

class FlowLayout(jep._PyJObject): ...

class RenderingHints(jep._PyJObject): ...

class GridBagConstraints(jep._PyJObject): ...

class CompositeContext(jep._PyJObject): ...

class MenuComponent(jep._PyJObject): ...

class FontMetrics(jep._PyJObject): ...

class ScrollPane(jep._PyJObject): ...

class Scrollbar(jep._PyJObject): ...

class KeyboardFocusManager(jep._PyJObject): ...

class Menu(jep._PyJObject): ...

class ContainerOrderFocusTraversalPolicy(jep._PyJObject): ...

class ImageCapabilities(jep._PyJObject): ...

class Component(jep._PyJObject): ...

class Adjustable(jep._PyJObject): ...

class Stroke(jep._PyJObject): ...

class Button(jep._PyJObject): ...

class TrayIcon(jep._PyJObject): ...

class RadialGradientPaint(jep._PyJObject): ...

class Graphics2D(jep._PyJObject): ...

class TextField(jep._PyJObject): ...

class Label(jep._PyJObject): ...

class AWTEventMulticaster(jep._PyJObject): ...

class Toolkit(jep._PyJObject): ...

class Transparency(jep._PyJObject): ...

class Dimension(jep._PyJObject): ...

class SystemColor(jep._PyJObject): ...

class ComponentOrientation(jep._PyJObject): ...

class MediaTracker(jep._PyJObject): ...

class LayoutManager(jep._PyJObject): ...

class PopupMenu(jep._PyJObject): ...

class Color(jep._PyJObject): ...

class BorderLayout(jep._PyJObject): ...

class Composite(jep._PyJObject): ...

class Font(jep._PyJObject): ...

class MenuContainer(jep._PyJObject): ...

class PaintContext(jep._PyJObject): ...

class PrintGraphics(jep._PyJObject): ...

class Graphics(jep._PyJObject): ...

class Canvas(jep._PyJObject): ...

class Image(jep._PyJObject): ...

class Window(jep._PyJObject): ...

class Insets(jep._PyJObject): ...

class JobAttributes(jep._PyJObject): ...

class GraphicsConfigTemplate(jep._PyJObject): ...

class GridBagLayoutInfo(jep._PyJObject): ...

class List(jep._PyJObject): ...

class FontFormatException(jep._PyJObject): ...

class Paint(jep._PyJObject): ...

class Checkbox(jep._PyJObject): ...

class TexturePaint(jep._PyJObject): ...

class BasicStroke(jep._PyJObject): ...

class Desktop(jep._PyJObject): ...

class Event(jep._PyJObject): ...

class PointerInfo(jep._PyJObject): ...

class GraphicsConfiguration(jep._PyJObject): ...

class MenuBar(jep._PyJObject): ...

class CheckboxMenuItem(jep._PyJObject): ...

class KeyEventPostProcessor(jep._PyJObject): ...

class ItemSelectable(jep._PyJObject): ...

class MenuShortcut(jep._PyJObject): ...

class MultipleGradientPaint(jep._PyJObject): ...

class PrintJob(jep._PyJObject): ...

class Shape(jep._PyJObject): ...

class Robot(jep._PyJObject): ...

class AlphaComposite(jep._PyJObject): ...

class KeyEventDispatcher(jep._PyJObject): ...

class TextComponent(jep._PyJObject): ...

class GridLayout(jep._PyJObject): ...

class IllegalComponentStateException(jep._PyJObject): ...

class BufferCapabilities(jep._PyJObject): ...

class Dialog(jep._PyJObject): ...

class ActiveEvent(jep._PyJObject): ...

class MenuItem(jep._PyJObject): ...

class Point(jep._PyJObject): ...

class AWTError(jep._PyJObject): ...

class FocusTraversalPolicy(jep._PyJObject): ...

class SplashScreen(jep._PyJObject): ...

class MouseInfo(jep._PyJObject): ...

class PageAttributes(jep._PyJObject): ...

class Frame(jep._PyJObject): ...

class SecondaryLoop(jep._PyJObject): ...

class FileDialog(jep._PyJObject): ...

class GraphicsEnvironment(jep._PyJObject): ...

class DisplayMode(jep._PyJObject): ...

class Taskbar(jep._PyJObject): ...

class CardLayout(jep._PyJObject): ...

class Polygon(jep._PyJObject): ...

class AWTEvent(jep._PyJObject): ...

class LayoutManager2(jep._PyJObject): ...

class AWTPermission(jep._PyJObject): ...

class GridBagLayout(jep._PyJObject): ...

