# pyright: reportPrivateUsage = none

import jep

class ComponentOrientation[**Ts](jep._PyJObject): ...

class Point[**Ts](jep._PyJObject): ...

class Cursor[**Ts](jep._PyJObject): ...

class JobAttributes[**Ts](jep._PyJObject): ...

class MediaTracker[**Ts](jep._PyJObject): ...

class Shape[**Ts](jep._PyJObject): ...

class GraphicsConfigTemplate[**Ts](jep._PyJObject): ...

class GridBagLayout[**Ts](jep._PyJObject): ...

class Label[**Ts](jep._PyJObject): ...

class Event[**Ts](jep._PyJObject): ...

class BasicStroke[**Ts](jep._PyJObject): ...

class Menu[**Ts](jep._PyJObject): ...

class CardLayout[**Ts](jep._PyJObject): ...

class Taskbar[**Ts](jep._PyJObject): ...

class AWTException[**Ts](jep._PyJObject): ...

class Paint[**Ts](jep._PyJObject): ...

class Component[**Ts](jep._PyJObject): ...

class List[**Ts](jep._PyJObject): ...

class Choice[**Ts](jep._PyJObject): ...

class GraphicsConfiguration[**Ts](jep._PyJObject): ...

class Checkbox[**Ts](jep._PyJObject): ...

class Graphics2D[**Ts](jep._PyJObject): ...

class RenderingHints[**Ts](jep._PyJObject): ...

class KeyboardFocusManager[**Ts](jep._PyJObject): ...

class Window[**Ts](jep._PyJObject): ...

class KeyEventDispatcher[**Ts](jep._PyJObject): ...

class Transparency[**Ts](jep._PyJObject): ...

class FontMetrics[**Ts](jep._PyJObject): ...

class Panel[**Ts](jep._PyJObject): ...

class CompositeContext[**Ts](jep._PyJObject): ...

class Rectangle[**Ts](jep._PyJObject): ...

class TextField[**Ts](jep._PyJObject): ...

class Desktop[**Ts](jep._PyJObject): ...

class MouseInfo[**Ts](jep._PyJObject): ...

class FocusTraversalPolicy[**Ts](jep._PyJObject): ...

class MenuBar[**Ts](jep._PyJObject): ...

class EventQueue[**Ts](jep._PyJObject): ...

class LayoutManager[**Ts](jep._PyJObject): ...

class ScrollPane[**Ts](jep._PyJObject): ...

class Button[**Ts](jep._PyJObject): ...

class PopupMenu[**Ts](jep._PyJObject): ...

class SplashScreen[**Ts](jep._PyJObject): ...

class Frame[**Ts](jep._PyJObject): ...

class Graphics[**Ts](jep._PyJObject): ...

class SystemTray[**Ts](jep._PyJObject): ...

class Dialog[**Ts](jep._PyJObject): ...

class DefaultFocusTraversalPolicy[**Ts](jep._PyJObject): ...

class PaintContext[**Ts](jep._PyJObject): ...

class PageAttributes[**Ts](jep._PyJObject): ...

class MenuComponent[**Ts](jep._PyJObject): ...

class Canvas[**Ts](jep._PyJObject): ...

class Dimension[**Ts](jep._PyJObject): ...

class MenuItem[**Ts](jep._PyJObject): ...

class MenuContainer[**Ts](jep._PyJObject): ...

class FontFormatException[**Ts](jep._PyJObject): ...

class GradientPaint[**Ts](jep._PyJObject): ...

class Scrollbar[**Ts](jep._PyJObject): ...

class SecondaryLoop[**Ts](jep._PyJObject): ...

class LayoutManager2[**Ts](jep._PyJObject): ...

class Polygon[**Ts](jep._PyJObject): ...

class CheckboxMenuItem[**Ts](jep._PyJObject): ...

class Insets[**Ts](jep._PyJObject): ...

class MenuShortcut[**Ts](jep._PyJObject): ...

class GridBagConstraints[**Ts](jep._PyJObject): ...

class ContainerOrderFocusTraversalPolicy[**Ts](jep._PyJObject): ...

class BorderLayout[**Ts](jep._PyJObject): ...

class FileDialog[**Ts](jep._PyJObject): ...

class Composite[**Ts](jep._PyJObject): ...

class Container[**Ts](jep._PyJObject): ...

class AWTError[**Ts](jep._PyJObject): ...

class Color[**Ts](jep._PyJObject): ...

class AlphaComposite[**Ts](jep._PyJObject): ...

class Robot[**Ts](jep._PyJObject): ...

class Image[**Ts](jep._PyJObject): ...

class AWTEventMulticaster[**Ts](jep._PyJObject): ...

class GridLayout[**Ts](jep._PyJObject): ...

class MultipleGradientPaint[**Ts](jep._PyJObject): ...

class PointerInfo[**Ts](jep._PyJObject): ...

class CheckboxGroup[**Ts](jep._PyJObject): ...

class GridBagLayoutInfo[**Ts](jep._PyJObject): ...

class TrayIcon[**Ts](jep._PyJObject): ...

class BufferCapabilities[**Ts](jep._PyJObject): ...

class Font[**Ts](jep._PyJObject): ...

class AWTEvent[**Ts](jep._PyJObject): ...

class ScrollPaneAdjustable[**Ts](jep._PyJObject): ...

class GraphicsDevice[**Ts](jep._PyJObject): ...

class PrintJob[**Ts](jep._PyJObject): ...

class IllegalComponentStateException[**Ts](jep._PyJObject): ...

class RadialGradientPaint[**Ts](jep._PyJObject): ...

class LinearGradientPaint[**Ts](jep._PyJObject): ...

class AWTKeyStroke[**Ts](jep._PyJObject): ...

class DisplayMode[**Ts](jep._PyJObject): ...

class Toolkit[**Ts](jep._PyJObject): ...

class GraphicsEnvironment[**Ts](jep._PyJObject): ...

class Adjustable[**Ts](jep._PyJObject): ...

class Stroke[**Ts](jep._PyJObject): ...

class FlowLayout[**Ts](jep._PyJObject): ...

class TexturePaint[**Ts](jep._PyJObject): ...

class ActiveEvent[**Ts](jep._PyJObject): ...

class TextComponent[**Ts](jep._PyJObject): ...

class ItemSelectable[**Ts](jep._PyJObject): ...

class ImageCapabilities[**Ts](jep._PyJObject): ...

class KeyEventPostProcessor[**Ts](jep._PyJObject): ...

class HeadlessException[**Ts](jep._PyJObject): ...

class SystemColor[**Ts](jep._PyJObject): ...

class DefaultKeyboardFocusManager[**Ts](jep._PyJObject): ...

class TextArea[**Ts](jep._PyJObject): ...

class AWTPermission[**Ts](jep._PyJObject): ...

class PrintGraphics[**Ts](jep._PyJObject): ...

