import jep

class ICC_ProfileRGB(jep._PyJObject): ...

class CMMException(jep._PyJObject): ...

class ICC_Profile(jep._PyJObject): ...

class ICC_ColorSpace(jep._PyJObject): ...

class ICC_ProfileGray(jep._PyJObject): ...

class ColorSpace(jep._PyJObject): ...

class ProfileDataException(jep._PyJObject): ...

