# pyright: reportPrivateUsage = none

import jep

class ICC_ColorSpace[**Ts](jep._PyJObject): ...

class ICC_Profile[**Ts](jep._PyJObject): ...

class ICC_ProfileRGB[**Ts](jep._PyJObject): ...

class ICC_ProfileGray[**Ts](jep._PyJObject): ...

class ProfileDataException[**Ts](jep._PyJObject): ...

class CMMException[**Ts](jep._PyJObject): ...

class ColorSpace[**Ts](jep._PyJObject): ...

