import jep

class ICC_ProfileRGB(jep.PyJObject): ...

class CMMException(jep.PyJObject): ...

class ICC_Profile(jep.PyJObject): ...

class ICC_ColorSpace(jep.PyJObject): ...

class ICC_ProfileGray(jep.PyJObject): ...

class ColorSpace(jep.PyJObject): ...

class ProfileDataException(jep.PyJObject): ...

