import jep

class FlavorTable(jep._PyJObject): ...

class FlavorMap(jep._PyJObject): ...

class StringSelection(jep._PyJObject): ...

class ClipboardOwner(jep._PyJObject): ...

class SystemFlavorMap(jep._PyJObject): ...

class FlavorListener(jep._PyJObject): ...

class FlavorEvent(jep._PyJObject): ...

class MimeTypeParseException(jep._PyJObject): ...

class DataFlavor(jep._PyJObject): ...

class Clipboard(jep._PyJObject): ...

class UnsupportedFlavorException(jep._PyJObject): ...

class Transferable(jep._PyJObject): ...

