# pyright: reportPrivateUsage = none

import jep

class Clipboard[**Ts](jep._PyJObject): ...

class UnsupportedFlavorException[**Ts](jep._PyJObject): ...

class Transferable[**Ts](jep._PyJObject): ...

class FlavorListener[**Ts](jep._PyJObject): ...

class FlavorEvent[**Ts](jep._PyJObject): ...

class SystemFlavorMap[**Ts](jep._PyJObject): ...

class FlavorMap[**Ts](jep._PyJObject): ...

class DataFlavor[**Ts](jep._PyJObject): ...

class FlavorTable[**Ts](jep._PyJObject): ...

class MimeTypeParseException[**Ts](jep._PyJObject): ...

class StringSelection[**Ts](jep._PyJObject): ...

class ClipboardOwner[**Ts](jep._PyJObject): ...

