import jep

class FlavorTable(jep.PyJObject): ...

class FlavorMap(jep.PyJObject): ...

class StringSelection(jep.PyJObject): ...

class ClipboardOwner(jep.PyJObject): ...

class SystemFlavorMap(jep.PyJObject): ...

class FlavorListener(jep.PyJObject): ...

class FlavorEvent(jep.PyJObject): ...

class MimeTypeParseException(jep.PyJObject): ...

class DataFlavor(jep.PyJObject): ...

class Clipboard(jep.PyJObject): ...

class UnsupportedFlavorException(jep.PyJObject): ...

class Transferable(jep.PyJObject): ...

