import jep

class SystemEventListener(jep._PyJObject): ...

class QuitStrategy(jep._PyJObject): ...

class OpenURIEvent(jep._PyJObject): ...

class QuitResponse(jep._PyJObject): ...

class AboutHandler(jep._PyJObject): ...

class AppEvent(jep._PyJObject): ...

class AppHiddenEvent(jep._PyJObject): ...

class UserSessionEvent(jep._PyJObject): ...

class QuitHandler(jep._PyJObject): ...

class AboutEvent(jep._PyJObject): ...

class AppForegroundListener(jep._PyJObject): ...

class UserSessionListener(jep._PyJObject): ...

class ScreenSleepEvent(jep._PyJObject): ...

class SystemSleepListener(jep._PyJObject): ...

class FilesEvent(jep._PyJObject): ...

class QuitEvent(jep._PyJObject): ...

class AppReopenedEvent(jep._PyJObject): ...

class PreferencesHandler(jep._PyJObject): ...

class OpenFilesHandler(jep._PyJObject): ...

class AppForegroundEvent(jep._PyJObject): ...

class PrintFilesEvent(jep._PyJObject): ...

class AppHiddenListener(jep._PyJObject): ...

class PreferencesEvent(jep._PyJObject): ...

class OpenURIHandler(jep._PyJObject): ...

class SystemSleepEvent(jep._PyJObject): ...

class PrintFilesHandler(jep._PyJObject): ...

class AppReopenedListener(jep._PyJObject): ...

class ScreenSleepListener(jep._PyJObject): ...

class OpenFilesEvent(jep._PyJObject): ...

