# pyright: reportPrivateUsage = none

import jep

class AppHiddenEvent[**Ts](jep._PyJObject): ...

class OpenURIEvent[**Ts](jep._PyJObject): ...

class AppForegroundEvent[**Ts](jep._PyJObject): ...

class SystemSleepListener[**Ts](jep._PyJObject): ...

class AppForegroundListener[**Ts](jep._PyJObject): ...

class SystemSleepEvent[**Ts](jep._PyJObject): ...

class FilesEvent[**Ts](jep._PyJObject): ...

class SystemEventListener[**Ts](jep._PyJObject): ...

class QuitStrategy[**Ts](jep._PyJObject): ...

class QuitResponse[**Ts](jep._PyJObject): ...

class AboutHandler[**Ts](jep._PyJObject): ...

class AppEvent[**Ts](jep._PyJObject): ...

class AppReopenedEvent[**Ts](jep._PyJObject): ...

class AboutEvent[**Ts](jep._PyJObject): ...

class ScreenSleepListener[**Ts](jep._PyJObject): ...

class QuitEvent[**Ts](jep._PyJObject): ...

class AppReopenedListener[**Ts](jep._PyJObject): ...

class PreferencesHandler[**Ts](jep._PyJObject): ...

class AppHiddenListener[**Ts](jep._PyJObject): ...

class PrintFilesEvent[**Ts](jep._PyJObject): ...

class PreferencesEvent[**Ts](jep._PyJObject): ...

class PrintFilesHandler[**Ts](jep._PyJObject): ...

class QuitHandler[**Ts](jep._PyJObject): ...

class UserSessionEvent[**Ts](jep._PyJObject): ...

class OpenFilesHandler[**Ts](jep._PyJObject): ...

class OpenURIHandler[**Ts](jep._PyJObject): ...

class OpenFilesEvent[**Ts](jep._PyJObject): ...

class ScreenSleepEvent[**Ts](jep._PyJObject): ...

