import jep

class SystemEventListener(jep.PyJObject): ...

class QuitStrategy(jep.PyJObject): ...

class OpenURIEvent(jep.PyJObject): ...

class QuitResponse(jep.PyJObject): ...

class AboutHandler(jep.PyJObject): ...

class AppEvent(jep.PyJObject): ...

class AppHiddenEvent(jep.PyJObject): ...

class UserSessionEvent(jep.PyJObject): ...

class QuitHandler(jep.PyJObject): ...

class AboutEvent(jep.PyJObject): ...

class AppForegroundListener(jep.PyJObject): ...

class UserSessionListener(jep.PyJObject): ...

class ScreenSleepEvent(jep.PyJObject): ...

class SystemSleepListener(jep.PyJObject): ...

class FilesEvent(jep.PyJObject): ...

class QuitEvent(jep.PyJObject): ...

class AppReopenedEvent(jep.PyJObject): ...

class PreferencesHandler(jep.PyJObject): ...

class OpenFilesHandler(jep.PyJObject): ...

class AppForegroundEvent(jep.PyJObject): ...

class PrintFilesEvent(jep.PyJObject): ...

class AppHiddenListener(jep.PyJObject): ...

class PreferencesEvent(jep.PyJObject): ...

class OpenURIHandler(jep.PyJObject): ...

class SystemSleepEvent(jep.PyJObject): ...

class PrintFilesHandler(jep.PyJObject): ...

class AppReopenedListener(jep.PyJObject): ...

class ScreenSleepListener(jep.PyJObject): ...

class OpenFilesEvent(jep.PyJObject): ...

