import jep

class DnDConstants(jep._PyJObject): ...

class InvalidDnDOperationException(jep._PyJObject): ...

class DropTargetListener(jep._PyJObject): ...

class DragSourceMotionListener(jep._PyJObject): ...

class DragSourceDropEvent(jep._PyJObject): ...

class DragSourceEvent(jep._PyJObject): ...

class DropTargetAdapter(jep._PyJObject): ...

class MouseDragGestureRecognizer(jep._PyJObject): ...

class DragGestureRecognizer(jep._PyJObject): ...

class DragSourceDragEvent(jep._PyJObject): ...

class DragSourceListener(jep._PyJObject): ...

class DropTargetContext(jep._PyJObject): ...

class DragGestureListener(jep._PyJObject): ...

class DropTargetEvent(jep._PyJObject): ...

class DropTargetDropEvent(jep._PyJObject): ...

class DropTarget(jep._PyJObject): ...

class DragGestureEvent(jep._PyJObject): ...

class DragSource(jep._PyJObject): ...

class Autoscroll(jep._PyJObject): ...

class DragSourceAdapter(jep._PyJObject): ...

class DragSourceContext(jep._PyJObject): ...

class DropTargetDragEvent(jep._PyJObject): ...

