import jep

class DnDConstants(jep.PyJObject): ...

class InvalidDnDOperationException(jep.PyJObject): ...

class DropTargetListener(jep.PyJObject): ...

class DragSourceMotionListener(jep.PyJObject): ...

class DragSourceDropEvent(jep.PyJObject): ...

class DragSourceEvent(jep.PyJObject): ...

class DropTargetAdapter(jep.PyJObject): ...

class MouseDragGestureRecognizer(jep.PyJObject): ...

class DragGestureRecognizer(jep.PyJObject): ...

class DragSourceDragEvent(jep.PyJObject): ...

class DragSourceListener(jep.PyJObject): ...

class DropTargetContext(jep.PyJObject): ...

class DragGestureListener(jep.PyJObject): ...

class DropTargetEvent(jep.PyJObject): ...

class DropTargetDropEvent(jep.PyJObject): ...

class DropTarget(jep.PyJObject): ...

class DragGestureEvent(jep.PyJObject): ...

class DragSource(jep.PyJObject): ...

class Autoscroll(jep.PyJObject): ...

class DragSourceAdapter(jep.PyJObject): ...

class DragSourceContext(jep.PyJObject): ...

class DropTargetDragEvent(jep.PyJObject): ...

