# pyright: reportPrivateUsage = none

import jep

class DropTargetEvent[**Ts](jep._PyJObject): ...

class InvalidDnDOperationException[**Ts](jep._PyJObject): ...

class DragSourceAdapter[**Ts](jep._PyJObject): ...

class DragSourceListener[**Ts](jep._PyJObject): ...

class DropTargetContext[**Ts](jep._PyJObject): ...

class DragGestureRecognizer[**Ts](jep._PyJObject): ...

class DropTargetListener[**Ts](jep._PyJObject): ...

class DragSourceContext[**Ts](jep._PyJObject): ...

class DragGestureEvent[**Ts](jep._PyJObject): ...

class DnDConstants[**Ts](jep._PyJObject): ...

class DragSource[**Ts](jep._PyJObject): ...

class DropTargetAdapter[**Ts](jep._PyJObject): ...

class DragSourceDragEvent[**Ts](jep._PyJObject): ...

class DragGestureListener[**Ts](jep._PyJObject): ...

class DragSourceMotionListener[**Ts](jep._PyJObject): ...

class MouseDragGestureRecognizer[**Ts](jep._PyJObject): ...

class DragSourceDropEvent[**Ts](jep._PyJObject): ...

class DropTargetDragEvent[**Ts](jep._PyJObject): ...

class DragSourceEvent[**Ts](jep._PyJObject): ...

class DropTargetDropEvent[**Ts](jep._PyJObject): ...

class DropTarget[**Ts](jep._PyJObject): ...

class Autoscroll[**Ts](jep._PyJObject): ...

