import jep

class ActionListener(jep.PyJObject): ...

class MouseMotionListener(jep.PyJObject): ...

class WindowStateListener(jep.PyJObject): ...

class TextListener(jep.PyJObject): ...

class ItemEvent(jep.PyJObject): ...

class AWTEventListener(jep.PyJObject): ...

class InputMethodEvent(jep.PyJObject): ...

class FocusEvent(jep.PyJObject): ...

class HierarchyBoundsAdapter(jep.PyJObject): ...

class ComponentEvent(jep.PyJObject): ...

class KeyEvent(jep.PyJObject): ...

class KeyListener(jep.PyJObject): ...

class HierarchyListener(jep.PyJObject): ...

class MouseAdapter(jep.PyJObject): ...

class InputMethodListener(jep.PyJObject): ...

class WindowListener(jep.PyJObject): ...

class KeyAdapter(jep.PyJObject): ...

class MouseMotionAdapter(jep.PyJObject): ...

class FocusAdapter(jep.PyJObject): ...

class ContainerListener(jep.PyJObject): ...

class HierarchyBoundsListener(jep.PyJObject): ...

class InvocationEvent(jep.PyJObject): ...

class ComponentListener(jep.PyJObject): ...

class ContainerEvent(jep.PyJObject): ...

class AdjustmentEvent(jep.PyJObject): ...

class MouseListener(jep.PyJObject): ...

class WindowAdapter(jep.PyJObject): ...

class InputEvent(jep.PyJObject): ...

class AdjustmentListener(jep.PyJObject): ...

class AWTEventListenerProxy(jep.PyJObject): ...

class ContainerAdapter(jep.PyJObject): ...

class HierarchyEvent(jep.PyJObject): ...

class PaintEvent(jep.PyJObject): ...

class ActionEvent(jep.PyJObject): ...

class FocusListener(jep.PyJObject): ...

class ItemListener(jep.PyJObject): ...

class WindowFocusListener(jep.PyJObject): ...

class MouseWheelListener(jep.PyJObject): ...

class TextEvent(jep.PyJObject): ...

class ComponentAdapter(jep.PyJObject): ...

class MouseWheelEvent(jep.PyJObject): ...

class MouseEvent(jep.PyJObject): ...

class WindowEvent(jep.PyJObject): ...

