# pyright: reportPrivateUsage = none

import jep

class KeyEvent[**Ts](jep._PyJObject): ...

class KeyAdapter[**Ts](jep._PyJObject): ...

class InputMethodEvent[**Ts](jep._PyJObject): ...

class TextEvent[**Ts](jep._PyJObject): ...

class ActionListener[**Ts](jep._PyJObject): ...

class AWTEventListener[**Ts](jep._PyJObject): ...

class ContainerAdapter[**Ts](jep._PyJObject): ...

class ContainerEvent[**Ts](jep._PyJObject): ...

class MouseWheelListener[**Ts](jep._PyJObject): ...

class WindowFocusListener[**Ts](jep._PyJObject): ...

class WindowAdapter[**Ts](jep._PyJObject): ...

class MouseMotionListener[**Ts](jep._PyJObject): ...

class InputEvent[**Ts](jep._PyJObject): ...

class HierarchyListener[**Ts](jep._PyJObject): ...

class MouseListener[**Ts](jep._PyJObject): ...

class ComponentAdapter[**Ts](jep._PyJObject): ...

class HierarchyEvent[**Ts](jep._PyJObject): ...

class MouseWheelEvent[**Ts](jep._PyJObject): ...

class ComponentEvent[**Ts](jep._PyJObject): ...

class InputMethodListener[**Ts](jep._PyJObject): ...

class TextListener[**Ts](jep._PyJObject): ...

class ItemListener[**Ts](jep._PyJObject): ...

class HierarchyBoundsListener[**Ts](jep._PyJObject): ...

class FocusListener[**Ts](jep._PyJObject): ...

class WindowListener[**Ts](jep._PyJObject): ...

class HierarchyBoundsAdapter[**Ts](jep._PyJObject): ...

class ComponentListener[**Ts](jep._PyJObject): ...

class MouseAdapter[**Ts](jep._PyJObject): ...

class MouseEvent[**Ts](jep._PyJObject): ...

class ActionEvent[**Ts](jep._PyJObject): ...

class InvocationEvent[**Ts](jep._PyJObject): ...

class PaintEvent[**Ts](jep._PyJObject): ...

class ContainerListener[**Ts](jep._PyJObject): ...

class MouseMotionAdapter[**Ts](jep._PyJObject): ...

class WindowEvent[**Ts](jep._PyJObject): ...

class AdjustmentListener[**Ts](jep._PyJObject): ...

class WindowStateListener[**Ts](jep._PyJObject): ...

class KeyListener[**Ts](jep._PyJObject): ...

class ItemEvent[**Ts](jep._PyJObject): ...

class FocusEvent[**Ts](jep._PyJObject): ...

class AWTEventListenerProxy[**Ts](jep._PyJObject): ...

class AdjustmentEvent[**Ts](jep._PyJObject): ...

class FocusAdapter[**Ts](jep._PyJObject): ...

