# pyright: reportPrivateUsage = none

import jep

class TextLayout[**Ts](jep._PyJObject): ...

class TextMeasurer[**Ts](jep._PyJObject): ...

class FontRenderContext[**Ts](jep._PyJObject): ...

class GraphicAttribute[**Ts](jep._PyJObject): ...

class GlyphMetrics[**Ts](jep._PyJObject): ...

class TextHitInfo[**Ts](jep._PyJObject): ...

class NumericShaper[**Ts](jep._PyJObject): ...

class OpenType[**Ts](jep._PyJObject): ...

class TextAttribute[**Ts](jep._PyJObject): ...

class LineMetrics[**Ts](jep._PyJObject): ...

class GlyphJustificationInfo[**Ts](jep._PyJObject): ...

class LineBreakMeasurer[**Ts](jep._PyJObject): ...

class ImageGraphicAttribute[**Ts](jep._PyJObject): ...

class ShapeGraphicAttribute[**Ts](jep._PyJObject): ...

class TransformAttribute[**Ts](jep._PyJObject): ...

class LayoutPath[**Ts](jep._PyJObject): ...

class GlyphVector[**Ts](jep._PyJObject): ...

class MultipleMaster[**Ts](jep._PyJObject): ...

