import jep

class TextAttribute(jep.PyJObject): ...

class GlyphJustificationInfo(jep.PyJObject): ...

class OpenType(jep.PyJObject): ...

class GraphicAttribute(jep.PyJObject): ...

class LineMetrics(jep.PyJObject): ...

class TextHitInfo(jep.PyJObject): ...

class GlyphMetrics(jep.PyJObject): ...

class TransformAttribute(jep.PyJObject): ...

class TextLayout(jep.PyJObject): ...

class MultipleMaster(jep.PyJObject): ...

class ShapeGraphicAttribute(jep.PyJObject): ...

class ImageGraphicAttribute(jep.PyJObject): ...

class FontRenderContext(jep.PyJObject): ...

class LineBreakMeasurer(jep.PyJObject): ...

class NumericShaper(jep.PyJObject): ...

class GlyphVector(jep.PyJObject): ...

class LayoutPath(jep.PyJObject): ...

