import jep

class TextAttribute(jep._PyJObject): ...

class GlyphJustificationInfo(jep._PyJObject): ...

class OpenType(jep._PyJObject): ...

class GraphicAttribute(jep._PyJObject): ...

class LineMetrics(jep._PyJObject): ...

class TextHitInfo(jep._PyJObject): ...

class GlyphMetrics(jep._PyJObject): ...

class TransformAttribute(jep._PyJObject): ...

class TextLayout(jep._PyJObject): ...

class MultipleMaster(jep._PyJObject): ...

class ShapeGraphicAttribute(jep._PyJObject): ...

class ImageGraphicAttribute(jep._PyJObject): ...

class FontRenderContext(jep._PyJObject): ...

class LineBreakMeasurer(jep._PyJObject): ...

class NumericShaper(jep._PyJObject): ...

class GlyphVector(jep._PyJObject): ...

class LayoutPath(jep._PyJObject): ...

