import jep

class Area(jep._PyJObject): ...

class Arc2D(jep._PyJObject): ...

class FlatteningPathIterator(jep._PyJObject): ...

class IllegalPathStateException(jep._PyJObject): ...

class Path2D(jep._PyJObject): ...

class Dimension2D(jep._PyJObject): ...

class CubicCurve2D(jep._PyJObject): ...

class RoundRectangle2D(jep._PyJObject): ...

class Rectangle2D(jep._PyJObject): ...

class RectangularShape(jep._PyJObject): ...

class Point2D(jep._PyJObject): ...

class NoninvertibleTransformException(jep._PyJObject): ...

class Line2D(jep._PyJObject): ...

class PathIterator(jep._PyJObject): ...

class Ellipse2D(jep._PyJObject): ...

class GeneralPath(jep._PyJObject): ...

class AffineTransform(jep._PyJObject): ...

class QuadCurve2D(jep._PyJObject): ...

