# pyright: reportPrivateUsage = none

import jep

class IllegalPathStateException[**Ts](jep._PyJObject): ...

class Point2D[**Ts](jep._PyJObject): ...

class Line2D[**Ts](jep._PyJObject): ...

class Rectangle2D[**Ts](jep._PyJObject): ...

class Ellipse2D[**Ts](jep._PyJObject): ...

class GeneralPath[**Ts](jep._PyJObject): ...

class AffineTransform[**Ts](jep._PyJObject): ...

class NoninvertibleTransformException[**Ts](jep._PyJObject): ...

class QuadCurve2D[**Ts](jep._PyJObject): ...

class RectangularShape[**Ts](jep._PyJObject): ...

class RoundRectangle2D[**Ts](jep._PyJObject): ...

class FlatteningPathIterator[**Ts](jep._PyJObject): ...

class Dimension2D[**Ts](jep._PyJObject): ...

class PathIterator[**Ts](jep._PyJObject): ...

class Arc2D[**Ts](jep._PyJObject): ...

class Path2D[**Ts](jep._PyJObject): ...

class Area[**Ts](jep._PyJObject): ...

class CubicCurve2D[**Ts](jep._PyJObject): ...

