import jep

class Area(jep.PyJObject): ...

class Arc2D(jep.PyJObject): ...

class FlatteningPathIterator(jep.PyJObject): ...

class IllegalPathStateException(jep.PyJObject): ...

class Path2D(jep.PyJObject): ...

class Dimension2D(jep.PyJObject): ...

class CubicCurve2D(jep.PyJObject): ...

class RoundRectangle2D(jep.PyJObject): ...

class Rectangle2D(jep.PyJObject): ...

class RectangularShape(jep.PyJObject): ...

class Point2D(jep.PyJObject): ...

class NoninvertibleTransformException(jep.PyJObject): ...

class Line2D(jep.PyJObject): ...

class PathIterator(jep.PyJObject): ...

class Ellipse2D(jep.PyJObject): ...

class GeneralPath(jep.PyJObject): ...

class AffineTransform(jep.PyJObject): ...

class QuadCurve2D(jep.PyJObject): ...

