import jep

class PrinterAbortException(jep.PyJObject): ...

class Pageable(jep.PyJObject): ...

class Book(jep.PyJObject): ...

class PrinterJob(jep.PyJObject): ...

class PageFormat(jep.PyJObject): ...

class PrinterIOException(jep.PyJObject): ...

class Paper(jep.PyJObject): ...

class Printable(jep.PyJObject): ...

class PrinterException(jep.PyJObject): ...

class PrinterGraphics(jep.PyJObject): ...

