# pyright: reportPrivateUsage = none

import jep

class PrinterJob[**Ts](jep._PyJObject): ...

class PageFormat[**Ts](jep._PyJObject): ...

class Pageable[**Ts](jep._PyJObject): ...

class Book[**Ts](jep._PyJObject): ...

class PrinterException[**Ts](jep._PyJObject): ...

class Printable[**Ts](jep._PyJObject): ...

class PrinterIOException[**Ts](jep._PyJObject): ...

class Paper[**Ts](jep._PyJObject): ...

class PrinterGraphics[**Ts](jep._PyJObject): ...

class PrinterAbortException[**Ts](jep._PyJObject): ...

