import jep

class PrinterAbortException(jep._PyJObject): ...

class Pageable(jep._PyJObject): ...

class Book(jep._PyJObject): ...

class PrinterJob(jep._PyJObject): ...

class PageFormat(jep._PyJObject): ...

class PrinterIOException(jep._PyJObject): ...

class Paper(jep._PyJObject): ...

class Printable(jep._PyJObject): ...

class PrinterException(jep._PyJObject): ...

class PrinterGraphics(jep._PyJObject): ...

