import jep

class CatalogManager(jep.PyJObject): ...

class CatalogFeatures(jep.PyJObject): ...

class CatalogException(jep.PyJObject): ...

class Catalog(jep.PyJObject): ...

class CatalogResolver(jep.PyJObject): ...

