# pyright: reportPrivateUsage = none

import jep

class CatalogException[**Ts](jep._PyJObject): ...

class CatalogResolver[**Ts](jep._PyJObject): ...

class CatalogManager[**Ts](jep._PyJObject): ...

class Catalog[**Ts](jep._PyJObject): ...

class CatalogFeatures[**Ts](jep._PyJObject): ...

