import jep

class CatalogManager(jep._PyJObject): ...

class CatalogFeatures(jep._PyJObject): ...

class CatalogException(jep._PyJObject): ...

class Catalog(jep._PyJObject): ...

class CatalogResolver(jep._PyJObject): ...

