import jep

class XMLGregorianCalendar(jep._PyJObject): ...

class DatatypeConstants(jep._PyJObject): ...

class DatatypeConfigurationException(jep._PyJObject): ...

class Duration(jep._PyJObject): ...

class DatatypeFactory(jep._PyJObject): ...

