# pyright: reportPrivateUsage = none

import jep

class DatatypeFactory[**Ts](jep._PyJObject): ...

class DatatypeConstants[**Ts](jep._PyJObject): ...

class XMLGregorianCalendar[**Ts](jep._PyJObject): ...

class Duration[**Ts](jep._PyJObject): ...

class DatatypeConfigurationException[**Ts](jep._PyJObject): ...

