import jep

class XMLGregorianCalendar(jep.PyJObject): ...

class DatatypeConstants(jep.PyJObject): ...

class DatatypeConfigurationException(jep.PyJObject): ...

class Duration(jep.PyJObject): ...

class DatatypeFactory(jep.PyJObject): ...

