import jep

class SAXParserFactory(jep._PyJObject): ...

class SAXParser(jep._PyJObject): ...

class DocumentBuilder(jep._PyJObject): ...

class ParserConfigurationException(jep._PyJObject): ...

class FactoryConfigurationError(jep._PyJObject): ...

class DocumentBuilderFactory(jep._PyJObject): ...

