import jep

class SAXParserFactory(jep.PyJObject): ...

class SAXParser(jep.PyJObject): ...

class DocumentBuilder(jep.PyJObject): ...

class ParserConfigurationException(jep.PyJObject): ...

class FactoryConfigurationError(jep.PyJObject): ...

class DocumentBuilderFactory(jep.PyJObject): ...

