# pyright: reportPrivateUsage = none

import jep

class SAXParser[**Ts](jep._PyJObject): ...

class DocumentBuilderFactory[**Ts](jep._PyJObject): ...

class DocumentBuilder[**Ts](jep._PyJObject): ...

class FactoryConfigurationError[**Ts](jep._PyJObject): ...

class ParserConfigurationException[**Ts](jep._PyJObject): ...

class SAXParserFactory[**Ts](jep._PyJObject): ...

