# pyright: reportPrivateUsage = none

import jep

class SOAPException[**Ts](jep._PyJObject): ...

class AttachmentPart[**Ts](jep._PyJObject): ...

class SOAPEnvelope[**Ts](jep._PyJObject): ...

class SOAPPart[**Ts](jep._PyJObject): ...

class SOAPBody[**Ts](jep._PyJObject): ...

class SOAPElementFactory[**Ts](jep._PyJObject): ...

class Name[**Ts](jep._PyJObject): ...

class SOAPFactory[**Ts](jep._PyJObject): ...

class SOAPMessage[**Ts](jep._PyJObject): ...

class SOAPConnection[**Ts](jep._PyJObject): ...

class MimeHeader[**Ts](jep._PyJObject): ...

class SOAPFault[**Ts](jep._PyJObject): ...

class SOAPBodyElement[**Ts](jep._PyJObject): ...

class SOAPConstants[**Ts](jep._PyJObject): ...

class SOAPElement[**Ts](jep._PyJObject): ...

class MessageFactory[**Ts](jep._PyJObject): ...

class SAAJResult[**Ts](jep._PyJObject): ...

class DetailEntry[**Ts](jep._PyJObject): ...

class SAAJMetaFactory[**Ts](jep._PyJObject): ...

class Detail[**Ts](jep._PyJObject): ...

class SOAPHeader[**Ts](jep._PyJObject): ...

class SOAPHeaderElement[**Ts](jep._PyJObject): ...

class SOAPConnectionFactory[**Ts](jep._PyJObject): ...

class Node[**Ts](jep._PyJObject): ...

class SOAPFaultElement[**Ts](jep._PyJObject): ...

class Text[**Ts](jep._PyJObject): ...

