import jep

class Name(jep.PyJObject): ...

class SOAPMessage(jep.PyJObject): ...

class Detail(jep.PyJObject): ...

class SOAPConstants(jep.PyJObject): ...

class Node(jep.PyJObject): ...

class Text(jep.PyJObject): ...

class SOAPHeader(jep.PyJObject): ...

class SOAPBody(jep.PyJObject): ...

class SOAPElement(jep.PyJObject): ...

class SOAPHeaderElement(jep.PyJObject): ...

class SOAPFactory(jep.PyJObject): ...

class SOAPEnvelope(jep.PyJObject): ...

class SOAPBodyElement(jep.PyJObject): ...

class SAAJMetaFactory(jep.PyJObject): ...

class MessageFactory(jep.PyJObject): ...

class MimeHeader(jep.PyJObject): ...

class SOAPConnectionFactory(jep.PyJObject): ...

class MimeHeaders(jep.PyJObject): ...

class DetailEntry(jep.PyJObject): ...

class SOAPConnection(jep.PyJObject): ...

class AttachmentPart(jep.PyJObject): ...

class SOAPFault(jep.PyJObject): ...

class SOAPPart(jep.PyJObject): ...

class SOAPException(jep.PyJObject): ...

class SOAPFaultElement(jep.PyJObject): ...

class SAAJResult(jep.PyJObject): ...

class SOAPElementFactory(jep.PyJObject): ...

