import jep

class Name(jep._PyJObject): ...

class SOAPMessage(jep._PyJObject): ...

class Detail(jep._PyJObject): ...

class SOAPConstants(jep._PyJObject): ...

class Node(jep._PyJObject): ...

class Text(jep._PyJObject): ...

class SOAPHeader(jep._PyJObject): ...

class SOAPBody(jep._PyJObject): ...

class SOAPElement(jep._PyJObject): ...

class SOAPHeaderElement(jep._PyJObject): ...

class SOAPFactory(jep._PyJObject): ...

class SOAPEnvelope(jep._PyJObject): ...

class SOAPBodyElement(jep._PyJObject): ...

class SAAJMetaFactory(jep._PyJObject): ...

class MessageFactory(jep._PyJObject): ...

class MimeHeader(jep._PyJObject): ...

class SOAPConnectionFactory(jep._PyJObject): ...

class MimeHeaders(jep._PyJObject): ...

class DetailEntry(jep._PyJObject): ...

class SOAPConnection(jep._PyJObject): ...

class AttachmentPart(jep._PyJObject): ...

class SOAPFault(jep._PyJObject): ...

class SOAPPart(jep._PyJObject): ...

class SOAPException(jep._PyJObject): ...

class SOAPFaultElement(jep._PyJObject): ...

class SAAJResult(jep._PyJObject): ...

class SOAPElementFactory(jep._PyJObject): ...

