import jep

class TypeInfoProvider(jep.PyJObject): ...

class SchemaFactory(jep.PyJObject): ...

class Schema(jep.PyJObject): ...

class Validator(jep.PyJObject): ...

class ValidatorHandler(jep.PyJObject): ...

class SchemaFactoryConfigurationError(jep.PyJObject): ...

class SchemaFactoryLoader(jep.PyJObject): ...

