import jep

class TypeInfoProvider(jep._PyJObject): ...

class SchemaFactory(jep._PyJObject): ...

class Schema(jep._PyJObject): ...

class Validator(jep._PyJObject): ...

class ValidatorHandler(jep._PyJObject): ...

class SchemaFactoryConfigurationError(jep._PyJObject): ...

class SchemaFactoryLoader(jep._PyJObject): ...

