# pyright: reportPrivateUsage = none

import jep

class SchemaFactory[**Ts](jep._PyJObject): ...

class Validator[**Ts](jep._PyJObject): ...

class SchemaFactoryConfigurationError[**Ts](jep._PyJObject): ...

class Schema[**Ts](jep._PyJObject): ...

class TypeInfoProvider[**Ts](jep._PyJObject): ...

class SchemaFactoryLoader[**Ts](jep._PyJObject): ...

class ValidatorHandler[**Ts](jep._PyJObject): ...

