import jep

class XPathVariableResolver(jep.PyJObject): ...

class XPathFactory(jep.PyJObject): ...

class XPathException(jep.PyJObject): ...

class XPathNodes(jep.PyJObject): ...

class XPath(jep.PyJObject): ...

class XPathFunction(jep.PyJObject): ...

class XPathFunctionResolver(jep.PyJObject): ...

class XPathFunctionException(jep.PyJObject): ...

class XPathExpression(jep.PyJObject): ...

class XPathExpressionException(jep.PyJObject): ...

class XPathConstants(jep.PyJObject): ...

class XPathEvaluationResult(jep.PyJObject): ...

