# pyright: reportPrivateUsage = none

import jep

class XPathExpressionException[**Ts](jep._PyJObject): ...

class XPathFactoryConfigurationException[**Ts](jep._PyJObject): ...

class XPathConstants[**Ts](jep._PyJObject): ...

class XPath[**Ts](jep._PyJObject): ...

class XPathEvaluationResult[**Ts](jep._PyJObject): ...

class XPathFunctionResolver[**Ts](jep._PyJObject): ...

class XPathVariableResolver[**Ts](jep._PyJObject): ...

class XPathFunction[**Ts](jep._PyJObject): ...

class XPathFactory[**Ts](jep._PyJObject): ...

class XPathExpression[**Ts](jep._PyJObject): ...

class XPathNodes[**Ts](jep._PyJObject): ...

class XPathException[**Ts](jep._PyJObject): ...

class XPathFunctionException[**Ts](jep._PyJObject): ...

