import jep

class XPathVariableResolver(jep._PyJObject): ...

class XPathFactory(jep._PyJObject): ...

class XPathException(jep._PyJObject): ...

class XPathNodes(jep._PyJObject): ...

class XPath(jep._PyJObject): ...

class XPathFunction(jep._PyJObject): ...

class XPathFunctionResolver(jep._PyJObject): ...

class XPathFunctionException(jep._PyJObject): ...

class XPathExpression(jep._PyJObject): ...

class XPathExpressionException(jep._PyJObject): ...

class XPathConstants(jep._PyJObject): ...

class XPathEvaluationResult(jep._PyJObject): ...

