import jep

class PostConstruct(jep._PyJObject): ...

class Generated(jep._PyJObject): ...

class Resource(jep._PyJObject): ...

class Resources(jep._PyJObject): ...

class PreDestroy(jep._PyJObject): ...

