# pyright: reportPrivateUsage = none

import jep

class PostConstruct[**Ts](jep._PyJObject): ...

class Resource[**Ts](jep._PyJObject): ...

class Generated[**Ts](jep._PyJObject): ...

class PreDestroy[**Ts](jep._PyJObject): ...

class Resources[**Ts](jep._PyJObject): ...

