import jep

class PostConstruct(jep.PyJObject): ...

class Generated(jep.PyJObject): ...

class Resource(jep.PyJObject): ...

class Resources(jep.PyJObject): ...

class PreDestroy(jep.PyJObject): ...

