# pyright: reportPrivateUsage = none

import jep

class Messager[**Ts](jep._PyJObject): ...

class RoundEnvironment[**Ts](jep._PyJObject): ...

class ProcessingEnvironment[**Ts](jep._PyJObject): ...

class Generated[**Ts](jep._PyJObject): ...

class Completions[**Ts](jep._PyJObject): ...

class Filer[**Ts](jep._PyJObject): ...

class SupportedSourceVersion[**Ts](jep._PyJObject): ...

class SupportedOptions[**Ts](jep._PyJObject): ...

class Processor[**Ts](jep._PyJObject): ...

class Completion[**Ts](jep._PyJObject): ...

class FilerException[**Ts](jep._PyJObject): ...

class SupportedAnnotationTypes[**Ts](jep._PyJObject): ...

