import jep

class Completions(jep._PyJObject): ...

class AbstractProcessor(jep._PyJObject): ...

class Filer(jep._PyJObject): ...

class Generated(jep._PyJObject): ...

class Messager(jep._PyJObject): ...

class Completion(jep._PyJObject): ...

class ProcessingEnvironment(jep._PyJObject): ...

class Processor(jep._PyJObject): ...

class SupportedSourceVersion(jep._PyJObject): ...

class FilerException(jep._PyJObject): ...

class SupportedAnnotationTypes(jep._PyJObject): ...

class SupportedOptions(jep._PyJObject): ...

