import jep

class Completions(jep.PyJObject): ...

class AbstractProcessor(jep.PyJObject): ...

class Filer(jep.PyJObject): ...

class Generated(jep.PyJObject): ...

class Messager(jep.PyJObject): ...

class Completion(jep.PyJObject): ...

class ProcessingEnvironment(jep.PyJObject): ...

class Processor(jep.PyJObject): ...

class SupportedSourceVersion(jep.PyJObject): ...

class FilerException(jep.PyJObject): ...

class SupportedAnnotationTypes(jep.PyJObject): ...

class SupportedOptions(jep.PyJObject): ...

