# pyright: reportPrivateUsage = none

import jep

class AccessibilityProvider[**Ts](jep._PyJObject): ...

class AccessibleRelation[**Ts](jep._PyJObject): ...

class AccessibleResourceBundle[**Ts](jep._PyJObject): ...

class AccessibleHyperlink[**Ts](jep._PyJObject): ...

class AccessibleKeyBinding[**Ts](jep._PyJObject): ...

class AccessibleHypertext[**Ts](jep._PyJObject): ...

class AccessibleComponent[**Ts](jep._PyJObject): ...

class AccessibleSelection[**Ts](jep._PyJObject): ...

class AccessibleExtendedText[**Ts](jep._PyJObject): ...

class AccessibleBundle[**Ts](jep._PyJObject): ...

class AccessibleTable[**Ts](jep._PyJObject): ...

class AccessibleStreamable[**Ts](jep._PyJObject): ...

class AccessibleIcon[**Ts](jep._PyJObject): ...

class AccessibleRelationSet[**Ts](jep._PyJObject): ...

class AccessibleAction[**Ts](jep._PyJObject): ...

class AccessibleRole[**Ts](jep._PyJObject): ...

class AccessibleTableModelChange[**Ts](jep._PyJObject): ...

class AccessibleAttributeSequence[**Ts](jep._PyJObject): ...

class AccessibleExtendedTable[**Ts](jep._PyJObject): ...

class AccessibleEditableText[**Ts](jep._PyJObject): ...

class AccessibleValue[**Ts](jep._PyJObject): ...

class AccessibleTextSequence[**Ts](jep._PyJObject): ...

class Accessible[**Ts](jep._PyJObject): ...

class AccessibleState[**Ts](jep._PyJObject): ...

class AccessibleExtendedComponent[**Ts](jep._PyJObject): ...

class AccessibleStateSet[**Ts](jep._PyJObject): ...

class AccessibleContext[**Ts](jep._PyJObject): ...

class AccessibleText[**Ts](jep._PyJObject): ...

