import jep

class AccessibleHyperlink(jep._PyJObject): ...

class AccessibleContext(jep._PyJObject): ...

class AccessibleStreamable(jep._PyJObject): ...

class AccessibleAction(jep._PyJObject): ...

class AccessibleKeyBinding(jep._PyJObject): ...

class AccessibleExtendedComponent(jep._PyJObject): ...

class AccessibleTextSequence(jep._PyJObject): ...

class AccessibleIcon(jep._PyJObject): ...

class AccessibleRelationSet(jep._PyJObject): ...

class AccessibleStateSet(jep._PyJObject): ...

class AccessibleRelation(jep._PyJObject): ...

class AccessibleValue(jep._PyJObject): ...

class AccessibleEditableText(jep._PyJObject): ...

class AccessibleTableModelChange(jep._PyJObject): ...

class AccessibleHypertext(jep._PyJObject): ...

class AccessibleComponent(jep._PyJObject): ...

class AccessibleExtendedTable(jep._PyJObject): ...

class AccessibleRole(jep._PyJObject): ...

class AccessibleExtendedText(jep._PyJObject): ...

class AccessibilityProvider(jep._PyJObject): ...

class AccessibleSelection(jep._PyJObject): ...

class AccessibleBundle(jep._PyJObject): ...

class AccessibleAttributeSequence(jep._PyJObject): ...

class AccessibleState(jep._PyJObject): ...

class AccessibleText(jep._PyJObject): ...

class AccessibleResourceBundle(jep._PyJObject): ...

class Accessible(jep._PyJObject): ...

class AccessibleTable(jep._PyJObject): ...

