import jep

class AccessibleHyperlink(jep.PyJObject): ...

class AccessibleContext(jep.PyJObject): ...

class AccessibleStreamable(jep.PyJObject): ...

class AccessibleAction(jep.PyJObject): ...

class AccessibleKeyBinding(jep.PyJObject): ...

class AccessibleExtendedComponent(jep.PyJObject): ...

class AccessibleTextSequence(jep.PyJObject): ...

class AccessibleIcon(jep.PyJObject): ...

class AccessibleRelationSet(jep.PyJObject): ...

class AccessibleStateSet(jep.PyJObject): ...

class AccessibleRelation(jep.PyJObject): ...

class AccessibleValue(jep.PyJObject): ...

class AccessibleEditableText(jep.PyJObject): ...

class AccessibleTableModelChange(jep.PyJObject): ...

class AccessibleHypertext(jep.PyJObject): ...

class AccessibleComponent(jep.PyJObject): ...

class AccessibleExtendedTable(jep.PyJObject): ...

class AccessibleRole(jep.PyJObject): ...

class AccessibleExtendedText(jep.PyJObject): ...

class AccessibilityProvider(jep.PyJObject): ...

class AccessibleSelection(jep.PyJObject): ...

class AccessibleBundle(jep.PyJObject): ...

class AccessibleAttributeSequence(jep.PyJObject): ...

class AccessibleState(jep.PyJObject): ...

class AccessibleText(jep.PyJObject): ...

class AccessibleResourceBundle(jep.PyJObject): ...

class Accessible(jep.PyJObject): ...

class AccessibleTable(jep.PyJObject): ...

