import jep

class DataContentHandler(jep._PyJObject): ...

class CommandObject(jep._PyJObject): ...

class UnsupportedDataTypeException(jep._PyJObject): ...

class CommandMap(jep._PyJObject): ...

class MimeType(jep._PyJObject): ...

class DataSource(jep._PyJObject): ...

class FileTypeMap(jep._PyJObject): ...

class MimeTypeParseException(jep._PyJObject): ...

class ActivationDataFlavor(jep._PyJObject): ...

class MimeTypeParameterList(jep._PyJObject): ...

class URLDataSource(jep._PyJObject): ...

class CommandInfo(jep._PyJObject): ...

class DataContentHandlerFactory(jep._PyJObject): ...

class DataHandler(jep._PyJObject): ...

class FileDataSource(jep._PyJObject): ...

class MimetypesFileTypeMap(jep._PyJObject): ...

class MailcapCommandMap(jep._PyJObject): ...

