import jep

class DataContentHandler(jep.PyJObject): ...

class CommandObject(jep.PyJObject): ...

class UnsupportedDataTypeException(jep.PyJObject): ...

class CommandMap(jep.PyJObject): ...

class MimeType(jep.PyJObject): ...

class DataSource(jep.PyJObject): ...

class FileTypeMap(jep.PyJObject): ...

class MimeTypeParseException(jep.PyJObject): ...

class ActivationDataFlavor(jep.PyJObject): ...

class MimeTypeParameterList(jep.PyJObject): ...

class URLDataSource(jep.PyJObject): ...

class CommandInfo(jep.PyJObject): ...

class DataContentHandlerFactory(jep.PyJObject): ...

class DataHandler(jep.PyJObject): ...

class FileDataSource(jep.PyJObject): ...

class MimetypesFileTypeMap(jep.PyJObject): ...

class MailcapCommandMap(jep.PyJObject): ...

