# pyright: reportPrivateUsage = none

import jep

class DataContentHandlerFactory[**Ts](jep._PyJObject): ...

class DataSource[**Ts](jep._PyJObject): ...

class CommandObject[**Ts](jep._PyJObject): ...

class MimetypesFileTypeMap[**Ts](jep._PyJObject): ...

class UnsupportedDataTypeException[**Ts](jep._PyJObject): ...

class CommandInfo[**Ts](jep._PyJObject): ...

class MimeTypeParseException[**Ts](jep._PyJObject): ...

class URLDataSource[**Ts](jep._PyJObject): ...

class FileTypeMap[**Ts](jep._PyJObject): ...

class MimeType[**Ts](jep._PyJObject): ...

class DataContentHandler[**Ts](jep._PyJObject): ...

class MimeTypeParameterList[**Ts](jep._PyJObject): ...

class ActivationDataFlavor[**Ts](jep._PyJObject): ...

class DataHandler[**Ts](jep._PyJObject): ...

class MailcapCommandMap[**Ts](jep._PyJObject): ...

class FileDataSource[**Ts](jep._PyJObject): ...

class CommandMap[**Ts](jep._PyJObject): ...

