import jep

class ServiceManager(jep._PyJObject): ...

class UnavailableServiceException(jep._PyJObject): ...

class ClipboardService(jep._PyJObject): ...

class SingleInstanceListener(jep._PyJObject): ...

class JNLPRandomAccessFile(jep._PyJObject): ...

class IntegrationService(jep._PyJObject): ...

class FileOpenService(jep._PyJObject): ...

class SingleInstanceService(jep._PyJObject): ...

class PrintService(jep._PyJObject): ...

class ExtensionInstallerService(jep._PyJObject): ...

class BasicService(jep._PyJObject): ...

class DownloadService(jep._PyJObject): ...

class FileContents(jep._PyJObject): ...

class ExtendedService(jep._PyJObject): ...

class PersistenceService(jep._PyJObject): ...

class FileSaveService(jep._PyJObject): ...

class DownloadService2(jep._PyJObject): ...

class ServiceManagerStub(jep._PyJObject): ...

class DownloadServiceListener(jep._PyJObject): ...

