# pyright: reportPrivateUsage = none

import jep

class ServiceManager[**Ts](jep._PyJObject): ...

class UnavailableServiceException[**Ts](jep._PyJObject): ...

class SingleInstanceService[**Ts](jep._PyJObject): ...

class PersistenceService[**Ts](jep._PyJObject): ...

class BasicService[**Ts](jep._PyJObject): ...

class JNLPRandomAccessFile[**Ts](jep._PyJObject): ...

class ExtendedService[**Ts](jep._PyJObject): ...

class PrintService[**Ts](jep._PyJObject): ...

class ExtensionInstallerService[**Ts](jep._PyJObject): ...

class FileOpenService[**Ts](jep._PyJObject): ...

class DownloadServiceListener[**Ts](jep._PyJObject): ...

class IntegrationService[**Ts](jep._PyJObject): ...

class DownloadService2[**Ts](jep._PyJObject): ...

class SingleInstanceListener[**Ts](jep._PyJObject): ...

class ClipboardService[**Ts](jep._PyJObject): ...

class ServiceManagerStub[**Ts](jep._PyJObject): ...

class FileContents[**Ts](jep._PyJObject): ...

class DownloadService[**Ts](jep._PyJObject): ...

class FileSaveService[**Ts](jep._PyJObject): ...

