import jep

class ServiceManager(jep.PyJObject): ...

class UnavailableServiceException(jep.PyJObject): ...

class ClipboardService(jep.PyJObject): ...

class SingleInstanceListener(jep.PyJObject): ...

class JNLPRandomAccessFile(jep.PyJObject): ...

class IntegrationService(jep.PyJObject): ...

class FileOpenService(jep.PyJObject): ...

class SingleInstanceService(jep.PyJObject): ...

class PrintService(jep.PyJObject): ...

class ExtensionInstallerService(jep.PyJObject): ...

class BasicService(jep.PyJObject): ...

class DownloadService(jep.PyJObject): ...

class FileContents(jep.PyJObject): ...

class ExtendedService(jep.PyJObject): ...

class PersistenceService(jep.PyJObject): ...

class FileSaveService(jep.PyJObject): ...

class DownloadService2(jep.PyJObject): ...

class ServiceManagerStub(jep.PyJObject): ...

class DownloadServiceListener(jep.PyJObject): ...

