import jep

class ScriptException(jep._PyJObject): ...

class ScriptEngineManager(jep._PyJObject): ...

class SimpleBindings(jep._PyJObject): ...

class ScriptContext(jep._PyJObject): ...

class CompiledScript(jep._PyJObject): ...

class Invocable(jep._PyJObject): ...

class ScriptEngineFactory(jep._PyJObject): ...

class Bindings(jep._PyJObject): ...

class AbstractScriptEngine(jep._PyJObject): ...

class ScriptEngine(jep._PyJObject): ...

class Compilable(jep._PyJObject): ...

class SimpleScriptContext(jep._PyJObject): ...

