# pyright: reportPrivateUsage = none

import jep

class SimpleScriptContext[**Ts](jep._PyJObject): ...

class Invocable[**Ts](jep._PyJObject): ...

class Bindings[**Ts](jep._PyJObject): ...

class AbstractScriptEngine[**Ts](jep._PyJObject): ...

class CompiledScript[**Ts](jep._PyJObject): ...

class ScriptEngineFactory[**Ts](jep._PyJObject): ...

class ScriptException[**Ts](jep._PyJObject): ...

class Compilable[**Ts](jep._PyJObject): ...

class ScriptEngineManager[**Ts](jep._PyJObject): ...

class SimpleBindings[**Ts](jep._PyJObject): ...

class ScriptContext[**Ts](jep._PyJObject): ...

class ScriptEngine[**Ts](jep._PyJObject): ...

