import jep

class ScriptException(jep.PyJObject): ...

class ScriptEngineManager(jep.PyJObject): ...

class SimpleBindings(jep.PyJObject): ...

class ScriptContext(jep.PyJObject): ...

class CompiledScript(jep.PyJObject): ...

class Invocable(jep.PyJObject): ...

class ScriptEngineFactory(jep.PyJObject): ...

class Bindings(jep.PyJObject): ...

class AbstractScriptEngine(jep.PyJObject): ...

class ScriptEngine(jep.PyJObject): ...

class Compilable(jep.PyJObject): ...

class SimpleScriptContext(jep.PyJObject): ...

