import jep

class CardException(jep.PyJObject): ...

class TerminalFactorySpi(jep.PyJObject): ...

class CommandAPDU(jep.PyJObject): ...

class Card(jep.PyJObject): ...

class CardNotPresentException(jep.PyJObject): ...

class CardTerminals(jep.PyJObject): ...

class CardChannel(jep.PyJObject): ...

class ATR(jep.PyJObject): ...

class TerminalFactory(jep.PyJObject): ...

class CardTerminal(jep.PyJObject): ...

class ResponseAPDU(jep.PyJObject): ...

class CardPermission(jep.PyJObject): ...

