import jep

class CardException(jep._PyJObject): ...

class TerminalFactorySpi(jep._PyJObject): ...

class CommandAPDU(jep._PyJObject): ...

class Card(jep._PyJObject): ...

class CardNotPresentException(jep._PyJObject): ...

class CardTerminals(jep._PyJObject): ...

class CardChannel(jep._PyJObject): ...

class ATR(jep._PyJObject): ...

class TerminalFactory(jep._PyJObject): ...

class CardTerminal(jep._PyJObject): ...

class ResponseAPDU(jep._PyJObject): ...

class CardPermission(jep._PyJObject): ...

