# pyright: reportPrivateUsage = none

import jep

class TerminalFactory[**Ts](jep._PyJObject): ...

class CardNotPresentException[**Ts](jep._PyJObject): ...

class CardTerminal[**Ts](jep._PyJObject): ...

class CardPermission[**Ts](jep._PyJObject): ...

class CommandAPDU[**Ts](jep._PyJObject): ...

class CardChannel[**Ts](jep._PyJObject): ...

class ATR[**Ts](jep._PyJObject): ...

class TerminalFactorySpi[**Ts](jep._PyJObject): ...

class CardException[**Ts](jep._PyJObject): ...

class CardTerminals[**Ts](jep._PyJObject): ...

class ResponseAPDU[**Ts](jep._PyJObject): ...

class Card[**Ts](jep._PyJObject): ...

