# pyright: reportPrivateUsage = none

import jep

class PooledConnectionBuilder[**Ts](jep._PyJObject): ...

class RowSetReader[**Ts](jep._PyJObject): ...

class RowSetEvent[**Ts](jep._PyJObject): ...

class RowSet[**Ts](jep._PyJObject): ...

class RowSetMetaData[**Ts](jep._PyJObject): ...

class StatementEventListener[**Ts](jep._PyJObject): ...

class RowSetInternal[**Ts](jep._PyJObject): ...

class DataSource[**Ts](jep._PyJObject): ...

class PooledConnection[**Ts](jep._PyJObject): ...

class CommonDataSource[**Ts](jep._PyJObject): ...

class RowSetListener[**Ts](jep._PyJObject): ...

class XAConnectionBuilder[**Ts](jep._PyJObject): ...

class ConnectionEventListener[**Ts](jep._PyJObject): ...

class XADataSource[**Ts](jep._PyJObject): ...

class ConnectionEvent[**Ts](jep._PyJObject): ...

class XAConnection[**Ts](jep._PyJObject): ...

class RowSetWriter[**Ts](jep._PyJObject): ...

class StatementEvent[**Ts](jep._PyJObject): ...

class ConnectionPoolDataSource[**Ts](jep._PyJObject): ...

