# pyright: reportPrivateUsage = none

import jep

class FileObject[**Ts](jep._PyJObject): ...

class JavaFileManager[**Ts](jep._PyJObject): ...

class Tool[**Ts](jep._PyJObject): ...

class ToolProvider[**Ts](jep._PyJObject): ...

class StandardLocation[**Ts](jep._PyJObject): ...

class ForwardingJavaFileObject[**Ts](jep._PyJObject): ...

class DocumentationTool[**Ts](jep._PyJObject): ...

class Diagnostic[**Ts](jep._PyJObject): ...

class DiagnosticListener[**Ts](jep._PyJObject): ...

class ForwardingJavaFileManager[**Ts](jep._PyJObject): ...

class JavaCompiler[**Ts](jep._PyJObject): ...

class StandardJavaFileManager[**Ts](jep._PyJObject): ...

class SimpleJavaFileObject[**Ts](jep._PyJObject): ...

class ForwardingFileObject[**Ts](jep._PyJObject): ...

class OptionChecker[**Ts](jep._PyJObject): ...

class DiagnosticCollector[**Ts](jep._PyJObject): ...

class JavaFileObject[**Ts](jep._PyJObject): ...

