import jep

class Diagnostic(jep.PyJObject): ...

class JavaCompiler(jep.PyJObject): ...

class SimpleJavaFileObject(jep.PyJObject): ...

class ForwardingJavaFileObject(jep.PyJObject): ...

class DiagnosticCollector(jep.PyJObject): ...

class Tool(jep.PyJObject): ...

class JavaFileObject(jep.PyJObject): ...

class OptionChecker(jep.PyJObject): ...

class JavaFileManager(jep.PyJObject): ...

class StandardLocation(jep.PyJObject): ...

class DocumentationTool(jep.PyJObject): ...

class ForwardingFileObject(jep.PyJObject): ...

class StandardJavaFileManager(jep.PyJObject): ...

class FileObject(jep.PyJObject): ...

class DiagnosticListener(jep.PyJObject): ...

class ForwardingJavaFileManager(jep.PyJObject): ...

class ToolProvider(jep.PyJObject): ...

