import jep

class Diagnostic(jep._PyJObject): ...

class JavaCompiler(jep._PyJObject): ...

class SimpleJavaFileObject(jep._PyJObject): ...

class ForwardingJavaFileObject(jep._PyJObject): ...

class DiagnosticCollector(jep._PyJObject): ...

class Tool(jep._PyJObject): ...

class JavaFileObject(jep._PyJObject): ...

class OptionChecker(jep._PyJObject): ...

class JavaFileManager(jep._PyJObject): ...

class StandardLocation(jep._PyJObject): ...

class DocumentationTool(jep._PyJObject): ...

class ForwardingFileObject(jep._PyJObject): ...

class StandardJavaFileManager(jep._PyJObject): ...

class FileObject(jep._PyJObject): ...

class DiagnosticListener(jep._PyJObject): ...

class ForwardingJavaFileManager(jep._PyJObject): ...

class ToolProvider(jep._PyJObject): ...

