import jep

class ArrayChangeListener(jep.PyJObject): ...

class MapChangeListener(jep.PyJObject): ...

class WeakSetChangeListener(jep.PyJObject): ...

class FXCollections(jep.PyJObject): ...

class ObservableMap(jep.PyJObject): ...

class ListChangeListener(jep.PyJObject): ...

class SetChangeListener(jep.PyJObject): ...

class ObservableFloatArray(jep.PyJObject): ...

class ObservableIntegerArray(jep.PyJObject): ...

class ObservableList(jep.PyJObject): ...

class ObservableArray(jep.PyJObject): ...

class ObservableListBase(jep.PyJObject): ...

class WeakListChangeListener(jep.PyJObject): ...

class ModifiableObservableListBase(jep.PyJObject): ...

class ObservableSet(jep.PyJObject): ...

class ObservableArrayBase(jep.PyJObject): ...

class WeakMapChangeListener(jep.PyJObject): ...

