import jep

class ArrayChangeListener(jep._PyJObject): ...

class MapChangeListener(jep._PyJObject): ...

class WeakSetChangeListener(jep._PyJObject): ...

class FXCollections(jep._PyJObject): ...

class ObservableMap(jep._PyJObject): ...

class ListChangeListener(jep._PyJObject): ...

class SetChangeListener(jep._PyJObject): ...

class ObservableFloatArray(jep._PyJObject): ...

class ObservableIntegerArray(jep._PyJObject): ...

class ObservableList(jep._PyJObject): ...

class ObservableArray(jep._PyJObject): ...

class ObservableListBase(jep._PyJObject): ...

class WeakListChangeListener(jep._PyJObject): ...

class ModifiableObservableListBase(jep._PyJObject): ...

class ObservableSet(jep._PyJObject): ...

class ObservableArrayBase(jep._PyJObject): ...

class WeakMapChangeListener(jep._PyJObject): ...

