# pyright: reportPrivateUsage = none

import jep

class ObservableIntegerArray[**Ts](jep._PyJObject): ...

class ObservableFloatArray[**Ts](jep._PyJObject): ...

class ObservableSet[**Ts](jep._PyJObject): ...

class SetChangeListener[**Ts](jep._PyJObject): ...

class ObservableListBase[**Ts](jep._PyJObject): ...

class WeakListChangeListener[**Ts](jep._PyJObject): ...

class ObservableList[**Ts](jep._PyJObject): ...

class FXCollections[**Ts](jep._PyJObject): ...

class ArrayChangeListener[**Ts](jep._PyJObject): ...

class ModifiableObservableListBase[**Ts](jep._PyJObject): ...

class WeakMapChangeListener[**Ts](jep._PyJObject): ...

class WeakSetChangeListener[**Ts](jep._PyJObject): ...

class ObservableArrayBase[**Ts](jep._PyJObject): ...

class ObservableArray[**Ts](jep._PyJObject): ...

class ObservableMap[**Ts](jep._PyJObject): ...

class MapChangeListener[**Ts](jep._PyJObject): ...

class ListChangeListener[**Ts](jep._PyJObject): ...

