import jep

class ConnectionEventListener(jep.PyJObject): ...

class XAConnection(jep.PyJObject): ...

class PooledConnection(jep.PyJObject): ...

class RowSetMetaData(jep.PyJObject): ...

class XADataSource(jep.PyJObject): ...

class RowSetWriter(jep.PyJObject): ...

class ConnectionPoolDataSource(jep.PyJObject): ...

class RowSetEvent(jep.PyJObject): ...

class RowSet(jep.PyJObject): ...

class RowSetInternal(jep.PyJObject): ...

class CommonDataSource(jep.PyJObject): ...

class RowSetListener(jep.PyJObject): ...

class RowSetReader(jep.PyJObject): ...

class StatementEventListener(jep.PyJObject): ...

class PooledConnectionBuilder(jep.PyJObject): ...

class ConnectionEvent(jep.PyJObject): ...

class DataSource(jep.PyJObject): ...

class StatementEvent(jep.PyJObject): ...

class XAConnectionBuilder(jep.PyJObject): ...

