import jep

class ConnectionEventListener(jep._PyJObject): ...

class XAConnection(jep._PyJObject): ...

class PooledConnection(jep._PyJObject): ...

class RowSetMetaData(jep._PyJObject): ...

class XADataSource(jep._PyJObject): ...

class RowSetWriter(jep._PyJObject): ...

class ConnectionPoolDataSource(jep._PyJObject): ...

class RowSetEvent(jep._PyJObject): ...

class RowSet(jep._PyJObject): ...

class RowSetInternal(jep._PyJObject): ...

class CommonDataSource(jep._PyJObject): ...

class RowSetListener(jep._PyJObject): ...

class RowSetReader(jep._PyJObject): ...

class StatementEventListener(jep._PyJObject): ...

class PooledConnectionBuilder(jep._PyJObject): ...

class ConnectionEvent(jep._PyJObject): ...

class DataSource(jep._PyJObject): ...

class StatementEvent(jep._PyJObject): ...

class XAConnectionBuilder(jep._PyJObject): ...

