# pyright: reportPrivateUsage = none

import jep

class GSSUtil[**Ts](jep._PyJObject): ...

class InquireType[**Ts](jep._PyJObject): ...

class ExtendedGSSContext[**Ts](jep._PyJObject): ...

class ExtendedGSSCredential[**Ts](jep._PyJObject): ...

class AuthorizationDataEntry[**Ts](jep._PyJObject): ...

class InquireSecContextPermission[**Ts](jep._PyJObject): ...

