import jep

class ExtendedGSSCredential(jep._PyJObject): ...

class InquireSecContextPermission(jep._PyJObject): ...

class GSSUtil(jep._PyJObject): ...

class InquireType(jep._PyJObject): ...

class ExtendedGSSContext(jep._PyJObject): ...

class AuthorizationDataEntry(jep._PyJObject): ...

