import jep

class ExtendedGSSCredential(jep.PyJObject): ...

class InquireSecContextPermission(jep.PyJObject): ...

class GSSUtil(jep.PyJObject): ...

class InquireType(jep.PyJObject): ...

class ExtendedGSSContext(jep.PyJObject): ...

class AuthorizationDataEntry(jep.PyJObject): ...

