import jep

class AccessibleAttribute(jep.PyJObject): ...

class ParallelCamera(jep.PyJObject): ...

class Camera(jep.PyJObject): ...

class AmbientLight(jep.PyJObject): ...

class ImageCursor(jep.PyJObject): ...

class AccessibleRole(jep.PyJObject): ...

class SubScene(jep.PyJObject): ...

class Group(jep.PyJObject): ...

class SceneAntialiasing(jep.PyJObject): ...

class PerspectiveCamera(jep.PyJObject): ...

class Parent(jep.PyJObject): ...

class Scene(jep.PyJObject): ...

class Cursor(jep.PyJObject): ...

class Node(jep.PyJObject): ...

class SnapshotResult(jep.PyJObject): ...

class DepthTest(jep.PyJObject): ...

class CacheHint(jep.PyJObject): ...

class AccessibleAction(jep.PyJObject): ...

class LightBase(jep.PyJObject): ...

class PointLight(jep.PyJObject): ...

class SnapshotParameters(jep.PyJObject): ...

