# pyright: reportPrivateUsage = none

import jep

class PointLight[**Ts](jep._PyJObject): ...

class Scene[**Ts](jep._PyJObject): ...

class SnapshotParameters[**Ts](jep._PyJObject): ...

class CacheHint[**Ts](jep._PyJObject): ...

class Camera[**Ts](jep._PyJObject): ...

class LightBase[**Ts](jep._PyJObject): ...

class ImageCursor[**Ts](jep._PyJObject): ...

class AccessibleAttribute[**Ts](jep._PyJObject): ...

class Cursor[**Ts](jep._PyJObject): ...

class AccessibleRole[**Ts](jep._PyJObject): ...

class SceneAntialiasing[**Ts](jep._PyJObject): ...

class AmbientLight[**Ts](jep._PyJObject): ...

class ParallelCamera[**Ts](jep._PyJObject): ...

class SubScene[**Ts](jep._PyJObject): ...

class DepthTest[**Ts](jep._PyJObject): ...

class Group[**Ts](jep._PyJObject): ...

class PerspectiveCamera[**Ts](jep._PyJObject): ...

class Parent[**Ts](jep._PyJObject): ...

class SnapshotResult[**Ts](jep._PyJObject): ...

class AccessibleAction[**Ts](jep._PyJObject): ...

class Node[**Ts](jep._PyJObject): ...

