import jep

class AccessibleAttribute(jep._PyJObject): ...

class ParallelCamera(jep._PyJObject): ...

class Camera(jep._PyJObject): ...

class AmbientLight(jep._PyJObject): ...

class ImageCursor(jep._PyJObject): ...

class AccessibleRole(jep._PyJObject): ...

class SubScene(jep._PyJObject): ...

class Group(jep._PyJObject): ...

class SceneAntialiasing(jep._PyJObject): ...

class PerspectiveCamera(jep._PyJObject): ...

class Parent(jep._PyJObject): ...

class Scene(jep._PyJObject): ...

class Cursor(jep._PyJObject): ...

class Node(jep._PyJObject): ...

class SnapshotResult(jep._PyJObject): ...

class DepthTest(jep._PyJObject): ...

class CacheHint(jep._PyJObject): ...

class AccessibleAction(jep._PyJObject): ...

class LightBase(jep._PyJObject): ...

class PointLight(jep._PyJObject): ...

class SnapshotParameters(jep._PyJObject): ...

