# pyright: reportPrivateUsage = none

import jep

class CategoryAxis[**Ts](jep._PyJObject): ...

class XYChart[**Ts](jep._PyJObject): ...

class BubbleChart[**Ts](jep._PyJObject): ...

class BarChart[**Ts](jep._PyJObject): ...

class PieChart[**Ts](jep._PyJObject): ...

class AreaChart[**Ts](jep._PyJObject): ...

class StackedBarChart[**Ts](jep._PyJObject): ...

class ScatterChart[**Ts](jep._PyJObject): ...

class Axis[**Ts](jep._PyJObject): ...

class StackedAreaChart[**Ts](jep._PyJObject): ...

class Chart[**Ts](jep._PyJObject): ...

class NumberAxis[**Ts](jep._PyJObject): ...

class ValueAxis[**Ts](jep._PyJObject): ...

class LineChart[**Ts](jep._PyJObject): ...

