import jep

class ScatterChart(jep._PyJObject): ...

class PieChart(jep._PyJObject): ...

class NumberAxis(jep._PyJObject): ...

class Chart(jep._PyJObject): ...

class CategoryAxis(jep._PyJObject): ...

class ValueAxis(jep._PyJObject): ...

class XYChart(jep._PyJObject): ...

class AreaChart(jep._PyJObject): ...

class Axis(jep._PyJObject): ...

class StackedAreaChart(jep._PyJObject): ...

class BarChart(jep._PyJObject): ...

class BubbleChart(jep._PyJObject): ...

class StackedBarChart(jep._PyJObject): ...

class LineChart(jep._PyJObject): ...

