import jep

class ScatterChart(jep.PyJObject): ...

class PieChart(jep.PyJObject): ...

class NumberAxis(jep.PyJObject): ...

class Chart(jep.PyJObject): ...

class CategoryAxis(jep.PyJObject): ...

class ValueAxis(jep.PyJObject): ...

class XYChart(jep.PyJObject): ...

class AreaChart(jep.PyJObject): ...

class Axis(jep.PyJObject): ...

class StackedAreaChart(jep.PyJObject): ...

class BarChart(jep.PyJObject): ...

class BubbleChart(jep.PyJObject): ...

class StackedBarChart(jep.PyJObject): ...

class LineChart(jep.PyJObject): ...

