# pyright: reportPrivateUsage = none

import jep

class Bloom[**Ts](jep._PyJObject): ...

class BoxBlur[**Ts](jep._PyJObject): ...

class ColorAdjust[**Ts](jep._PyJObject): ...

class ColorInput[**Ts](jep._PyJObject): ...

class Lighting[**Ts](jep._PyJObject): ...

class InnerShadow[**Ts](jep._PyJObject): ...

class GaussianBlur[**Ts](jep._PyJObject): ...

class Shadow[**Ts](jep._PyJObject): ...

class ImageInput[**Ts](jep._PyJObject): ...

class BlurType[**Ts](jep._PyJObject): ...

class Reflection[**Ts](jep._PyJObject): ...

class SepiaTone[**Ts](jep._PyJObject): ...

class Effect[**Ts](jep._PyJObject): ...

class DropShadow[**Ts](jep._PyJObject): ...

class PerspectiveTransform[**Ts](jep._PyJObject): ...

class Glow[**Ts](jep._PyJObject): ...

class BlendMode[**Ts](jep._PyJObject): ...

class MotionBlur[**Ts](jep._PyJObject): ...

class FloatMap[**Ts](jep._PyJObject): ...

class DisplacementMap[**Ts](jep._PyJObject): ...

class Light[**Ts](jep._PyJObject): ...

class Blend[**Ts](jep._PyJObject): ...

