import jep

class Glow(jep._PyJObject): ...

class MotionBlur(jep._PyJObject): ...

class SepiaTone(jep._PyJObject): ...

class InnerShadow(jep._PyJObject): ...

class BlendMode(jep._PyJObject): ...

class DisplacementMap(jep._PyJObject): ...

class Bloom(jep._PyJObject): ...

class GaussianBlur(jep._PyJObject): ...

class Shadow(jep._PyJObject): ...

class ColorInput(jep._PyJObject): ...

class Reflection(jep._PyJObject): ...

class Light(jep._PyJObject): ...

class PerspectiveTransform(jep._PyJObject): ...

class Lighting(jep._PyJObject): ...

class ImageInput(jep._PyJObject): ...

class BlurType(jep._PyJObject): ...

class BoxBlur(jep._PyJObject): ...

class DropShadow(jep._PyJObject): ...

class Effect(jep._PyJObject): ...

class FloatMap(jep._PyJObject): ...

class Blend(jep._PyJObject): ...

class ColorAdjust(jep._PyJObject): ...

