import jep

class Glow(jep.PyJObject): ...

class MotionBlur(jep.PyJObject): ...

class SepiaTone(jep.PyJObject): ...

class InnerShadow(jep.PyJObject): ...

class BlendMode(jep.PyJObject): ...

class DisplacementMap(jep.PyJObject): ...

class Bloom(jep.PyJObject): ...

class GaussianBlur(jep.PyJObject): ...

class Shadow(jep.PyJObject): ...

class ColorInput(jep.PyJObject): ...

class Reflection(jep.PyJObject): ...

class Light(jep.PyJObject): ...

class PerspectiveTransform(jep.PyJObject): ...

class Lighting(jep.PyJObject): ...

class ImageInput(jep.PyJObject): ...

class BlurType(jep.PyJObject): ...

class BoxBlur(jep.PyJObject): ...

class DropShadow(jep.PyJObject): ...

class Effect(jep.PyJObject): ...

class FloatMap(jep.PyJObject): ...

class Blend(jep.PyJObject): ...

class ColorAdjust(jep.PyJObject): ...

