import jep

class ImageView(jep._PyJObject): ...

class WritableImage(jep._PyJObject): ...

class PixelWriter(jep._PyJObject): ...

class Image(jep._PyJObject): ...

class PixelReader(jep._PyJObject): ...

class PixelFormat(jep._PyJObject): ...

class WritablePixelFormat(jep._PyJObject): ...

