import jep

class ImageView(jep.PyJObject): ...

class WritableImage(jep.PyJObject): ...

class PixelWriter(jep.PyJObject): ...

class Image(jep.PyJObject): ...

class PixelReader(jep.PyJObject): ...

class PixelFormat(jep.PyJObject): ...

class WritablePixelFormat(jep.PyJObject): ...

