# pyright: reportPrivateUsage = none

import jep

class Image[**Ts](jep._PyJObject): ...

class PixelReader[**Ts](jep._PyJObject): ...

class PixelWriter[**Ts](jep._PyJObject): ...

class ImageView[**Ts](jep._PyJObject): ...

class PixelFormat[**Ts](jep._PyJObject): ...

class WritableImage[**Ts](jep._PyJObject): ...

class WritablePixelFormat[**Ts](jep._PyJObject): ...

