import jep

class RotateEvent(jep.PyJObject): ...

class KeyCode(jep.PyJObject): ...

class DataFormat(jep.PyJObject): ...

class InputMethodEvent(jep.PyJObject): ...

class TouchEvent(jep.PyJObject): ...

class ZoomEvent(jep.PyJObject): ...

class InputMethodRequests(jep.PyJObject): ...

class ContextMenuEvent(jep.PyJObject): ...

class Dragboard(jep.PyJObject): ...

class KeyEvent(jep.PyJObject): ...

class TouchPoint(jep.PyJObject): ...

class InputEvent(jep.PyJObject): ...

class KeyCharacterCombination(jep.PyJObject): ...

class InputMethodTextRun(jep.PyJObject): ...

class PickResult(jep.PyJObject): ...

class DragEvent(jep.PyJObject): ...

class Mnemonic(jep.PyJObject): ...

class MouseEvent(jep.PyJObject): ...

class TransferMode(jep.PyJObject): ...

class ClipboardContent(jep.PyJObject): ...

class Clipboard(jep.PyJObject): ...

class InputMethodHighlight(jep.PyJObject): ...

class SwipeEvent(jep.PyJObject): ...

class MouseDragEvent(jep.PyJObject): ...

class KeyCombination(jep.PyJObject): ...

class MouseButton(jep.PyJObject): ...

class ScrollEvent(jep.PyJObject): ...

class KeyCodeCombination(jep.PyJObject): ...

class GestureEvent(jep.PyJObject): ...

