import jep

class RotateEvent(jep._PyJObject): ...

class KeyCode(jep._PyJObject): ...

class DataFormat(jep._PyJObject): ...

class InputMethodEvent(jep._PyJObject): ...

class TouchEvent(jep._PyJObject): ...

class ZoomEvent(jep._PyJObject): ...

class InputMethodRequests(jep._PyJObject): ...

class ContextMenuEvent(jep._PyJObject): ...

class Dragboard(jep._PyJObject): ...

class KeyEvent(jep._PyJObject): ...

class TouchPoint(jep._PyJObject): ...

class InputEvent(jep._PyJObject): ...

class KeyCharacterCombination(jep._PyJObject): ...

class InputMethodTextRun(jep._PyJObject): ...

class PickResult(jep._PyJObject): ...

class DragEvent(jep._PyJObject): ...

class Mnemonic(jep._PyJObject): ...

class MouseEvent(jep._PyJObject): ...

class TransferMode(jep._PyJObject): ...

class ClipboardContent(jep._PyJObject): ...

class Clipboard(jep._PyJObject): ...

class InputMethodHighlight(jep._PyJObject): ...

class SwipeEvent(jep._PyJObject): ...

class MouseDragEvent(jep._PyJObject): ...

class KeyCombination(jep._PyJObject): ...

class MouseButton(jep._PyJObject): ...

class ScrollEvent(jep._PyJObject): ...

class KeyCodeCombination(jep._PyJObject): ...

class GestureEvent(jep._PyJObject): ...

