# pyright: reportPrivateUsage = none

import jep

class ScrollEvent[**Ts](jep._PyJObject): ...

class InputMethodHighlight[**Ts](jep._PyJObject): ...

class MouseDragEvent[**Ts](jep._PyJObject): ...

class KeyEvent[**Ts](jep._PyJObject): ...

class InputEvent[**Ts](jep._PyJObject): ...

class ContextMenuEvent[**Ts](jep._PyJObject): ...

class Dragboard[**Ts](jep._PyJObject): ...

class MouseEvent[**Ts](jep._PyJObject): ...

class SwipeEvent[**Ts](jep._PyJObject): ...

class PickResult[**Ts](jep._PyJObject): ...

class InputMethodEvent[**Ts](jep._PyJObject): ...

class DragEvent[**Ts](jep._PyJObject): ...

class KeyCharacterCombination[**Ts](jep._PyJObject): ...

class ClipboardContent[**Ts](jep._PyJObject): ...

class RotateEvent[**Ts](jep._PyJObject): ...

class KeyCombination[**Ts](jep._PyJObject): ...

class DataFormat[**Ts](jep._PyJObject): ...

class Mnemonic[**Ts](jep._PyJObject): ...

class Clipboard[**Ts](jep._PyJObject): ...

class MouseButton[**Ts](jep._PyJObject): ...

class TouchEvent[**Ts](jep._PyJObject): ...

class TouchPoint[**Ts](jep._PyJObject): ...

class KeyCodeCombination[**Ts](jep._PyJObject): ...

class TransferMode[**Ts](jep._PyJObject): ...

class GestureEvent[**Ts](jep._PyJObject): ...

class InputMethodRequests[**Ts](jep._PyJObject): ...

class ZoomEvent[**Ts](jep._PyJObject): ...

class InputMethodTextRun[**Ts](jep._PyJObject): ...

class KeyCode[**Ts](jep._PyJObject): ...

