# pyright: reportPrivateUsage = none

import jep

class BackgroundPosition[**Ts](jep._PyJObject): ...

class ColumnConstraints[**Ts](jep._PyJObject): ...

class BorderImage[**Ts](jep._PyJObject): ...

class BackgroundRepeat[**Ts](jep._PyJObject): ...

class GridPane[**Ts](jep._PyJObject): ...

class BorderStroke[**Ts](jep._PyJObject): ...

class BorderPane[**Ts](jep._PyJObject): ...

class HBox[**Ts](jep._PyJObject): ...

class Border[**Ts](jep._PyJObject): ...

class VBox[**Ts](jep._PyJObject): ...

class Pane[**Ts](jep._PyJObject): ...

class Region[**Ts](jep._PyJObject): ...

class BackgroundFill[**Ts](jep._PyJObject): ...

class Background[**Ts](jep._PyJObject): ...

class BackgroundSize[**Ts](jep._PyJObject): ...

class FlowPane[**Ts](jep._PyJObject): ...

class BorderRepeat[**Ts](jep._PyJObject): ...

class RowConstraints[**Ts](jep._PyJObject): ...

class BorderWidths[**Ts](jep._PyJObject): ...

class TilePane[**Ts](jep._PyJObject): ...

class CornerRadii[**Ts](jep._PyJObject): ...

class ConstraintsBase[**Ts](jep._PyJObject): ...

class StackPane[**Ts](jep._PyJObject): ...

class BackgroundImage[**Ts](jep._PyJObject): ...

class AnchorPane[**Ts](jep._PyJObject): ...

class Priority[**Ts](jep._PyJObject): ...

class BorderStrokeStyle[**Ts](jep._PyJObject): ...

