import jep

class MediaView(jep.PyJObject): ...

class AudioSpectrumListener(jep.PyJObject): ...

class Track(jep.PyJObject): ...

class AudioEqualizer(jep.PyJObject): ...

class MediaException(jep.PyJObject): ...

class MediaPlayer(jep.PyJObject): ...

class EqualizerBand(jep.PyJObject): ...

class AudioTrack(jep.PyJObject): ...

class SubtitleTrack(jep.PyJObject): ...

class MediaErrorEvent(jep.PyJObject): ...

class Media(jep.PyJObject): ...

class VideoTrack(jep.PyJObject): ...

class AudioClip(jep.PyJObject): ...

class MediaMarkerEvent(jep.PyJObject): ...

