# pyright: reportPrivateUsage = none

import jep

class Media[**Ts](jep._PyJObject): ...

class AudioEqualizer[**Ts](jep._PyJObject): ...

class MediaView[**Ts](jep._PyJObject): ...

class MediaErrorEvent[**Ts](jep._PyJObject): ...

class MediaPlayer[**Ts](jep._PyJObject): ...

class MediaException[**Ts](jep._PyJObject): ...

class EqualizerBand[**Ts](jep._PyJObject): ...

class AudioClip[**Ts](jep._PyJObject): ...

class SubtitleTrack[**Ts](jep._PyJObject): ...

class VideoTrack[**Ts](jep._PyJObject): ...

class Track[**Ts](jep._PyJObject): ...

class AudioSpectrumListener[**Ts](jep._PyJObject): ...

class AudioTrack[**Ts](jep._PyJObject): ...

class MediaMarkerEvent[**Ts](jep._PyJObject): ...

