import jep

class MediaView(jep._PyJObject): ...

class AudioSpectrumListener(jep._PyJObject): ...

class Track(jep._PyJObject): ...

class AudioEqualizer(jep._PyJObject): ...

class MediaException(jep._PyJObject): ...

class MediaPlayer(jep._PyJObject): ...

class EqualizerBand(jep._PyJObject): ...

class AudioTrack(jep._PyJObject): ...

class SubtitleTrack(jep._PyJObject): ...

class MediaErrorEvent(jep._PyJObject): ...

class Media(jep._PyJObject): ...

class VideoTrack(jep._PyJObject): ...

class AudioClip(jep._PyJObject): ...

class MediaMarkerEvent(jep._PyJObject): ...

