# pyright: reportPrivateUsage = none

import jep

class Material[**Ts](jep._PyJObject): ...

class LinearGradient[**Ts](jep._PyJObject): ...

class RadialGradient[**Ts](jep._PyJObject): ...

class ImagePattern[**Ts](jep._PyJObject): ...

class PhongMaterial[**Ts](jep._PyJObject): ...

class Color[**Ts](jep._PyJObject): ...

class Stop[**Ts](jep._PyJObject): ...

class CycleMethod[**Ts](jep._PyJObject): ...

