import jep

class Color(jep._PyJObject): ...

class ImagePattern(jep._PyJObject): ...

class CycleMethod(jep._PyJObject): ...

class LinearGradient(jep._PyJObject): ...

class Material(jep._PyJObject): ...

class Stop(jep._PyJObject): ...

class PhongMaterial(jep._PyJObject): ...

class RadialGradient(jep._PyJObject): ...

class Paint(jep._PyJObject): ...

