import jep

class Color(jep.PyJObject): ...

class ImagePattern(jep.PyJObject): ...

class CycleMethod(jep.PyJObject): ...

class LinearGradient(jep.PyJObject): ...

class Material(jep.PyJObject): ...

class Stop(jep.PyJObject): ...

class PhongMaterial(jep.PyJObject): ...

class RadialGradient(jep.PyJObject): ...

class Paint(jep.PyJObject): ...

