import jep

class CubicCurve(jep._PyJObject): ...

class Line(jep._PyJObject): ...

class StrokeType(jep._PyJObject): ...

class CubicCurveTo(jep._PyJObject): ...

class Mesh(jep._PyJObject): ...

class Circle(jep._PyJObject): ...

class CullFace(jep._PyJObject): ...

class Arc(jep._PyJObject): ...

class Shape3D(jep._PyJObject): ...

class ArcTo(jep._PyJObject): ...

class LineTo(jep._PyJObject): ...

class VertexFormat(jep._PyJObject): ...

class StrokeLineJoin(jep._PyJObject): ...

class Cylinder(jep._PyJObject): ...

class SVGPath(jep._PyJObject): ...

class MeshView(jep._PyJObject): ...

class StrokeLineCap(jep._PyJObject): ...

class QuadCurveTo(jep._PyJObject): ...

class TriangleMesh(jep._PyJObject): ...

class DrawMode(jep._PyJObject): ...

class Box(jep._PyJObject): ...

class HLineTo(jep._PyJObject): ...

class Rectangle(jep._PyJObject): ...

class ClosePath(jep._PyJObject): ...

class MoveTo(jep._PyJObject): ...

class Shape(jep._PyJObject): ...

class Polygon(jep._PyJObject): ...

class Path(jep._PyJObject): ...

class Sphere(jep._PyJObject): ...

class ObservableFaceArray(jep._PyJObject): ...

class Polyline(jep._PyJObject): ...

class VLineTo(jep._PyJObject): ...

class Ellipse(jep._PyJObject): ...

class QuadCurve(jep._PyJObject): ...

class ArcType(jep._PyJObject): ...

class PathElement(jep._PyJObject): ...

class FillRule(jep._PyJObject): ...

