import jep

class CubicCurve(jep.PyJObject): ...

class Line(jep.PyJObject): ...

class StrokeType(jep.PyJObject): ...

class CubicCurveTo(jep.PyJObject): ...

class Mesh(jep.PyJObject): ...

class Circle(jep.PyJObject): ...

class CullFace(jep.PyJObject): ...

class Arc(jep.PyJObject): ...

class Shape3D(jep.PyJObject): ...

class ArcTo(jep.PyJObject): ...

class LineTo(jep.PyJObject): ...

class VertexFormat(jep.PyJObject): ...

class StrokeLineJoin(jep.PyJObject): ...

class Cylinder(jep.PyJObject): ...

class SVGPath(jep.PyJObject): ...

class MeshView(jep.PyJObject): ...

class StrokeLineCap(jep.PyJObject): ...

class QuadCurveTo(jep.PyJObject): ...

class TriangleMesh(jep.PyJObject): ...

class DrawMode(jep.PyJObject): ...

class Box(jep.PyJObject): ...

class HLineTo(jep.PyJObject): ...

class Rectangle(jep.PyJObject): ...

class ClosePath(jep.PyJObject): ...

class MoveTo(jep.PyJObject): ...

class Shape(jep.PyJObject): ...

class Polygon(jep.PyJObject): ...

class Path(jep.PyJObject): ...

class Sphere(jep.PyJObject): ...

class ObservableFaceArray(jep.PyJObject): ...

class Polyline(jep.PyJObject): ...

class VLineTo(jep.PyJObject): ...

class Ellipse(jep.PyJObject): ...

class QuadCurve(jep.PyJObject): ...

class ArcType(jep.PyJObject): ...

class PathElement(jep.PyJObject): ...

class FillRule(jep.PyJObject): ...

