# pyright: reportPrivateUsage = none

import jep

class MoveTo[**Ts](jep._PyJObject): ...

class QuadCurveTo[**Ts](jep._PyJObject): ...

class StrokeType[**Ts](jep._PyJObject): ...

class ClosePath[**Ts](jep._PyJObject): ...

class LineTo[**Ts](jep._PyJObject): ...

class Cylinder[**Ts](jep._PyJObject): ...

class Circle[**Ts](jep._PyJObject): ...

class Sphere[**Ts](jep._PyJObject): ...

class CubicCurveTo[**Ts](jep._PyJObject): ...

class StrokeLineCap[**Ts](jep._PyJObject): ...

class ArcType[**Ts](jep._PyJObject): ...

class Polygon[**Ts](jep._PyJObject): ...

class Rectangle[**Ts](jep._PyJObject): ...

class ArcTo[**Ts](jep._PyJObject): ...

class Line[**Ts](jep._PyJObject): ...

class TriangleMesh[**Ts](jep._PyJObject): ...

class StrokeLineJoin[**Ts](jep._PyJObject): ...

class Box[**Ts](jep._PyJObject): ...

class Path[**Ts](jep._PyJObject): ...

class Ellipse[**Ts](jep._PyJObject): ...

class Mesh[**Ts](jep._PyJObject): ...

class HLineTo[**Ts](jep._PyJObject): ...

class FillRule[**Ts](jep._PyJObject): ...

class QuadCurve[**Ts](jep._PyJObject): ...

class Shape[**Ts](jep._PyJObject): ...

class Arc[**Ts](jep._PyJObject): ...

class Polyline[**Ts](jep._PyJObject): ...

class VertexFormat[**Ts](jep._PyJObject): ...

class SVGPath[**Ts](jep._PyJObject): ...

class Shape3D[**Ts](jep._PyJObject): ...

class MeshView[**Ts](jep._PyJObject): ...

class ObservableFaceArray[**Ts](jep._PyJObject): ...

class DrawMode[**Ts](jep._PyJObject): ...

class PathElement[**Ts](jep._PyJObject): ...

class CullFace[**Ts](jep._PyJObject): ...

class CubicCurve[**Ts](jep._PyJObject): ...

class VLineTo[**Ts](jep._PyJObject): ...

