# pyright: reportPrivateUsage = none

import jep

class FontSmoothingType[**Ts](jep._PyJObject): ...

class Font[**Ts](jep._PyJObject): ...

class HitInfo[**Ts](jep._PyJObject): ...

class Text[**Ts](jep._PyJObject): ...

class FontPosture[**Ts](jep._PyJObject): ...

class TextFlow[**Ts](jep._PyJObject): ...

class FontWeight[**Ts](jep._PyJObject): ...

class TextBoundsType[**Ts](jep._PyJObject): ...

class TextAlignment[**Ts](jep._PyJObject): ...

