import jep

class FontWeight(jep.PyJObject): ...

class HitInfo(jep.PyJObject): ...

class Text(jep.PyJObject): ...

class TextFlow(jep.PyJObject): ...

class FontSmoothingType(jep.PyJObject): ...

class FontPosture(jep.PyJObject): ...

class TextAlignment(jep.PyJObject): ...

class TextBoundsType(jep.PyJObject): ...

class Font(jep.PyJObject): ...

