import jep

class FontWeight(jep._PyJObject): ...

class HitInfo(jep._PyJObject): ...

class Text(jep._PyJObject): ...

class TextFlow(jep._PyJObject): ...

class FontSmoothingType(jep._PyJObject): ...

class FontPosture(jep._PyJObject): ...

class TextAlignment(jep._PyJObject): ...

class TextBoundsType(jep._PyJObject): ...

class Font(jep._PyJObject): ...

