# pyright: reportPrivateUsage = none

import jep

class TransformChangedEvent[**Ts](jep._PyJObject): ...

class Shear[**Ts](jep._PyJObject): ...

class MatrixType[**Ts](jep._PyJObject): ...

class Affine[**Ts](jep._PyJObject): ...

class Translate[**Ts](jep._PyJObject): ...

class Transform[**Ts](jep._PyJObject): ...

class Scale[**Ts](jep._PyJObject): ...

class NonInvertibleTransformException[**Ts](jep._PyJObject): ...

class Rotate[**Ts](jep._PyJObject): ...

