import jep

class Transform(jep.PyJObject): ...

class Affine(jep.PyJObject): ...

class Scale(jep.PyJObject): ...

class TransformChangedEvent(jep.PyJObject): ...

class MatrixType(jep.PyJObject): ...

class Translate(jep.PyJObject): ...

class NonInvertibleTransformException(jep.PyJObject): ...

class Rotate(jep.PyJObject): ...

class Shear(jep.PyJObject): ...

