import jep

class Transform(jep._PyJObject): ...

class Affine(jep._PyJObject): ...

class Scale(jep._PyJObject): ...

class TransformChangedEvent(jep._PyJObject): ...

class MatrixType(jep._PyJObject): ...

class Translate(jep._PyJObject): ...

class NonInvertibleTransformException(jep._PyJObject): ...

class Rotate(jep._PyJObject): ...

class Shear(jep._PyJObject): ...

