# pyright: reportPrivateUsage = none

import jep

class PromptData[**Ts](jep._PyJObject): ...

class WebHistory[**Ts](jep._PyJObject): ...

class WebView[**Ts](jep._PyJObject): ...

class PopupFeatures[**Ts](jep._PyJObject): ...

class WebEngine[**Ts](jep._PyJObject): ...

class WebErrorEvent[**Ts](jep._PyJObject): ...

class WebEvent[**Ts](jep._PyJObject): ...

class HTMLEditorSkin[**Ts](jep._PyJObject): ...

class HTMLEditor[**Ts](jep._PyJObject): ...

