import jep

class WebHistory(jep._PyJObject): ...

class WebEngine(jep._PyJObject): ...

class PromptData(jep._PyJObject): ...

class HTMLEditorSkin(jep._PyJObject): ...

class WebEvent(jep._PyJObject): ...

class PopupFeatures(jep._PyJObject): ...

class HTMLEditor(jep._PyJObject): ...

class WebErrorEvent(jep._PyJObject): ...

class WebView(jep._PyJObject): ...

