import jep

class WebHistory(jep.PyJObject): ...

class WebEngine(jep.PyJObject): ...

class PromptData(jep.PyJObject): ...

class HTMLEditorSkin(jep.PyJObject): ...

class WebEvent(jep.PyJObject): ...

class PopupFeatures(jep.PyJObject): ...

class HTMLEditor(jep.PyJObject): ...

class WebErrorEvent(jep.PyJObject): ...

class WebView(jep.PyJObject): ...

