import jep

class NamingContextExtOperations(jep.PyJObject): ...

class NamingContextExt(jep.PyJObject): ...

class _NamingContextStub(jep.PyJObject): ...

class BindingListHolder(jep.PyJObject): ...

class IstringHelper(jep.PyJObject): ...

class BindingHelper(jep.PyJObject): ...

class _BindingIteratorStub(jep.PyJObject): ...

class BindingIteratorHelper(jep.PyJObject): ...

class _BindingIteratorImplBase(jep.PyJObject): ...

class BindingTypeHelper(jep.PyJObject): ...

class BindingIteratorOperations(jep.PyJObject): ...

class NamingContextExtPOA(jep.PyJObject): ...

class BindingType(jep.PyJObject): ...

class NamingContextPOA(jep.PyJObject): ...

class NamingContext(jep.PyJObject): ...

class NameComponentHolder(jep.PyJObject): ...

class NamingContextExtHolder(jep.PyJObject): ...

class NameHolder(jep.PyJObject): ...

class BindingIterator(jep.PyJObject): ...

class NameComponent(jep.PyJObject): ...

class NamingContextOperations(jep.PyJObject): ...

class NameHelper(jep.PyJObject): ...

class BindingIteratorHolder(jep.PyJObject): ...

class BindingListHelper(jep.PyJObject): ...

class NamingContextExtHelper(jep.PyJObject): ...

class BindingHolder(jep.PyJObject): ...

class BindingTypeHolder(jep.PyJObject): ...

class NameComponentHelper(jep.PyJObject): ...

class BindingIteratorPOA(jep.PyJObject): ...

class NamingContextHolder(jep.PyJObject): ...

class NamingContextHelper(jep.PyJObject): ...

class _NamingContextImplBase(jep.PyJObject): ...

class _NamingContextExtStub(jep.PyJObject): ...

class Binding(jep.PyJObject): ...

