# pyright: reportPrivateUsage = none

import jep

class BindingListHolder[**Ts](jep._PyJObject): ...

class NamingContextOperations[**Ts](jep._PyJObject): ...

class BindingHelper[**Ts](jep._PyJObject): ...

class NameHelper[**Ts](jep._PyJObject): ...

class NameComponentHelper[**Ts](jep._PyJObject): ...

class _NamingContextExtStub[**Ts](jep._PyJObject): ...

class NamingContextHelper[**Ts](jep._PyJObject): ...

class NamingContextExtHolder[**Ts](jep._PyJObject): ...

class NamingContextPOA[**Ts](jep._PyJObject): ...

class NamingContextExtOperations[**Ts](jep._PyJObject): ...

class NamingContextExtPOA[**Ts](jep._PyJObject): ...

class BindingIteratorHelper[**Ts](jep._PyJObject): ...

class BindingTypeHolder[**Ts](jep._PyJObject): ...

class NamingContextHolder[**Ts](jep._PyJObject): ...

class IstringHelper[**Ts](jep._PyJObject): ...

class BindingType[**Ts](jep._PyJObject): ...

class _NamingContextStub[**Ts](jep._PyJObject): ...

class BindingHolder[**Ts](jep._PyJObject): ...

class BindingIteratorOperations[**Ts](jep._PyJObject): ...

class NamingContextExt[**Ts](jep._PyJObject): ...

class _NamingContextImplBase[**Ts](jep._PyJObject): ...

class BindingTypeHelper[**Ts](jep._PyJObject): ...

class BindingIteratorPOA[**Ts](jep._PyJObject): ...

class NamingContext[**Ts](jep._PyJObject): ...

class NameComponentHolder[**Ts](jep._PyJObject): ...

class _BindingIteratorImplBase[**Ts](jep._PyJObject): ...

class _BindingIteratorStub[**Ts](jep._PyJObject): ...

class Binding[**Ts](jep._PyJObject): ...

class NameComponent[**Ts](jep._PyJObject): ...

class BindingIteratorHolder[**Ts](jep._PyJObject): ...

class NameHolder[**Ts](jep._PyJObject): ...

class BindingIterator[**Ts](jep._PyJObject): ...

class BindingListHelper[**Ts](jep._PyJObject): ...

class NamingContextExtHelper[**Ts](jep._PyJObject): ...

