import jep

class CannotProceedHelper(jep._PyJObject): ...

class CannotProceedHolder(jep._PyJObject): ...

class NotFoundReasonHolder(jep._PyJObject): ...

class InvalidNameHolder(jep._PyJObject): ...

class InvalidNameHelper(jep._PyJObject): ...

class InvalidName(jep._PyJObject): ...

class NotFoundHolder(jep._PyJObject): ...

class NotEmptyHolder(jep._PyJObject): ...

class NotEmptyHelper(jep._PyJObject): ...

class NotFound(jep._PyJObject): ...

class NotEmpty(jep._PyJObject): ...

class NotFoundHelper(jep._PyJObject): ...

class AlreadyBoundHelper(jep._PyJObject): ...

class NotFoundReasonHelper(jep._PyJObject): ...

class CannotProceed(jep._PyJObject): ...

class AlreadyBound(jep._PyJObject): ...

class AlreadyBoundHolder(jep._PyJObject): ...

