# pyright: reportPrivateUsage = none

import jep

class NotEmpty[**Ts](jep._PyJObject): ...

class NotFoundReasonHelper[**Ts](jep._PyJObject): ...

class NotFoundHolder[**Ts](jep._PyJObject): ...

class NotEmptyHelper[**Ts](jep._PyJObject): ...

class AlreadyBoundHolder[**Ts](jep._PyJObject): ...

class AlreadyBound[**Ts](jep._PyJObject): ...

class InvalidName[**Ts](jep._PyJObject): ...

class NotFoundReason[**Ts](jep._PyJObject): ...

class AlreadyBoundHelper[**Ts](jep._PyJObject): ...

class NotFoundReasonHolder[**Ts](jep._PyJObject): ...

class CannotProceedHelper[**Ts](jep._PyJObject): ...

class NotFound[**Ts](jep._PyJObject): ...

class InvalidNameHelper[**Ts](jep._PyJObject): ...

class CannotProceed[**Ts](jep._PyJObject): ...

class NotFoundHelper[**Ts](jep._PyJObject): ...

class CannotProceedHolder[**Ts](jep._PyJObject): ...

class InvalidNameHolder[**Ts](jep._PyJObject): ...

