import jep

class InvalidAddressHolder(jep.PyJObject): ...

class StringNameHelper(jep.PyJObject): ...

class InvalidAddress(jep.PyJObject): ...

class InvalidAddressHelper(jep.PyJObject): ...

class AddressHelper(jep.PyJObject): ...

class URLStringHelper(jep.PyJObject): ...

