import jep

class CannotProceedHelper(jep.PyJObject): ...

class CannotProceedHolder(jep.PyJObject): ...

class NotFoundReasonHolder(jep.PyJObject): ...

class InvalidNameHolder(jep.PyJObject): ...

class InvalidNameHelper(jep.PyJObject): ...

class InvalidName(jep.PyJObject): ...

class NotFoundHolder(jep.PyJObject): ...

class NotEmptyHolder(jep.PyJObject): ...

class NotEmptyHelper(jep.PyJObject): ...

class NotFound(jep.PyJObject): ...

class NotEmpty(jep.PyJObject): ...

class NotFoundHelper(jep.PyJObject): ...

class AlreadyBoundHelper(jep.PyJObject): ...

class NotFoundReasonHelper(jep.PyJObject): ...

class CannotProceed(jep.PyJObject): ...

class AlreadyBound(jep.PyJObject): ...

class AlreadyBoundHolder(jep.PyJObject): ...

