import jep

class InvalidAddressHolder(jep._PyJObject): ...

class StringNameHelper(jep._PyJObject): ...

class InvalidAddress(jep._PyJObject): ...

class InvalidAddressHelper(jep._PyJObject): ...

class AddressHelper(jep._PyJObject): ...

class URLStringHelper(jep._PyJObject): ...

