# pyright: reportPrivateUsage = none

import jep

class InvalidAddress[**Ts](jep._PyJObject): ...

class InvalidAddressHolder[**Ts](jep._PyJObject): ...

class StringNameHelper[**Ts](jep._PyJObject): ...

class URLStringHelper[**Ts](jep._PyJObject): ...

class AddressHelper[**Ts](jep._PyJObject): ...

class InvalidAddressHelper[**Ts](jep._PyJObject): ...

