# pyright: reportPrivateUsage = none

import jep

class Provider[**Ts](jep._PyJObject): ...

class Invoker[**Ts](jep._PyJObject): ...

class ServiceDelegate[**Ts](jep._PyJObject): ...

class WebServiceFeatureAnnotation[**Ts](jep._PyJObject): ...

