# pyright: reportPrivateUsage = none

import jep

class MBeanServerInvocationHandler[**Ts](jep._PyJObject): ...

class AttributeList[**Ts](jep._PyJObject): ...

class AttributeChangeNotification[**Ts](jep._PyJObject): ...

class MBeanException[**Ts](jep._PyJObject): ...

class MXBean[**Ts](jep._PyJObject): ...

class ConstructorParameters[**Ts](jep._PyJObject): ...

class ServiceNotFoundException[**Ts](jep._PyJObject): ...

class ObjectInstance[**Ts](jep._PyJObject): ...

class MBeanRegistration[**Ts](jep._PyJObject): ...

class OperationsException[**Ts](jep._PyJObject): ...

class ReflectionException[**Ts](jep._PyJObject): ...

class MBeanPermission[**Ts](jep._PyJObject): ...

class JMX[**Ts](jep._PyJObject): ...

class MBeanServerDelegate[**Ts](jep._PyJObject): ...

class DescriptorRead[**Ts](jep._PyJObject): ...

class AttributeNotFoundException[**Ts](jep._PyJObject): ...

class InvalidAttributeValueException[**Ts](jep._PyJObject): ...

class StandardEmitterMBean[**Ts](jep._PyJObject): ...

class MBeanOperationInfo[**Ts](jep._PyJObject): ...

class MBeanServerNotification[**Ts](jep._PyJObject): ...

class DynamicMBean[**Ts](jep._PyJObject): ...

class ValueExp[**Ts](jep._PyJObject): ...

class RuntimeMBeanException[**Ts](jep._PyJObject): ...

class MBeanServerConnection[**Ts](jep._PyJObject): ...

class NotificationEmitter[**Ts](jep._PyJObject): ...

class AttributeChangeNotificationFilter[**Ts](jep._PyJObject): ...

class MBeanAttributeInfo[**Ts](jep._PyJObject): ...

class NotificationFilterSupport[**Ts](jep._PyJObject): ...

class NotCompliantMBeanException[**Ts](jep._PyJObject): ...

class NotificationBroadcaster[**Ts](jep._PyJObject): ...

class QueryEval[**Ts](jep._PyJObject): ...

class MBeanServerDelegateMBean[**Ts](jep._PyJObject): ...

class RuntimeErrorException[**Ts](jep._PyJObject): ...

class AttributeValueExp[**Ts](jep._PyJObject): ...

class Notification[**Ts](jep._PyJObject): ...

class MBeanTrustPermission[**Ts](jep._PyJObject): ...

class NotificationListener[**Ts](jep._PyJObject): ...

class MBeanServerBuilder[**Ts](jep._PyJObject): ...

class NotificationFilter[**Ts](jep._PyJObject): ...

class ListenerNotFoundException[**Ts](jep._PyJObject): ...

class BadStringOperationException[**Ts](jep._PyJObject): ...

class QueryExp[**Ts](jep._PyJObject): ...

class InvalidApplicationException[**Ts](jep._PyJObject): ...

class BadBinaryOpValueExpException[**Ts](jep._PyJObject): ...

class MBeanRegistrationException[**Ts](jep._PyJObject): ...

class DescriptorKey[**Ts](jep._PyJObject): ...

class DefaultLoaderRepository[**Ts](jep._PyJObject): ...

class StandardMBean[**Ts](jep._PyJObject): ...

class IntrospectionException[**Ts](jep._PyJObject): ...

class MBeanNotificationInfo[**Ts](jep._PyJObject): ...

class MBeanParameterInfo[**Ts](jep._PyJObject): ...

class MBeanInfo[**Ts](jep._PyJObject): ...

class InstanceAlreadyExistsException[**Ts](jep._PyJObject): ...

class MBeanServerFactory[**Ts](jep._PyJObject): ...

class InstanceNotFoundException[**Ts](jep._PyJObject): ...

class StringValueExp[**Ts](jep._PyJObject): ...

class MBeanServerPermission[**Ts](jep._PyJObject): ...

class JMException[**Ts](jep._PyJObject): ...

class JMRuntimeException[**Ts](jep._PyJObject): ...

class RuntimeOperationsException[**Ts](jep._PyJObject): ...

class Query[**Ts](jep._PyJObject): ...

class BadAttributeValueExpException[**Ts](jep._PyJObject): ...

class NotificationBroadcasterSupport[**Ts](jep._PyJObject): ...

class ImmutableDescriptor[**Ts](jep._PyJObject): ...

class MBeanConstructorInfo[**Ts](jep._PyJObject): ...

class DescriptorAccess[**Ts](jep._PyJObject): ...

class MBeanServer[**Ts](jep._PyJObject): ...

class PersistentMBean[**Ts](jep._PyJObject): ...

class MalformedObjectNameException[**Ts](jep._PyJObject): ...

class Descriptor[**Ts](jep._PyJObject): ...

class Attribute[**Ts](jep._PyJObject): ...

class MBeanFeatureInfo[**Ts](jep._PyJObject): ...

class ObjectName[**Ts](jep._PyJObject): ...

