import jep

class PrivateMLet(jep.PyJObject): ...

class MLetContent(jep.PyJObject): ...

class MLetMBean(jep.PyJObject): ...

class MLet(jep.PyJObject): ...

class ClassLoaderRepository(jep.PyJObject): ...

class PrivateClassLoader(jep.PyJObject): ...

class DefaultLoaderRepository(jep.PyJObject): ...

