# pyright: reportPrivateUsage = none

import jep

class MLetMBean[**Ts](jep._PyJObject): ...

class MLet[**Ts](jep._PyJObject): ...

class PrivateClassLoader[**Ts](jep._PyJObject): ...

class ClassLoaderRepository[**Ts](jep._PyJObject): ...

class DefaultLoaderRepository[**Ts](jep._PyJObject): ...

class PrivateMLet[**Ts](jep._PyJObject): ...

class MLetContent[**Ts](jep._PyJObject): ...

