import jep

class PrivateMLet(jep._PyJObject): ...

class MLetContent(jep._PyJObject): ...

class MLetMBean(jep._PyJObject): ...

class MLet(jep._PyJObject): ...

class ClassLoaderRepository(jep._PyJObject): ...

class PrivateClassLoader(jep._PyJObject): ...

class DefaultLoaderRepository(jep._PyJObject): ...

