import jep

class ModelMBeanAttributeInfo(jep._PyJObject): ...

class ModelMBeanNotificationInfo(jep._PyJObject): ...

class ModelMBeanInfoSupport(jep._PyJObject): ...

class DescriptorSupport(jep._PyJObject): ...

class ModelMBeanOperationInfo(jep._PyJObject): ...

class ModelMBeanConstructorInfo(jep._PyJObject): ...

class ModelMBeanNotificationBroadcaster(jep._PyJObject): ...

class RequiredModelMBean(jep._PyJObject): ...

class XMLParseException(jep._PyJObject): ...

class InvalidTargetObjectTypeException(jep._PyJObject): ...

class ModelMBeanInfo(jep._PyJObject): ...

class ModelMBean(jep._PyJObject): ...

