# pyright: reportPrivateUsage = none

import jep

class ModelMBeanNotificationInfo[**Ts](jep._PyJObject): ...

class InvalidTargetObjectTypeException[**Ts](jep._PyJObject): ...

class ModelMBeanInfoSupport[**Ts](jep._PyJObject): ...

class XMLParseException[**Ts](jep._PyJObject): ...

class ModelMBeanNotificationBroadcaster[**Ts](jep._PyJObject): ...

class DescriptorSupport[**Ts](jep._PyJObject): ...

class RequiredModelMBean[**Ts](jep._PyJObject): ...

class ModelMBeanAttributeInfo[**Ts](jep._PyJObject): ...

class ModelMBeanOperationInfo[**Ts](jep._PyJObject): ...

class ModelMBean[**Ts](jep._PyJObject): ...

class ModelMBeanConstructorInfo[**Ts](jep._PyJObject): ...

class ModelMBeanInfo[**Ts](jep._PyJObject): ...

