import jep

class ModelMBeanAttributeInfo(jep.PyJObject): ...

class ModelMBeanNotificationInfo(jep.PyJObject): ...

class ModelMBeanInfoSupport(jep.PyJObject): ...

class DescriptorSupport(jep.PyJObject): ...

class ModelMBeanOperationInfo(jep.PyJObject): ...

class ModelMBeanConstructorInfo(jep.PyJObject): ...

class ModelMBeanNotificationBroadcaster(jep.PyJObject): ...

class RequiredModelMBean(jep.PyJObject): ...

class XMLParseException(jep.PyJObject): ...

class InvalidTargetObjectTypeException(jep.PyJObject): ...

class ModelMBeanInfo(jep.PyJObject): ...

class ModelMBean(jep.PyJObject): ...

