import jep

class Monitor(jep._PyJObject): ...

class StringMonitor(jep._PyJObject): ...

class GaugeMonitorMBean(jep._PyJObject): ...

class CounterMonitorMBean(jep._PyJObject): ...

class GaugeMonitor(jep._PyJObject): ...

class MonitorSettingException(jep._PyJObject): ...

class StringMonitorMBean(jep._PyJObject): ...

class MonitorNotification(jep._PyJObject): ...

class CounterMonitor(jep._PyJObject): ...

class MonitorMBean(jep._PyJObject): ...

