import jep

class Monitor(jep.PyJObject): ...

class StringMonitor(jep.PyJObject): ...

class GaugeMonitorMBean(jep.PyJObject): ...

class CounterMonitorMBean(jep.PyJObject): ...

class GaugeMonitor(jep.PyJObject): ...

class MonitorSettingException(jep.PyJObject): ...

class StringMonitorMBean(jep.PyJObject): ...

class MonitorNotification(jep.PyJObject): ...

class CounterMonitor(jep.PyJObject): ...

class MonitorMBean(jep.PyJObject): ...

