# pyright: reportPrivateUsage = none

import jep

class GaugeMonitor[**Ts](jep._PyJObject): ...

class MonitorMBean[**Ts](jep._PyJObject): ...

class StringMonitorMBean[**Ts](jep._PyJObject): ...

class StringMonitor[**Ts](jep._PyJObject): ...

class CounterMonitor[**Ts](jep._PyJObject): ...

class MonitorNotification[**Ts](jep._PyJObject): ...

class GaugeMonitorMBean[**Ts](jep._PyJObject): ...

class Monitor[**Ts](jep._PyJObject): ...

class CounterMonitorMBean[**Ts](jep._PyJObject): ...

class MonitorSettingException[**Ts](jep._PyJObject): ...

