import jep

class OpenMBeanAttributeInfo(jep.PyJObject): ...

class OpenMBeanInfoSupport(jep.PyJObject): ...

class OpenType(jep.PyJObject): ...

class OpenMBeanConstructorInfoSupport(jep.PyJObject): ...

class CompositeType(jep.PyJObject): ...

class CompositeData(jep.PyJObject): ...

class TabularDataSupport(jep.PyJObject): ...

class KeyAlreadyExistsException(jep.PyJObject): ...

class CompositeDataView(jep.PyJObject): ...

class CompositeDataInvocationHandler(jep.PyJObject): ...

class TabularType(jep.PyJObject): ...

class InvalidKeyException(jep.PyJObject): ...

class OpenMBeanInfo(jep.PyJObject): ...

class CompositeDataSupport(jep.PyJObject): ...

class OpenMBeanParameterInfoSupport(jep.PyJObject): ...

class TabularData(jep.PyJObject): ...

class ArrayType(jep.PyJObject): ...

class OpenDataException(jep.PyJObject): ...

class OpenMBeanOperationInfoSupport(jep.PyJObject): ...

class OpenMBeanConstructorInfo(jep.PyJObject): ...

class OpenMBeanAttributeInfoSupport(jep.PyJObject): ...

class OpenMBeanOperationInfo(jep.PyJObject): ...

class SimpleType(jep.PyJObject): ...

class OpenMBeanParameterInfo(jep.PyJObject): ...

