# pyright: reportPrivateUsage = none

import jep

class OpenMBeanOperationInfo[**Ts](jep._PyJObject): ...

class OpenMBeanConstructorInfo[**Ts](jep._PyJObject): ...

class OpenMBeanOperationInfoSupport[**Ts](jep._PyJObject): ...

class OpenMBeanParameterInfoSupport[**Ts](jep._PyJObject): ...

class TabularDataSupport[**Ts](jep._PyJObject): ...

class ArrayType[**Ts](jep._PyJObject): ...

class CompositeDataView[**Ts](jep._PyJObject): ...

class TabularData[**Ts](jep._PyJObject): ...

class CompositeData[**Ts](jep._PyJObject): ...

class OpenMBeanInfo[**Ts](jep._PyJObject): ...

class OpenMBeanAttributeInfo[**Ts](jep._PyJObject): ...

class InvalidOpenTypeException[**Ts](jep._PyJObject): ...

class OpenType[**Ts](jep._PyJObject): ...

class KeyAlreadyExistsException[**Ts](jep._PyJObject): ...

class OpenMBeanAttributeInfoSupport[**Ts](jep._PyJObject): ...

class CompositeDataInvocationHandler[**Ts](jep._PyJObject): ...

class CompositeType[**Ts](jep._PyJObject): ...

class OpenMBeanInfoSupport[**Ts](jep._PyJObject): ...

class OpenMBeanConstructorInfoSupport[**Ts](jep._PyJObject): ...

class OpenDataException[**Ts](jep._PyJObject): ...

class CompositeDataSupport[**Ts](jep._PyJObject): ...

class SimpleType[**Ts](jep._PyJObject): ...

class OpenMBeanParameterInfo[**Ts](jep._PyJObject): ...

class InvalidKeyException[**Ts](jep._PyJObject): ...

class TabularType[**Ts](jep._PyJObject): ...

