import jep

class OpenMBeanAttributeInfo(jep._PyJObject): ...

class OpenMBeanInfoSupport(jep._PyJObject): ...

class OpenType(jep._PyJObject): ...

class OpenMBeanConstructorInfoSupport(jep._PyJObject): ...

class CompositeType(jep._PyJObject): ...

class CompositeData(jep._PyJObject): ...

class TabularDataSupport(jep._PyJObject): ...

class KeyAlreadyExistsException(jep._PyJObject): ...

class CompositeDataView(jep._PyJObject): ...

class CompositeDataInvocationHandler(jep._PyJObject): ...

class TabularType(jep._PyJObject): ...

class InvalidKeyException(jep._PyJObject): ...

class OpenMBeanInfo(jep._PyJObject): ...

class CompositeDataSupport(jep._PyJObject): ...

class OpenMBeanParameterInfoSupport(jep._PyJObject): ...

class TabularData(jep._PyJObject): ...

class ArrayType(jep._PyJObject): ...

class OpenDataException(jep._PyJObject): ...

class OpenMBeanOperationInfoSupport(jep._PyJObject): ...

class OpenMBeanConstructorInfo(jep._PyJObject): ...

class OpenMBeanAttributeInfoSupport(jep._PyJObject): ...

class OpenMBeanOperationInfo(jep._PyJObject): ...

class SimpleType(jep._PyJObject): ...

class OpenMBeanParameterInfo(jep._PyJObject): ...

