# pyright: reportPrivateUsage = none

import jep

class InvalidRelationIdException[**Ts](jep._PyJObject): ...

class RelationTypeSupport[**Ts](jep._PyJObject): ...

class RelationServiceMBean[**Ts](jep._PyJObject): ...

class RelationException[**Ts](jep._PyJObject): ...

class RelationSupportMBean[**Ts](jep._PyJObject): ...

class RelationNotFoundException[**Ts](jep._PyJObject): ...

class RoleResult[**Ts](jep._PyJObject): ...

class RoleList[**Ts](jep._PyJObject): ...

class RoleNotFoundException[**Ts](jep._PyJObject): ...

class RoleInfoNotFoundException[**Ts](jep._PyJObject): ...

class RelationType[**Ts](jep._PyJObject): ...

class RelationNotification[**Ts](jep._PyJObject): ...

class RelationServiceNotRegisteredException[**Ts](jep._PyJObject): ...

class InvalidRelationTypeException[**Ts](jep._PyJObject): ...

class InvalidRoleInfoException[**Ts](jep._PyJObject): ...

class Role[**Ts](jep._PyJObject): ...

class RoleStatus[**Ts](jep._PyJObject): ...

class Relation[**Ts](jep._PyJObject): ...

class RoleUnresolved[**Ts](jep._PyJObject): ...

class InvalidRelationServiceException[**Ts](jep._PyJObject): ...

class RoleUnresolvedList[**Ts](jep._PyJObject): ...

class RelationService[**Ts](jep._PyJObject): ...

class MBeanServerNotificationFilter[**Ts](jep._PyJObject): ...

class RoleInfo[**Ts](jep._PyJObject): ...

class InvalidRoleValueException[**Ts](jep._PyJObject): ...

class RelationSupport[**Ts](jep._PyJObject): ...

