import jep

class RoleStatus(jep.PyJObject): ...

class RelationSupportMBean(jep.PyJObject): ...

class RelationServiceMBean(jep.PyJObject): ...

class RelationSupport(jep.PyJObject): ...

class RelationTypeNotFoundException(jep.PyJObject): ...

class MBeanServerNotificationFilter(jep.PyJObject): ...

class RoleResult(jep.PyJObject): ...

class RoleInfo(jep.PyJObject): ...

class RoleUnresolvedList(jep.PyJObject): ...

class RelationException(jep.PyJObject): ...

class InvalidRoleInfoException(jep.PyJObject): ...

class Role(jep.PyJObject): ...

class RoleList(jep.PyJObject): ...

class RelationService(jep.PyJObject): ...

class InvalidRelationServiceException(jep.PyJObject): ...

class RelationTypeSupport(jep.PyJObject): ...

class RelationNotification(jep.PyJObject): ...

class RelationType(jep.PyJObject): ...

class InvalidRelationTypeException(jep.PyJObject): ...

class RoleNotFoundException(jep.PyJObject): ...

class InvalidRoleValueException(jep.PyJObject): ...

class RelationServiceNotRegisteredException(jep.PyJObject): ...

class InvalidRelationIdException(jep.PyJObject): ...

class RoleUnresolved(jep.PyJObject): ...

class Relation(jep.PyJObject): ...

class RelationNotFoundException(jep.PyJObject): ...

class RoleInfoNotFoundException(jep.PyJObject): ...

