import jep

class RoleStatus(jep._PyJObject): ...

class RelationSupportMBean(jep._PyJObject): ...

class RelationServiceMBean(jep._PyJObject): ...

class RelationSupport(jep._PyJObject): ...

class RelationTypeNotFoundException(jep._PyJObject): ...

class MBeanServerNotificationFilter(jep._PyJObject): ...

class RoleResult(jep._PyJObject): ...

class RoleInfo(jep._PyJObject): ...

class RoleUnresolvedList(jep._PyJObject): ...

class RelationException(jep._PyJObject): ...

class InvalidRoleInfoException(jep._PyJObject): ...

class Role(jep._PyJObject): ...

class RoleList(jep._PyJObject): ...

class RelationService(jep._PyJObject): ...

class InvalidRelationServiceException(jep._PyJObject): ...

class RelationTypeSupport(jep._PyJObject): ...

class RelationNotification(jep._PyJObject): ...

class RelationType(jep._PyJObject): ...

class InvalidRelationTypeException(jep._PyJObject): ...

class RoleNotFoundException(jep._PyJObject): ...

class InvalidRoleValueException(jep._PyJObject): ...

class RelationServiceNotRegisteredException(jep._PyJObject): ...

class InvalidRelationIdException(jep._PyJObject): ...

class RoleUnresolved(jep._PyJObject): ...

class Relation(jep._PyJObject): ...

class RelationNotFoundException(jep._PyJObject): ...

class RoleInfoNotFoundException(jep._PyJObject): ...

