import jep

class CallSiteDescriptor(jep.PyJObject): ...

class NamespaceOperation(jep.PyJObject): ...

class Operation(jep.PyJObject): ...

class StandardNamespace(jep.PyJObject): ...

class StandardOperation(jep.PyJObject): ...

class NamedOperation(jep.PyJObject): ...

class SecureLookupSupplier(jep.PyJObject): ...

class RelinkableCallSite(jep.PyJObject): ...

class NoSuchDynamicMethodException(jep.PyJObject): ...

class DynamicLinker(jep.PyJObject): ...

class Namespace(jep.PyJObject): ...

class DynamicLinkerFactory(jep.PyJObject): ...

