# pyright: reportPrivateUsage = none

import jep

class Namespace[**Ts](jep._PyJObject): ...

class Operation[**Ts](jep._PyJObject): ...

class NamedOperation[**Ts](jep._PyJObject): ...

class SecureLookupSupplier[**Ts](jep._PyJObject): ...

class RelinkableCallSite[**Ts](jep._PyJObject): ...

class NamespaceOperation[**Ts](jep._PyJObject): ...

class DynamicLinkerFactory[**Ts](jep._PyJObject): ...

class CallSiteDescriptor[**Ts](jep._PyJObject): ...

class NoSuchDynamicMethodException[**Ts](jep._PyJObject): ...

class StandardOperation[**Ts](jep._PyJObject): ...

class DynamicLinker[**Ts](jep._PyJObject): ...

class StandardNamespace[**Ts](jep._PyJObject): ...

