import jep

class CallSiteDescriptor(jep._PyJObject): ...

class NamespaceOperation(jep._PyJObject): ...

class Operation(jep._PyJObject): ...

class StandardNamespace(jep._PyJObject): ...

class StandardOperation(jep._PyJObject): ...

class NamedOperation(jep._PyJObject): ...

class SecureLookupSupplier(jep._PyJObject): ...

class RelinkableCallSite(jep._PyJObject): ...

class NoSuchDynamicMethodException(jep._PyJObject): ...

class DynamicLinker(jep._PyJObject): ...

class Namespace(jep._PyJObject): ...

class DynamicLinkerFactory(jep._PyJObject): ...

